// Generated by TyraX. Do not edit - regenerated on every build.
#pragma once

// Ambient-occlusion occluders: solid authored objects as oriented
// boxes / spheres, baked on the host. ax/ay/az = the object's local
// axes in world space; sphere = 1 reads half[0] as the radius;
// objIndex = scene-table index (an object never occludes itself).

namespace {
struct AoOccData {
  float pos[3];
  float ax[3], ay[3], az[3];
  float half[3];
  int sphere;
  int objIndex;
};

static const AoOccData S0_AO_OCC[8] = {
    {{-8.0F, 0.9F, 8.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.9F, 0.9F, 0.9F}, 0, 5},
    {{-4.0F, 0.9F, 13.0F}, {0.978148F, 0.0F, -0.207912F}, {0.0F, 1.0F, 0.0F}, {0.207912F, 0.0F, 0.978148F}, {0.9F, 0.9F, 0.9F}, 0, 6},
    {{0.0F, 0.9F, 8.0F}, {0.913545F, 0.0F, -0.406737F}, {0.0F, 1.0F, 0.0F}, {0.406737F, 0.0F, 0.913545F}, {0.9F, 0.9F, 0.9F}, 0, 7},
    {{4.0F, 0.9F, 13.0F}, {0.809017F, 0.0F, -0.587785F}, {0.0F, 1.0F, 0.0F}, {0.587785F, 0.0F, 0.809017F}, {0.9F, 0.9F, 0.9F}, 0, 8},
    {{8.0F, 0.9F, 8.0F}, {0.669131F, 0.0F, -0.743145F}, {0.0F, 1.0F, 0.0F}, {0.743145F, 0.0F, 0.669131F}, {0.9F, 0.9F, 0.9F}, 0, 9},
    {{-11.0F, 1.3F, 20.0F}, {-1.0F, 0.0F, 8.74228e-08F}, {-0.0F, 1.0F, 0.0F}, {-8.74228e-08F, 0.0F, -1.0F}, {0.8F, 1.3F, 0.8F}, 0, 10},
    {{11.0F, 1.3F, 20.0F}, {-1.0F, 0.0F, 8.74228e-08F}, {-0.0F, 1.0F, 0.0F}, {-8.74228e-08F, 0.0F, -1.0F}, {0.8F, 1.3F, 0.8F}, 0, 11},
    {{0.0F, 1.2F, 16.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {5.0F, 1.2F, 0.3F}, 0, 12},
};

static const AoOccData* const SCENE_AO_OCC_TABLES[] = {S0_AO_OCC};
static const int SCENE_AO_OCC_COUNTS[] = {8};

struct EmisLightData {
  float pos[3];
  float ax[3], ay[3], az[3];
  float half[3];
  int sphere;
  int objIndex;
  float color[3];
  float range, bright;
};


static const EmisLightData* const SCENE_EMIS_TABLES[] = {nullptr};
static const int SCENE_EMIS_COUNTS[] = {0};

struct AoAtlasRect {
  float u0, v0, du, dv;
};
static const AoAtlasRect S0_AO_RECTS[42] = {{0.574219F, 0.910156F, 0.164062F, 0.03125F}, {0.363281F, 0.839844F, 0.164062F, 0.03125F}, {0.230469F, 0.964844F, 0.015625F, 0.015625F}, {0.152344F, 0.699219F, 0.117188F, 0.117188F}, {0.394531F, 0.511719F, 0.03125F, 0.164062F}, {0.339844F, 0.511719F, 0.03125F, 0.164062F}, {0.550781F, 0.839844F, 0.164062F, 0.03125F}, {0.0117188F, 0.839844F, 0.140625F, 0.046875F}, {0.269531F, 0.964844F, 0.0234375F, 0.0078125F}, {0.589844F, 0.699219F, 0.171875F, 0.0859375F}, {0.449219F, 0.511719F, 0.0625F, 0.132812F}, {0.175781F, 0.511719F, 0.03125F, 0.164062F}, {0.738281F, 0.839844F, 0.164062F, 0.03125F}, {0.386719F, 0.910156F, 0.164062F, 0.03125F}, {0.191406F, 0.964844F, 0.015625F, 0.015625F}, {0.0117188F, 0.699219F, 0.117188F, 0.117188F}, {0.0117188F, 0.511719F, 0.03125F, 0.164062F}, {0.0664062F, 0.511719F, 0.03125F, 0.164062F}, {0.175781F, 0.839844F, 0.164062F, 0.03125F}, {0.785156F, 0.699219F, 0.117188F, 0.0703125F}, {0.761719F, 0.910156F, 0.0234375F, 0.0234375F}, {0.777344F, 0.511719F, 0.132812F, 0.117188F}, {0.675781F, 0.511719F, 0.078125F, 0.117188F}, {0.121094F, 0.511719F, 0.03125F, 0.164062F}, {0.199219F, 0.910156F, 0.164062F, 0.03125F}, {0.0117188F, 0.910156F, 0.164062F, 0.03125F}, {0.808594F, 0.910156F, 0.015625F, 0.015625F}, {0.535156F, 0.511719F, 0.117188F, 0.117188F}, {0.230469F, 0.511719F, 0.03125F, 0.164062F}, {0.285156F, 0.511719F, 0.03125F, 0.164062F}, {0.230469F, 0.0117188F, 0.109375F, 0.234375F}, {0.847656F, 0.910156F, 0.015625F, 0.015625F}, {0.425781F, 0.699219F, 0.109375F, 0.109375F}, {0.0976562F, 0.0117188F, 0.109375F, 0.234375F}, {0.886719F, 0.910156F, 0.015625F, 0.015625F}, {0.292969F, 0.699219F, 0.109375F, 0.109375F}, {0.316406F, 0.964844F, 0.210938F, 0.0078125F}, {0.0117188F, 0.964844F, 0.15625F, 0.015625F}, {0.558594F, 0.699219F, 0.0078125F, 0.0859375F}, {0.0117188F, 0.0117188F, 0.0625F, 0.476562F}, {0.363281F, 0.0117188F, 0.226562F, 0.210938F}, {0.613281F, 0.0117188F, 0.375F, 0.195312F}};
static const int S0_AO_FIRST[13] = {-1, -1, -1, -1, -1, 0, 6, 12, 18, 24, 30, 33, 36};
static const unsigned char S0_AO_LIT[13] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static const AoAtlasRect* const SCENE_AO_ATLAS_RECTS_T[] = {S0_AO_RECTS};
static const int* const SCENE_AO_ATLAS_FIRSTS_T[] = {S0_AO_FIRST};
static const unsigned char* const SCENE_AO_ATLAS_LITS_T[] = {S0_AO_LIT};
static const char* const SCENE_AO_ATLAS_PATHS[] = {"aoatlas/scene0.png"};
static const char* const SCENE_AO_MAP_PATHS[] = {"aomap/scene0.png"};
static const unsigned char SCENE_AO_MAP_OCCS[] = {1};
static const unsigned char SCENE_AO_MAP_LITS[] = {0};
static const unsigned char SCENE_AO_ATLAS_GIS[] = {0};
static const unsigned char SCENE_AO_MAP_GIS[] = {0};
}  // namespace

#define SCENE_AO_OCC SCENE_AO_OCC_TABLES[g_activeScene]
#define SCENE_AO_OCC_COUNT SCENE_AO_OCC_COUNTS[g_activeScene]
#define SCENE_EMIS SCENE_EMIS_TABLES[g_activeScene]
#define SCENE_EMIS_COUNT SCENE_EMIS_COUNTS[g_activeScene]
#define SCENE_AO_ATLAS_RECTS SCENE_AO_ATLAS_RECTS_T[g_activeScene]
#define SCENE_AO_ATLAS_FIRST SCENE_AO_ATLAS_FIRSTS_T[g_activeScene]
#define SCENE_AO_ATLAS_LIT SCENE_AO_ATLAS_LITS_T[g_activeScene]
#define SCENE_AO_ATLAS_PATH SCENE_AO_ATLAS_PATHS[g_activeScene]
#define SCENE_AO_MAP_PATH SCENE_AO_MAP_PATHS[g_activeScene]
#define SCENE_AO_MAP_OCC SCENE_AO_MAP_OCCS[g_activeScene]
#define SCENE_AO_MAP_LIT SCENE_AO_MAP_LITS[g_activeScene]
#define SCENE_AO_ATLAS_GI SCENE_AO_ATLAS_GIS[g_activeScene]
#define SCENE_AO_MAP_GI SCENE_AO_MAP_GIS[g_activeScene]
