from pathlib import Path
import json,hashlib,subprocess,os,time,re,signal,shutil
b=Path('/mnt/f/Projects/tyrax2-lab-20261001');g=b/'sky-retint-production-vehicle-v1/game';out=b/'sky-retint-production-v3-runtime';assert not out.exists();out.mkdir();sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
manifest=json.loads((b/'sky-retint-production-v3-source-manifest.json').read_text());assert all(sha(g/n)==v for n,v in manifest.items());build=json.loads((b/'sky-retint-production-v3-build-exit.json').read_text(encoding='utf-8-sig'));assert build['exitCode']==0;assert '[editor] Native build complete:' in (b/'sky-retint-production-native-v3.log').read_text();elf=g/'bin/vehicle-playground.elf';assert not Path('/mnt/wslg/runtime-dir/pcsx2.sock.28205').exists()
root=Path('/home/spider/tyrax2-debugger-linux-v1');run=Path('/home/spider/sky-retint-production-v3');assert not run.exists();inis=run/'profile/PCSX2/inis';inis.mkdir(parents=True);s=(root/'profile/PCSX2/inis/PCSX2.ini').read_text();s=re.sub(r'^PINESlot\s*=.*$','PINESlot = 28205',s,flags=re.M);s=re.sub(r'^(StartPaused|ShowOnStartup)\s*=.*$',r'\1 = false',s,flags=re.M);audio=re.search(r'^\[SPU2/Output\]\n(.*?)(?=^\[|\Z)',s,re.M|re.S);assert audio;block=re.sub(r'^Backend\s*=.*$','Backend = Null',audio[0],flags=re.M);s=s[:audio.start()]+block+s[audio.end():];(inis/'PCSX2.ini').write_text(s)
exe=root/'squashfs-root/usr/bin/pcsx2-qt';assert sha(exe)=='c4629baf9c5daca45a9df6ad1ee84a188aeb025627b822a3ea62bdc48b23da18';env=os.environ.copy();env.update(DISPLAY=':93',QT_QPA_PLATFORM='xcb',LIBGL_ALWAYS_SOFTWARE='1');env.pop('WAYLAND_DISPLAY',None);log=run/'emulator.log';args=[str(root/'squashfs-root/AppRun'),'-datapath',str(run/'profile'),'-logfile',str(log),'-batch','-nogui','-elf',str(elf)];p=subprocess.Popen(args,cwd=g,env=env,stdout=(run/'stdout.log').open('w'),stderr=subprocess.STDOUT,start_new_session=True);owned=dict(pid=p.pid,args=args,exe=str(exe),exeSha256=sha(exe),elfSha256=sha(elf),symbolSha256=sha(elf.with_suffix('.elf.sym')),sourceManifestSha256=sha(b/'sky-retint-production-v3-source-manifest.json'),buildRecordSha256=sha(b/'sky-retint-production-v3-build-exit.json'),helperSha256=sha(Path(__file__)));(out/'owned-launch.json').write_text(json.dumps(owned,indent=2)+'\n');print('Owned production emulator',p.pid,flush=True)
seen={};deadline=time.monotonic()+300
while time.monotonic()<deadline:
 text=log.read_text(errors='replace')if log.exists()else'';assert 'equal=0' not in text,'full-array oracle failed'
 rows=re.findall(r'LOG: SKYWARM scene=(\d+) generation=(\d+) count=(\d+) check=(\d+)',text)
 if rows:
  scene,gen,count,check=map(int,rows[-1]);key=str(gen)
  if key not in seen and check>=180:
   tree=subprocess.check_output(['xwininfo','-root','-tree'],env=env,text=True);wins=re.findall(r'(0x[0-9a-fA-F]+) "vehicle-playground[^"\n]*"',tree);assert len(wins)==1;win=wins[0];prop=subprocess.check_output(['xprop','-id',win,'_NET_WM_PID'],env=env,text=True);assert re.search(r'=\s*'+str(p.pid)+r'\s*$',prop);image=out/f'gen-{gen}-scene-{scene}.png';before=sha(log);subprocess.run(['import','-window',win,str(image)],env=env,check=True,timeout=10);after=log.read_text(errors='replace');generations=re.findall(r'LOG: SKYMOTION scene=\d+ generation=(\d+)',after);assert generations and int(generations[-1])==gen;seen[key]=dict(scene=scene,generation=gen,count=count,check=check,image=image.name,sha256=sha(image),beforeLogSha256=before,afterLogSha256=sha(log),warmAfterReference=True);print('Warm capture',gen,scene,count,check,flush=True)
 if 'LOG: SKYMOTION done stage=3' in text:break
 assert p.poll() is None,'emulator exited before completion';time.sleep(.1)
else:raise RuntimeError('Incomplete private production qualification; exact owned process retained')
assert len(seen)==4 and sorted(x['scene']for x in seen.values())==[0,0,1,2],seen
oracles=[tuple(map(int,x))for x in re.findall(r'LOG: SKYORACLE scene=(\d+) generation=(\d+) count=(\d+) equal=(\d+) check=(\d+)',text)];assert oracles and all(x[3]==1 for x in oracles) and set(x[2]for x in oracles)=={504,1152};assert all(sha(g/n)==v for n,v in manifest.items())
shutil.copyfile(log,out/'emulator.log');shutil.copyfile(run/'stdout.log',out/'stdout.log');shutil.copyfile(b/'sky-retint-production-v3-source-manifest.json',out/'source-manifest.json');proof=dict(status='PASS_PRIVATE_PRODUCTION_ACTIVE_RGB_FOUR_GENERATIONS_EXACT_ORACLE',images=seen,oracleCalls=len(oracles),comparedVertices=sum(x[2]for x in oracles),counts=sorted(set(x[2]for x in oracles)),visualReviewPending=True,physicalPricingAccepted=False,logSha256=sha(out/'emulator.log'),ownedLaunchSha256=sha(out/'owned-launch.json'));(out/'proof.json').write_text(json.dumps(proof,indent=2)+'\n');proc=Path('/proc')/str(p.pid);assert proc.joinpath('exe').resolve()==exe and str(run/'profile').encode()in proc.joinpath('cmdline').read_bytes().split(b'\0');os.kill(p.pid,signal.SIGTERM);(out/'owned-stop.json').write_text(json.dumps(dict(pid=p.pid,reason='completed_motion_four_generations_active_RGB_exact_oracles'),indent=2)+'\n');print(proof['status'],len(oracles),flush=True)
