// Generated by TyraX. Do not edit - regenerated on every build.
#pragma once

// Ambient-occlusion occluders: solid authored objects as oriented
// boxes / spheres, baked on the host. ax/ay/az = the object's local
// axes in world space; sphere = 1 reads half[0] as the radius;
// objIndex = scene-table index (an object never occludes itself).

namespace {
struct AoOccData {
  float pos[3];
  float ax[3], ay[3], az[3];
  float half[3];
  int sphere;
  int objIndex;
};


static const AoOccData* const SCENE_AO_OCC_TABLES[] = {nullptr, nullptr};
static const int SCENE_AO_OCC_COUNTS[] = {0, 0};
}  // namespace

#define SCENE_AO_OCC SCENE_AO_OCC_TABLES[g_activeScene]
#define SCENE_AO_OCC_COUNT SCENE_AO_OCC_COUNTS[g_activeScene]
