// Generated by tyra-editor. Do not edit - regenerated on every build.
#pragma once

namespace Showcase {

struct HudImageData {
  const char* path;  // relative to the game binary (res/ is copied there)
  float x, y;        // normalized screen position, center anchor
  float w, h;        // size in pixels
};

constexpr int HUD_COUNT = 1;
inline const HudImageData HUD_IMAGES[HUD_COUNT > 0 ? HUD_COUNT : 1] = {
    {"ui/crosshair.png", 0.5F, 0.5F, 24.0F, 24.0F},  // crosshair
};

}  // namespace Showcase
