// Generated by TyraX. Do not edit - regenerated on every build.
// Input recorder hook (docs/input-replay.md). Implemented in
// src/gen/input_replay.gen.cpp; the game loop calls tick() as the LAST stage
// of a frame's input, after every overlay.
#pragma once

#include <tyra>

namespace Showcase {
namespace inputreplay {

/** Records or replays this frame's input. Call once per frame, after
 * Pad::update(), after the keyboard/mouse fold and after livepad::tick - it
 * OVERWRITES the pad rather than merging, so anything that runs later would
 * undo it. `pad2` is the optional second connector (null when the project is
 * single-player). */
void tick(Tyra::Engine* engine, Tyra::Pad* pad2);

/** The one non-deterministic number the game asks for: a runtime procedural
 * volume's seed. While recording it stores `chosen` and hands it straight
 * back; while replaying it returns what was stored, so the world generates
 * identically. Off, it is `chosen`. */
unsigned int seed(unsigned int volume, unsigned int chosen);

}  // namespace inputreplay
}  // namespace Showcase
