// Generated by TyraX. Do not edit - regenerated on every build.
#pragma once

namespace Showcase {

struct SceneObjectData {
  int type;  // 0=box 1=sphere 2=cylinder 3=cone 4=spawn-point 5=model
             // 6=player 7=emitter 8=sound 9=point-light 10=save-point
             // 11=empty (pure transform, no geometry/collision)
             // 12=plane 13=decal 14=camera (cutscene shot marker)
             // 15=mirror (glass quad; reflections via MIRRORS below)
  float position[3];
  float rotation[3];  // degrees
  float scale[3];
  float color[3];  // 0..1
  int physics;  // 1 = falls with gravity
  int model;    // index into MODEL_PATHS / gameModels, -1 = none
  int material; // primitives: index into MATERIAL_PATHS, -1 = plain color
  int usable;   // 1 = shows the USE prompt up close (see controls.hpp)
  int emitKind;   // emitters: 0 fire, 1 smoke, 2 fog, 3 sparks, 4 rain,
                  // 5 custom (physics below)
  int emitCount;  // emitters: particle pool size (density)
  float emitSize; // emitters: base particle size
  int emitEnabled; // emitters: 0 = starts disabled (Show Object enables)
  int emitFollow;  // emitters: 1 = position is an offset from the player
  float emitSpeed;   // custom: emission speed along rotated +Y, units/s
  float emitSpread;  // custom: cone half-angle, degrees
  float emitGravity; // custom: units/s^2, negative = rises
  float emitWeight;  // custom: air drag ~ 1/weight
  float emitLife;    // custom: particle lifetime, seconds
  float emitGrow;    // custom: size multiplier at end of life
  float emitOpacity; // custom: base alpha 0..1
  int emitDieGround; // custom: 1 = particle dies on the terrain
  int snd;        // sound emitters: index into SND_PATHS, -1 = none
  int sndAuto;    // sound emitters: 1 = plays while in range
  float sndRange;    // sound emitters: audible distance
  float sndInterval; // sound emitters: retrigger period (s), 0 = loop
  int sndOnPlayer;   // sound emitters: 1 = centered on the player
                     // (plain stereo, full volume, no distance/pan)
  float lightBright; // point lights (type 9): baked intensity
  float lightRadius; // point lights (type 9): falloff radius
  int saveState;  // 1 = position/color/visibility persisted in saves
  int collision;  // 0 = box (models: mesh AABB), 1 = mesh, 2 = none
  float drawDistance;  // not drawn farther than this from the camera;
                       // 0 = unlimited (collision/logic always run)
  int animModel;  // animated models: index into ANIM_MODEL_PATHS, -1 = none
  const char* animClip;  // animated models: starting clip ("" = first)
  int animAutoplay;      // animated models: 1 = play at scene start
  int animLoop;          // animated models: 1 = starting clip loops
  float animSpeed;       // animated models: playback speed multiplier
  int primDetail;        // segments (curved) or box subdivisions/edge
  int layer;      // streaming layer (SCENE_LAYER_* tables), -1 = none:
                  // always resident, never streamed out
};

constexpr int SCENE_COUNT = 2;

// scene "vale"
constexpr SceneObjectData SCENE_0_OBJECTS[60] = {
    {6, {0.0F, -0.0286F, -8.0F}, {0.0F, 0.0F, 0.0F}, {1.0F, 1.0F, 1.0F}, {0.15F, 0.9F, 0.9F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 16, -1},  // player
    {2, {-6.0F, 0.0288F, 2.0F}, {0.0F, 0.0F, 0.0F}, {1.3F, 0.5F, 1.3F}, {0.25F, 0.16F, 0.1F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 10, -1},  // campfire-logs
    {7, {-6.0F, 0.1788F, 2.0F}, {0.0F, 0.0F, 0.0F}, {1.1F, 1.0F, 1.1F}, {1.0F, 0.55F, 0.15F}, 0, -1, -1, 0, 0, 40, 0.55F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 16, -1},  // campfire-fire
    {7, {-6.0F, 1.1788F, 2.0F}, {0.0F, 0.0F, 0.0F}, {1.0F, 1.0F, 1.0F}, {0.35F, 0.34F, 0.33F}, 0, -1, -1, 0, 1, 26, 0.8F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 16, -1},  // campfire-smoke
    {9, {-6.0F, 0.7788F, 2.0F}, {0.0F, 0.0F, 0.0F}, {1.0F, 1.0F, 1.0F}, {1.0F, 0.6F, 0.25F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.4F, 12.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 16, -1},  // campfire-light
    {8, {-6.0F, 0.2788F, 2.0F}, {0.0F, 0.0F, 0.0F}, {1.0F, 1.0F, 1.0F}, {1.0F, 0.5F, 0.2F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, 0, 1, 16.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 16, -1},  // campfire-sfx
    {10, {-3.0F, 0.8362F, 4.0F}, {0.0F, 0.0F, 0.0F}, {0.8F, 1.2F, 0.8F}, {0.4F, 0.75F, 1.0F}, 0, -1, -1, 1, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 1, -1},  // save-shrine
    {0, {10.0F, 2.1965F, -6.0F}, {0.0F, 0.0F, 0.0F}, {1.4F, 3.0F, 0.4F}, {0.5F, 0.2F, 0.8F}, 0, -1, -1, 1, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 1, -1},  // portal-to-cavern
    {13, {11.0F, 2.2965F, -5.7F}, {0.0F, -35.0F, 0.0F}, {1.2F, 1.2F, 1.0F}, {0.6F, 0.6F, 0.6F}, 0, -1, 0, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 16, -1},  // portal-sign
    {11, {38.0F, 1.1841F, -34.0F}, {0.0F, 0.0F, 0.0F}, {1.0F, 1.0F, 1.0F}, {0.9F, 0.8F, 0.2F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 16, -1},  // gate-village
    {11, {-40.0F, 0.9659F, -40.0F}, {0.0F, 0.0F, 0.0F}, {1.0F, 1.0F, 1.0F}, {0.9F, 0.8F, 0.2F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 16, -1},  // gate-ruins
    {2, {16.0F, 3.8402F, 18.0F}, {0.0F, 0.0F, 0.0F}, {0.35F, 1.26F, 0.35F}, {0.33F, 0.22F, 0.12F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 84.0F, -1, "", 1, 1, 1.0F, 8, 0},  // cylinder-2
    {3, {16.0F, 5.3202F, 18.0F}, {0.0F, 0.0F, 0.0F}, {1.7F, 2.1F, 1.7F}, {0.188F, 0.42F, 0.16F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 2, 84.0F, -1, "", 1, 1, 1.0F, 10, 0},  // cone-1
    {2, {22.0F, 3.7402F, 10.0F}, {0.0F, 0.0F, 0.0F}, {0.35F, 1.575F, 0.35F}, {0.33F, 0.22F, 0.12F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 84.0F, -1, "", 1, 1, 1.0F, 8, 0},  // cylinder-3
    {3, {22.0F, 5.6402F, 10.0F}, {0.0F, 0.0F, 0.0F}, {1.7F, 2.625F, 1.7F}, {0.2235F, 0.42F, 0.16F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 2, 84.0F, -1, "", 1, 1, 1.0F, 10, 0},  // cone-2
    {2, {12.0F, 4.3832F, 26.0F}, {0.0F, 0.0F, 0.0F}, {0.35F, 1.89F, 0.35F}, {0.33F, 0.22F, 0.12F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 84.0F, -1, "", 1, 1, 1.0F, 8, 0},  // cylinder-4
    {3, {12.0F, 6.7032F, 26.0F}, {0.0F, 0.0F, 0.0F}, {1.7F, 3.15F, 1.7F}, {0.2076F, 0.42F, 0.16F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 2, 84.0F, -1, "", 1, 1, 1.0F, 10, 0},  // cone-3
    {2, {-14.0F, -0.3331F, 20.0F}, {0.0F, 0.0F, 0.0F}, {0.35F, 1.26F, 0.35F}, {0.33F, 0.22F, 0.12F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 84.0F, -1, "", 1, 1, 1.0F, 8, 0},  // cylinder-5
    {3, {-14.0F, 1.1469F, 20.0F}, {0.0F, 0.0F, 0.0F}, {1.7F, 2.1F, 1.7F}, {0.1926F, 0.42F, 0.16F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 2, 84.0F, -1, "", 1, 1, 1.0F, 10, 0},  // cone-4
    {2, {-22.0F, -2.1483F, 14.0F}, {0.0F, 0.0F, 0.0F}, {0.35F, 1.575F, 0.35F}, {0.33F, 0.22F, 0.12F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 84.0F, -1, "", 1, 1, 1.0F, 8, 0},  // cylinder-6
    {3, {-22.0F, -0.2483F, 14.0F}, {0.0F, 0.0F, 0.0F}, {1.7F, 2.625F, 1.7F}, {0.2156F, 0.42F, 0.16F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 2, 84.0F, -1, "", 1, 1, 1.0F, 10, 0},  // cone-5
    {2, {-8.0F, 0.7355F, 28.0F}, {0.0F, 0.0F, 0.0F}, {0.35F, 1.89F, 0.35F}, {0.33F, 0.22F, 0.12F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 84.0F, -1, "", 1, 1, 1.0F, 8, 0},  // cylinder-7
    {3, {-8.0F, 3.0555F, 28.0F}, {0.0F, 0.0F, 0.0F}, {1.7F, 3.15F, 1.7F}, {0.2128F, 0.42F, 0.16F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 2, 84.0F, -1, "", 1, 1, 1.0F, 10, 0},  // cone-6
    {2, {30.0F, 4.4099F, 6.0F}, {0.0F, 0.0F, 0.0F}, {0.35F, 1.26F, 0.35F}, {0.33F, 0.22F, 0.12F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 84.0F, -1, "", 1, 1, 1.0F, 8, 0},  // cylinder-8
    {3, {30.0F, 5.8899F, 6.0F}, {0.0F, 0.0F, 0.0F}, {1.7F, 2.1F, 1.7F}, {0.1901F, 0.42F, 0.16F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 2, 84.0F, -1, "", 1, 1, 1.0F, 10, 0},  // cone-7
    {2, {-30.0F, -4.4455F, 2.0F}, {0.0F, 0.0F, 0.0F}, {0.35F, 1.575F, 0.35F}, {0.33F, 0.22F, 0.12F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 84.0F, -1, "", 1, 1, 1.0F, 8, 0},  // cylinder-9
    {3, {-30.0F, -2.5455F, 2.0F}, {0.0F, 0.0F, 0.0F}, {1.7F, 2.625F, 1.7F}, {0.2288F, 0.42F, 0.16F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 2, 84.0F, -1, "", 1, 1, 1.0F, 10, 0},  // cone-8
    {2, {18.0F, 1.1284F, -18.0F}, {0.0F, 0.0F, 0.0F}, {0.35F, 1.89F, 0.35F}, {0.33F, 0.22F, 0.12F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 84.0F, -1, "", 1, 1, 1.0F, 8, 0},  // cylinder-10
    {3, {18.0F, 3.4484F, -18.0F}, {0.0F, 0.0F, 0.0F}, {1.7F, 3.15F, 1.7F}, {0.1986F, 0.42F, 0.16F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 2, 84.0F, -1, "", 1, 1, 1.0F, 10, 0},  // cone-9
    {2, {-18.0F, -1.5249F, -16.0F}, {0.0F, 0.0F, 0.0F}, {0.35F, 1.26F, 0.35F}, {0.33F, 0.22F, 0.12F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 84.0F, -1, "", 1, 1, 1.0F, 8, 0},  // cylinder-11
    {3, {-18.0F, -0.0449F, -16.0F}, {0.0F, 0.0F, 0.0F}, {1.7F, 2.1F, 1.7F}, {0.2062F, 0.42F, 0.16F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 2, 84.0F, -1, "", 1, 1, 1.0F, 10, 0},  // cone-10
    {1, {6.0F, 1.5442F, 14.0F}, {0.0F, 0.0F, 0.0F}, {1.1F, 0.88F, 1.1F}, {0.42F, 0.44F, 0.46F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 82.0F, -1, "", 1, 1, 1.0F, 12, -1},  // sphere-1
    {1, {-10.0F, 0.201F, 10.0F}, {0.0F, 0.0F, 0.0F}, {1.6F, 1.28F, 1.6F}, {0.42F, 0.44F, 0.46F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 82.0F, -1, "", 1, 1, 1.0F, 12, -1},  // sphere-2
    {1, {20.0F, 1.6948F, -8.0F}, {0.0F, 0.0F, 0.0F}, {1.3F, 1.04F, 1.3F}, {0.42F, 0.44F, 0.46F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 82.0F, -1, "", 1, 1, 1.0F, 12, -1},  // sphere-3
    {1, {-16.0F, -0.5702F, -6.0F}, {0.0F, 0.0F, 0.0F}, {0.9F, 0.72F, 0.9F}, {0.42F, 0.44F, 0.46F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 82.0F, -1, "", 1, 1, 1.0F, 12, -1},  // sphere-4
    {5, {3.0F, 0.9064F, 6.0F}, {0.0F, 0.0F, 0.0F}, {1.2F, 1.2F, 1.2F}, {0.9F, 0.95F, 0.95F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 2, 0.0F, 0, "Wiggle", 1, 1, 1.0F, 16, -1},  // model-1
    {5, {-2.0F, 0.5092F, 9.0F}, {0.0F, 0.0F, 0.0F}, {1.0F, 1.0F, 1.0F}, {0.9F, 0.95F, 0.95F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 2, 0.0F, 0, "Wiggle", 1, 1, 1.3F, 16, -1},  // model-2
    {7, {0.0F, 12.0F, 0.0F}, {0.0F, 0.0F, 0.0F}, {16.0F, 1.0F, 16.0F}, {0.6F, 0.7F, 0.85F}, 0, -1, -1, 0, 4, 120, 0.12F, 1, 1, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 16, 3},  // rain
    {0, {36.0F, 2.2762F, -39.0F}, {0.0F, 0.0F, 0.0F}, {6.0F, 5.0F, 6.0F}, {0.7F, 0.6F, 0.45F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 1, 1},  // box-2
    {0, {45.0F, 3.3595F, -34.0F}, {0.0F, 0.0F, 0.0F}, {5.0F, 7.0F, 5.0F}, {0.6F, 0.55F, 0.5F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 1, 1},  // box-3
    {0, {38.0F, 2.4039F, -30.0F}, {0.0F, 0.0F, 0.0F}, {7.0F, 4.0F, 4.0F}, {0.72F, 0.62F, 0.4F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 1, 1},  // box-4
    {0, {46.0F, 2.2639F, -42.0F}, {0.0F, 0.0F, 0.0F}, {4.0F, 6.0F, 4.0F}, {0.65F, 0.5F, 0.42F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 1, 1},  // box-5
    {0, {40.0F, 0.4192F, -36.0F}, {0.0F, 0.0F, 0.0F}, {3.0F, 0.3F, 3.0F}, {0.5F, 0.35F, 0.2F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 1, 1},  // box-6
    {2, {37.0F, 1.2731F, -36.0F}, {0.0F, 0.0F, 0.0F}, {0.15F, 2.4F, 0.15F}, {0.2F, 0.16F, 0.12F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 16, 1},  // cylinder-12
    {9, {37.0F, 2.6731F, -36.0F}, {0.0F, 0.0F, 0.0F}, {1.0F, 1.0F, 1.0F}, {1.0F, 0.8F, 0.4F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.1F, 9.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 16, 1},  // point-light-2
    {2, {44.0F, 1.173F, -33.0F}, {0.0F, 0.0F, 0.0F}, {0.15F, 2.4F, 0.15F}, {0.2F, 0.16F, 0.12F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 16, 1},  // cylinder-13
    {9, {44.0F, 2.573F, -33.0F}, {0.0F, 0.0F, 0.0F}, {1.0F, 1.0F, 1.0F}, {1.0F, 0.8F, 0.4F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.1F, 9.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 16, 1},  // point-light-3
    {5, {40.0F, 0.0762F, -35.0F}, {0.0F, 0.0F, 0.0F}, {1.4F, 1.4F, 1.4F}, {0.9F, 0.95F, 0.95F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 2, 0.0F, 0, "Wiggle", 1, 1, 1.1F, 16, 1},  // model-3
    {5, {42.0F, -0.1739F, -37.0F}, {0.0F, 0.0F, 0.0F}, {1.2F, 1.2F, 1.2F}, {0.9F, 0.95F, 0.95F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 2, 0.0F, 0, "Twist", 1, 1, 0.9F, 16, 1},  // model-4
    {7, {45.0F, 7.5192F, -34.0F}, {0.0F, 0.0F, 0.0F}, {0.8F, 1.0F, 0.8F}, {0.4F, 0.4F, 0.4F}, 0, -1, -1, 0, 1, 20, 0.7F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 16, 1},  // chimney-smoke
    {2, {-34.0F, 2.4472F, -40.0F}, {0.0F, 0.0F, 0.0F}, {0.9F, 5.0F, 0.9F}, {0.55F, 0.53F, 0.48F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 12, 2},  // cylinder-14
    {2, {-38.1459F, -0.2751F, -34.2937F}, {0.0F, 0.0F, 0.0F}, {0.9F, 3.5F, 0.9F}, {0.55F, 0.53F, 0.48F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 12, 2},  // cylinder-15
    {2, {-44.8541F, 1.5393F, -36.4733F}, {0.0F, 0.0F, 0.0F}, {0.9F, 6.0F, 0.9F}, {0.55F, 0.53F, 0.48F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 12, 2},  // cylinder-16
    {2, {-44.8541F, 1.0755F, -43.5267F}, {0.0F, 0.0F, 0.0F}, {0.9F, 2.5F, 0.9F}, {0.55F, 0.53F, 0.48F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 12, 2},  // cylinder-17
    {2, {-38.1459F, 3.7857F, -45.7063F}, {0.0F, 0.0F, 0.0F}, {0.9F, 4.5F, 0.9F}, {0.55F, 0.53F, 0.48F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 12, 2},  // cylinder-18
    {7, {-40.0F, 2.4659F, -40.0F}, {0.0F, 0.0F, 0.0F}, {1.5F, 1.0F, 1.5F}, {0.6F, 1.0F, 0.7F}, 0, -1, -1, 0, 3, 40, 0.14F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 16, 2},  // ruins-sparks
    {7, {-40.0F, 0.5659F, -40.0F}, {0.0F, 0.0F, 0.0F}, {8.0F, 1.0F, 8.0F}, {0.55F, 0.7F, 0.6F}, 0, -1, -1, 0, 2, 30, 3.0F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 16, 2},  // ruins-mist
    {9, {-40.0F, 2.4659F, -40.0F}, {0.0F, 0.0F, 0.0F}, {1.0F, 1.0F, 1.0F}, {0.4F, 1.0F, 0.6F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.3F, 14.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 16, 2},  // point-light-4
    {5, {-40.0F, -0.0341F, -40.0F}, {0.0F, 0.0F, 0.0F}, {1.8F, 1.8F, 1.8F}, {0.9F, 0.95F, 0.95F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 2, 0.0F, 0, "Twist", 1, 1, 0.7F, 16, 2},  // model-5
    {1, {-37.0F, 1.3659F, -38.0F}, {0.0F, 0.0F, 0.0F}, {0.7F, 0.7F, 0.7F}, {1.0F, 0.9F, 0.3F}, 0, -1, -1, 1, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 1, 0, 0.0F, -1, "", 1, 1, 1.0F, 18, 2},  // relic-orb
};
// scene "cavern"
constexpr SceneObjectData SCENE_1_OBJECTS[14] = {
    {6, {0.0F, 1.7784F, -20.0F}, {0.0F, 0.0F, 0.0F}, {1.0F, 1.0F, 1.0F}, {0.15F, 0.9F, 0.9F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 16, -1},  // player
    {0, {0.0F, 3.3378F, -26.0F}, {0.0F, 0.0F, 0.0F}, {1.4F, 3.0F, 0.4F}, {0.5F, 0.2F, 0.8F}, 0, -1, -1, 1, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 1, -1},  // portal-to-vale
    {3, {6.0F, 1.7451F, -14.0F}, {0.0F, 0.0F, 0.0F}, {0.9F, 2.0F, 0.9F}, {0.3F, 0.8F, 1.0F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 8, 0},  // cone-11
    {9, {6.0F, 2.7451F, -14.0F}, {0.0F, 0.0F, 0.0F}, {1.0F, 1.0F, 1.0F}, {0.3F, 0.8F, 1.0F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.5F, 11.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 16, 0},  // point-light-5
    {3, {-7.0F, 3.5095F, -12.0F}, {0.0F, 0.0F, 0.0F}, {0.9F, 3.1F, 0.9F}, {0.3F, 0.8F, 1.0F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 8, 0},  // cone-12
    {3, {10.0F, 3.8565F, -4.0F}, {0.0F, 0.0F, 0.0F}, {0.9F, 4.2F, 0.9F}, {0.3F, 0.8F, 1.0F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 8, 0},  // cone-13
    {9, {10.0F, 5.9565F, -4.0F}, {0.0F, 0.0F, 0.0F}, {1.0F, 1.0F, 1.0F}, {0.3F, 0.8F, 1.0F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.5F, 11.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 16, 0},  // point-light-6
    {3, {-11.0F, 2.3571F, -6.0F}, {0.0F, 0.0F, 0.0F}, {0.9F, 2.0F, 0.9F}, {0.3F, 0.8F, 1.0F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 8, 0},  // cone-14
    {3, {3.0F, 3.0773F, 2.0F}, {0.0F, 0.0F, 0.0F}, {0.9F, 3.1F, 0.9F}, {0.3F, 0.8F, 1.0F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 8, 0},  // cone-15
    {9, {3.0F, 4.6273F, 2.0F}, {0.0F, 0.0F, 0.0F}, {1.0F, 1.0F, 1.0F}, {0.3F, 0.8F, 1.0F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.5F, 11.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 16, 0},  // point-light-7
    {3, {-4.0F, 2.8023F, 4.0F}, {0.0F, 0.0F, 0.0F}, {0.9F, 4.2F, 0.9F}, {0.3F, 0.8F, 1.0F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 8, 0},  // cone-16
    {7, {0.0F, 1.43F, -6.0F}, {0.0F, 0.0F, 0.0F}, {20.0F, 1.0F, 20.0F}, {0.4F, 0.5F, 0.7F}, 0, -1, -1, 0, 2, 40, 4.0F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 16, 0},  // cave-fog
    {7, {2.0F, 2.93F, -8.0F}, {0.0F, 0.0F, 0.0F}, {10.0F, 1.0F, 10.0F}, {0.7F, 1.0F, 0.6F}, 0, -1, -1, 0, 3, 30, 0.1F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, -1, "", 1, 1, 1.0F, 16, 0},  // fireflies
    {5, {0.0F, 0.9002F, -8.0F}, {0.0F, 0.0F, 0.0F}, {1.6F, 1.6F, 1.6F}, {0.9F, 0.95F, 0.95F}, 0, -1, -1, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 2, 0.0F, 0, "Twist", 1, 1, 0.6F, 16, 0},  // model-6
};

constexpr int SCENE_OBJECT_COUNTS[SCENE_COUNT] = {60, 14};
inline const SceneObjectData* SCENE_OBJECT_TABLES[SCENE_COUNT] = {SCENE_0_OBJECTS, SCENE_1_OBJECTS};

constexpr unsigned long long SCENE_0_OBJECT_ID_HASHES[60] = {0xd9dcdb32b73feb70ULL, 0x580466f2787a1530ULL, 0x9311a917d523fbf6ULL, 0x995000570f4f4334ULL, 0x88bc5ec7b182dad3ULL, 0xa183fce02c07d2d1ULL, 0x7dbeac9a2873ea08ULL, 0x1b9609e52b0b437cULL, 0xf35d41a24e27af45ULL, 0x0c69b388796b0e89ULL, 0x7984d5a3f29517b9ULL, 0x118b2a8f7c342dc7ULL, 0xdd9a5e4859644172ULL, 0x0587c349f7e4007cULL, 0x6231be6218add6feULL, 0xb4e4105fe9f6b715ULL, 0xcad26e81b81b1022ULL, 0x64a751a0aa03a4f0ULL, 0x88201a4e92a82a1aULL, 0xd0a9f5f0595a18cbULL, 0x5c94e1405acf4db7ULL, 0x25719986b039b8bfULL, 0xb5aad98e5dd868c9ULL, 0x13754908f82a0e2fULL, 0x2f74c701af66eb3dULL, 0x32f3718282919b22ULL, 0xe87383fdf8164aebULL, 0x247bdf685a7441feULL, 0x1eb55684583dac65ULL, 0x79fb9051d516cc2eULL, 0x734fe2985e9a4386ULL, 0x1698da25404fd33bULL, 0x41a2bffdd80747feULL, 0x5e082e130666f17eULL, 0x30ba0e237136fa47ULL, 0x0b896bb536660e7dULL, 0x3e25f8091b69f93cULL, 0x53c6c8bc75338de4ULL, 0xd21972f3e56d82b5ULL, 0xa533d208b3b1eaeeULL, 0x65a40a2865e245a5ULL, 0xb9834c6db35c60e3ULL, 0x394f58bb1cda2cedULL, 0xb2f6ea12bb1ff97eULL, 0xb77571e0512dc475ULL, 0xb5790a871bdcd659ULL, 0x7ebb0004976d17caULL, 0xfd8aab0c5ce95279ULL, 0xd8d296b4b400524aULL, 0xc5df021d33df45f5ULL, 0x615f602d046ee9d4ULL, 0x24987bd8c518b897ULL, 0x1b1b92a235a35425ULL, 0x3ddd89f917a2dc06ULL, 0x868eb40cfd3f78d8ULL, 0x307011be939f54bdULL, 0x8f54867811c5d3e6ULL, 0x09110107c82942ddULL, 0xbe72a4bf9cfb0994ULL, 0x25d0043245caf981ULL};
constexpr unsigned long long SCENE_1_OBJECT_ID_HASHES[14] = {0x4988a18b7bcdfc16ULL, 0x0dc345608a0641e1ULL, 0xf2a96ee9f285b9f8ULL, 0xabee7e6cc5cbff26ULL, 0xb62185af60613628ULL, 0xe5b45f5fa46e0053ULL, 0x355e48314be2243dULL, 0xdc3a0ad008c5ca65ULL, 0x841d7d8708dd286eULL, 0x6af0f9d96c86c357ULL, 0x477753c0f0d099caULL, 0xd38c45d0f819463aULL, 0x26822ad53d1e7f78ULL, 0xd473ad5ea73cf17eULL};
inline const unsigned long long* SCENE_OBJECT_ID_TABLES[SCENE_COUNT] = {SCENE_0_OBJECT_ID_HASHES, SCENE_1_OBJECT_ID_HASHES};

constexpr int SCENE_LAYER_COUNTS[SCENE_COUNT] = {4, 1};
constexpr int SCENE_MAX_LAYERS = 4;
constexpr bool SCENE_LAYER_STARTS[SCENE_COUNT][SCENE_MAX_LAYERS] = {{true, false, false, true}, {true, true, true, true}};
constexpr float SCENE_LAYER_STREAM_XS[SCENE_COUNT][SCENE_MAX_LAYERS] = {{0.0F, 0.0F, 0.0F, 0.0F}, {0.0F, 0.0F, 0.0F, 0.0F}};
constexpr float SCENE_LAYER_STREAM_ZS[SCENE_COUNT][SCENE_MAX_LAYERS] = {{0.0F, 0.0F, 0.0F, 0.0F}, {0.0F, 0.0F, 0.0F, 0.0F}};
constexpr float SCENE_LAYER_STREAM_RADII[SCENE_COUNT][SCENE_MAX_LAYERS] = {{0.0F, 0.0F, 0.0F, 0.0F}, {0.0F, 0.0F, 0.0F, 0.0F}};

// Mirrors (type 15): each entry re-draws its target objects
// reflected across the mirror plane (renderMirrors in the game
// cpp). Targets index the mirror's own scene object table.
struct MirrorData {
  int scene;          // scene index
  int object;         // the mirror's index in its scene table
  float opacity;      // glass alpha 0..1 (tint = object color)
  int reflectPlayer;  // 1 = also reflect the third-person avatar
  int firstTarget;    // first entry in MIRROR_TARGETS
  int targetCount;
};
constexpr int MIRROR_COUNT = 0;
constexpr MirrorData MIRRORS[1] = {
    {0, -1, 0.0F, 0, 0, 0}
};
constexpr int MIRROR_TARGETS[1] = {-1};

constexpr int SND_COUNT = 1;
inline const char* SND_PATHS[1] = {"sfx/fire.adpcm"};

constexpr int PLAYER_INDEXES[SCENE_COUNT] = {0, 0};
constexpr int PLAYER_MODES[SCENE_COUNT] = {0, 0};
constexpr float PLAYER_WALK_SPEEDS[SCENE_COUNT] = {0.5F, 0.42F};
constexpr float PLAYER_LOOK_SPEEDS[SCENE_COUNT] = {1.0F, 1.0F};
constexpr float PLAYER_EYE_HEIGHTS[SCENE_COUNT] = {1.8F, 1.8F};
constexpr float PLAYER_JUMP_SPEEDS[SCENE_COUNT] = {4.5F, 4.5F};
constexpr bool PLAYER_CAN_JUMPS[SCENE_COUNT] = {true, true};
constexpr float PLAYER_RUN_THRESHOLDS[SCENE_COUNT] = {0.55F, 0.55F};
constexpr float PLAYER_CAM_DISTS[SCENE_COUNT] = {6.0F, 6.0F};
constexpr float PLAYER_CAM_HEIGHTS[SCENE_COUNT] = {1.6F, 1.6F};
constexpr float PLAYER_CAM_SHOULDERS[SCENE_COUNT] = {0.0F, 0.0F};
constexpr float PLAYER_TURN_RATES[SCENE_COUNT] = {0.25F, 0.25F};
constexpr const char* PLAYER_IDLE_CLIPS[SCENE_COUNT] = {"", ""};
constexpr const char* PLAYER_WALK_CLIPS[SCENE_COUNT] = {"", ""};
constexpr const char* PLAYER_RUN_CLIPS[SCENE_COUNT] = {"", ""};
constexpr const char* PLAYER_JUMP_CLIPS[SCENE_COUNT] = {"", ""};

constexpr float TERRAIN_WIDTHS[SCENE_COUNT] = {192.0F, 64.0F};
constexpr float TERRAIN_DEPTHS[SCENE_COUNT] = {192.0F, 64.0F};
constexpr float SCENE_LIGHT_XS[SCENE_COUNT] = {0.542677F, 0.449439F};
constexpr float SCENE_LIGHT_YS[SCENE_COUNT] = {0.455849F, 0.399501F};
constexpr float SCENE_LIGHT_ZS[SCENE_COUNT] = {-0.705481F, 0.799002F};
constexpr float SCENE_AMBIENTS[SCENE_COUNT] = {0.4F, 0.15F};
constexpr float SCENE_DIFFUSES[SCENE_COUNT] = {0.7F, 0.35F};
constexpr float SCENE_LIGHT_COL_RS[SCENE_COUNT] = {1.0F, 0.6F};
constexpr float SCENE_LIGHT_COL_GS[SCENE_COUNT] = {0.82F, 0.75F};
constexpr float SCENE_LIGHT_COL_BS[SCENE_COUNT] = {0.6F, 1.0F};
constexpr float SCENE_BRIGHTNESSES[SCENE_COUNT] = {1.0F, 0.9F};
constexpr bool CLIP_PRECISES[SCENE_COUNT] = {true, true};
constexpr bool CLIP_VU1S[SCENE_COUNT] = {false, false};
constexpr float SKY_RS[SCENE_COUNT] = {219.3F, 12.75F};
constexpr float SKY_GS[SCENE_COUNT] = {127.5F, 15.3F};
constexpr float SKY_BS[SCENE_COUNT] = {81.6F, 30.6F};
constexpr bool SKY_DOMES[SCENE_COUNT] = {true, true};
constexpr float SKY_ZENITH_EXPS[SCENE_COUNT] = {1.0F, 1.0F};
constexpr float SKY_TOP_RS[SCENE_COUNT] = {25.5F, 5.1F};
constexpr float SKY_TOP_GS[SCENE_COUNT] = {40.8F, 5.1F};
constexpr float SKY_TOP_BS[SCENE_COUNT] = {107.1F, 15.3F};
constexpr int POSTFX_BLOOMS[SCENE_COUNT] = {20, 64};
constexpr int POSTFX_GRAINS[SCENE_COUNT] = {12, 32};
constexpr int POSTFX_DOFS[SCENE_COUNT] = {0, 0};
constexpr float POSTFX_DOF_FOCUSES[SCENE_COUNT] = {20.0F, 20.0F};
constexpr float POSTFX_DOF_RANGES[SCENE_COUNT] = {15.0F, 15.0F};
constexpr bool FOG_ENABLEDS[SCENE_COUNT] = {true, true};
constexpr float FOG_RS[SCENE_COUNT] = {209.1F, 15.3F};
constexpr float FOG_GS[SCENE_COUNT] = {140.25F, 20.4F};
constexpr float FOG_BS[SCENE_COUNT] = {102.0F, 40.8F};
constexpr float FOG_STARTS[SCENE_COUNT] = {20.0F, 4.0F};
constexpr float FOG_ENDS[SCENE_COUNT] = {82.0F, 42.0F};
constexpr bool FLASHLIGHT_ENABLEDS[SCENE_COUNT] = {false, true};
constexpr float FLASHLIGHT_RS[SCENE_COUNT] = {115.2F, 89.6F};
constexpr float FLASHLIGHT_GS[SCENE_COUNT] = {108.8F, 102.4F};
constexpr float FLASHLIGHT_BS[SCENE_COUNT] = {76.8F, 128.0F};
constexpr float FLASHLIGHT_RANGES[SCENE_COUNT] = {34.0F, 30.0F};
constexpr float FLASHLIGHT_ANGLES[SCENE_COUNT] = {22.0F, 24.0F};
constexpr bool HIGHLIGHT_USABLES[SCENE_COUNT] = {true, true};
constexpr float HIGHLIGHT_DISTANCES[SCENE_COUNT] = {6.0F, 6.0F};
constexpr float HIGHLIGHT_RS[SCENE_COUNT] = {255.0F, 255.0F};
constexpr float HIGHLIGHT_GS[SCENE_COUNT] = {216.75F, 216.75F};
constexpr float HIGHLIGHT_BS[SCENE_COUNT] = {76.5F, 76.5F};
constexpr float HIGHLIGHT_WIDTHS[SCENE_COUNT] = {0.19F, 0.19F};
constexpr int HIGHLIGHT_STEPS_S[SCENE_COUNT] = {4, 4};
constexpr float HIGHLIGHT_OPACITIES[SCENE_COUNT] = {0.15F, 0.15F};
constexpr bool HIGHLIGHT_OVERLAYS[SCENE_COUNT] = {true, true};

constexpr int GRADING_COUNT = 2;
inline const char* GRADING_NAMES[GRADING_COUNT > 0 ? GRADING_COUNT : 1] = {"Golden Hour", "Nightfall"};
constexpr unsigned char GRADING_GAINS[GRADING_COUNT > 0 ? GRADING_COUNT : 1][3] = {{171, 148, 124}, {105, 127, 168}};
constexpr short GRADING_LIFTS[GRADING_COUNT > 0 ? GRADING_COUNT : 1][3] = {{-10, -15, -20}, {-31, -26, -15}};
constexpr unsigned char GRADING_MIX_COLORS[GRADING_COUNT > 0 ? GRADING_COUNT : 1][3] = {{255, 179, 102}, {110, 145, 215}};
constexpr unsigned char GRADING_MIX_AMTS[GRADING_COUNT > 0 ? GRADING_COUNT : 1] = {23, 46};
constexpr int GRADING_DEFAULT = 0;

// Template so this header stays engine-include-free; instantiated
// where Tyra::Engine is complete. index -1 (or any out of range)
// is a no-op.
template <typename TEngine>
inline void applySceneGrading(TEngine* engine, int index) {
  if (index < 0 || index >= GRADING_COUNT) return;
  engine->renderer.core.postFx.setGrading(
      GRADING_GAINS[index], GRADING_LIFTS[index],
      GRADING_MIX_COLORS[index], GRADING_MIX_AMTS[index]);
}

constexpr int SAVE_VALUE_COUNT = 5;
inline const char* SAVE_VALUE_NAMES[SAVE_VALUE_COUNT > 0 ? SAVE_VALUE_COUNT : 1] = {"orbs", "gfx-fog", "gfx-grain", "gfx-bloom", "gfx-part"};
constexpr float SAVE_VALUE_DEFAULTS[SAVE_VALUE_COUNT > 0 ? SAVE_VALUE_COUNT : 1] = {0.0F, 1.0F, 1.0F, 1.0F, 1.0F};
constexpr int SAVE_TEXT_COUNT = 0;
constexpr int SAVE_TEXT_LEN = 32;  // incl. the terminating NUL
inline const char* SAVE_TEXT_NAMES[SAVE_TEXT_COUNT > 0 ? SAVE_TEXT_COUNT : 1] = {""};
inline const char* SAVE_TEXT_DEFAULTS[SAVE_TEXT_COUNT > 0 ? SAVE_TEXT_COUNT : 1] = {""};
constexpr int SAVE_OBJECT_MAX = 60;

}  // namespace Showcase

// Index of the scene the game is currently in (defined in the game cpp).
extern int g_activeScene;

// Wall-clock normalization (defined in the game cpp, set at init from the
// video mode): the game logic is tuned per-frame at PAL's 50 Hz, so on a
// 60 Hz NTSC signal every per-frame step is multiplied by g_frameScale
// (50/60) to cover the same distance per real second. g_frameDt is the real
// seconds-per-frame for code that works in units/s.
extern float g_frameRate;   // vsync rate: 50 (PAL) or 60 (NTSC)
extern float g_frameDt;     // 1 / g_frameRate
extern float g_frameScale;  // 50 / g_frameRate

// Camera flashlight runtime state (a Player object property), defined in the
// game cpp. g_flashEnabled is the master switch (Set Flashlight flow node);
// g_flashOn is the on/off toggle state the player controls with the optional
// toggle button. The beam shows only while both are set.
extern bool g_flashEnabled;
extern bool g_flashOn;
template <typename TEngine>
inline bool flashlightTogglePressed(TEngine* engine) {
  (void)engine;
  switch (g_activeScene) {
    case 0: return engine->pad.getClicked().Circle;
    case 1: return engine->pad.getClicked().Circle;
    default: break;
  }
  return false;
}
// Frames per `seconds` of wall-clock time (>= 1), for frame-counter timers.
inline int everyFrames(float seconds) {
  const int f = (int)(seconds * g_frameRate);
  return f < 1 ? 1 : f;
}
#define SCENE_OBJECT_COUNT SCENE_OBJECT_COUNTS[g_activeScene]
#define SCENE_OBJECTS SCENE_OBJECT_TABLES[g_activeScene]
#define SCENE_LAYER_COUNT SCENE_LAYER_COUNTS[g_activeScene]
#define SCENE_LAYER_START SCENE_LAYER_STARTS[g_activeScene]
#define SCENE_LAYER_STREAM_X SCENE_LAYER_STREAM_XS[g_activeScene]
#define SCENE_LAYER_STREAM_Z SCENE_LAYER_STREAM_ZS[g_activeScene]
#define SCENE_LAYER_STREAM_R SCENE_LAYER_STREAM_RADII[g_activeScene]
#define PLAYER_INDEX PLAYER_INDEXES[g_activeScene]
#define PLAYER_MODE PLAYER_MODES[g_activeScene]
#define PLAYER_WALK_SPEED PLAYER_WALK_SPEEDS[g_activeScene]
#define PLAYER_LOOK_SPEED PLAYER_LOOK_SPEEDS[g_activeScene]
#define PLAYER_EYE_HEIGHT PLAYER_EYE_HEIGHTS[g_activeScene]
#define PLAYER_JUMP_SPEED PLAYER_JUMP_SPEEDS[g_activeScene]
#define PLAYER_CAN_JUMP PLAYER_CAN_JUMPS[g_activeScene]
#define PLAYER_RUN_THRESHOLD PLAYER_RUN_THRESHOLDS[g_activeScene]
#define PLAYER_CAM_DIST PLAYER_CAM_DISTS[g_activeScene]
#define PLAYER_CAM_HEIGHT PLAYER_CAM_HEIGHTS[g_activeScene]
#define PLAYER_CAM_SHOULDER PLAYER_CAM_SHOULDERS[g_activeScene]
#define PLAYER_TURN_RATE PLAYER_TURN_RATES[g_activeScene]
#define PLAYER_IDLE_CLIP PLAYER_IDLE_CLIPS[g_activeScene]
#define PLAYER_WALK_CLIP PLAYER_WALK_CLIPS[g_activeScene]
#define PLAYER_RUN_CLIP PLAYER_RUN_CLIPS[g_activeScene]
#define PLAYER_JUMP_CLIP PLAYER_JUMP_CLIPS[g_activeScene]
#define TERRAIN_WIDTH TERRAIN_WIDTHS[g_activeScene]
#define TERRAIN_DEPTH TERRAIN_DEPTHS[g_activeScene]
#define SCENE_LIGHT_X SCENE_LIGHT_XS[g_activeScene]
#define SCENE_LIGHT_Y SCENE_LIGHT_YS[g_activeScene]
#define SCENE_LIGHT_Z SCENE_LIGHT_ZS[g_activeScene]
#define SCENE_AMBIENT SCENE_AMBIENTS[g_activeScene]
#define SCENE_DIFFUSE SCENE_DIFFUSES[g_activeScene]
#define SCENE_LIGHT_COL_R SCENE_LIGHT_COL_RS[g_activeScene]
#define SCENE_LIGHT_COL_G SCENE_LIGHT_COL_GS[g_activeScene]
#define SCENE_LIGHT_COL_B SCENE_LIGHT_COL_BS[g_activeScene]
#define SCENE_BRIGHTNESS SCENE_BRIGHTNESSES[g_activeScene]
#define HM_W HM_WS[g_activeScene]
#define HM_D HM_DS[g_activeScene]
#define TERRAIN_HEIGHTS TERRAIN_HEIGHTS_TABLES[g_activeScene]
#define TERRAIN_TEXTURE TERRAIN_TEXTURES[g_activeScene]
#define TERRAIN_TILE_U TERRAIN_TILE_US[g_activeScene]
#define TERRAIN_TILE_V TERRAIN_TILE_VS[g_activeScene]
#define TERRAIN_HAS_MATERIAL TERRAIN_HAS_MATERIALS[g_activeScene]
#define TERRAIN_TINT_R TERRAIN_TINTS[g_activeScene][0]
#define TERRAIN_TINT_G TERRAIN_TINTS[g_activeScene][1]
#define TERRAIN_TINT_B TERRAIN_TINTS[g_activeScene][2]
// Per-scene sky / clipping / post-FX / usable-highlight (Scene > Preferences)
#define CLIP_PRECISE CLIP_PRECISES[g_activeScene]
#define CLIP_VU1 CLIP_VU1S[g_activeScene]
#define SKY_R SKY_RS[g_activeScene]
#define SKY_G SKY_GS[g_activeScene]
#define SKY_B SKY_BS[g_activeScene]
#define SKY_DOME SKY_DOMES[g_activeScene]
#define SKY_ZENITH_EXP SKY_ZENITH_EXPS[g_activeScene]
#define SKY_TOP_R SKY_TOP_RS[g_activeScene]
#define SKY_TOP_G SKY_TOP_GS[g_activeScene]
#define SKY_TOP_B SKY_TOP_BS[g_activeScene]
#define POSTFX_BLOOM POSTFX_BLOOMS[g_activeScene]
#define POSTFX_GRAIN POSTFX_GRAINS[g_activeScene]
#define POSTFX_DOF POSTFX_DOFS[g_activeScene]
#define POSTFX_DOF_FOCUS POSTFX_DOF_FOCUSES[g_activeScene]
#define POSTFX_DOF_RANGE POSTFX_DOF_RANGES[g_activeScene]
#define FOG_ENABLED FOG_ENABLEDS[g_activeScene]
#define FOG_R FOG_RS[g_activeScene]
#define FOG_G FOG_GS[g_activeScene]
#define FOG_B FOG_BS[g_activeScene]
#define FOG_START FOG_STARTS[g_activeScene]
#define FOG_END FOG_ENDS[g_activeScene]
#define FLASHLIGHT_ENABLED FLASHLIGHT_ENABLEDS[g_activeScene]
#define FLASHLIGHT_R FLASHLIGHT_RS[g_activeScene]
#define FLASHLIGHT_G FLASHLIGHT_GS[g_activeScene]
#define FLASHLIGHT_B FLASHLIGHT_BS[g_activeScene]
#define FLASHLIGHT_RANGE FLASHLIGHT_RANGES[g_activeScene]
#define FLASHLIGHT_ANGLE FLASHLIGHT_ANGLES[g_activeScene]
#define HIGHLIGHT_USABLE HIGHLIGHT_USABLES[g_activeScene]
#define HIGHLIGHT_DISTANCE HIGHLIGHT_DISTANCES[g_activeScene]
#define HIGHLIGHT_R HIGHLIGHT_RS[g_activeScene]
#define HIGHLIGHT_G HIGHLIGHT_GS[g_activeScene]
#define HIGHLIGHT_B HIGHLIGHT_BS[g_activeScene]
#define HIGHLIGHT_WIDTH HIGHLIGHT_WIDTHS[g_activeScene]
#define HIGHLIGHT_STEPS HIGHLIGHT_STEPS_S[g_activeScene]
#define HIGHLIGHT_OPACITY HIGHLIGHT_OPACITIES[g_activeScene]
#define HIGHLIGHT_OVERLAY HIGHLIGHT_OVERLAYS[g_activeScene]
#define terrainHeightAt(x, z) terrainHeightAtScene(g_activeScene, (x), (z))
