// Generated by tyra-editor. Delete this line to take ownership of this file.
#pragma once

#include <tyra>
#include <map>
#include <memory>
#include <string>
#include <vector>
#include "save_system.gen.hpp"
#include "scripts/script.hpp"

namespace Showcase {

class TerrainGame : public Tyra::Game {
 public:
  explicit TerrainGame(Tyra::Engine* engine);
  ~TerrainGame();

  void init() override;
  void loop() override;

 private:
  void buildScene();
  void resetTerrainChunks();
  void buildTerrainChunk(int slot, int cx, int cz);
  void updateTerrainChunks(float focusX, float focusZ, int budget);
  void renderTerrain();
  void updatePlayer();

  Tyra::Engine* engine;
  Tyra::StaticPipeline stapip;

  Tyra::Vec4 cameraPosition, cameraLookAt;
  float playerX, playerZ, yaw, pitch;
  float playerY, playerVelY;  // feet height + vertical velocity (physics)

  // Terrain chunks: the heightmap grid is cut into TERRAIN_CHUNK_CELLS-sized
  // square tiles, one StaPip bag each (see the chunk functions in the .cpp).
  // Slots live in a pool sized once per scene load (resetTerrainChunks) and
  // never move afterwards - each bag points into its own slot's vectors.
  struct TerrainChunk {
    std::vector<Tyra::Vec4> vertices;
    std::vector<Tyra::Color> colors;
    std::vector<Tyra::Vec4> sts;  // texture coordinates (textured terrain)
    std::unique_ptr<Tyra::StaPipBag> bag;
    std::unique_ptr<Tyra::StaPipColorBag> colorBag;
    Tyra::StaPipTextureBag texBag;
    int cx = -1, cz = -1;  // chunk coords; -1 = free pool slot
  };
  std::vector<TerrainChunk> terrainChunks;  // slot pool
  std::vector<short> terrainChunkSlot;      // chunk index -> slot, -1 = unbuilt
  int terrainChunksX = 0, terrainChunksZ = 0;

  Tyra::M4x4 model;
  std::unique_ptr<Tyra::StaPipInfoBag> infoBag;  // shared by all chunk bags

  // Scene objects at runtime (mutable by scripts/physics); geometry per
  // object, one draw part per model material (primitives use parts[0])
  struct GeoPart {
    std::vector<Tyra::Vec4> vertices;
    std::vector<Tyra::Color> colors;
    std::vector<Tyra::Vec4> sts;  // texture coordinates
    std::unique_ptr<Tyra::StaPipBag> bag;
    std::unique_ptr<Tyra::StaPipInfoBag> infoBag;
    std::unique_ptr<Tyra::StaPipColorBag> colorBag;
    std::unique_ptr<Tyra::StaPipTextureBag> texBag;
  };
  struct ObjectGeometry {
    std::vector<GeoPart> parts;
    // Animated models (.glb): this object's skeletal instance (own
    // playback state + skinned output mesh, samples the shared SkelModel).
    std::unique_ptr<Tyra::SkelInstance> animInst;
    // StaPip bags pointing straight into animInst's skinned arrays; the
    // skinned vertices stay in model space, so the object transform rides
    // in animMat (info bag + light matrix), not in the vertex data.
    struct AnimPart {
      std::unique_ptr<Tyra::StaPipBag> bag;
      std::unique_ptr<Tyra::StaPipColorBag> colorBag;
      std::unique_ptr<Tyra::StaPipTextureBag> texBag;
      std::unique_ptr<Tyra::StaPipLightingBag> lightBag;
      // The lit StaPip VU1 programs (_d/_td) derive the vertex color purely
      // from the directional lights - they never read a base/vertex color -
      // so an untextured mesh would render in the plain scene light color
      // (i.e. gray). This part's material albedo is folded into its own light
      // and ambient colors instead (outputColor = albedo * sceneLighting),
      // matching how the editor viewport tints the .glb. Directions stay
      // shared (animLightDirs); only the colors carry the per-part tint.
      std::unique_ptr<Tyra::PipelineDirLightsBag> animLights;
      Tyra::Vec4 litColors[4];
    };
    std::vector<AnimPart> animParts;
    std::unique_ptr<Tyra::StaPipInfoBag> animInfoBag;
    Tyra::M4x4 animMat;
    u32 animLastTick = 0;  // animLodTick of the last in-view frame; 0 = never
    // Usable-object highlight: fading shells grown around the object
    // center, drawn after the scene (see renderHighlightHull)
    std::vector<Tyra::Vec4> hullVerts;
    std::vector<Tyra::Color> hullCols;
    std::unique_ptr<Tyra::StaPipBag> hullBag;
    std::unique_ptr<Tyra::StaPipInfoBag> hullInfoBag;
    std::unique_ptr<Tyra::StaPipColorBag> hullColorBag;
  };
  // Custom .obj models (paths in model_data.gen.hpp): geometry split per MTL
  // material with optional per-material textures, the real mesh AABB for box
  // collision, a CollisionMesh for mesh collision. Loaded on demand by the
  // layer streaming - only models some resident layer uses stay in memory.
  struct GameModelPart {
    std::vector<float> verts;  // 8 floats per vertex: x,y,z,nx,ny,nz,u,v
    Tyra::Texture* texture = nullptr;
    float kd[3] = {1.0F, 1.0F, 1.0F};
  };
  struct GameModel {
    std::vector<GameModelPart> parts;  // empty = missing/unparseable model
    float mn[3] = {-0.5F, -0.5F, -0.5F};
    float mx[3] = {0.5F, 0.5F, 0.5F};
    Tyra::CollisionMesh collider;  // built only when a scene needs mesh mode
    std::vector<std::string> texPaths;  // texture-cache refs this model holds
  };
  std::vector<GameModel> gameModels;
  void loadModelAsset(int index);
  void freeModelAsset(int index);
  // Animated .glb models: serialized by the editor to .tskl skeletal files
  // (paths in model_data.gen.hpp) - bone keyframe tracks + bind-pose mesh.
  // Poses are evaluated and skinned on the EE/VU0 (SkelInstance) for the
  // in-view instances only; the skinned arrays render through the SAME
  // static pipeline as the rest of the scene (single vertex upload, no VU1
  // program swap, EE clipping). See updateAndRenderAnimObjects for the
  // real-hardware numbers behind this design - PCSX2's fast EE hides them.
  struct GameAnimModel {
    std::unique_ptr<Tyra::SkelModel> src;   // skeleton + mesh + clip tracks
    std::vector<Tyra::Texture*> textures;   // per part, nullptr = untextured
    std::vector<std::string> texPaths;      // texture-cache refs held
    Tyra::CoreBBox cullBox;  // local AABB over all clips + margin (see load)
  };
  std::vector<GameAnimModel> gameAnimModels;
  void loadAnimModelAsset(int index);
  void freeAnimModelAsset(int index);
  void setupAnimObject(int index);  // per-object instance + playback state
  void updateAndRenderAnimObjects();
  // Directional light for the animated pass, mirroring the baked static
  // look. The manual dir-lights layout: colors[0..2] + ambient in [3].
  Tyra::Vec4 animLightColors[4];
  Tyra::Vec4 animLightDirs[3];
  Tyra::PipelineDirLightsBag animDirLights{true};
  u32 animLodTick = 0;  // frame counter for the ANIM_LOD_DISTANCE stagger

 public:
  // Clip-name lookup for scripts/flow graph (ScriptContext::resolveClip).
  int resolveClipIndex(int objectIndex, const char* clipName) const;

 private:
  // Primitive materials: .mtl assigned to a box/sphere/... - the file's
  // first material supplies the color (kd) and optional texture.
  struct GameMaterial {
    Tyra::Texture* texture = nullptr;
    float kd[3] = {1.0F, 1.0F, 1.0F};
    std::string texPath;  // texture-cache ref held ("" = untextured)
  };
  std::vector<GameMaterial> gameMaterials;
  void loadMaterialAsset(int index);
  void freeMaterialAsset(int index);
  std::vector<Tyra::Texture*> loadedTextures;

  // Streaming layers (SCENE_LAYER_* tables): an asset is resident only while
  // some active-scene object in a resident layer (or with no layer) uses it.
  // Load Layer queues the layer's missing assets and the queue drains one
  // asset per frame (loads spread out - no long stall); Unload Layer drops
  // the layer's objects immediately and frees whatever nothing else needs.
  // Textures shared between layers/models are reference-counted by path.
  struct TexEntry {
    Tyra::Texture* tex = nullptr;
    int refs = 0;
  };
  std::map<std::string, TexEntry> texCache;
  Tyra::Texture* acquireTexture(const std::string& path);
  void releaseTexture(const std::string& path);
  void loadSceneTexture(int index);
  void freeSceneTexture(int index);
  std::vector<unsigned char> modelLoaded, materialLoaded, animModelLoaded,
      sceneTexLoaded;
  bool layerOn(int layer) const;  // desired residency of an object's layer
  void applyLayerResidency();     // free unneeded assets, queue missing ones
  void processOneStreamJob();
  void activateObject(int index);
  void deactivateObject(int index);
  void updateLayerStreaming();
  std::vector<unsigned char> layerState;   // 0 unloaded, 1 loading, 2 loaded
  std::vector<unsigned char> layerTarget;  // desired residency per layer
  std::vector<signed char> layerRequest;   // script requests (-1 = none)
  std::vector<int> streamQueue;            // (kind << 16) | asset index
  std::vector<RuntimeObject> runtimeObjects;
  std::vector<ObjectGeometry> objectGeometry;
  GeoPart skyDome;
  float skyHorizonR = 0, skyHorizonG = 0, skyHorizonB = 0;
  std::vector<Tyra::Sprite> hudSprites;

  void buildSkyDome();
  void rebuildObjectGeometry(int index);
  // Player-vs-objects collision shared by both walkers: box (scale box or
  // model AABB), mesh (CollisionMesh) or none, per SceneObjectData.collision.
  // ceiling receives the lowest overhead surface so the walkers can keep the
  // camera from poking into geometry from below (jump clamp).
  void collidePlayer(float prevX, float prevZ, float* nextX, float* nextZ,
                     float feetY, float eyeHeight, float* ground,
                     float* ceiling);
  void updateObjectPhysics();
  void renderScene();
  void renderHighlightHull(int index);

  // Player entity (PLAYER_INDEXES in scene_data.hpp); overrides the template
  // camera when present. Returns false when the scene has no player.
  bool updatePlayerEntity();
  float entX = 0, entY = 0, entZ = 0, entVelY = 0, entYaw = 0, entPitch = 0;

  // Multiple scenes: the game starts in scene 0; the flow graph Switch
  // Scene node requests a change applied between frames.
  void loadScene(int sceneIndex);
  int currentScene = 0;
  unsigned int sceneGeneration = 0;

  // Particle emitters (type 7): fixed pools sized at scene load, zero
  // per-frame allocations; camera-facing quads (textured when the emitter
  // has a material with a map_Kd), one bag per emitter.
  struct ParticleSystem {
    int objectIndex = -1;
    unsigned int rng = 1;
    std::vector<Tyra::Vec4> pos, vel;
    std::vector<float> life, maxLife;
    std::vector<Tyra::Vec4> verts;
    std::vector<Tyra::Color> cols;
    std::vector<Tyra::Vec4> sts;  // fixed per-quad UVs (textured emitters)
    std::unique_ptr<Tyra::StaPipBag> bag;
    std::unique_ptr<Tyra::StaPipInfoBag> infoBag;
    std::unique_ptr<Tyra::StaPipColorBag> colorBag;
    std::unique_ptr<Tyra::StaPipTextureBag> texBag;
  };
  std::vector<ParticleSystem> particles;
  void buildParticles();
  void updateParticles();

  // Sound emitters (type 8): distance-attenuated one-shots on channels 16-23
  std::vector<audsrv_adpcm_t*> sndSamples;  // scene_data.hpp SND_PATHS order
  std::vector<int> sndTimers;               // per-object retrigger countdown
  void updateSoundEmitters();

  // Scene switches show res/hud/loading.png on black for a moment
  Tyra::Sprite loadingSprite;
  int loadingFrames = 0, loadingTarget = -1;

  // "Use" interaction: nearest usable object the camera looks at (controls.hpp)
  void updateUseTarget();
  int useTargetIndex = -1;
  Tyra::Sprite usePromptSprite;

  // Memory card save menu (save_system.gen.hpp): opened by using a Save
  // point object or the Open Save Menu flow node; gameplay pauses while
  // open. updateSaveMenu() returns true while it owns the pad.
  bool updateSaveMenu();
  void renderSaveMenu();
  void doSave(int slot);
  void doLoad(int slot);
  void applySavedObjects();
  void refreshSlotStates();
  std::vector<float> saveValues;
  std::vector<char> saveTexts;  // SAVE_TEXT_COUNT slots of SAVE_TEXT_LEN bytes
  std::vector<SaveObjectState> pendingObjState;  // applied after a scene load
  int pendingObjScene = -1;
  bool saveMenuOpen = false;
  int saveMenuSlot = 0;
  int saveMenuGrace = 0;  // frames to ignore pad input after opening
  bool slotUsed[SAVE_SLOTS] = {};
  int saveFeedback = 0, saveFeedbackFrames = 0;  // 1 saved, 2 loaded, 3 error
  Tyra::Sprite saveMenuSprite, saveCursorSprite, saveUsedSprite;
  Tyra::Sprite saveFeedbackSprites[3];  // saved / loaded / error

  // Game menus (menu_data.gen.hpp): panels baked by the editor, opened by
  // the Open Menu flow node, a menu entry, or at boot (title screen).
  // Gameplay pauses while one is open; Triangle walks the submenu stack.
  bool updateGameMenu();
  void renderGameMenu();
  std::vector<Tyra::Sprite> menuSprites;
  // Toggle/Choice entry values: one sub-rect sprite per menu into its baked
  // value strip (menu_data.gen.hpp; only menus with such entries have one).
  std::vector<Tyra::Sprite> menuValueSprites;

  // On-screen texts (hud_data.gen.hpp): baked text sprites the Show Text /
  // Hide Text flow nodes flip via ScriptContext; a positive timer auto-hides.
  void updateAndRenderHudTexts();
  std::vector<Tyra::Sprite> hudTextSprites;
  std::vector<signed char> hudTextReq;   // ScriptContext::textRequest
  std::vector<float> hudTextDur;         // ScriptContext::textDuration
  std::vector<unsigned char> hudTextOn;  // visible this frame
  std::vector<float> hudTextTimer;       // seconds left (0 = until hidden)
  Tyra::Sprite menuCursorSprite;
  Tyra::Sprite menuDimSprite;  // fullscreen dim under pausing menus
  int gameMenuIndex = -1;
  int gameMenuCursor = 0;
  int gameMenuGrace = 0;
  int gameMenuStack[4] = {};
  int gameMenuStackDepth = 0;

  ScriptContext scriptCtx;
};

}  // namespace Showcase
