name: cloth-curtain-f5c477d4
volumes:
  tyra-game-volume:
  tyra-engine:
    external: true
    name: tyra-engine-0be53feb
services:
  compiler:
    environment:
      TERM: xterm-256color
    network_mode: host
    image: ${TYRAX_IMAGE:-h4570/tyra}
    working_dir: /src
    command: ["sleep", "infinity"]
    tty: true
    volumes:
      - tyra-game-volume:/src
      - tyra-engine:/tyra
      - ./:/host
      - "D:/tyra-editor/vendor/tyra:/engine-src:ro"
