// Generated by TyraX. Do not edit - regenerated on every build.
#pragma once

namespace Blocks_terrain {

// A glyph's cell in the atlas and how to lay it down. Mirrors
// menubake::AtlasGlyph - the metrics here and the baked pixels come
// from the same atlasLayout() call, so they cannot drift.
struct FontGlyph {
  short u, v;        // top-left texel in the atlas
  short w, h;        // glyph size (0 = nothing to draw)
  short xoff, yoff;  // pen/line-top -> glyph top-left, at baseSize
  short adv;         // pen step to the next glyph, at baseSize
};

struct FontData {
  const char* atlas;  // relative to the game binary
  short texW, texH;
  short lineH;        // baseline pitch at baseSize
  short baseSize;     // size the metrics were baked at
  unsigned char r, g, b;  // tint (glyphs bake white)
  unsigned char shadow;   // 1 = draw a dark 1px offset pass first
  const FontGlyph* glyphs;
};

constexpr int FONT_FIRST_CHAR = 32;
constexpr int FONT_CHAR_COUNT = 95;
constexpr int FONT_COUNT = 1;

inline const FontGlyph FONT_GLYPHS_0[FONT_CHAR_COUNT] = {
    {0, 0, 0, 0, 0, 12, 9},
    {11, 0, 3, 13, 3, 0, 9},
    {22, 0, 7, 5, 1, 0, 9},
    {33, 0, 9, 11, 0, 1, 9},
    {44, 0, 9, 14, 0, 0, 9},
    {55, 0, 9, 13, 0, 0, 9},
    {66, 0, 10, 12, 0, 1, 9},
    {77, 0, 3, 5, 3, 0, 9},
    {88, 0, 6, 16, 2, 0, 9},
    {99, 0, 6, 16, 1, 0, 9},
    {110, 0, 7, 8, 1, 0, 9},
    {0, 18, 9, 9, 0, 3, 9},
    {11, 18, 5, 6, 1, 9, 9},
    {22, 18, 6, 3, 1, 6, 9},
    {33, 18, 4, 4, 2, 9, 9},
    {44, 18, 8, 14, 0, 0, 9},
    {55, 18, 9, 12, 0, 1, 9},
    {66, 18, 8, 11, 0, 1, 9},
    {77, 18, 8, 11, 0, 1, 9},
    {88, 18, 7, 12, 1, 1, 9},
    {99, 18, 9, 11, 0, 1, 9},
    {110, 18, 7, 12, 1, 1, 9},
    {0, 36, 9, 12, 0, 1, 9},
    {11, 36, 8, 11, 0, 1, 9},
    {22, 36, 8, 12, 0, 1, 9},
    {33, 36, 8, 11, 0, 1, 9},
    {44, 36, 4, 10, 2, 3, 9},
    {55, 36, 5, 12, 1, 3, 9},
    {66, 36, 8, 10, 0, 3, 9},
    {77, 36, 7, 6, 1, 5, 9},
    {88, 36, 7, 10, 1, 3, 9},
    {99, 36, 6, 13, 2, 0, 9},
    {110, 36, 9, 16, 0, 0, 9},
    {0, 54, 9, 11, 0, 1, 9},
    {11, 54, 8, 11, 1, 1, 9},
    {22, 54, 8, 12, 0, 1, 9},
    {33, 54, 9, 11, 0, 1, 9},
    {44, 54, 7, 11, 1, 1, 9},
    {55, 54, 7, 11, 1, 1, 9},
    {66, 54, 9, 12, 0, 1, 9},
    {77, 54, 9, 11, 0, 1, 9},
    {88, 54, 7, 11, 1, 1, 9},
    {99, 54, 7, 12, 1, 1, 9},
    {110, 54, 8, 11, 1, 1, 9},
    {0, 72, 7, 11, 1, 1, 9},
    {11, 72, 9, 11, 0, 1, 9},
    {22, 72, 9, 11, 0, 1, 9},
    {33, 72, 9, 12, 0, 1, 9},
    {44, 72, 8, 11, 1, 1, 9},
    {55, 72, 9, 14, 0, 1, 9},
    {66, 72, 8, 11, 1, 1, 9},
    {77, 72, 8, 12, 0, 1, 9},
    {88, 72, 9, 11, 0, 1, 9},
    {99, 72, 9, 12, 0, 1, 9},
    {110, 72, 9, 11, 0, 1, 9},
    {0, 90, 9, 11, 0, 1, 9},
    {11, 90, 9, 11, 0, 1, 9},
    {22, 90, 9, 11, 0, 1, 9},
    {33, 90, 8, 11, 0, 1, 9},
    {44, 90, 5, 16, 2, 0, 9},
    {55, 90, 9, 14, 0, 0, 9},
    {66, 90, 5, 16, 2, 0, 9},
    {77, 90, 9, 6, 0, 1, 9},
    {88, 90, 9, 3, 0, 13, 9},
    {99, 90, 6, 5, 0, 0, 9},
    {110, 90, 8, 10, 0, 3, 9},
    {0, 108, 8, 13, 1, 0, 9},
    {11, 108, 7, 10, 1, 3, 9},
    {22, 108, 8, 13, 0, 0, 9},
    {33, 108, 8, 10, 0, 3, 9},
    {44, 108, 9, 12, 0, 0, 9},
    {55, 108, 9, 13, 0, 3, 9},
    {66, 108, 7, 12, 1, 0, 9},
    {77, 108, 7, 12, 1, 0, 9},
    {88, 108, 8, 16, 0, 0, 9},
    {99, 108, 8, 12, 1, 0, 9},
    {110, 108, 7, 12, 1, 0, 9},
    {0, 126, 9, 9, 0, 3, 9},
    {11, 126, 7, 9, 1, 3, 9},
    {22, 126, 9, 10, 0, 3, 9},
    {33, 126, 8, 13, 1, 3, 9},
    {44, 126, 8, 13, 0, 3, 9},
    {55, 126, 8, 9, 1, 3, 9},
    {66, 126, 7, 10, 1, 3, 9},
    {77, 126, 8, 12, 0, 1, 9},
    {88, 126, 7, 9, 1, 4, 9},
    {99, 126, 9, 8, 0, 4, 9},
    {110, 126, 9, 8, 0, 4, 9},
    {0, 144, 9, 8, 0, 4, 9},
    {11, 144, 9, 12, 0, 4, 9},
    {22, 144, 7, 8, 1, 4, 9},
    {33, 144, 7, 16, 1, 0, 9},
    {44, 144, 3, 17, 3, -1, 9},
    {55, 144, 7, 16, 1, 0, 9},
    {66, 144, 9, 5, 0, 5, 9},
};

inline const FontData FONTS[FONT_COUNT > 0 ? FONT_COUNT : 1] = {
    {"fonts/atlas-default.png", 128, 256, 19, 16, 255, 255, 255, 1, FONT_GLYPHS_0},  // Default
};

// One slot per Display Text node (see DynTextSlot in templates.cpp).
struct DynTextData {
  short font;   // index into FONTS
  float x, y;   // normalized screen position, center anchor
  float size;   // glyph height in pixels
};

constexpr int DYN_TEXT_COUNT = 0;
constexpr int DYN_TEXT_LEN = 64;  // per-slot string buffer
inline const DynTextData DYN_TEXTS[DYN_TEXT_COUNT > 0 ? DYN_TEXT_COUNT : 1] = {
    {0, 0, 0, 0},
};

}  // namespace Blocks_terrain
