// Generated by TyraX. Do not edit - regenerated on every build.
#pragma once

// Runtime procedural generation (docs/procedural-runtime.md).
// ENABLED is the on/off seam: with no runtime volume in the
// project it is a compile-time false and every call site folds
// away, so a game that does not use the feature carries none of
// it.

namespace procrt {

constexpr bool ENABLED = true;
constexpr int VOLUME_COUNT = 1;
constexpr int MAX_INSTANCES = 12000;
constexpr int BLOCK_COLUMNS = 2000;
#define PROC_ATTR_SLOTS 10

// One generated instance. The buffer is BOTH the working set the
// graph transforms and the result the merge reads - a second
// array would be a copy of 4000 structs for no reason.
struct Pt {
  float x, y, z;
  float rx, ry, rz;   // degrees
  float sc;           // uniform scale
  unsigned long long key;  // stable identity (see ProcOverride)
  short asset;        // index into VolumeDef::assets, -1 = none
  short prefab;       // index into VolumeDef::prefabs, -1 = none
  unsigned char faces;  // visible-face mask, 63 = all six
  // 1 = this point is a cell of the block lattice, so the merge
  // may read the collision field around it for ambient occlusion.
  // Stated rather than inferred: `faces` is 63 for a fully
  // exposed block AND for every point that never met the node,
  // so a graph merging blocks with a scatter has no other way to
  // tell the two apart.
  unsigned char block;
  float a[PROC_ATTR_SLOTS];
};

struct Ctx {
  float (*terrainY)(float, float);
  float volPos[3];
  float volScale[3];
  float volYaw;            // degrees
  float footX0, footZ0;    // axis-aligned footprint corner
  float footX, footZ;      // ...and its size
  float mapW, mapD;        // terrain extent (off-map rejection)
  unsigned int seed;
  Pt* buf;
  int cap;
  int count;
  // Block collision field, filled by a Blocks Fill node. One
  // 32-bit word per column (bit i = level i solid), which is why
  // a block world is capped at 32 levels.
  unsigned int* blockCol;
  int blockCap;
  int blockNx, blockNz, blockLevels;
  float blockOx, blockOz, blockCell, blockBaseY;
};

struct VolumeDef {
  int scene;
  int objectIndex;      // the Procedural volume in that scene
  const char* name;
  float cell;           // chunk size (merge + cull granularity)
  float drawDist;
  int collide;
  int runAtStart;
  int seedMode;         // 0 = the authored seed, 1 = fresh per run
  unsigned int seed;
  int maxInstances;
  int hasBlocks;
  const short* assets;  // model index per asset slot
  int assetCount;
  const short* prefabs; // prefab index per prefab slot
  int prefabCount;
};

extern const VolumeDef VOLUMES[];

// Fills c.buf with the volume's instances and returns the count.
// Never throws, never allocates: everything it touches is in Ctx.
int generate(int volume, Ctx& c);

// Asset and prefab slots are resolved BY NAME once per
// generation: the model table is per project and the game owns
// it, so baking indices in here would mean two files agreeing
// about a table neither of them fully sees.
const char* const* volumeAssetNames(int v, int* count);
const char* const* volumePrefabNames(int v, int* count);
short* volumeAssetSlots(int v);
short* volumePrefabSlots(int v);

}  // namespace procrt
