# GitHub reads this file to show the "Sponsor" button on the repository page.
# Docs: https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
github: [doctorspider42]
