// Generated by TyraX. Do not edit. Conservative visibility proxies.
#pragma once

namespace Physics_playground {
struct OcclusionProxyBox { float mn[3], mx[3]; };
struct OcclusionProxyObject { int scene, object, first, count; };
constexpr bool OCCLUSION_CULLING = false;
static const OcclusionProxyBox OCCLUSION_BOXES[] = {
  {{0,0,0},{0,0,0}},
};
static const OcclusionProxyObject OCCLUSION_OBJECTS[] = {
  {-1,-1,0,0},
};
constexpr int OCCLUSION_OBJECT_COUNT = 0;
static const int OCCLUSION_SCENE_OFFSETS[] = {0,38};
static const unsigned char OCCLUSION_CAN_CULL[] = {1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1};
static const unsigned char OCCLUSION_IS_OCCLUDER[] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
inline int occlusionObjectIndex(int scene,int object){
  if(scene<0 || scene+1>=(int)(sizeof(OCCLUSION_SCENE_OFFSETS)/sizeof(int))) return -1;
  const int i=OCCLUSION_SCENE_OFFSETS[scene]+object;
  return object>=0 && i<OCCLUSION_SCENE_OFFSETS[scene+1] ? i : -1;
}
inline bool occlusionCanCull(int scene,int object){
  const int i=occlusionObjectIndex(scene,object);
  return i>=0 && OCCLUSION_CAN_CULL[i]!=0;
}
inline bool occlusionIsOccluder(int scene,int object){
  const int i=occlusionObjectIndex(scene,object);
  return i>=0 && OCCLUSION_IS_OCCLUDER[i]!=0;
}
}  // namespace Physics_playground
