"""Reproduce the 2026-09-28 full-throttle night drive in an isolated fixture.

Stages: prepare before editor --build; input after generation; profile after
baseline collection. Rebuild input/profile with native-build, without another
editor generation. Profiling stores 120 frames in RAM, then writes to host:. The optional entry
stage follows profile: delay entry to frame 180, gas to 210, capture all 480
frames including the walking-camera control before entry. Apply stationary
after entry for the same capture with zero throttle throughout.
"""
import argparse
import json
from pathlib import Path
import subprocess
import sys

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('project', type=Path)
parser.add_argument('--stage', choices=('prepare', 'input', 'profile', 'entry', 'stationary'), required=True)
a = parser.parse_args()
assert (a.project / 'BENCHMARK.json').exists(), 'Use benchmark-district.py in an isolated directory'
p = a.project / 'src/terrain_game.cpp'

SAMPLER = r'''#include "scripts/script.hpp"
#include "scripts/district_data.hpp"
#include "drive_test.hpp"
#include "file/file_utils.hpp"
#include <cstdio>
namespace Vehicle_playground {
class NightDriveBenchmark : public Script {
  struct Row { unsigned frame; float x,z,fps; };
  Row rows[120]; unsigned count=0; bool done=false;
public:
  void update(ScriptContext& ctx) override {
    if (ctx.saveValues && DISTRICT_NIGHT_VALUE < ctx.saveValueCount)
      ctx.saveValues[DISTRICT_NIGHT_VALUE] = 1.0F;
    if (driveTest::frame == 0) ctx.vehicleRequest = 132;
    ++driveTest::frame;
    if (ctx.objectCount <= 132 || done) return;
    const auto& p = ctx.objects[132].data.position;
    if (p[2] >= -69.0F && count < 120)
      rows[count++] = {driveTest::frame,p[0],p[2],ctx.engine->info.getFps()};
    if (count == 120 && driveTest::frame > rows[count-1].frame) {
      FILE* f=std::fopen(Tyra::FileUtils::fromCwd("drive-pose.csv").c_str(),"w");
      if(f) {
        std::fprintf(f,"frame,x,z,fps\n");
        for(unsigned i=0;i<count;++i)
          std::fprintf(f,"%u,%.5f,%.5f,%.5f\n",rows[i].frame,rows[i].x,rows[i].z,rows[i].fps);
        std::fclose(f);
      }
      done=true;
    }
  }
};
}
TYRA_SCRIPT(Vehicle_playground::NightDriveBenchmark);
'''

if a.stage == 'prepare':
    manifest = json.loads((a.project / 'vehicle-playground.tyra').read_text(encoding='utf-8'))
    objects = manifest['scenes'][0]['objects']
    vehicle = json.loads((a.project / 'objects' / (objects[132] + '.json')).read_text(encoding='utf-8'))
    assert vehicle['name'] == 'ravager-1', 'Vehicle index changed; update the sampler and its position gate'
    (a.project / 'inc/drive_test.hpp').write_text('#pragma once\nnamespace driveTest { inline unsigned frame = 0; }\n', encoding='utf-8')
    (a.project / 'src/scripts/zz_district_benchmark.cpp').write_text(SAMPLER, encoding='utf-8')
    path = a.project / 'BENCHMARK.json'
    data = json.loads(path.read_text(encoding='utf-8'))
    data.update(camera='normal vehicle chase camera (mode 0); no override', night=True,
                fullThrottleAfterFrame=120, sampleStartForwardDistance=5,
                sampleFrames=120, entryObjectIndex=132,
                sampler='120 consecutive position/FPS rows after 5 m; RAM buffer, export after sampling')
    path.write_text(json.dumps(data, indent=2)+'\n', encoding='utf-8')
elif a.stage == 'input':
    s=p.read_text(encoding="utf-8")
    assert '#include "drive_test.hpp"' not in s, 'Input already patched'
    first, rest = s.split('\n', 1)
    assert 'Generated by TyraX' in first, 'Use a freshly generated fixture'
    s = first + '\n#include "drive_test.hpp"\n' + rest
    needle="    } else if (v.wpCount > 0 && v.damage < 0.999F) {"
    assert s.count(needle)==1
    s=s.replace(needle,'''      // Test fixture: full R2-equivalent throttle after warm-up, no host polling.
      inThrottle = driveTest::frame >= 120 ? 1.0F : 0.0F;
      inBrake = inSteer = 0.0F; inHand = inNos = 0;
      v.lightsOn = 1;
'''+needle)
    p.write_text(s,encoding="utf-8")
elif a.stage == 'profile':
    subprocess.run([sys.executable, str(Path(__file__).with_name('instrument-frame-cost.py')),
                    str(a.project), '--attribute'], check=True)
    s=p.read_text(encoding='utf-8')
    def replace(a,b):
        global s
        assert s.count(a)==1,(a,s.count(a))
        s=s.replace(a,b)
    replace('static unsigned frame = 0, count = 0;', 'static unsigned frame = 0, count = 0;\nstatic bool written = false;')
    replace('  unsigned uploads, reuploads;', '  unsigned uploads, reuploads;\n  float x, z, speed, fps;')
    replace('uploads,reuploads\\n', 'uploads,reuploads,x,z,speed,fps\\n')
    replace('%.6f,%u,%u,%u,%u\\n",', '%.6f,%u,%u,%u,%u,%.6f,%.6f,%.6f,%.6f\\n",')
    replace('r.wait/294912.0,r.flushes,r.triangles,r.uploads,r.reuploads);', 'r.wait/294912.0,r.flushes,r.triangles,r.uploads,r.reuploads,r.x,r.z,r.speed,r.fps);')
    replace('if (dmF < 1440 && dmF % 360 >= 120 && districtMeasure::count < 960)', 'if (vehicleDriver_ >= 0 && vehicles_[vehicleDriver_].pos[2] >= -69.0F && districtMeasure::count < 120)')
    replace('dmTex.uploads-dmTex0.uploads,dmTex.reuploads-dmTex0.reuploads};', 'dmTex.uploads-dmTex0.uploads,dmTex.reuploads-dmTex0.reuploads,\n      vehicles_[vehicleDriver_].pos[0],vehicles_[vehicleDriver_].pos[2],vehicles_[vehicleDriver_].speed,engine->info.getFps()};')
    replace('  if (dmF == 1440) districtMeasure::save();\n  if (dmF == 1440) districtMeasure::saveAtt();', '  if (districtMeasure::count == 120 && !districtMeasure::written) {\n    districtMeasure::save(); districtMeasure::saveAtt(); districtMeasure::written = true;\n  }')
    p.write_text(s,encoding='utf-8')
    print('Driving sample gate and motion columns installed')

elif a.stage == 'entry':
    p=a.project / 'src/terrain_game.cpp'
    s=p.read_text(encoding='utf-8')
    assert '  int driver;' not in s, 'Entry already patched'
    s=s.replace('driveTest::frame >= 120', 'driveTest::frame >= 210')
    s=s.replace('  float x, z, speed, fps;', '  float x, z, speed, fps;\n  int driver;')
    s=s.replace('uploads,reuploads,x,z,speed,fps\\n', 'uploads,reuploads,x,z,speed,fps,driver\\n')
    s=s.replace('%.6f,%u,%u,%u,%u,%.6f,%.6f,%.6f,%.6f\\n', '%.6f,%u,%u,%u,%u,%.6f,%.6f,%.6f,%.6f,%d\\n')
    s=s.replace('r.x,r.z,r.speed,r.fps);', 'r.x,r.z,r.speed,r.fps,r.driver);')
    s=s.replace('vehicleDriver_ >= 0 && vehicles_[vehicleDriver_].pos[2] >= -69.0F && districtMeasure::count < 120', 'districtMeasure::count < 480')
    s=s.replace('vehicles_[vehicleDriver_].pos[0],vehicles_[vehicleDriver_].pos[2],vehicles_[vehicleDriver_].speed,engine->info.getFps()};', 'vehicles_[0].pos[0],vehicles_[0].pos[2],vehicles_[0].speed,engine->info.getFps(),vehicleDriver_};')
    s=s.replace('districtMeasure::count == 120', 'districtMeasure::count == 480')
    p.write_text(s, encoding='utf-8')
    p=a.project / 'src/scripts/zz_district_benchmark.cpp'
    s=p.read_text(encoding='utf-8').replace('rows[120]', 'rows[480]').replace('driveTest::frame == 0', 'driveTest::frame == 180').replace('if (p[2] >= -69.0F && count < 120)', 'if (count < 480)').replace('count == 120','count == 480')
    p.write_text(s, encoding='utf-8')
    p=a.project / 'src/gen/flow_graph.gen.cpp'
    s=p.read_text(encoding='utf-8'); assert s.count('ctx.vehicleRequest = 132;') == 2
    s=s.replace('ctx.vehicleRequest = 132;', '// Entry delayed by the night-drive test script.')
    p.write_text(s, encoding='utf-8')
    print('Entry at frame 180, gas at 210; 480-frame continuous profile')

    path = a.project / 'BENCHMARK.json'
    data = json.loads(path.read_text(encoding='utf-8'))
    data.update(entryAtFrame=180, fullThrottleAfterFrame=210, sampleFrames=480,
                sampleStartForwardDistance=None,
                sampler='480 consecutive frames from boot, entry+drive; buffered export after sampling')
    path.write_text(json.dumps(data, indent=2)+'\n', encoding='utf-8')

elif a.stage == 'stationary':
    s=p.read_text(encoding='utf-8')
    needle='inThrottle = driveTest::frame >= 210 ? 1.0F : 0.0F;'
    assert s.count(needle)==1, 'Apply entry before stationary'
    p.write_text(s.replace(needle, 'inThrottle = 0.0F; // Stationary entry control: no gas.'), encoding='utf-8')
    path = a.project / 'BENCHMARK.json'
    data = json.loads(path.read_text(encoding='utf-8'))
    data.update(fullThrottleAfterFrame=None, throttle=0.0,
                sampler='480 consecutive frames from boot; stationary entry, buffered export after sampling')
    path.write_text(json.dumps(data, indent=2)+'\n', encoding='utf-8')

print(a.stage, a.project)
