// Generated by TyraX. Do not edit - regenerated on every build.
#pragma once

namespace Particle_lab {

constexpr int MODEL_COUNT = 0;
inline const char* MODEL_PATHS[MODEL_COUNT > 0 ? MODEL_COUNT : 1] = {
    "",
};
// per-model .mtl override, for the .obj fallback path only (a
// .tmdl already carries the resolved override) - "" = none
inline const char* MODEL_MTLS[MODEL_COUNT > 0 ? MODEL_COUNT : 1] = {
    "",
};
// The AUTHORED asset path each slot was baked from ("res/models/x.obj").
// Nothing loads it - it is the key a runtime procedural volume
// resolves its asset pool against, because a graph names assets the
// way the editor does and the console only has baked .tmdl names.
inline const char* MODEL_SOURCES[MODEL_COUNT > 0 ? MODEL_COUNT : 1] = {
    "",
};
constexpr bool MODEL_NEEDS_COLLIDER[MODEL_COUNT > 0 ? MODEL_COUNT : 1] = {false};

constexpr int ANIM_MODEL_COUNT = 0;
inline const char* ANIM_MODEL_PATHS[ANIM_MODEL_COUNT > 0 ? ANIM_MODEL_COUNT : 1] = {
    "",
};

// .mtl libraries assigned to primitives (first material = surface)
constexpr int MATERIAL_COUNT = 9;
inline const char* MATERIAL_PATHS[MATERIAL_COUNT > 0 ? MATERIAL_COUNT : 1] = {
    "materials/particles/campfire.mtl",
    "materials/particles/campfire-f1.mtl",
    "materials/particles/campfire-f2.mtl",
    "materials/particles/campfire-f3.mtl",
    "materials/particles/wood-smoke.mtl",
    "materials/particles/torch-sparks.mtl",
    "materials/particles/magic-motes.mtl",
    "materials/particles/campfire-embers.mtl",
    "materials/particles/campfire-glow.mtl",
};

// The tyre-smoke pool's texture (MATERIAL_PATHS slot, -1 = untextured)
// and blend (docs/particles.md) - always emitted, the residency pass
// keeps the slot loaded.
constexpr int VEHICLE_SMOKE_MATERIAL = -1;
constexpr bool VEHICLE_SMOKE_ADDITIVE = false;
// texture atlas summary, logged at scene boot ("" = no atlas)
constexpr const char* TEXTURE_ATLAS_INFO = "";

}  // namespace Particle_lab
