// Generated by TyraX. Do not edit - regenerated on every build.
#pragma once

// Ambient-occlusion occluders: solid authored objects as oriented
// boxes / spheres, baked on the host. ax/ay/az = the object's local
// axes in world space; sphere = 1 reads half[0] as the radius;
// objIndex = scene-table index (an object never occludes itself).

namespace {
struct AoOccData {
  float pos[3];
  float ax[3], ay[3], az[3];
  float half[3];
  int sphere;
  int objIndex;
};

static const AoOccData S0_AO_OCC[10] = {
    {{-8.0F, 1.0F, -6.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.3F, 0.3F, 0.3F}, 1, 1},
    {{6.0F, 1.0F, -9.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.3F, 0.3F, 0.3F}, 1, 2},
    {{10.0F, 1.0F, 7.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.3F, 0.3F, 0.3F}, 1, 3},
    {{-12.0F, 1.0F, 8.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.2F, 0.2F, 0.2F}, 0, 4},
    {{-4.0F, 1.0F, 10.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.4F, 1.0F, 0.4F}, 0, 5},
    {{0.0F, 1.2F, -12.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {1.5F, 1.2F, 1.0F}, 0, 6},
    {{3.5F, 1.0F, -12.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.25F, 0.4F, 0.25F}, 0, 7},
    {{0.0F, 3.4F, -12.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.35F, 0.35F, 0.35F}, 1, 8},
    {{14.0F, 2.0F, 0.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.3F, 2.0F, 2.5F}, 0, 9},
    {{0.0F, 1.0F, 4.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.3F, 0.7F, 0.3F}, 0, 10},
};

static const AoOccData* const SCENE_AO_OCC_TABLES[] = {S0_AO_OCC};
static const int SCENE_AO_OCC_COUNTS[] = {10};

struct EmisLightData {
  float pos[3];
  float ax[3], ay[3], az[3];
  float half[3];
  int sphere;
  int objIndex;
  float color[3];
  float range, bright;
};


static const EmisLightData* const SCENE_EMIS_TABLES[] = {nullptr};
static const int SCENE_EMIS_COUNTS[] = {0};

struct AoAtlasRect {
  float u0, v0, du, dv;
};
static const AoAtlasRect* const SCENE_AO_ATLAS_RECTS_T[] = {nullptr};
static const int* const SCENE_AO_ATLAS_FIRSTS_T[] = {nullptr};
static const unsigned char* const SCENE_AO_ATLAS_LITS_T[] = {nullptr};
static const char* const SCENE_AO_ATLAS_PATHS[] = {""};
static const char* const SCENE_AO_MAP_PATHS[] = {"aomap/scene0.png"};
static const unsigned char SCENE_AO_MAP_OCCS[] = {1};
static const unsigned char SCENE_AO_MAP_LITS[] = {0};
static const unsigned char SCENE_AO_ATLAS_GIS[] = {0};
static const unsigned char SCENE_AO_MAP_GIS[] = {0};
}  // namespace

#define SCENE_AO_OCC SCENE_AO_OCC_TABLES[g_activeScene]
#define SCENE_AO_OCC_COUNT SCENE_AO_OCC_COUNTS[g_activeScene]
#define SCENE_EMIS SCENE_EMIS_TABLES[g_activeScene]
#define SCENE_EMIS_COUNT SCENE_EMIS_COUNTS[g_activeScene]
#define SCENE_AO_ATLAS_RECTS SCENE_AO_ATLAS_RECTS_T[g_activeScene]
#define SCENE_AO_ATLAS_FIRST SCENE_AO_ATLAS_FIRSTS_T[g_activeScene]
#define SCENE_AO_ATLAS_LIT SCENE_AO_ATLAS_LITS_T[g_activeScene]
#define SCENE_AO_ATLAS_PATH SCENE_AO_ATLAS_PATHS[g_activeScene]
#define SCENE_AO_MAP_PATH SCENE_AO_MAP_PATHS[g_activeScene]
#define SCENE_AO_MAP_OCC SCENE_AO_MAP_OCCS[g_activeScene]
#define SCENE_AO_MAP_LIT SCENE_AO_MAP_LITS[g_activeScene]
#define SCENE_AO_ATLAS_GI SCENE_AO_ATLAS_GIS[g_activeScene]
#define SCENE_AO_MAP_GI SCENE_AO_MAP_GIS[g_activeScene]
