// Generated by tyra-editor. Delete this line to take ownership of this file.
#pragma once

#include <tyra>
#include <vector>
#include "scene_data.hpp"

namespace Script_demo {

/** A scene object at runtime. Mutate `data` (position/rotation/scale/color),
 * `visible` or `velocityY`, then set `dirty = true` so the geometry gets
 * rebuilt on the next frame. */
struct RuntimeObject {
  SceneObjectData data;
  bool visible = true;
  float velocityY = 0.0F;  // vertical velocity (object physics)
  bool dirty = true;
  // False while the object's streaming layer is not resident: the object is
  // fully out of the game (no render, collision, sound, USE, physics) and
  // its geometry/assets may be freed. Managed by the game's layer streaming
  // - scripts should use the Load/Unload Layer flow nodes (or
  // ctx.layerRequest) instead of writing this directly.
  bool active = true;

  // Animated models (.glb) playback state; ignored on everything else.
  // To switch clips set animClip (resolve names with ctx.resolveClip or the
  // playAnimation() helper below) and animRestart = true; the game applies
  // it during the render pass.
  int animClip = 0;          // active clip index (model's clip table order)
  bool animPlaying = false;  // false = frozen on the current pose
  bool animLoop = true;
  float animSpeed = 1.0F;    // multiplier on the authored playback speed
  bool animRestart = false;  // (re)start animClip on the next frame
  float animFade = 0.0F;     // crossfade seconds for that restart (0 = pop)
  bool animFinished = false; // one frame: the clip reached its last frame
                             // (one-shots: once; looping: every wrap)
};

/** Everything a script can see and touch each frame. */
struct ScriptContext {
  Tyra::Engine* engine = nullptr;  // pad, renderer, audio, ...
  Tyra::Vec4 playerPosition;       // camera/player position this frame
  RuntimeObject* objects = nullptr;  // mutable scene objects
  int objectCount = 0;
  Tyra::Color skyColor;  // write to change the clear color

  // Set teleport = true and teleportPos to move the player (Player entity or
  // the FPP template player) there; the game applies and clears it.
  // teleportYaw: facing direction in degrees (Y rotation, 0 = +Z).
  bool teleport = false;
  Tyra::Vec4 teleportPos;
  float teleportYaw = 0.0F;

  // Index of the usable object the player pressed BTN_USE on this frame
  // (-1 = none). Drives the flow graph "On Used" trigger.
  int usedObject = -1;

  // Write to show/hide all HUD images (the USE prompt is unaffected).
  bool hudVisible = true;

  // Camera flashlight master switch (the Player object's "Enabled"). Write 1
  // to turn it on, 0 to turn it off, -1 to leave it unchanged; the game
  // applies and resets it. The optional toggle button still gates the beam.
  int flashlight = -1;

  // Runtime graphics switches (Set Fog / Set Bloom / Set Grain / Set Particles
  // flow nodes). fog / particles: -1 = leave, 0 = off, 1 = on. bloom / grain:
  // -1 = leave, else a 0..128 fixed-point amount. The game applies and resets.
  int fog = -1;
  int bloom = -1;
  int grain = -1;
  int particles = -1;

  // Save data: named values persisted in memory card slots (SAVE_VALUE_NAMES
  // order, scene_data.hpp). Set openSaveMenu = true to open the in-game
  // save/load menu (also opened by using a Save point object); the game
  // applies and clears it.
  float* saveValues = nullptr;
  int saveValueCount = 0;
  // Text values: saveTextCount slots of SAVE_TEXT_LEN bytes each
  // (SAVE_TEXT_NAMES order, scene_data.hpp), always NUL-terminated.
  char* saveTexts = nullptr;
  int saveTextCount = 0;
  bool openSaveMenu = false;

  // Game menus (menu_data.gen.hpp order). Write a menu index into openMenu
  // to open it (the game applies and clears it). menuEvent holds the index
  // of the "Flow event" a menu entry fired this frame (-1 = none) - it
  // drives the "On Menu Event" trigger.
  int openMenu = -1;
  int menuEvent = -1;

  // Scenes: `scene` is the active scene index (scene_data.hpp order),
  // `sceneGeneration` bumps on every (re)load - scripts use it to reset
  // their state. Write a scene index into `requestScene` to switch after
  // the current frame's scripts.
  int scene = 0;
  unsigned int sceneGeneration = 0;
  int requestScene = -1;

  // Streaming layers (SCENE_LAYER_* tables, per active scene). layerState[i]:
  // 0 = unloaded, 1 = loading (assets streaming in over frames), 2 = loaded.
  // Write 1 into layerRequest[i] to start loading a layer, 0 to unload it
  // (the game applies requests after this frame's scripts; -1 = none).
  // Loading is incremental - GTA3 style: request the next area's layer a
  // corridor early and it pops in without a hitch.
  const unsigned char* layerState = nullptr;
  signed char* layerRequest = nullptr;
  int layerCount = 0;

  // Animated models: clip-name -> clip-index lookup for an object (-1 =
  // unknown clip / not an animated model). Set by the game at startup.
  int (*resolveClip)(int objectIndex, const char* clipName) = nullptr;
};

/** Plays a named clip on an animated model object ("" = its first clip).
 * fade > 0 crossfades from the current pose over that many seconds instead
 * of snapping. No-op on objects that are not animated models. */
inline void playAnimation(ScriptContext& ctx, int objectIndex,
                          const char* clip = "", bool loop = true,
                          float speed = 1.0F, float fade = 0.0F) {
  if (objectIndex < 0 || objectIndex >= ctx.objectCount) return;
  const int index = ctx.resolveClip ? ctx.resolveClip(objectIndex, clip) : -1;
  if (index < 0) return;
  RuntimeObject& o = ctx.objects[objectIndex];
  o.animClip = index;
  o.animLoop = loop;
  o.animSpeed = speed;
  o.animFade = fade > 0.0F ? fade : 0.0F;
  o.animPlaying = true;
  o.animRestart = true;
}

/** Freezes an animated model object on its current pose. */
inline void stopAnimation(ScriptContext& ctx, int objectIndex) {
  if (objectIndex < 0 || objectIndex >= ctx.objectCount) return;
  ctx.objects[objectIndex].animPlaying = false;
}

/** True the frame an object's clip reached its last frame (one-shots: once;
 * looping clips: every wrap). */
inline bool animationFinished(const ScriptContext& ctx, int objectIndex) {
  if (objectIndex < 0 || objectIndex >= ctx.objectCount) return false;
  return ctx.objects[objectIndex].animFinished;
}

/** Base class for GLOBAL game scripts: registered with TYRA_SCRIPT, one
 * instance for the whole game, update() runs every frame in every scene.
 * For per-object behavior prefer ObjectScript below. */
class Script {
 public:
  virtual ~Script() {}
  virtual void init(ScriptContext&) {}
  virtual void update(ScriptContext&) {}
};

inline std::vector<Script*>& getScripts() {
  static std::vector<Script*> scripts;
  return scripts;
}

/** Base class for OBJECT scripts (Unity-style components). Write a class in
 * src/scripts/, register it with TYRA_OBJECT_SCRIPT(MyScript); inside your
 * namespace, then attach it to objects in the editor (Properties > Scripts).
 *
 * The game creates one instance per attachment when a scene (re)loads and
 * deletes it when the scene is left - the same class attached to five
 * objects runs as five independent instances, each with its own members and
 * its own `self`. Only attached scripts run; an unattached class costs
 * nothing. */
class ObjectScript {
 public:
  virtual ~ObjectScript() {}

  /** The object this instance is attached to - mutate self->data (position/
   * rotation/scale/color), self->visible or self->velocityY, then set
   * self->dirty = true. Equals &ctx.objects[selfIndex]; refreshed by the
   * game every frame before onUpdate. */
  RuntimeObject* self = nullptr;
  int selfIndex = -1;

  /** Scene (re)loaded: self is valid, runs before the first onUpdate. */
  virtual void onStart(ScriptContext&) {}
  /** Every frame while the owning scene is active. */
  virtual void onUpdate(ScriptContext&) {}
  /** The player pressed USE on self this frame (usable objects only). */
  virtual void onUsed(ScriptContext&) {}
};

/** Object-script classes register here by name (via TYRA_OBJECT_SCRIPT);
 * the generated object_scripts.gen.cpp instantiates attachments by name at
 * scene load. */
struct ObjectScriptFactory {
  const char* name;
  ObjectScript* (*create)();
};

inline std::vector<ObjectScriptFactory>& getObjectScriptFactories() {
  static std::vector<ObjectScriptFactory> factories;
  return factories;
}

}  // namespace Script_demo

/** Registers a script class. Put TYRA_SCRIPT(MyScript); at file scope. */
#define TYRA_SCRIPT_CONCAT_INNER(a, b) a##b
#define TYRA_SCRIPT_CONCAT(a, b) TYRA_SCRIPT_CONCAT_INNER(a, b)
#define TYRA_SCRIPT(ClassName)                                             \
  static const bool TYRA_SCRIPT_CONCAT(_tyraScript_, __COUNTER__) = []() { \
    Script_demo::getScripts().push_back(new ClassName());            \
    return true;                                                           \
  }()

/** Registers an object script class under its (stringized) name - the name
 * the editor's Properties > Scripts attach list shows. Put
 * TYRA_OBJECT_SCRIPT(MyScript); at file scope INSIDE your namespace. */
#define TYRA_OBJECT_SCRIPT(ClassName)                                         \
  static const bool TYRA_SCRIPT_CONCAT(_tyraObjScript_, __COUNTER__) = []() { \
    Script_demo::getObjectScriptFactories().push_back(                  \
        {#ClassName, []() -> Script_demo::ObjectScript* {               \
          return new ClassName();                                             \
        }});                                                                  \
    return true;                                                              \
  }()
