name: large-terrain-174c31e5
volumes:
  tyra-game-volume:
  tyra-engine:
    external: true
    name: tyra-engine-101292b0
services:
  compiler:
    environment:
      TERM: xterm-256color
    network_mode: host
    image: h4570/tyra
    working_dir: /src
    command: ["sleep", "infinity"]
    tty: true
    volumes:
      - tyra-game-volume:/src
      - tyra-engine:/tyra
      - ./:/host
      - "/home/spider/Projects/tyra-editor/vendor/tyra:/engine-src:ro"
