// Generated by TyraX. Do not edit - regenerated on every build.
#pragma once

namespace Impostor_grove {

constexpr int MODEL_COUNT = 10;
inline const char* MODEL_PATHS[MODEL_COUNT > 0 ? MODEL_COUNT : 1] = {
    "models/trees/young-oak.tmdl",
    "models/trees/young-oak-impostor.tmdl",
    "models/trees/silver-birch.tmdl",
    "models/trees/silver-birch-impostor.tmdl",
    "models/trees/old-oak.tmdl",
    "models/trees/old-oak-impostor.tmdl",
    "models/trees/fern-bush.tmdl",
    "models/trees/fern-bush-impostor.tmdl",
    "models/waystone.tmdl",
    "models/impostors/waystone.tmdl",
};
// per-model .mtl override, for the .obj fallback path only (a
// .tmdl already carries the resolved override) - "" = none
inline const char* MODEL_MTLS[MODEL_COUNT > 0 ? MODEL_COUNT : 1] = {
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
};
// The AUTHORED asset path each slot was baked from ("res/models/x.obj").
// Nothing loads it - it is the key a runtime procedural volume
// resolves its asset pool against, because a graph names assets the
// way the editor does and the console only has baked .tmdl names.
inline const char* MODEL_SOURCES[MODEL_COUNT > 0 ? MODEL_COUNT : 1] = {
    "res/models/trees/young-oak.obj",
    "res/models/trees/young-oak-impostor.obj",
    "res/models/trees/silver-birch.obj",
    "res/models/trees/silver-birch-impostor.obj",
    "res/models/trees/old-oak.obj",
    "res/models/trees/old-oak-impostor.obj",
    "res/models/trees/fern-bush.obj",
    "res/models/trees/fern-bush-impostor.obj",
    "res/models/waystone.obj",
    "res/models/impostors/waystone.obj",
};
constexpr bool MODEL_NEEDS_COLLIDER[MODEL_COUNT > 0 ? MODEL_COUNT : 1] = {false, false, false, false, false, false, false, false, false, false};

constexpr int ANIM_MODEL_COUNT = 0;
inline const char* ANIM_MODEL_PATHS[ANIM_MODEL_COUNT > 0 ? ANIM_MODEL_COUNT : 1] = {
    "",
};

// .mtl libraries assigned to primitives (first material = surface)
constexpr int MATERIAL_COUNT = 1;
inline const char* MATERIAL_PATHS[MATERIAL_COUNT > 0 ? MATERIAL_COUNT : 1] = {
    "materials/stone.mtl",
};

// texture atlas summary, logged at scene boot ("" = no atlas)
constexpr const char* TEXTURE_ATLAS_INFO = "";

}  // namespace Impostor_grove
