// Generated by TyraX. Do not edit - regenerated on every build.
//
// A project with no src/vu0/*.cpp gets this: no driver classes, and
// ENABLED a compile-time false. When the project HAS a kernel, the
// build container replaces this file with one that includes every
// generated driver (docs/vu-authoring.md, "VU0 kernels").
#pragma once

namespace vukernel {

constexpr bool ENABLED = false;
constexpr int COUNT = 0;

inline const char* name(int) { return ""; }

}  // namespace vukernel
