// Generated by tyra-editor. Delete this line to take ownership of this file.
#pragma once

#include <tyra>
#include <memory>
#include <vector>
#include "scripts/script.hpp"

namespace Script_demo {

class TerrainGame : public Tyra::Game {
 public:
  explicit TerrainGame(Tyra::Engine* engine);
  ~TerrainGame();

  void init() override;
  void loop() override;

 private:
  void buildScene();
  void generateTerrainGrid();
  void updatePlayer();

  Tyra::Engine* engine;
  Tyra::StaticPipeline stapip;

  Tyra::Vec4 cameraPosition, cameraLookAt;
  float playerX, playerZ, yaw, pitch;

  std::vector<Tyra::Vec4> vertices;
  std::vector<Tyra::Color> colors;

  Tyra::M4x4 model;
  std::unique_ptr<Tyra::StaPipBag> bag;
  std::unique_ptr<Tyra::StaPipInfoBag> infoBag;
  std::unique_ptr<Tyra::StaPipColorBag> colorBag;

  ScriptContext scriptCtx;
};

}  // namespace Script_demo
