// Generated by tyra-editor. Do not edit - regenerated on every build.
#pragma once

namespace Script_demo {

// Terrain size and lighting are per scene - see scene_data.hpp arrays and
// the TERRAIN_*/SCENE_* accessor macros defined there.

// Project preferences (Project > Preferences in the editor). These are
// project-wide; sky, clipping, post-FX and the usable-highlight can be
// overridden per scene and live as SCENE_COUNT arrays in scene_data.hpp
// (reached through the accessor macros defined in scene_data.hpp).
constexpr int TERRAIN_MAX_CELLS = 32;
constexpr float EYE_HEIGHT = 1.8F;
constexpr float WALK_SPEED = 0.4F;
constexpr float LOOK_SPEED = 1.0F;    // multiplier
constexpr float ORBIT_SPEED = 1.0F;  // multiplier
constexpr float GRAVITY = 9.8F;          // units/s^2
constexpr float JUMP_SPEED = 4.5F;    // units/s

// Scene switches show res/hud/loading.png on black for a moment
constexpr bool LOADING_SCREEN = true;

}  // namespace Script_demo
