// Generated by tyra-editor. Delete this line to take ownership of this file.
#pragma once

#include <tyra>
#include <vector>
#include "scene_data.hpp"

namespace Script_demo {

/** Everything a script can see and touch each frame. */
struct ScriptContext {
  Tyra::Engine* engine = nullptr;  // pad, renderer, audio, ...
  Tyra::Vec4 playerPosition;       // camera/player position this frame
  const SceneObjectData* objects = nullptr;  // scene objects (read-only)
  int objectCount = 0;
  Tyra::Color skyColor;  // write to change the clear color
};

/** Base class for game scripts. Put .cpp files in src/scripts/. */
class Script {
 public:
  virtual ~Script() {}
  virtual void init(ScriptContext&) {}
  virtual void update(ScriptContext&) {}
};

inline std::vector<Script*>& getScripts() {
  static std::vector<Script*> scripts;
  return scripts;
}

}  // namespace Script_demo

/** Registers a script class. Put TYRA_SCRIPT(MyScript); at file scope. */
#define TYRA_SCRIPT_CONCAT_INNER(a, b) a##b
#define TYRA_SCRIPT_CONCAT(a, b) TYRA_SCRIPT_CONCAT_INNER(a, b)
#define TYRA_SCRIPT(ClassName)                                             \
  static const bool TYRA_SCRIPT_CONCAT(_tyraScript_, __COUNTER__) = []() { \
    Script_demo::getScripts().push_back(new ClassName());            \
    return true;                                                           \
  }()
