"""Instrument a refreshed SCRATCH copy: freeze poses and toggle old/new GI with L1.

Run after --refresh-gen, before --build. Remove the scratch terrain_game.cpp
and refresh again to restore ordinary gameplay. No shipped runtime toggle.
"""
import pathlib
import sys

root = pathlib.Path(sys.argv[1]).resolve()
example = pathlib.Path(__file__).resolve().parents[1]
if root == example:
    raise SystemExit("Use a scratch copy, not the checked-in example.")
path = root / "src/terrain_game.cpp"
source = path.read_text(encoding="utf-8")
if not source.startswith("// Generated by TyraX."):
    raise SystemExit("Expected freshly generated source; refusing to replace owned code.")
source = source.split("\n", 1)[1]
source = source.replace("o.animFinished = inst->advance(step);",
                        "o.animFinished = inst->advance(step * 0.0F); // comparison: fixed pose")
entry = "void TerrainGame::updateAndRenderAnimObjects() {"
source = source.replace(entry, entry + """
  static bool compareLegacy = false;
  static bool compareFirst = true;
  bool compareReport = compareFirst;
  compareFirst = false;
  if (engine->pad.getClicked().L1) {
    compareLegacy = !compareLegacy;
    compareReport = true;
  }
""")
start = source.index(entry)
head, body = source[:start], source[start:]
body = body.replace("const bool hasProbe = giProbeAt", "bool hasProbe = giProbeAt", 1)
needle = "      const GameAnimModel& gam = gameAnimModels[o.data.animModel];"
assert body.count(needle) == 1
body = body.replace(needle, """
      if (hasProbe && compareLegacy) {
        ldir = {0.299F*gs.l1[0][0] + 0.587F*gs.l1[0][1] + 0.114F*gs.l1[0][2],
                0.299F*gs.l1[1][0] + 0.587F*gs.l1[1][1] + 0.114F*gs.l1[1][2],
                0.299F*gs.l1[2][0] + 0.587F*gs.l1[2][1] + 0.114F*gs.l1[2][2]};
        const float length = sqrtf(ldir.x*ldir.x + ldir.y*ldir.y + ldir.z*ldir.z);
        ldir = length > 0.0001F ? V3{ldir.x/length,ldir.y/length,ldir.z/length} : sun;
        for (int k = 0; k < 3; ++k) {
          amb[k] = gs.l0[k] > 0 ? gs.l0[k] : 0;
          const float d = (2.0F / 3.0F) * (gs.l1[0][k]*ldir.x +
                            gs.l1[1][k]*ldir.y + gs.l1[2][k]*ldir.z);
          dif[k] = d > 0 ? d : 0;
        }
        hasProbe = false; // select the original one-lobe path
      }
      if (compareReport) {
        char line[160];
        snprintf(line, sizeof(line), "PROBECOMPARE dominant=%d object=%d pos=%.2f,%.2f,%.2f",
                 compareLegacy, i, o.data.position[0],o.data.position[1],o.data.position[2]);
        TYRA_LOG(line);
      }
""" + needle)
path.write_text("// Scratch comparison: poses frozen; L1 toggles dominant projection / full RGB SH.\n" +
                head + body, encoding="utf-8")
print(path)
