"""Instrument a refreshed SCRATCH copy: freeze poses and toggle old/new GI with L1.

Run after --refresh-gen, before --build. Remove the scratch terrain_game.cpp
and refresh again to restore ordinary gameplay. No shipped runtime toggle.
"""
import pathlib
import sys

root = pathlib.Path(sys.argv[1]).resolve()
example = pathlib.Path(__file__).resolve().parents[1]
if root == example:
    raise SystemExit("Use a scratch copy, not the checked-in example.")
path = root / "src/terrain_game.cpp"
source = path.read_text(encoding="utf-8")
if not source.startswith("// Generated by TyraX."):
    raise SystemExit("Expected freshly generated source; refusing to replace owned code.")
source = source.split("\n", 1)[1]
source = source.replace("o.animFinished = inst->advance(step);",
                        "o.animFinished = inst->advance(step * 0.0F); // comparison: fixed pose")
entry = "void TerrainGame::updateAndRenderAnimObjects() {"
source = source.replace(entry, entry + """
  static bool compareLegacy = false;
  static bool compareFirst = true;
  bool compareReport = compareFirst;
  compareFirst = false;
  if (engine->pad.getClicked().L1) {
    compareLegacy = !compareLegacy;
    compareReport = true;
  }
""")
start = source.index(entry)
head, body = source[:start], source[start:]
needle = "        ldir = giDominantLight(gs, sun, amb, dif);"
assert body.count(needle) == 1
body = body.replace(needle, """      {
        ldir = giDominantLight(gs, sun, amb, dif);
        if (compareLegacy) {
          ldir = sun;
          for (int k = 0; k < 3; ++k) {
            const float d = (2.0F / 3.0F) * (gs.l1[0][k] * sun.x +
                gs.l1[1][k] * sun.y + gs.l1[2][k] * sun.z);
            dif[k] = d > 0 ? d : 0;
          }
        }
      }
      if (compareReport) {
        char line[320];
        snprintf(line, sizeof(line), "PROBECOMPARE legacy=%d object=%d pos=%.2f,%.2f,%.2f "
               "dir=%.3f,%.3f,%.3f ambient=%.3f,%.3f,%.3f "
               "diffuse=%.3f,%.3f,%.3f", compareLegacy, i,
               o.data.position[0], o.data.position[1], o.data.position[2],
               ldir.x, ldir.y, ldir.z, amb[0], amb[1], amb[2],
               dif[0], dif[1], dif[2]);
        TYRA_LOG(line);
      }
""")
path.write_text("// Scratch comparison: poses frozen; L1 toggles sun projection.\n" +
                head + body, encoding="utf-8")
print(path)
