// Generated by TyraX. Do not edit - regenerated on every build.
#pragma once

// Ambient-occlusion occluders: solid authored objects as oriented
// boxes / spheres, baked on the host. ax/ay/az = the object's local
// axes in world space; sphere = 1 reads half[0] as the radius;
// objIndex = scene-table index (an object never occludes itself).

namespace ao_data_gen_hpp_detail {
struct AoOccData {
  float pos[3];
  float ax[3], ay[3], az[3];
  float half[3];
  int sphere;
  int objIndex;
};


inline const AoOccData* const SCENE_AO_OCC_TABLES[] = {nullptr};
inline const int SCENE_AO_OCC_COUNTS[] = {0};

struct EmisLightData {
  float pos[3];
  float ax[3], ay[3], az[3];
  float half[3];
  int sphere;
  int objIndex;
  float color[3];
  float range, bright;
};


inline const EmisLightData* const SCENE_EMIS_TABLES[] = {nullptr};
inline const int SCENE_EMIS_COUNTS[] = {0};

struct AoAtlasRect {
  float u0, v0, du, dv;
};
inline const AoAtlasRect* const SCENE_AO_ATLAS_RECTS_T[] = {nullptr};
inline const int* const SCENE_AO_ATLAS_FIRSTS_T[] = {nullptr};
inline const unsigned char* const SCENE_AO_ATLAS_LITS_T[] = {nullptr};
inline const char* const SCENE_AO_ATLAS_PATHS[] = {""};
inline const char* const SCENE_AO_MAP_PATHS[] = {""};
inline const unsigned char SCENE_AO_MAP_OCCS[] = {0};
inline const unsigned char SCENE_AO_MAP_LITS[] = {0};
inline const unsigned char SCENE_AO_ATLAS_GIS[] = {0};
inline const unsigned char SCENE_AO_MAP_GIS[] = {0};
inline const unsigned char SCENE_AO_MAP_GILUMS[] = {0};
}  // namespace

#define SCENE_AO_OCC SCENE_AO_OCC_TABLES[g_activeScene]
#define SCENE_AO_OCC_COUNT SCENE_AO_OCC_COUNTS[g_activeScene]
#define SCENE_EMIS SCENE_EMIS_TABLES[g_activeScene]
#define SCENE_EMIS_COUNT SCENE_EMIS_COUNTS[g_activeScene]
#define SCENE_AO_ATLAS_RECTS SCENE_AO_ATLAS_RECTS_T[g_activeScene]
#define SCENE_AO_ATLAS_FIRST SCENE_AO_ATLAS_FIRSTS_T[g_activeScene]
#define SCENE_AO_ATLAS_LIT SCENE_AO_ATLAS_LITS_T[g_activeScene]
#define SCENE_AO_ATLAS_PATH SCENE_AO_ATLAS_PATHS[g_activeScene]
#define SCENE_AO_MAP_PATH SCENE_AO_MAP_PATHS[g_activeScene]
#define SCENE_AO_MAP_OCC SCENE_AO_MAP_OCCS[g_activeScene]
#define SCENE_AO_MAP_LIT SCENE_AO_MAP_LITS[g_activeScene]
#define SCENE_AO_ATLAS_GI SCENE_AO_ATLAS_GIS[g_activeScene]
#define SCENE_AO_MAP_GI SCENE_AO_MAP_GIS[g_activeScene]
#define SCENE_AO_MAP_GILUM SCENE_AO_MAP_GILUMS[g_activeScene]

using namespace ao_data_gen_hpp_detail;
