// ======================================================================
// Network: the editor's built-in default network (fitted on examples/upscaler-lab examples/material-lab examples/endless-runner examples/cube examples/save-points examples/procedural examples/endless-scroller bestiary)
//   rebuild it with: tyrax-editor --blss-train examples/upscaler-lab examples/material-lab examples/endless-runner examples/cube examples/save-points examples/procedural examples/endless-scroller bestiary --all-shots --frames 660 --no-jitter -o resources/blss-default.net
//
// This project has no blss.net of its own, so it is built with the
// network the editor ships. Measured leave-one-PROJECT-out, that
// net scores +0.29 dB on a project it has never seen against the
// project's own net's +0.31 - a tie - and fitting your own scene
// still reaches the highest number in distribution:
//
//     tyrax-editor --blss-eval <projectDir>    (is there a ceiling?)
//     tyrax-editor --blss-train <projectDir> --all-shots
//
// then rebuild. See docs/neural-upscaler.md.
// ======================================================================
// GENERATED by tyrax-editor --blss-emit. Do not edit.
// The trained BLSS network (docs/neural-upscaler.md): an MLP
// 6 -> 12 -> 3 (123 weights), tanh hidden, logistic outputs.
// Handed to RendererCoreBlss::setNet(), which runs it per 32x32 screen tile.
// The engine's kHidden must match: vendor/tyra/engine/inc/renderer/core/blss.
//
// Inputs, in order: motion, depth, depthGrad, edgeDens, texDetail, coverage
// Outputs, in order: point, temporal, sharpen

#pragma once

static const float BLSS_NET_W1[72] = {
    -4.08271958e-08F, 1.503214e-09F, -2.68656014e-10F, -8.23061157e-08F, 4.25922345e-13F, -0.00018637201F,
    -0.113984652F, -0.0969442725F, -0.100488022F, -0.2211124F, -0.0445848517F, -0.0853832513F,
    -0.114348762F, -0.0972586274F, -0.100718565F, -0.221029282F, -0.0449139439F, -0.0854326487F,
    -0.11352317F, -0.0971318558F, -0.100211337F, -0.22058326F, -0.0449844636F, -0.0849032104F,
    0.113876097F, 0.0967411622F, 0.100102156F, 0.220686182F, 0.0452808924F, 0.085030213F,
    0.113906786F, 0.0968594253F, 0.100398973F, 0.221285075F, 0.0446193777F, 0.0853556693F,
    0.195581526F, 1.13869059F, -0.036897555F, -0.531534493F, -1.85319138F, -0.372657508F,
    -1.1205641F, -0.393476218F, -0.540941834F, -0.0897769332F, 0.30586955F, -0.275208473F,
    -0.113793619F, -0.096932359F, -0.10036999F, -0.221181929F, -0.0446638539F, -0.0853160545F,
    -1.6679553e-07F, -5.52287156e-06F, -3.59016049e-05F, 2.8530088e-11F, -4.99555645e-05F, -1.50635016e-09F,
    0.114087626F, 0.0968739018F, 0.100553378F, 0.221144006F, 0.0445293263F, 0.0852285624F,
    0.114087671F, 0.0969286859F, 0.100512139F, 0.22109668F, 0.044550024F, 0.0852599889F,};

static const float BLSS_NET_B1[12] = {
    -1.41271492e-08F, -0.77819711F, -0.778480947F, -0.777893364F, 0.77810955F, 0.778212607F,
    0.40345791F, 0.912411869F, -0.778174996F, -7.02173111e-07F, 0.778204858F, 0.778168082F,};

static const float BLSS_NET_W2[36] = {
    5.92491411e-40F, 0.555675864F, 0.555828333F, 0.556177914F, -0.55570811F, -0.555991411F, 0.0484703779F, -0.633350432F, 0.55577445F, 9.38351491e-41F, -0.555672824F, -0.55583787F,
    2.3393697e-40F, 0.382305682F, 0.382521093F, 0.382211447F, -0.38267529F, -0.382225841F, -1.82199335F, -1.12339413F, 0.382231861F, -1.67703196e-40F, -0.382421911F, -0.382072896F,
    -5.18109088e-40F, 0.609667718F, 0.609719098F, 0.609502792F, -0.609896183F, -0.609666705F, -0.266150773F, -0.156364232F, 0.609680533F, 2.86048457e-40F, -0.609689832F, -0.60969305F,};

static const float BLSS_NET_B2[3] = {
    -0.914613545F, -0.811011136F, -0.85265553F,};

