// Generated by TyraX. Do not edit - regenerated on every build.
#pragma once

#include <math.h>

#include "scene_data.hpp"

namespace Vehicle_playground {
namespace daynight {

// Live state, seeded by reset() and advanced by tick(). Every
// consumer reads these instead of the baked SCENE_* constants while
// active(scene) is true.
inline float g_hour = 12.0F;
inline float g_sun[3] = {0.0F, 1.0F, 0.0F};
inline float g_moon[3] = {0.0F, -1.0F, 0.0F};
inline float g_light[3] = {0.0F, 1.0F, 0.0F};
inline float g_sky[3] = {0.0F, 0.0F, 0.0F};
inline float g_top[3] = {0.0F, 0.0F, 0.0F};
inline float g_fog[3] = {0.0F, 0.0F, 0.0F};
inline float g_stars = 0.0F, g_sunRad = 0.0F, g_moonRad = 0.0F;
// 0..1, how much of a cast shadow the live light is entitled to
// throw: 1 while one body owns the sky, 0 across the handover where
// the direction swaps (ambience::Resolved::shadowFade). Projected
// silhouettes and blob shadows multiply their alpha by it.
inline float g_shadowFade = 1.0F;
inline float g_moonRoll = 0.0F;
inline float g_gain[3] = {1.0F, 1.0F, 1.0F};
inline float g_lift[3] = {0.0F, 0.0F, 0.0F};
inline float g_mixColor[3] = {0.0F, 0.0F, 0.0F};
inline float g_mixAmount = 0.0F;
// 1/gain, clamped to the colour bags' 2x headroom: what the sky, the
// discs and the stars are pre-multiplied by so the full-screen grade
// brings them back to the hour they were authored at instead of
// darkening them a second time (ambience::driftCompensation).
inline float g_comp[3] = {1.0F, 1.0F, 1.0F};

inline bool active(int scene) {
  return DAYCYCLE_USED && scene >= 0 && scene < SCENE_COUNT &&
         DAYCYCLE_RUNTIMES[scene];
}
inline bool gradeOn(int scene) {
  return DAYCYCLE_USED && scene >= 0 && scene < SCENE_COUNT &&
         DAYCYCLE_GRADES[scene];
}

inline float wrap24(float h) {
  h = fmodf(h, 24.0F);
  return h < 0.0F ? h + 24.0F : h;
}
inline float clampf(float v, float lo, float hi) {
  return v < lo ? lo : (v > hi ? hi : v);
}

// ambience::arcDirection. cos(t)*R + sin(t)*P over a great circle:
// R is the horizon crossing at `rise`, P the tilted peak a quarter
// turn later, and t runs 0..pi above the horizon and on beneath it.
inline void arcDir(float azDeg, float tiltDeg, float rise, float set,
                   float hour, float out[3]) {
  const float az = azDeg * 0.01745329252F;
  const float tilt = clampf(tiltDeg, -89.0F, 89.0F) * 0.01745329252F;
  const float Rx = sinf(az), Rz = cosf(az);
  const float Hx = cosf(az), Hz = -sinf(az);
  const float st = sinf(tilt), ct = cosf(tilt);
  float up = wrap24(set - rise);
  up = clampf(up, 0.25F, 23.75F);
  const float since = wrap24(hour - rise);
  const float t = since <= up ? 3.14159265F * (since / up)
                             : 3.14159265F +
                                   3.14159265F * ((since - up) / (24.0F - up));
  const float c = cosf(t), sn = sinf(t);
  out[0] = c * Rx + sn * st * Hx;
  out[1] = sn * ct;
  out[2] = c * Rz + sn * st * Hz;
  const float l = sqrtf(out[0] * out[0] + out[1] * out[1] + out[2] * out[2]);
  if (l > 1e-6F) {
    out[0] /= l;
    out[1] /= l;
    out[2] /= l;
  } else {
    out[0] = 0.0F, out[1] = 1.0F, out[2] = 0.0F;
  }
}

// ambience::sampleKeys. Cyclic: the last key of the day carries
// through midnight into the first, which is what makes a night that
// spans 00:00 one interval instead of two.
inline void sampleKeys(int scene, float hour, DayKeyData& k) {
  const int first = DAYCYCLE_KEY_FIRSTS[scene];
  const int n = DAYCYCLE_KEY_COUNTS[scene];
  if (n <= 0) return;
  if (n == 1) {
    k = DAY_KEYS[first];
    return;
  }
  const float h = wrap24(hour);
  int hi = 0;
  while (hi < n && wrap24(DAY_KEYS[first + hi].hour) <= h) ++hi;
  const int lo = (hi - 1 + n) % n;
  hi %= n;
  const DayKeyData& a = DAY_KEYS[first + lo];
  const DayKeyData& b = DAY_KEYS[first + hi];
  const float ha = wrap24(a.hour);
  const float span = wrap24(wrap24(b.hour) - ha);
  if (span < 1e-4F) {
    k = a;
    return;
  }
  const float t = clampf(wrap24(h - ha) / span, 0.0F, 1.0F);
  k.hour = h;
  for (int i = 0; i < 3; ++i) {
    k.sky[i] = a.sky[i] + (b.sky[i] - a.sky[i]) * t;
    k.top[i] = a.top[i] + (b.top[i] - a.top[i]) * t;
    k.lit[i] = a.lit[i] + (b.lit[i] - a.lit[i]) * t;
    k.fog[i] = a.fog[i] + (b.fog[i] - a.fog[i]) * t;
  }
  k.amb = a.amb + (b.amb - a.amb) * t;
  k.dif = a.dif + (b.dif - a.dif) * t;
  k.bright = a.bright + (b.bright - a.bright) * t;
  k.stars = a.stars + (b.stars - a.stars) * t;
}

// The whole cycle at `hour`, into the globals above. `grade` false
// skips the drift maths entirely.
inline void evaluate(int scene, float hour) {
  g_hour = wrap24(hour);
  DayKeyData k = DAY_KEYS[0];
  sampleKeys(scene, g_hour, k);
  for (int i = 0; i < 3; ++i) {
    g_sky[i] = k.sky[i];
    g_top[i] = k.top[i];
    g_fog[i] = k.fog[i];
  }
  g_stars = clampf(k.stars, 0.0F, 1.0F);
  const float sunrise = DAYCYCLE_SUNRISES[scene];
  const float sunset = DAYCYCLE_SUNSETS[scene];
  const float moff = DAYCYCLE_MOON_OFFS[scene];
  arcDir(DAYCYCLE_SUN_AZS[scene], DAYCYCLE_SUN_TILTS[scene], sunrise,
         sunset, g_hour, g_sun);
  arcDir(DAYCYCLE_MOON_AZS[scene], DAYCYCLE_MOON_TILTS[scene],
         wrap24(sunrise + moff), wrap24(sunset + moff), g_hour, g_moon);
  const float sunElev = asinf(clampf(g_sun[1], -1.0F, 1.0F)) * 57.2957795F;
  const float moonElev = asinf(clampf(g_moon[1], -1.0F, 1.0F)) * 57.2957795F;
  // Below -10 degrees a body stops being drawn - the same rule the
  // baked SCENE_SUN_R / SCENE_MOON_R use, so a setting sun slides out
  // of view instead of vanishing whole.
  g_sunRad = sunElev < -10.0F ? 0.0F : DAYCYCLE_SUN_RADS[scene];
  g_moonRad = moonElev < -10.0F ? 0.0F : DAYCYCLE_MOON_RADS[scene];
  // The twilight handover, zenith term and all - see ambience.cpp for
  // why the 4*w*(1-w) pull is not optional.
  float w = clampf((sunElev + 6.0F) / 12.0F, 0.0F, 1.0F);
  w = w * w * (3.0F - 2.0F * w);
  // The dominant body OWNS the direction - never a blend of the two.
  // They are near-opposite at the crossover, so a weighted sum
  // cancels (a 180-degree shadow flip) and rescuing it with a zenith
  // term points the light straight up (shadows vanish, then come
  // back from the wrong side). g_shadowFade below is what makes the
  // switch invisible instead. See ambience::evaluate - the twin.
  float L[3];
  for (int i = 0; i < 3; ++i) L[i] = w >= 0.5F ? g_sun[i] : g_moon[i];
  {
    const float sf = fabsf(2.0F * w - 1.0F);
    g_shadowFade = sf * sf * (3.0F - 2.0F * sf);
  }
  {
    const float l = sqrtf(L[0] * L[0] + L[1] * L[1] + L[2] * L[2]);
    if (l > 1e-6F) {
      L[0] /= l, L[1] /= l, L[2] /= l;
    } else {
      L[0] = 0.0F, L[1] = 1.0F, L[2] = 0.0F;
    }
  }
  const float minY = 0.0871557F;  // sin(5 degrees)
  if (L[1] < minY) {
    const float hl = sqrtf(L[0] * L[0] + L[2] * L[2]);
    const float want = sqrtf(1.0F - minY * minY);
    if (hl > 1e-5F) {
      L[0] = L[0] / hl * want;
      L[2] = L[2] / hl * want;
    }
    L[1] = minY;
  }
  // ...and never ON the pole: a steeply authored arc peaks within a
  // degree of straight up, and M4x4::lookAt's hardcoded world-up
  // makes that direction degenerate every basis built from it - the
  // projected shadows' light camera above all.
  const float maxY = 0.99939F;  // sin(88 deg), ambience::kMaxLightElevation
  if (L[1] > maxY) {
    const float hl = sqrtf(L[0] * L[0] + L[2] * L[2]);
    const float want = sqrtf(1.0F - maxY * maxY);
    if (hl > 1e-5F) {
      L[0] = L[0] / hl * want;
      L[2] = L[2] / hl * want;
    } else {
      L[0] = want;
      L[2] = 0.0F;
    }
    L[1] = maxY;
  }
  for (int i = 0; i < 3; ++i) g_light[i] = L[i];
  // Moon roll: the sun projected into the disc's plane, so the lit
  // limb keeps facing the sun (the disc is baked lit-side-to-+X).
  {
    float rx = g_moon[2], rz = -g_moon[0];
    const float rl = sqrtf(rx * rx + rz * rz);
    if (rl < 1e-5F) {
      rx = 1.0F, rz = 0.0F;
    } else {
      rx /= rl, rz /= rl;
    }
    const float ux = g_moon[1] * rz;
    const float uy = -g_moon[0] * rz + g_moon[2] * rx;
    const float uz = -g_moon[1] * rx;
    const float sx = g_sun[0] * rx + g_sun[2] * rz;
    const float sy = g_sun[0] * ux + g_sun[1] * uy + g_sun[2] * uz;
    g_moonRoll = atan2f(sy, sx);
  }
  // ambience::driftGrade. Identity when the clock sits on the hour
  // the geometry was baked at, which is the property that makes this
  // safe to leave on.
  if (!gradeOn(scene)) {
    g_gain[0] = g_gain[1] = g_gain[2] = 1.0F;
    g_lift[0] = g_lift[1] = g_lift[2] = 0.0F;
    g_comp[0] = g_comp[1] = g_comp[2] = 1.0F;
    g_mixAmount = 0.0F;
    return;
  }
  DayKeyData bk = DAY_KEYS[0];
  sampleKeys(scene, DAYCYCLE_BAKEDS[scene], bk);
  const float lit = (bk.amb + 0.5F * bk.dif) * bk.bright;
  const float want = (k.amb + 0.5F * k.dif) * k.bright;
  const float ratio = clampf(lit > 1e-4F ? want / lit : 1.0F, 0.15F, 2.0F);
  for (int i = 0; i < 3; ++i) {
    const float cb = bk.lit[i] < 0.02F ? 0.02F : bk.lit[i];
    g_gain[i] = clampf(ratio * (0.45F + 0.55F * (k.lit[i] / cb)),
                       0.5F, 2.0F);  // ambience::kMinDriftGain
    g_lift[i] = clampf(k.sky[i] * 0.06F * (1.0F - ratio), 0.0F, 0.12F);
    g_mixColor[i] = k.sky[i];
  }
  g_mixAmount = clampf(0.30F * (1.0F - ratio) +
                           (ratio > 1.0F ? 0.10F * (ratio - 1.0F) : 0.0F),
                       0.0F, 0.35F);
  for (int i = 0; i < 3; ++i)
    g_comp[i] = clampf(g_gain[i] > 1e-4F ? 1.0F / g_gain[i] : 1.0F, 1.0F, 2.0F);
}

// Called on every scene load: park the clock at the authored hour so
// the first frame of a scene matches what the editor previewed.
inline void reset(int scene) {
  if (!active(scene)) return;
  evaluate(scene, DAYCYCLE_STARTS[scene]);
}

// One frame. dt is real seconds; DAYCYCLE_DAYLEN is how many of them
// a whole 24 h takes.
inline void tick(int scene, float dt) {
  if (!active(scene)) return;
  const float len = DAYCYCLE_DAYLENS[scene];
  if (len > 0.001F) g_hour = wrap24(g_hour + dt * (24.0F / len));
  evaluate(scene, g_hour);
}

}  // namespace daynight

// Weather and street lamps (docs/weather.md): each scene's authored weather
// and lamp mode, the core both the editor and this game compile
// (src/weather_core.inl), and the one live state Set Weather drives.
namespace weather {

inline constexpr int SCENE_WEATHERS[SCENE_COUNT] = {0, 0, 0};
inline constexpr float SCENE_WEATHER_INTENSITIES[SCENE_COUNT] = {1.0F, 1.0F, 1.0F};
inline constexpr int SCENE_LAMP_MODES[SCENE_COUNT] = {0, 0, 0};
inline constexpr float SCENE_LAMP_STATIC[SCENE_COUNT] = {0.0F, 0.0F, 0.0F};

// Weather and street-lamp core (docs/weather.md).
//
// ONE SOURCE, TWO HOMES - the roadstream_core.inl arrangement. The editor
// compiles this file inside namespace weather (src/roadlight.cpp: the
// --vehicle-check "wet roads and lamps" block and the viewport preview), and
// the codegen pastes it VERBATIM into namespace weather of a generated game's
// inc/daynight.gen.hpp (embedded at build by CMake). So: no #include, no C
// block comments (the paste can land inside one), plain floats, and nothing
// but asinf from math.h, which both homes already include.
//
// What lives here is the part of the weather that has to agree between the
// editor and the console: the state machine a scene's authored weather and the
// Set Weather flow node drive, and the street lamps' level from the sun.

// What a scene's weather or a Set Weather node asks for.
enum : int { kWeatherDry = 0, kWeatherRain = 1 };

// How long the roads take to get wet and to dry again, in seconds for the
// whole 0..1 range. Wetness FOLLOWS the rain: it never runs ahead of it and
// it lags behind it, so a shower that stops leaves the streets shining for
// a while - which is half of what makes a city look rained on.
inline constexpr float kWeatherSoakSeconds = 6.0F;
inline constexpr float kWeatherDrySeconds = 40.0F;

struct WeatherState {
  float rain = 0.0F;  // rain intensity now, 0..1: the drops and their density
  float wet = 0.0F;   // how wet the roads are now, 0..1: tint and streaks
  float from = 0.0F, to = 0.0F;   // the rain transition in flight
  float time = 0.0F, span = 0.0F; // its clock and length (0 = none)

  static float clamp01(float v) { return v < 0.0F ? 0.0F : (v > 1.0F ? 1.0F : v); }

  // A scene load: the scene's authored weather, already soaked - a scene
  // that starts in the rain starts with wet streets.
  void reset(float intensity) {
    rain = wet = from = to = clamp01(intensity);
    time = span = 0.0F;
  }

  // Set Weather. `seconds` <= 0 switches at once, wetness included (the
  // way to set a scene up from On Start); otherwise the rain ramps linearly
  // from where it is now and the roads follow at their own pace.
  void request(int kind, float intensity, float seconds) {
    const float target = kind == kWeatherRain ? clamp01(intensity) : 0.0F;
    if (!(seconds > 0.0F)) {
      reset(target);
      return;
    }
    from = rain;
    to = target;
    time = 0.0F;
    span = seconds;
  }

  // One frame of `dt` seconds (0 while the game is paused).
  void tick(float dt) {
    if (!(dt > 0.0F)) return;
    if (span > 0.0F) {
      time += dt;
      if (time >= span) {
        rain = to;
        span = 0.0F;
      } else {
        rain = from + (to - from) * (time / span);
      }
    }
    if (wet < rain) {
      wet += dt * (1.0F / kWeatherSoakSeconds);
      if (wet > rain) wet = rain;
    } else if (wet > rain) {
      wet -= dt * (1.0F / kWeatherDrySeconds);
      if (wet < rain) wet = rain;
    }
  }
};

// The street lamps' level, 0 (off, day) .. 1 (fully lit, night), from the
// sun's direction (its y is the sine of its elevation). Full at 3 degrees
// below the horizon, off at 6 above, smoothstepped between - real lamps come
// on in the dusk, before the sky is dark.
inline float weatherLampLevel(float sunY) {
  const float y = sunY < -1.0F ? -1.0F : (sunY > 1.0F ? 1.0F : sunY);
  const float elev = asinf(y) * 57.2957795F;
  float t = (elev + 3.0F) * (1.0F / 9.0F);
  t = t < 0.0F ? 0.0F : (t > 1.0F ? 1.0F : t);
  return 1.0F - t * t * (3.0F - 2.0F * t);
}

// --- puddles -------------------------------------------------------------
//
// A puddle is a road-detail decal (src/roaddetail.cpp) whose chunks share ONE
// colour, set once a frame from the wetness: nothing per vertex, ever. It
// fills after the road is wet and empties before it is dry, so a shower that
// barely darkens the asphalt leaves no puddles and a soaked street keeps
// them for a while after the rain.
inline constexpr float kWeatherPuddleFrom = 0.35F;  // wetness where the first water shows
inline constexpr float kWeatherPuddleFull = 0.85F;  // ... and where the puddles are full

inline float weatherPuddleLevel(float wet) {
  float t = (wet - kWeatherPuddleFrom) * (1.0F / (kWeatherPuddleFull - kWeatherPuddleFrom));
  t = t < 0.0F ? 0.0F : (t > 1.0F ? 1.0F : t);
  return t * t * (3.0F - 2.0F * t);
}

// The puddles' one colour (0..255, alpha 0..128 in the GS's 128 = 1 scale):
// still water mirrors what is above it, so a puddle is dark water plus a
// share of the sky (bluer and lighter than the wet asphalt by day) plus, at
// night, the warm glow of the lit street it mirrors (`lamps`, the street
// lamps' level 0..1). `sky` is the colour the sky is drawn with, 0..255.
// Alpha 0 = dry: the GS alpha test drops every texel.
inline void weatherPuddleColor(float wet, float skyR, float skyG, float skyB, float lamps,
                               float out[4]) {
  const float lv = weatherPuddleLevel(wet);
  const float l = lamps < 0.0F ? 0.0F : (lamps > 1.0F ? 1.0F : lamps);
  const float sky[3] = {skyR, skyG, skyB};
  const float water[3] = {12.0F, 14.0F, 19.0F};
  const float glow[3] = {72.0F, 62.0F, 46.0F};
  for (int a = 0; a < 3; ++a) {
    float c = water[a] + 0.5F * sky[a] + l * glow[a];
    out[a] = c < 0.0F ? 0.0F : (c > 255.0F ? 255.0F : c);
  }
  out[3] = 116.0F * lv;
}

// --- car lights on a wet road ----------------------------------------------
//
// Every car whose lamps are on mirrors them in a wet road: a streak lying on
// the road from under the lamp toward the viewer, the street lamps' wet
// streak at a car lamp's height. Two lamps a face, two faces a car, and only
// the faces turned to the camera draw - so a car costs two quads, four at
// most, in the street lamps' own sprite bag.
inline constexpr float kWeatherCarStreakFar = 45.0F;  // farther cars draw none
inline constexpr int kWeatherCarStreakMax = 24;       // quads a frame, every car together

// Which faces of a car mirror their lamps: the headlights while the lights
// are on (an unbroken lamp), the tail lamps while the lights are on or the
// brake is - and none of it on a dry road.
inline void weatherCarLamps(int lightsOn, int brakeOn, int broken, float wet, int* front,
                            int* rear) {
  const bool w = wet > 0.02F;
  *front = w && lightsOn > 0 && (broken & 1) == 0 ? 1 : 0;
  *rear = w && (lightsOn > 0 || brakeOn != 0) && (broken & 2) == 0 ? 1 : 0;
}

// One lamp's streak. The lamp at (lx, ly, lz) faces (nx, nz) (unit,
// horizontal); the road under the car is the plane through (lx, gy, lz) with
// slope (sx, sz) = dy/dx, dy/dz; the eye is (ex, ey, ez). Returns 0 when it
// draws nothing (dry, too far, the lamp turned away), else writes the quad's
// four corners - the lamp's end first, x y z each - and its brightness 0..1.
inline int weatherCarStreak(float lx, float ly, float lz, float gy, float sx, float sz,
                            float nx, float nz, float hw, float ex, float ey, float ez,
                            float wet, float quad[12], float* k) {
  if (!(wet > 0.02F)) return 0;
  float tx = ex - lx, tz = ez - lz;
  const float hd = sqrtf(tx * tx + tz * tz);
  if (hd < 0.6F || hd > kWeatherCarStreakFar) return 0;
  tx /= hd, tz /= hd;
  const float facing = tx * nx + tz * nz;
  if (facing < 0.15F) return 0;
  // The mirror point, from the foot of the lamp: a low lamp mirrors close to
  // the car, which is why a car's streak hugs its own bumper.
  const float h = ly - gy > 0.15F ? ly - gy : 0.15F;
  const float eyeH = ey - gy > 0.3F ? ey - gy : 0.3F;
  const float m = hd * h / (h + eyeH);
  float half = 0.6F * m + 0.5F;
  if (half > 4.0F) half = 4.0F;
  float a = m - half, b = m + half;
  if (a < 0.1F) a = 0.1F;
  if (b > hd - 0.5F) b = hd - 0.5F;
  if (b <= a + 0.2F) return 0;
  const float wd = hw + 0.004F * hd;
  const float px = -tz * wd, pz = tx * wd;
  const float x0 = lx + tx * a, z0 = lz + tz * a;
  const float x1 = lx + tx * b, z1 = lz + tz * b;
  const float cx[4] = {x0 - px, x0 + px, x1 + px, x1 - px};
  const float cz[4] = {z0 - pz, z0 + pz, z1 + pz, z1 - pz};
  for (int c = 0; c < 4; ++c) {
    quad[c * 3 + 0] = cx[c];
    quad[c * 3 + 1] = gy + sx * (cx[c] - lx) + sz * (cz[c] - lz) + 0.06F;
    quad[c * 3 + 2] = cz[c];
  }
  const float fade = hd > 0.7F * kWeatherCarStreakFar
                         ? (kWeatherCarStreakFar - hd) / (0.3F * kWeatherCarStreakFar)
                         : 1.0F;
  float w = wet > 1.0F ? 1.0F : wet;
  *k = w * sqrtf(facing) * fade;
  return 1;
}

// A whole car: up to four streaks (front pair, then rear pair) into quads
// (12 floats each), their brightness into ks and 1 for a tail lamp into
// rear. The lamps are the model's measured lamp boxes (lampFront/lampRear:
// half spacing x, height y, z along the body, size; size 0 = the model
// marked none, and the shape-blind guess the tail-lamp glow uses stands in).
// groundFront/groundRear are the road under each axle (the wheels' own
// contact heights), which also tilt the streaks with the car's pitch.
inline int weatherCarStreaks(const float pos[3], float yawDeg, float scale,
                             const float lampFront[4], const float lampRear[4], float track,
                             float wheelBase, float overhang, float groundFront,
                             float groundRear, int lightsOn, int brakeOn, int broken,
                             float ex, float ey, float ez, float wet, float quads[48],
                             float ks[4], int rear[4]) {
  int front = 0, back = 0;
  weatherCarLamps(lightsOn, brakeOn, broken, wet, &front, &back);
  if (!front && !back) return 0;
  const float yr = yawDeg * 0.017453293F;
  const float cy = cosf(yr), sy = sinf(yr);
  const float fx = sy, fz = cy;    // forward
  const float rx = cy, rz = -sy;   // right
  const float hz = 0.5F * wheelBase * scale;
  const float pitch = wheelBase > 0.01F ? (groundFront - groundRear) / (wheelBase * scale) : 0.0F;
  const float sx = pitch * fx, sz = pitch * fz;
  int n = 0;
  for (int face = 0; face < 2; ++face) {
    if (face == 0 ? !front : !back) continue;
    const float* L = face == 0 ? lampFront : lampRear;
    const bool measured = L[3] > 0.0F;
    const float side = measured ? L[0] * scale : 0.32F * track * scale;
    const float up = measured ? L[1] * scale : (face == 0 ? 0.55F : 0.62F) * scale;
    const float along = measured ? L[2] * scale
                                 : (face == 0 ? hz + overhang * scale
                                              : -(hz + overhang * scale));
    const float size = measured ? L[3] * scale : 0.16F * scale;
    const float gy = face == 0 ? groundFront : groundRear;
    const float nx = face == 0 ? fx : -fx, nz = face == 0 ? fz : -fz;
    for (int s = -1; s <= 1; s += 2) {
      const float lx = pos[0] + fx * along + rx * side * (float)s;
      const float lz = pos[2] + fz * along + rz * side * (float)s;
      if (weatherCarStreak(lx, gy + up, lz, gy, sx, sz, nx, nz, 0.6F * size + 0.08F, ex, ey, ez,
                           wet, &quads[n * 12], &ks[n])) {
        rear[n] = face;
        ++n;
      }
    }
  }
  return n;
}

inline WeatherState g_state;
// A scene load: its authored weather, roads already wet.
inline void reset(int scene) {
  if (scene < 0 || scene >= SCENE_COUNT) return;
  g_state.reset(SCENE_WEATHERS[scene] == kWeatherRain ? SCENE_WEATHER_INTENSITIES[scene]
                                                      : 0.0F);
}
// The Set Weather flow node.
inline void request(int kind, float intensity, float seconds) {
  g_state.request(kind, intensity, seconds);
}

}  // namespace weather
}  // namespace Vehicle_playground
