// Generated by TyraX. Do not edit - regenerated on every build.
#pragma once

// Ambient-occlusion occluders: solid authored objects as oriented
// boxes / spheres, baked on the host. ax/ay/az = the object's local
// axes in world space; sphere = 1 reads half[0] as the radius;
// objIndex = scene-table index (an object never occludes itself).

namespace {
struct AoOccData {
  float pos[3];
  float ax[3], ay[3], az[3];
  float half[3];
  int sphere;
  int objIndex;
};

static const AoOccData S0_AO_OCC[6] = {
    {{-4.5F, 1.0F, 8.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {1.0F, 1.0F, 1.0F}, 0, 1},
    {{-1.5F, 1.0F, 8.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.9F, 0.9F, 0.9F}, 1, 2},
    {{1.5F, 1.0F, 8.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {1.0F, 1.0F, 1.0F}, 0, 3},
    {{4.5F, 1.1F, 8.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {1.0F, 1.0F, 1.0F}, 1, 4},
    {{0.0F, 2.5F, 15.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.5F, 2.5F, 0.5F}, 0, 5},
    {{2.0F, 1.0F, 4.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.6F, 0.6F, 0.6F}, 1, 6},
};

static const AoOccData* const SCENE_AO_OCC_TABLES[] = {S0_AO_OCC};
static const int SCENE_AO_OCC_COUNTS[] = {6};

struct EmisLightData {
  float pos[3];
  float ax[3], ay[3], az[3];
  float half[3];
  int sphere;
  int objIndex;
  float color[3];
  float range, bright;
};


static const EmisLightData* const SCENE_EMIS_TABLES[] = {nullptr};
static const int SCENE_EMIS_COUNTS[] = {0};

struct AoAtlasRect {
  float u0, v0, du, dv;
};
static const AoAtlasRect S0_AO_RECTS[13] = {{0.472656F, 0.582031F, 0.242188F, 0.171875F}, {0.0117188F, 0.910156F, 0.3125F, 0.0703125F}, {0.347656F, 0.910156F, 0.0234375F, 0.0703125F}, {0.488281F, 0.0117188F, 0.140625F, 0.390625F}, {0.824219F, 0.0117188F, 0.0703125F, 0.320312F}, {0.917969F, 0.0117188F, 0.0703125F, 0.320312F}, {0.214844F, 0.582031F, 0.234375F, 0.179688F}, {0.738281F, 0.582031F, 0.242188F, 0.171875F}, {0.394531F, 0.910156F, 0.0234375F, 0.0625F}, {0.652344F, 0.0117188F, 0.148438F, 0.367188F}, {0.0117188F, 0.582031F, 0.078125F, 0.304688F}, {0.113281F, 0.582031F, 0.078125F, 0.304688F}, {0.0117188F, 0.0117188F, 0.453125F, 0.546875F}};
static const int S0_AO_FIRST[7] = {-1, 0, -1, 6, 12, -1, -1};
static const unsigned char S0_AO_LIT[7] = {0, 0, 0, 0, 0, 0, 0};
static const AoAtlasRect* const SCENE_AO_ATLAS_RECTS_T[] = {S0_AO_RECTS};
static const int* const SCENE_AO_ATLAS_FIRSTS_T[] = {S0_AO_FIRST};
static const unsigned char* const SCENE_AO_ATLAS_LITS_T[] = {S0_AO_LIT};
static const char* const SCENE_AO_ATLAS_PATHS[] = {"aoatlas/scene0.png"};
static const char* const SCENE_AO_MAP_PATHS[] = {"aomap/scene0.png"};
static const unsigned char SCENE_AO_MAP_OCCS[] = {1};
static const unsigned char SCENE_AO_MAP_LITS[] = {0};
static const unsigned char SCENE_AO_ATLAS_GIS[] = {0};
static const unsigned char SCENE_AO_MAP_GIS[] = {0};
}  // namespace

#define SCENE_AO_OCC SCENE_AO_OCC_TABLES[g_activeScene]
#define SCENE_AO_OCC_COUNT SCENE_AO_OCC_COUNTS[g_activeScene]
#define SCENE_EMIS SCENE_EMIS_TABLES[g_activeScene]
#define SCENE_EMIS_COUNT SCENE_EMIS_COUNTS[g_activeScene]
#define SCENE_AO_ATLAS_RECTS SCENE_AO_ATLAS_RECTS_T[g_activeScene]
#define SCENE_AO_ATLAS_FIRST SCENE_AO_ATLAS_FIRSTS_T[g_activeScene]
#define SCENE_AO_ATLAS_LIT SCENE_AO_ATLAS_LITS_T[g_activeScene]
#define SCENE_AO_ATLAS_PATH SCENE_AO_ATLAS_PATHS[g_activeScene]
#define SCENE_AO_MAP_PATH SCENE_AO_MAP_PATHS[g_activeScene]
#define SCENE_AO_MAP_OCC SCENE_AO_MAP_OCCS[g_activeScene]
#define SCENE_AO_MAP_LIT SCENE_AO_MAP_LITS[g_activeScene]
#define SCENE_AO_ATLAS_GI SCENE_AO_ATLAS_GIS[g_activeScene]
#define SCENE_AO_MAP_GI SCENE_AO_MAP_GIS[g_activeScene]
