// Generated by TyraX. Do not edit - regenerated on every build.
#pragma once

namespace Hud_animation {

struct HudImageData {
  const char* path;  // relative to the game binary (res/ is copied there)
  float x, y;        // normalized screen position, center anchor
  float w, h;        // size in pixels
  int anim;          // looped motion (hudanim::Kind), 0 = none
  float animPeriod, animAmount;
  int trans;         // show/hide transition (hudanim::Transition)
  float transSec;
  int visible;       // 1 = shown when the game starts
};

constexpr int HUD_COUNT = 0;
inline const HudImageData HUD_IMAGES[HUD_COUNT > 0 ? HUD_COUNT : 1] = {
    {"", 0, 0, 0, 0, 0, 1, 0, 0, 0, 1},
};

// Screen-stack positions of the full-screen effects (Tools > UI
// Editor). The effect applies right before the HUD sprite at this
// index, so lower-index sprites get it and higher ones draw crisp on
// top. -1 = at end of frame, over everything including menus. Bloom
// carries color grading; film grain is placed independently.
constexpr int HUD_BLOOM_LAYER = -1;
constexpr int HUD_GRAIN_LAYER = -1;

// The USE prompt sprite (shown while looking at a usable object)
constexpr const char* USE_PROMPT_PATH = "hud/use-text.png";
constexpr float USE_PROMPT_X = 0.5F;  // normalized, center anchor
constexpr float USE_PROMPT_Y = 0.755714F;
constexpr float USE_PROMPT_W = 128.0F;  // on-screen pixels
constexpr float USE_PROMPT_H = 32.0F;
// The "PICK UP" variant, shown instead for pickable objects
// (same screen position as USE; its own text/image and size)
constexpr const char* PICK_PROMPT_PATH = "hud/pick-text.png";
constexpr float PICK_PROMPT_W = 128.0F;
constexpr float PICK_PROMPT_H = 32.0F;

// Live glyph slots in the prompt sprites: the baked text leaves a
// hole per {{action}} token and the game blits the CURRENT binding's
// icon into each, so a runtime rebind is reflected. One entry per
// token in reading order, so "Press {{use}} to open" and a two-
// action prompt both work; count 0 = the sprite is complete on its
// own (icons that are not actions are baked in - see docs).
struct PromptIconSlot {
  short action;   // index into the Input Map's actions
  short x, y;     // top-left inside the prompt sprite, pixels
  short size;     // glyph box side, pixels
};
constexpr int USE_PROMPT_ICON_COUNT = 1;
inline const PromptIconSlot USE_PROMPT_ICONS[USE_PROMPT_ICON_COUNT > 0 ? USE_PROMPT_ICON_COUNT : 1] = {
    {6, 32, 2, 20},  // use
};
constexpr int PICK_PROMPT_ICON_COUNT = 1;
inline const PromptIconSlot PICK_PROMPT_ICONS[PICK_PROMPT_ICON_COUNT > 0 ? PICK_PROMPT_ICON_COUNT : 1] = {
    {6, 10, 2, 20},  // use
};

struct HudTextData {
  const char* path;  // baked text sprite, relative to the ELF
  float x, y;        // normalized screen position, center anchor
  int w, h;          // texture size (pow2; content centered)
  int visible;       // 1 = shown when the game starts
  int anim;          // looped motion (hudanim::Kind), 0 = none
  float animPeriod, animAmount;
  int trans;         // show/hide transition (hudanim::Transition)
  float transSec;
};

constexpr int HUD_TEXT_COUNT = 2;
inline const HudTextData HUD_TEXTS[HUD_TEXT_COUNT > 0 ? HUD_TEXT_COUNT : 1] = {
    {"hud/text-animated-hud.png", 0.5F, 0.16F, 256, 64, 1, 4, 1.8F, 0.08F, 6, 0.3F},  // ANIMATED HUD
    {"hud/text-controls.png", 0.5F, 0.91F, 512, 32, 1, 1, 2.4F, 0.2F, 0, 0.25F},  // controls
};

struct HudBarData {
  int kind;              // 0 = continuous fill, 1 = quantized segments
  float x, y;            // normalized screen position, center anchor
  float w, h;            // total on-screen size in pixels
  float bg[3], fill[3], ghost[3];  // tints, GS range (128 = 1.0)
  int hasGhost;          // draw the lingering strip where the fill was
  int rightToLeft;       // fill anchored on the right edge
  float smoothing;       // seconds to reach a new value (0 = snap)
  float lowFrac;         // pulse the fill below this fraction (0 = never)
  int segments;          // quantized only
  float spacing;         // quantized: gap between segments, px
  int source;            // save value index, -1 = node-driven
  float minV, maxV, startV;
  const char* fillPath;  // fill image; "" = a tinted quad
  const char* framePath; // frame drawn over the bar; "" = none
  float frameW, frameH;  // the frame's own on-screen size
  int anim;              // looped motion (hudanim::Kind), 0 = none
  float animPeriod, animAmount;
  int trans;             // show/hide transition (hudanim::Transition)
  float transSec;
  int visible;           // 1 = shown when the game starts
};

constexpr int HUD_BAR_COUNT = 3;
inline const HudBarData HUD_BARS[HUD_BAR_COUNT > 0 ? HUD_BAR_COUNT : 1] = {
    {0, 0.24F, 0.08F, 190.0F, 16.0F, {15.36F, 5.12F, 5.12F}, {117.76F, 20.48F, 15.36F}, {128.0F, 99.84F, 25.6F}, 1, 0, 0.28F, 0.3F, 5, 4.0F, 0, 0.0F, 100.0F, 100.0F, "", "", 64.0F, 64.0F, 0, 1.0F, 4.0F, 2, 0.35F, 1},  // health
    {0, 0.76F, 0.08F, 150.0F, 10.0F, {3.84F, 11.52F, 15.36F}, {15.36F, 92.16F, 117.76F}, {74.24F, 115.2F, 128.0F}, 0, 1, 0.18F, 0.0F, 5, 4.0F, -1, 0.0F, 100.0F, 85.0F, "", "", 64.0F, 64.0F, 2, 1.7F, 2.0F, 3, 0.35F, 1},  // stamina
    {1, 0.5F, 0.82F, 180.0F, 14.0F, {15.36F, 15.36F, 20.48F}, {122.88F, 92.16F, 15.36F}, {128.0F, 115.2F, 57.6F}, 0, 0, 0.0F, 0.0F, 5, 6.0F, -1, 0.0F, 5.0F, 3.0F, "", "", 64.0F, 64.0F, 6, 2.2F, 1.5F, 6, 0.25F, 1},  // keys
};

// Every HUD element in one index space (the Set HUD Element Visible /
// Play HUD Effect nodes): images, then texts, then bars.
constexpr int HUD_ELEM_TEXT0 = HUD_COUNT;
constexpr int HUD_ELEM_BAR0 = HUD_COUNT + HUD_TEXT_COUNT;
constexpr int HUD_ELEM_COUNT = HUD_COUNT + HUD_TEXT_COUNT + HUD_BAR_COUNT;

}  // namespace Hud_animation
