#!/usr/bin/env python3
"""Writes the imported props of the physics playground (res/models/).

Low-poly furniture built from boxes, so every model is deliberately CONCAVE
and uneven - exactly the shapes that used to collide as their bounding box:
a stool that stands on four thin legs, a railing that is one long post-and-bar
frame, a chair whose backrest puts the centre of mass off the seat, a table.
The game collides them as their baked convex hulls (docs/physics.md).

Run from the example directory:  python3 authoring/make-props.py
Origins sit at the bottom centre, so a prop placed at y = 0 stands on the
ground.
"""
import os

OUT = os.path.join(os.path.dirname(__file__), "..", "res", "models")

MATERIALS = {
    "wood": (0.62, 0.40, 0.22),
    "darkwood": (0.36, 0.22, 0.12),
    "metal": (0.55, 0.58, 0.62),
    "paint": (0.85, 0.22, 0.12),
    "stripe": (0.95, 0.95, 0.9),
}


def box(cx, cy, cz, sx, sy, sz):
    x0, x1 = cx - sx / 2, cx + sx / 2
    y0, y1 = cy - sy / 2, cy + sy / 2
    z0, z1 = cz - sz / 2, cz + sz / 2
    v = [(x0, y0, z0), (x1, y0, z0), (x1, y1, z0), (x0, y1, z0),
         (x0, y0, z1), (x1, y0, z1), (x1, y1, z1), (x0, y1, z1)]
    # outward, counter-clockwise faces
    f = [(0, 3, 2, 1), (4, 5, 6, 7), (0, 1, 5, 4), (3, 7, 6, 2),
         (0, 4, 7, 3), (1, 2, 6, 5)]
    return v, f


def write(name, parts):
    lines = ["# Generated by authoring/make-props.py", "mtllib props.mtl"]
    base = 1
    for mat, boxes in parts:
        lines.append("usemtl " + mat)
        for b in boxes:
            v, f = box(*b)
            lines += ["v %.4f %.4f %.4f" % p for p in v]
            lines += ["f %d %d %d %d" % tuple(base + i for i in q) for q in f]
            base += 8
    with open(os.path.join(OUT, name + ".obj"), "w", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")


def legs(w, d, h, t, inset=0.0):
    out = []
    for sx in (-1, 1):
        for sz in (-1, 1):
            out.append((sx * (w / 2 - t / 2 - inset), h / 2, sz * (d / 2 - t / 2 - inset), t, h, t))
    return out


os.makedirs(OUT, exist_ok=True)
with open(os.path.join(OUT, "props.mtl"), "w", newline="\n") as fh:
    for n, c in MATERIALS.items():
        fh.write("newmtl %s\nKd %.3f %.3f %.3f\n\n" % (n, *c))

# Bar stool: a small seat on four long, slightly splayed-looking legs.
write("stool", [
    ("wood", [(0, 0.72, 0, 0.42, 0.06, 0.42)]),
    ("darkwood", legs(0.46, 0.46, 0.69, 0.05)
     + [(0, 0.28, 0.19, 0.38, 0.04, 0.03), (0, 0.28, -0.19, 0.38, 0.04, 0.03)]),
])

# Road barrier: two feet, two posts, a striped top rail and a lower bar.
write("barrier", [
    ("metal", [(-0.85, 0.03, 0, 0.12, 0.06, 0.55), (0.85, 0.03, 0, 0.12, 0.06, 0.55),
               (-0.85, 0.5, 0, 0.07, 0.9, 0.07), (0.85, 0.5, 0, 0.07, 0.9, 0.07),
               (0, 0.45, 0, 1.64, 0.05, 0.04)]),
    ("paint", [(-0.55, 0.9, 0, 0.55, 0.18, 0.05), (0.55, 0.9, 0, 0.55, 0.18, 0.05)]),
    ("stripe", [(0, 0.9, 0, 0.55, 0.18, 0.05)]),
])

# Chair: seat, four legs, a tall backrest - centre of mass behind the seat.
write("chair", [
    ("wood", [(0, 0.46, 0, 0.46, 0.05, 0.44),
              (0, 0.95, -0.2, 0.46, 0.34, 0.04)]),
    ("darkwood", legs(0.44, 0.42, 0.44, 0.045)
     + [(-0.2, 0.7, -0.2, 0.045, 0.5, 0.045), (0.2, 0.7, -0.2, 0.045, 0.5, 0.045)]),
])

# Table: a wide top on four legs.
write("table", [
    ("wood", [(0, 0.74, 0, 1.3, 0.06, 0.8)]),
    ("darkwood", legs(1.2, 0.7, 0.71, 0.07, 0.03)),
])
print("wrote", OUT)
