# Build ONE arm of the EE-submission bounding probes
# (docs/ee-submission-rearchitecture.md, "The two probes that come first").
#
# Every arm is a SEPARATE ELF: the probes are compile-time macros in
# vendor/tyra/engine/inc/renderer/3d/pipeline/static/core/stapip_probes.hpp, and
# the engine and the generated game must both see the same values, so the
# header's defaults are what this script moves. Record every ELF's sha256 and
# check that two "arms" are not one binary.
#
# The fixture is regenerated by the editor FOR THIS ARM before the
# instrumentation is applied, then compiled with tools/toolchain/native-build.ps1
# DIRECTLY - an editor --build would regenerate the instrumentation away, and a
# fixture carrying the example's committed generated sources measures a
# different game (docs/vu1-and-dma-cache-cost.md, "the fixture was stale").
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$Arm,
    [int]$AcceptAll = 0,          # Probe A1
    [int]$CoarseClassify = 0,     # Probe A2
    [int]$UncachedChain = 0,      # Probe B: 0 off, 1 P2_TYPE_UNCACHED, 2 UNCACHED_ACCL
    [int]$LogSends = 0,           # Probe B reader - PCSX2 only, never a timing arm
    [int]$ForceFlush = 0,         # Probe B second control: uncached AND still flushing
    [int]$Attrib = 0,             # TYRA_STAPIP_ATTRIB - the classification bracket
    [string]$Root = 'D:/tyra-eeprobe-0916'
)
$ErrorActionPreference = 'Stop'

$worktree = (Resolve-Path (Join-Path $PSScriptRoot '../../../..')).Path
$example  = Join-Path $worktree 'examples/vehicle-playground'
$editor   = 'D:/tyra-editor/build/tyrax-editor.exe'
$header   = Join-Path $worktree 'vendor/tyra/engine/inc/renderer/3d/pipeline/static/core/stapip_probes.hpp'
$cache    = Join-Path $env:LOCALAPPDATA 'tyra-editor/native-build/eeprobe-0916'
$toolchain= Join-Path $env:LOCALAPPDATA 'tyra-editor/toolchain/ps2dev'
$fixture  = Join-Path $Root "arms/$Arm"

if (Test-Path -LiteralPath $fixture) { throw "Archive $fixture before re-running this arm" }
New-Item -ItemType Directory -Force -Path (Join-Path $Root 'arms') | Out-Null

# --- 1. set the arm's macros in the shared header -------------------------
# One edit moves both halves (engine + generated game), which is the contract
# stapip_probes.hpp states. Anything else risks an ODR split on StaPipTelemetry.
$attribHeader = Join-Path $worktree 'vendor/tyra/engine/inc/renderer/3d/pipeline/static/core/stapip_attrib.hpp'
$ah = Get-Content -LiteralPath $attribHeader -Raw
$ahNew = $ah -replace "(?m)^#define\s+TYRA_STAPIP_ATTRIB\s+\d+$", "#define TYRA_STAPIP_ATTRIB $Attrib"
if ($ahNew -eq $ah -and $ah -notmatch "(?m)^#define\s+TYRA_STAPIP_ATTRIB\s+$Attrib$") {
    throw "Could not set TYRA_STAPIP_ATTRIB in $attribHeader"
}
Set-Content -LiteralPath $attribHeader -Value $ahNew -NoNewline -Encoding ascii
if ([IO.File]::ReadAllBytes($attribHeader) -contains 13) { throw "CRLF crept into $attribHeader" }

$h = Get-Content -LiteralPath $header -Raw
foreach ($pair in @(
        @('TYRA_STAPIP_PROBE_ACCEPT_ALL', $AcceptAll),
        @('TYRA_STAPIP_PROBE_COARSE_CLASSIFY', $CoarseClassify),
        @('TYRA_STAPIP_PROBE_UNCACHED_CHAIN', $UncachedChain),
        @('TYRA_STAPIP_PROBE_FORCE_FLUSH', $ForceFlush),
        @('TYRA_STAPIP_PROBE_LOG_SENDS', $LogSends))) {
    $name = $pair[0]; $val = $pair[1]
    $new = $h -replace "(?m)^#define\s+$name\s+\d+$", "#define $name $val"
    if ($new -eq $h -and $h -notmatch "(?m)^#define\s+$name\s+$val$") {
        throw "Could not set $name in $header"
    }
    $h = $new
}
Set-Content -LiteralPath $header -Value $h -NoNewline -Encoding ascii
# LF only under vendor/tyra (.gitattributes; vclpp chokes on CRLF) - and a
# PowerShell write is exactly the kind that reintroduces them.
$bytes = [IO.File]::ReadAllBytes($header)
if ($bytes -contains 13) { throw "CRLF crept into $header - vendor/tyra is LF only" }
Write-Output "== $Arm : acceptAll=$AcceptAll coarse=$CoarseClassify uncached=$UncachedChain logSends=$LogSends"

# --- 2. fixture from the example, with the baked tree copied in -----------
& python (Join-Path $example 'authoring/benchmark-district.py') $fixture --profile debug
if ($LASTEXITCODE -ne 0) { throw 'benchmark-district.py failed' }
Copy-Item -Recurse -Force (Join-Path $example '.res-baked') (Join-Path $fixture '.res-baked')
New-Item -ItemType Directory -Force -Path (Join-Path $fixture 'bin') | Out-Null
foreach ($d in 'aoatlas', 'aomap') {
    $src = Join-Path $example "bin/$d"
    if (Test-Path -LiteralPath $src) { Copy-Item -Recurse -Force $src (Join-Path $fixture "bin/$d") }
}

# --- 3. regenerate, THEN instrument --------------------------------------
& $editor --refresh-gen $fixture
if ($LASTEXITCODE -ne 0) { throw '--refresh-gen failed' }
& python (Join-Path $example 'authoring/instrument-frame-cost.py') $fixture --attribute
if ($LASTEXITCODE -ne 0) { throw 'instrument-frame-cost.py failed' }

# --- 4. compile with the native toolchain directly -----------------------
& (Join-Path $worktree 'tools/toolchain/native-build.ps1') `
    -Project $fixture -Engine (Join-Path $worktree 'vendor/tyra') `
    -Cache $cache -Toolchain $toolchain
if ($LASTEXITCODE -ne 0) { throw 'native-build failed' }

$elf = Join-Path $fixture 'bin/vehicle-playground.elf'
if (!(Test-Path -LiteralPath $elf)) { throw 'No ELF produced' }
$hash = (Get-FileHash -LiteralPath $elf -Algorithm SHA256).Hash
[pscustomobject]@{
    arm = $Arm; acceptAll = $AcceptAll; coarseClassify = $CoarseClassify
    uncachedChain = $UncachedChain; logSends = $LogSends
    forceFlush = $ForceFlush; stapipAttrib = $Attrib
    elfSha256 = $hash; built = (Get-Date).ToString('o')
    editorSha256 = (Get-FileHash -LiteralPath $editor -Algorithm SHA256).Hash
    commit = (& git -C $worktree rev-parse HEAD)
} | ConvertTo-Json | Set-Content -LiteralPath (Join-Path $fixture 'ARM.json')
Write-Output "ELF sha256 $hash"
