// Generated by TyraX. Do not edit - regenerated on every build.
#pragma once

namespace Ambient_occlusion {

constexpr int MODEL_COUNT = 7;
inline const char* MODEL_PATHS[MODEL_COUNT > 0 ? MODEL_COUNT : 1] = {
    "models/Wall_Plaster_Straight.tmdl",
    "models/Wall_Plaster_Door_Round.tmdl",
    "models/Prop_Chimney2.tmdl",
    "models/Prop_Wagon.tmdl",
    "models/Stairs_Exterior_Straight_Center.tmdl",
    "models/Prop_Crate.tmdl",
    "models/Prop_WoodenFence_Single.tmdl",
};
// per-model .mtl override, for the .obj fallback path only (a
// .tmdl already carries the resolved override) - "" = none
inline const char* MODEL_MTLS[MODEL_COUNT > 0 ? MODEL_COUNT : 1] = {
    "",
    "",
    "",
    "",
    "",
    "",
    "",
};
// The AUTHORED asset path each slot was baked from ("res/models/x.obj").
// Nothing loads it - it is the key a runtime procedural volume
// resolves its asset pool against, because a graph names assets the
// way the editor does and the console only has baked .tmdl names.
inline const char* MODEL_SOURCES[MODEL_COUNT > 0 ? MODEL_COUNT : 1] = {
    "res/models/Wall_Plaster_Straight.obj",
    "res/models/Wall_Plaster_Door_Round.obj",
    "res/models/Prop_Chimney2.obj",
    "res/models/Prop_Wagon.obj",
    "res/models/Stairs_Exterior_Straight_Center.obj",
    "res/models/Prop_Crate.obj",
    "res/models/Prop_WoodenFence_Single.obj",
};
constexpr bool MODEL_NEEDS_COLLIDER[MODEL_COUNT > 0 ? MODEL_COUNT : 1] = {false, false, false, false, false, false, false};

constexpr int ANIM_MODEL_COUNT = 0;
inline const char* ANIM_MODEL_PATHS[ANIM_MODEL_COUNT > 0 ? ANIM_MODEL_COUNT : 1] = {
    "",
};

// Per-clip Foot IK rules, sliced per rig by firstRule/ruleCount.
// The clip is the EFFECTIVE (post-rename) name, which is what
// the .tskl carries and what SkelInstance reports.
struct FootIkClipRuleData {
  const char* clip;
  int solve;             // 0 = this clip plays as authored
  float plantScale;      // x plant / release / descent reach
  float clearanceScale;  // x toe clearance
};
constexpr int FOOT_IK_CLIP_RULE_COUNT = 0;
inline const FootIkClipRuleData FOOT_IK_CLIP_RULES[FOOT_IK_CLIP_RULE_COUNT > 0 ? FOOT_IK_CLIP_RULE_COUNT : 1] = {
    {"", 1, 1.0F, 1.0F},
};

// The leg binding and tolerances of one animated model asset.
// Bones are bound by NAME so a re-export may reorder the
// hierarchy; the game resolves them once per instance.
struct FootIkRigData {
  int solve;  // 0 = this model is not bound; ignore the rest
  const char *leftHip, *leftKnee, *leftAnkle;
  const char *rightHip, *rightKnee, *rightAnkle;
  float sole, probeUp, probeDown, plant, release, pelvis;
  float maxFootAngle, toeClearance, descendReach;
  int neural;            // learned VU0 assist (raycast-gated)
  float neuralStrength;  // 0..1 influence
  int firstRule, ruleCount;  // slice of FOOT_IK_CLIP_RULES
};
inline const FootIkRigData FOOT_IK_RIGS[ANIM_MODEL_COUNT > 0 ? ANIM_MODEL_COUNT : 1] = {
    {0, "", "", "", "", "", "", 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0, 0.0F, 0, 0},
};

// .mtl libraries assigned to primitives (first material = surface)
constexpr int MATERIAL_COUNT = 3;
inline const char* MATERIAL_PATHS[MATERIAL_COUNT > 0 ? MATERIAL_COUNT : 1] = {
    "materials/terrace.mtl",
    "materials/wall.mtl",
    "materials/plaster.mtl",
};

// texture atlas summary, logged at scene boot ("" = no atlas)
constexpr const char* TEXTURE_ATLAS_INFO = "";

}  // namespace Ambient_occlusion
