// Generated by TyraX. Do not edit - regenerated on every build.
#pragma once

namespace Glow {

constexpr int TEXTURE_COUNT = 0;
inline const char* TEXTURE_PATHS[TEXTURE_COUNT > 0 ? TEXTURE_COUNT : 1] = {
    "",
};

constexpr int TERRAIN_TEXTURES[1] = {-1};
constexpr float TERRAIN_TILE_US[1] = {1.0F};
constexpr float TERRAIN_TILE_VS[1] = {1.0F};
constexpr bool TERRAIN_HAS_MATERIALS[1] = {true};
constexpr float TERRAIN_TINTS[1][3] = {{0.26F, 0.26F, 0.3F}};
constexpr float TERRAIN_TINT_VARIATIONS[1] = {0.0F};
constexpr float TERRAIN_TINT_SCALES[1] = {24.0F};

constexpr int TERRAIN_LAYER_COUNTS[1] = {0};
constexpr int TERRAIN_MAX_LAYERS = 1;
constexpr int TERRAIN_LAYER_TEXTURES[1][1] = {};
constexpr float TERRAIN_LAYER_TILE_US[1][1] = {};
constexpr float TERRAIN_LAYER_TILE_VS[1][1] = {};
constexpr float TERRAIN_LAYER_TINTS[1][1][3] = {};

}  // namespace Glow
