// Generated by TyraX. Do not edit - regenerated on every build.
#pragma once

// Ambient-occlusion occluders: solid authored objects as oriented
// boxes / spheres, baked on the host. ax/ay/az = the object's local
// axes in world space; sphere = 1 reads half[0] as the radius;
// objIndex = scene-table index (an object never occludes itself).

namespace {
struct AoOccData {
  float pos[3];
  float ax[3], ay[3], az[3];
  float half[3];
  int sphere;
  int objIndex;
};

static const AoOccData S0_AO_OCC[7] = {
    {{0.0F, 2.2F, 0.0F}, {0.939693F, 0.0F, -0.34202F}, {0.0F, 1.0F, 0.0F}, {0.34202F, 0.0F, 0.939693F}, {3.4F, 2.2F, 3.4F}, 0, 0},
    {{-5.0F, 1.4F, -5.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.45F, 1.4F, 0.45F}, 0, 1},
    {{5.0F, 1.4F, -5.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.45F, 1.4F, 0.45F}, 0, 2},
    {{-5.0F, 1.4F, 5.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.45F, 1.4F, 0.45F}, 0, 3},
    {{5.0F, 1.4F, 5.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.45F, 1.4F, 0.45F}, 0, 4},
    {{-7.5F, 0.8F, 0.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.8F, 0.8F, 0.8F}, 1, 5},
    {{7.5F, 0.8F, 0.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.8F, 0.8F, 0.8F}, 1, 6},
};

static const AoOccData* const SCENE_AO_OCC_TABLES[] = {S0_AO_OCC};
static const int SCENE_AO_OCC_COUNTS[] = {7};

struct AoAtlasRect {
  float u0, v0, du, dv;
};
static const AoAtlasRect S0_AO_RECTS[26] = {{0.675781F, 0.160156F, 0.125F, 0.03125F}, {0.527344F, 0.214844F, 0.125F, 0.03125F}, {0.472656F, 0.214844F, 0.03125F, 0.03125F}, {0.417969F, 0.214844F, 0.03125F, 0.03125F}, {0.488281F, 0.0117188F, 0.03125F, 0.125F}, {0.542969F, 0.0117188F, 0.03125F, 0.125F}, {0.269531F, 0.214844F, 0.125F, 0.03125F}, {0.121094F, 0.214844F, 0.125F, 0.03125F}, {0.0664062F, 0.214844F, 0.03125F, 0.03125F}, {0.0117188F, 0.214844F, 0.03125F, 0.03125F}, {0.652344F, 0.0117188F, 0.03125F, 0.125F}, {0.707031F, 0.0117188F, 0.03125F, 0.125F}, {0.824219F, 0.160156F, 0.125F, 0.03125F}, {0.0117188F, 0.160156F, 0.125F, 0.03125F}, {0.621094F, 0.160156F, 0.03125F, 0.03125F}, {0.566406F, 0.160156F, 0.03125F, 0.03125F}, {0.816406F, 0.0117188F, 0.03125F, 0.125F}, {0.761719F, 0.0117188F, 0.03125F, 0.125F}, {0.417969F, 0.160156F, 0.125F, 0.03125F}, {0.269531F, 0.160156F, 0.125F, 0.03125F}, {0.214844F, 0.160156F, 0.03125F, 0.03125F}, {0.160156F, 0.160156F, 0.03125F, 0.03125F}, {0.597656F, 0.0117188F, 0.03125F, 0.125F}, {0.433594F, 0.0117188F, 0.03125F, 0.125F}, {0.222656F, 0.0117188F, 0.1875F, 0.125F}, {0.0117188F, 0.0117188F, 0.1875F, 0.125F}};
static const int S0_AO_FIRST[7] = {-1, 0, 6, 12, 18, 24, 25};
static const AoAtlasRect* const SCENE_AO_ATLAS_RECTS_T[] = {S0_AO_RECTS};
static const int* const SCENE_AO_ATLAS_FIRSTS_T[] = {S0_AO_FIRST};
static const char* const SCENE_AO_ATLAS_PATHS[] = {"aoatlas/scene0.png"};
static const char* const SCENE_AO_MAP_PATHS[] = {"aomap/scene0.png"};
}  // namespace

#define SCENE_AO_OCC SCENE_AO_OCC_TABLES[g_activeScene]
#define SCENE_AO_OCC_COUNT SCENE_AO_OCC_COUNTS[g_activeScene]
#define SCENE_AO_ATLAS_RECTS SCENE_AO_ATLAS_RECTS_T[g_activeScene]
#define SCENE_AO_ATLAS_FIRST SCENE_AO_ATLAS_FIRSTS_T[g_activeScene]
#define SCENE_AO_ATLAS_PATH SCENE_AO_ATLAS_PATHS[g_activeScene]
#define SCENE_AO_MAP_PATH SCENE_AO_MAP_PATHS[g_activeScene]
