// Generated by TyraX. Do not edit - regenerated on every build.
#pragma once

namespace Material_lab {

constexpr int MODEL_COUNT = 1;
inline const char* MODEL_PATHS[MODEL_COUNT > 0 ? MODEL_COUNT : 1] = {
    "models/altar.obj",
};
// per-model .mtl override ("" = the model's own material libraries)
inline const char* MODEL_MTLS[MODEL_COUNT > 0 ? MODEL_COUNT : 1] = {
    "",
};
constexpr bool MODEL_NEEDS_COLLIDER[MODEL_COUNT > 0 ? MODEL_COUNT : 1] = {false};

constexpr int ANIM_MODEL_COUNT = 0;
inline const char* ANIM_MODEL_PATHS[ANIM_MODEL_COUNT > 0 ? ANIM_MODEL_COUNT : 1] = {
    "",
};

// .mtl libraries assigned to primitives (first material = surface)
constexpr int MATERIAL_COUNT = 3;
inline const char* MATERIAL_PATHS[MATERIAL_COUNT > 0 ? MATERIAL_COUNT : 1] = {
    "materials/pillar.mtl",
    "materials/trim.mtl",
    "materials/canvas.mtl",
};

// texture atlas summary, logged at scene boot ("" = no atlas)
constexpr const char* TEXTURE_ATLAS_INFO = "Texture atlas: 3 textures in 2 page(s)";

}  // namespace Material_lab
