// Generated by TyraX. Do not edit - regenerated on every build.
// Weapons are edited in Tools > Weapon Editor (docs/weapons.md).
#pragma once

// The project uses no combat - the weapon tables and runtime are not generated.
