// Generated by TyraX. Do not edit - regenerated on every build.
#pragma once

#include "scripts/script.hpp"

namespace Save_points {
namespace credits {
// What a finished roll asks the game to do (CreditsRollData::finish
// resolved): the player itself cannot switch scenes or open menus -
// those live on TerrainGame - so it reports and the loop applies.
struct Result {
  int finish = 0;  // 0 resume, 1 scene, 2 menu, 3 event, 4 hold
  int scene = -1;
  int menu = -1;
  int event = -1;
};

extern int g_active;  // rolling index, -1 = none
// Rolls that have finished this session. The On Credits Finished
// trigger watches THIS rather than the falling edge of playing():
// a roll freezes every graph, so a node cannot latch "it was
// playing" while it runs.
extern int g_ended;
// True while a roll owns the screen and the pad.
inline bool playing() { return g_active >= 0; }
inline int endCount() { return g_ended; }
void play(int index);  // start CREDITS[index] from the top
void stop();           // end it now, as a skip would
// One frame of the roll: presents it and advances. The returned
// Result matters only on the frame playing() goes false.
Result tick(Tyra::Engine* engine, Tyra::Pad& pad, float dt);
}  // namespace credits
}  // namespace Save_points
