// Generated by TyraX. Do not edit - regenerated on every build.
#pragma once

namespace Two_players {

// A credits roll. The roll's blocks are already pixels: the editor
// bakes them into a vertical STRIP of pow2 page textures, and the
// runtime scrolls that strip past the screen (or shows one page at a
// time in card mode) - see docs/credits.md.
struct CreditsRollData {
  const char* name;
  float bg[3];       // clear color behind everything, 0..255
  const char* bgPath;  // still backdrop ("" = none)
  float bgX, bgY, bgW, bgH;  // normalized center anchor + px size
  int pageFirst, pageCount;  // slice into CREDITS_PAGES
  int pageW, pageH;          // page texture size
  int contentH;              // laid-out strip height in px
  int opaque;   // 1 = pages are opaque plates of bg (no backdrop)
  int mode;     // 0 = scroll up, 1 = one card per page
  float speed;         // scroll: px per second
  float cardSeconds;   // cards: seconds per card
  float startDelay, endHold, fadeIn, fadeOut;
  const char* music;   // track to start ("" = leave the current one)
  int musicLoop, musicStop, musicVolume;
  int skippable;
  // INPUT_ACTION index the skip listens on; -1 = the menu confirm
  // and menu (Start) roles, i.e. "any of the obvious buttons".
  int skipAction;
  float skipAfter;
  const char* hintPath;  // baked skip hint ("" = none)
  int hintW, hintH;
  float hintX, hintY;
  // What happens when the roll ends or is skipped: 0 resume the
  // game, 1 switch scene, 2 open menu, 3 fire a flow event, 4 hold
  // the last frame. The targets are resolved indices (-1 = unknown,
  // which degrades to "resume").
  int finish, finishScene, finishMenu, finishEvent;
};

constexpr int CREDITS_COUNT = 0;
constexpr int CREDITS_PAGE_TOTAL = 0;
inline const char* const CREDITS_PAGES[CREDITS_PAGE_TOTAL > 0 ? CREDITS_PAGE_TOTAL : 1] = {
    "",
};

inline const CreditsRollData CREDITS[CREDITS_COUNT > 0 ? CREDITS_COUNT : 1] = {
    {"", {0, 0, 0}, "", 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "", 0, 0, 0, 0, -1, 0, "", 0, 0, 0, 0, 0, -1, -1, -1},
};

}  // namespace Two_players
