// Generated by TyraX. Do not edit - regenerated on every build.
#pragma once

// Ambient-occlusion occluders: solid authored objects as oriented
// boxes / spheres, baked on the host. ax/ay/az = the object's local
// axes in world space; sphere = 1 reads half[0] as the radius;
// objIndex = scene-table index (an object never occludes itself).

namespace {
struct AoOccData {
  float pos[3];
  float ax[3], ay[3], az[3];
  float half[3];
  int sphere;
  int objIndex;
};

static const AoOccData S0_AO_OCC[16] = {
    {{-6.375F, 0.5F, 13.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.35F, 0.5F, 0.35F}, 0, 1},
    {{-5.525F, 0.5F, 13.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.35F, 0.5F, 0.35F}, 0, 2},
    {{-4.675F, 0.5F, 13.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.35F, 0.5F, 0.35F}, 0, 3},
    {{-3.825F, 0.5F, 13.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.35F, 0.5F, 0.35F}, 0, 4},
    {{-2.975F, 0.5F, 13.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.35F, 0.5F, 0.35F}, 0, 5},
    {{-2.125F, 0.5F, 13.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.35F, 0.5F, 0.35F}, 0, 6},
    {{-1.275F, 0.5F, 13.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.35F, 0.5F, 0.35F}, 0, 7},
    {{-0.425F, 0.5F, 13.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.35F, 0.5F, 0.35F}, 0, 8},
    {{0.425F, 0.5F, 13.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.35F, 0.5F, 0.35F}, 0, 9},
    {{1.275F, 0.5F, 13.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.35F, 0.5F, 0.35F}, 0, 10},
    {{2.125F, 0.5F, 13.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.35F, 0.5F, 0.35F}, 0, 11},
    {{2.975F, 0.5F, 13.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.35F, 0.5F, 0.35F}, 0, 12},
    {{3.825F, 0.5F, 13.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.35F, 0.5F, 0.35F}, 0, 13},
    {{4.675F, 0.5F, 13.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.35F, 0.5F, 0.35F}, 0, 14},
    {{5.525F, 0.5F, 13.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.35F, 0.5F, 0.35F}, 0, 15},
    {{6.375F, 0.5F, 13.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.35F, 0.5F, 0.35F}, 0, 16},
};

static const AoOccData* const SCENE_AO_OCC_TABLES[] = {S0_AO_OCC};
static const int SCENE_AO_OCC_COUNTS[] = {16};

struct EmisLightData {
  float pos[3];
  float ax[3], ay[3], az[3];
  float half[3];
  int sphere;
  int objIndex;
  float color[3];
  float range, bright;
};


static const EmisLightData* const SCENE_EMIS_TABLES[] = {nullptr};
static const int SCENE_EMIS_COUNTS[] = {0};

struct AoAtlasRect {
  float u0, v0, du, dv;
};
static const AoAtlasRect* const SCENE_AO_ATLAS_RECTS_T[] = {nullptr};
static const int* const SCENE_AO_ATLAS_FIRSTS_T[] = {nullptr};
static const unsigned char* const SCENE_AO_ATLAS_LITS_T[] = {nullptr};
static const char* const SCENE_AO_ATLAS_PATHS[] = {""};
static const char* const SCENE_AO_MAP_PATHS[] = {"aomap/scene0.png"};
static const unsigned char SCENE_AO_MAP_OCCS[] = {1};
static const unsigned char SCENE_AO_MAP_LITS[] = {0};
static const unsigned char SCENE_AO_ATLAS_GIS[] = {0};
static const unsigned char SCENE_AO_MAP_GIS[] = {0};
}  // namespace

#define SCENE_AO_OCC SCENE_AO_OCC_TABLES[g_activeScene]
#define SCENE_AO_OCC_COUNT SCENE_AO_OCC_COUNTS[g_activeScene]
#define SCENE_EMIS SCENE_EMIS_TABLES[g_activeScene]
#define SCENE_EMIS_COUNT SCENE_EMIS_COUNTS[g_activeScene]
#define SCENE_AO_ATLAS_RECTS SCENE_AO_ATLAS_RECTS_T[g_activeScene]
#define SCENE_AO_ATLAS_FIRST SCENE_AO_ATLAS_FIRSTS_T[g_activeScene]
#define SCENE_AO_ATLAS_LIT SCENE_AO_ATLAS_LITS_T[g_activeScene]
#define SCENE_AO_ATLAS_PATH SCENE_AO_ATLAS_PATHS[g_activeScene]
#define SCENE_AO_MAP_PATH SCENE_AO_MAP_PATHS[g_activeScene]
#define SCENE_AO_MAP_OCC SCENE_AO_MAP_OCCS[g_activeScene]
#define SCENE_AO_MAP_LIT SCENE_AO_MAP_LITS[g_activeScene]
#define SCENE_AO_ATLAS_GI SCENE_AO_ATLAS_GIS[g_activeScene]
#define SCENE_AO_MAP_GI SCENE_AO_MAP_GIS[g_activeScene]
