from pathlib import Path
import shutil,json,hashlib
b=Path('F:/Projects/tyrax2-lab-20261001');f=b/'light-pick-far-physical-v1';h=b/'light-pick-far-root-helpers-v1';c=b/'light-pick-far-controls-v1';assert not h.exists()and not c.exists();shutil.copytree(b/'corona24-pricing-root-helpers-v1',h);shutil.copytree(b/'wild-gs-sprite-corona-controls-v2',c);sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
for p in h.iterdir():
 if p.suffix in('.py','.ps1','.md'):
  s=p.read_text(encoding='utf8').replace('corona24-pricing-physical-v1','light-pick-far-physical-v1').replace('corona24-pricing-root-helpers-v1','light-pick-far-root-helpers-v1').replace('wild-gs-sprite-corona-controls-v2','light-pick-far-controls-v1');s=s.replace('choices=(9,)','choices=(12,)').replace('a.kind==9','a.kind==12').replace("d['kind']==9","d['kind']==12").replace('kind==9 and order','kind==12 and order');p.write_bytes(s.encode())
p=h/'qualify-emulator.py';s=p.read_text(encoding='utf8');a="assert len(coronaRows)==1 and coronaRows[0][0]=='1' and int(coronaRows[0][1])==int((current==1)!=(d['order']==1))";assert a in s;s=s.replace(a,"assert len(coronaRows)==1 and coronaRows[0]==('0','0'); rr=re.findall(r'LOG: NIGHTFARPICKPHASE phase='+str(current)+r' enabled=(\\d+)',after);assert len(rr)==1 and int(rr[0])==int((current==1)!=(d['order']==1))");s=s.replace('coronaSpriteEnabled=int(coronaRows[0][1]),','coronaSpriteEnabled=0,farPickEnabled=int(rr[0]),');p.write_bytes(s.encode())
shutil.copy2(f/'tyra/engine/inc/debug/night_plan.hpp',c/'source-controls/night_plan.hpp')
p=c/'analyze-night.py';s=p.read_text(encoding='utf8').replace('in(5,6,7,8,9)','in(5,6,7,8,9,12)').replace('in(3,5,6,7,8,9)','in(3,5,6,7,8,9,12)').replace('in(7,8,9)','in(7,8,9,12)').replace('in(8,9)','in(8,9,12)');a=' # Native dialect9: full inherited sampler plus actual typed cold request accounting.';assert a in s;s=s.replace(a,''' if kind==12:
  fp=loop.unique(loop.rows(stdout,'NIGHTFARPICKPHASE'),'phase',range(3));flags=[int((p==1)!=(order==1))for p in range(3)];fg=loop.rows(stdout,'NIGHTFARPICKGATES');need(len(fg)==6,'six far-pick gates');fm={}
  for p,row in fp.items():need(set(row)=={'phase','enabled'} and n(row,'enabled')==flags[p],'far-pick phase')
  for row in fg:
   need(set(row)==set('phase offset enabled calls candidates rejected applied compared mismatches'.split()),'far-pick schema');key=(n(row,'phase'),n(row,'offset'));need(key in gs and key not in fm,'far-pick ownership');fm[key]=row;en=flags[key[0]]
   need(all(n(row,k)<=0xffffffff for k in row),'far-pick uint32');need(n(row,'enabled')==en and n(row,'calls')==n(row,'compared')>0 and n(row,'mismatches')==0,'far-pick target parity');need(0<n(row,'rejected')<=n(row,'candidates')<=9*n(row,'calls'),'far-pick candidate bounds');need(n(row,'applied')==en*n(row,'rejected'),'far-pick actual arm')
  need(set(fm)==set(gs),'far-pick identities');r.update(farPickFlags=flags,farPickColdWindows={f'{p}:{o}':row for(p,o),row in fm.items()},farPickFullTimedActivationKnown=False)
'''+a);s=s.replace("r['interpretation']='GS SPRITE", "r['interpretation']='Far light broad-phase candidate elapsed contrast' if kind==12 else 'GS SPRITE");p.write_bytes(s.encode())
p=c/'analyze-night-cli.py';s=p.read_text(encoding='utf8').replace('choices=[0,1,2,3,5,6,7,8,9]','choices=[12]');p.write_bytes(s.encode());files=['analyze-loop.py','analyze-night.py','analyze-night-cli.py','corona_controls.py','source-controls/night_plan.hpp','source-controls/stapip_vu1_shared_defines.h'];(h/'host-authority.json').write_bytes((json.dumps(dict(sourcePins={str(c/n):sha(c/n)for n in files},pricingSourceManifestSha256=sha(f/'target-source-manifest.json')),indent=2)+'\n').encode());(h/'source-review.md').write_bytes(b'Private kind12 full-night broad phase, all visual families retained. Same-ELF on/off selection with untimed actual EE pointer oracle. Wide exponent margin; no score/tie/order changes, no cache. Host parity does not replace actual target parity; common code/branch footprint unpriced.\n')
s=(b/'compile-corona24-pricing-abi-root-v1.py').read_text(encoding='utf8').replace('corona24-pricing-physical-v1','light-pick-far-physical-v1');(b/'compile-light-pick-far-abi-root-v1.py').write_bytes(s.encode())
s=(b/'audit-corona24-pricing-native-root-v1.py').read_text(encoding='utf8');start=s.index("assert F.name=='corona24-pricing-physical-v1'");end=s.index("assert sha(F/'target-source-manifest.json')",start);s=s[:start]+'''assert F.name=='light-pick-far-physical-v1'
base=read(pin(F.parent/'corona24-pricing-physical-v1/target-source-manifest.json'));assert sorted(k for k in m['files']if m['files'][k]!=base['files'][k])==fr['changes']
'''+s[end:];s=s.replace('PASS_ROOT_CORONA_ACTUAL_NATIVE_501_SOURCE_LINKED_TC_ABI_ASSETS','PASS_ROOT_FAR_PICK_ACTUAL_NATIVE_501_SOURCE_LINKED_ABI_ASSETS');(b/'audit-light-pick-far-native-root-v1.py').write_bytes(s.encode())
for n in('start','wait'):
 s=(b/f'{n}-corona24-physical-root-v1.ps1').read_text(encoding='utf8').replace('corona24-pricing-root-helpers-v1','light-pick-far-root-helpers-v1').replace('--kind 9','--kind 12');(b/f'{n}-light-pick-far-physical-root-v1.ps1').write_bytes(s.encode())
print(h,c)
