// Generated by TyraX. Do not edit - regenerated on every build.
#pragma once

namespace Night_walk {

constexpr int MODEL_COUNT = 36;
inline const char* MODEL_PATHS[MODEL_COUNT > 0 ? MODEL_COUNT : 1] = {
    "models/shed__ovrf284.tmdl",
    "models/shed.tmdl",
    "models/procgen-5c17a90e-pine-xm3zm2.tmdl",
    "models/procgen-5c17a90e-pine-xm2zm2.tmdl",
    "models/procgen-5c17a90e-pine-xm2zm1.tmdl",
    "models/procgen-5c17a90e-pine-xm2z0.tmdl",
    "models/procgen-5c17a90e-pine-xm2z1.tmdl",
    "models/procgen-5c17a90e-pine-xm1zm2.tmdl",
    "models/procgen-5c17a90e-pine-xm1zm1.tmdl",
    "models/procgen-5c17a90e-pine-xm1z0.tmdl",
    "models/procgen-5c17a90e-pine-xm1z1.tmdl",
    "models/procgen-5c17a90e-pine-x0zm2.tmdl",
    "models/procgen-5c17a90e-pine-x0zm1.tmdl",
    "models/procgen-5c17a90e-pine-x0z0.tmdl",
    "models/procgen-5c17a90e-pine-x0z1.tmdl",
    "models/procgen-5c17a90e-pine-x1zm2.tmdl",
    "models/procgen-5c17a90e-pine-x1zm1.tmdl",
    "models/procgen-5c17a90e-pine-x1z0.tmdl",
    "models/procgen-5c17a90e-pine-x1z1.tmdl",
    "models/procgen-5c17a90e-rock-xm2zm2.tmdl",
    "models/procgen-5c17a90e-rock-xm2zm1.tmdl",
    "models/procgen-5c17a90e-rock-xm2z0.tmdl",
    "models/procgen-5c17a90e-rock-xm2z1.tmdl",
    "models/procgen-5c17a90e-rock-xm1zm2.tmdl",
    "models/procgen-5c17a90e-rock-xm1zm1.tmdl",
    "models/procgen-5c17a90e-rock-xm1z0.tmdl",
    "models/procgen-5c17a90e-rock-xm1z1.tmdl",
    "models/procgen-5c17a90e-rock-xm1z2.tmdl",
    "models/procgen-5c17a90e-rock-x0zm2.tmdl",
    "models/procgen-5c17a90e-rock-x0zm1.tmdl",
    "models/procgen-5c17a90e-rock-x0z0.tmdl",
    "models/procgen-5c17a90e-rock-x0z1.tmdl",
    "models/procgen-5c17a90e-rock-x1zm2.tmdl",
    "models/procgen-5c17a90e-rock-x1zm1.tmdl",
    "models/procgen-5c17a90e-rock-x1z0.tmdl",
    "models/procgen-5c17a90e-rock-x1z1.tmdl",
};
// per-model .mtl override, for the .obj fallback path only (a
// .tmdl already carries the resolved override) - "" = none
inline const char* MODEL_MTLS[MODEL_COUNT > 0 ? MODEL_COUNT : 1] = {
    "materials/shed-lit-lit.mtl",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
};
// The AUTHORED asset path each slot was baked from ("res/models/x.obj").
// Nothing loads it - it is the key a runtime procedural volume
// resolves its asset pool against, because a graph names assets the
// way the editor does and the console only has baked .tmdl names.
inline const char* MODEL_SOURCES[MODEL_COUNT > 0 ? MODEL_COUNT : 1] = {
    "res/models/shed.obj",
    "res/models/shed.obj",
    "res/models/procgen-5c17a90e-pine-xm3zm2.obj",
    "res/models/procgen-5c17a90e-pine-xm2zm2.obj",
    "res/models/procgen-5c17a90e-pine-xm2zm1.obj",
    "res/models/procgen-5c17a90e-pine-xm2z0.obj",
    "res/models/procgen-5c17a90e-pine-xm2z1.obj",
    "res/models/procgen-5c17a90e-pine-xm1zm2.obj",
    "res/models/procgen-5c17a90e-pine-xm1zm1.obj",
    "res/models/procgen-5c17a90e-pine-xm1z0.obj",
    "res/models/procgen-5c17a90e-pine-xm1z1.obj",
    "res/models/procgen-5c17a90e-pine-x0zm2.obj",
    "res/models/procgen-5c17a90e-pine-x0zm1.obj",
    "res/models/procgen-5c17a90e-pine-x0z0.obj",
    "res/models/procgen-5c17a90e-pine-x0z1.obj",
    "res/models/procgen-5c17a90e-pine-x1zm2.obj",
    "res/models/procgen-5c17a90e-pine-x1zm1.obj",
    "res/models/procgen-5c17a90e-pine-x1z0.obj",
    "res/models/procgen-5c17a90e-pine-x1z1.obj",
    "res/models/procgen-5c17a90e-rock-xm2zm2.obj",
    "res/models/procgen-5c17a90e-rock-xm2zm1.obj",
    "res/models/procgen-5c17a90e-rock-xm2z0.obj",
    "res/models/procgen-5c17a90e-rock-xm2z1.obj",
    "res/models/procgen-5c17a90e-rock-xm1zm2.obj",
    "res/models/procgen-5c17a90e-rock-xm1zm1.obj",
    "res/models/procgen-5c17a90e-rock-xm1z0.obj",
    "res/models/procgen-5c17a90e-rock-xm1z1.obj",
    "res/models/procgen-5c17a90e-rock-xm1z2.obj",
    "res/models/procgen-5c17a90e-rock-x0zm2.obj",
    "res/models/procgen-5c17a90e-rock-x0zm1.obj",
    "res/models/procgen-5c17a90e-rock-x0z0.obj",
    "res/models/procgen-5c17a90e-rock-x0z1.obj",
    "res/models/procgen-5c17a90e-rock-x1zm2.obj",
    "res/models/procgen-5c17a90e-rock-x1zm1.obj",
    "res/models/procgen-5c17a90e-rock-x1z0.obj",
    "res/models/procgen-5c17a90e-rock-x1z1.obj",
};
constexpr bool MODEL_NEEDS_COLLIDER[MODEL_COUNT > 0 ? MODEL_COUNT : 1] = {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false};

constexpr int ANIM_MODEL_COUNT = 0;
inline const char* ANIM_MODEL_PATHS[ANIM_MODEL_COUNT > 0 ? ANIM_MODEL_COUNT : 1] = {
    "",
};

// .mtl libraries assigned to primitives (first material = surface)
constexpr int MATERIAL_COUNT = 0;
inline const char* MATERIAL_PATHS[MATERIAL_COUNT > 0 ? MATERIAL_COUNT : 1] = {
    "",
};

// texture atlas summary, logged at scene boot ("" = no atlas)
constexpr const char* TEXTURE_ATLAS_INFO = "";

}  // namespace Night_walk
