// Generated by tyra-editor from the per-object Flow Graphs. Do not
// edit - regenerated on every build. Edit the graphs in the editor.
#include "scripts/script.hpp"

#include <math.h>
#include <stdio.h>

#include <string>

namespace Video_modes {

// Scene "main": graph of "aspect-ball" (object 0)
class FlowGraphScript_0_0 : public Script {
 public:
  void update(ScriptContext& ctx) override {
    if (ctx.scene != 0) return;
    if (ctx.sceneGeneration != generation) {
      // scene was (re)loaded - back to the initial state
      generation = ctx.sceneGeneration;
      frame = 0;
      started = false;
    }
    frame++;
    if (ctx.engine->pad.getClicked().Square) {
      ctx.requestDisplayMode = 0;
      ctx.displayConfirmSec = 8.0F;
    }
    if (ctx.engine->pad.getClicked().Triangle) {
      ctx.requestDisplayMode = 1;
      ctx.displayConfirmSec = 8.0F;
    }
    if (ctx.engine->pad.getClicked().Circle) {
      ctx.requestDisplayMode = 2;
      ctx.displayConfirmSec = 8.0F;
    }
    if (ctx.engine->pad.getClicked().L1) {
      ctx.widescreen = 0;
    }
    if (ctx.engine->pad.getClicked().R1) {
      ctx.widescreen = 1;
    }
  }

 private:
  unsigned int generation = 0;
  int frame = 0;
  bool started = false;
};

}  // namespace Video_modes

TYRA_SCRIPT(Video_modes::FlowGraphScript_0_0);
