// Generated by TyraX (src/vugen.cpp). Do not edit - regenerate from
// the C++ description with: tyrax-editor --vu-emit <dir>
//
// The unpack layout below and the microprogram's addressing come from
// ONE description, so they cannot drift apart - which is the whole
// reason this file is generated (docs/vu-framework.md).

#include "debug/debug.hpp"
#include "renderer/3d/pipeline/static/core/programs/as_is/stapip_as_is_td_vu1_program.hpp"

#include "renderer/3d/pipeline/static/core/stapip_vu1_experiments.hpp"

// Modified by TyraX: a measured-only experiment can swap in another image
// (stapip_vu1_experiments.hpp). The #if branch is the experiment; the
// #else branch is the shipping image `--vu-check` verifies.
#if TYRA_VU1_EXP_EE_LIGHT_FOLD
extern u32 StaPipVU1As_Is_TD_FOLD_CodeStart __attribute__((section(".vudata")));
extern u32 StaPipVU1As_Is_TD_FOLD_CodeEnd __attribute__((section(".vudata")));
#define TYRA_WRAPPER_IMAGE_START (&StaPipVU1As_Is_TD_FOLD_CodeStart)
#define TYRA_WRAPPER_IMAGE_END (&StaPipVU1As_Is_TD_FOLD_CodeEnd)
#else
extern u32 StaPipVU1As_Is_TD_CodeStart __attribute__((section(".vudata")));
extern u32 StaPipVU1As_Is_TD_CodeEnd __attribute__((section(".vudata")));
#define TYRA_WRAPPER_IMAGE_START (&StaPipVU1As_Is_TD_CodeStart)
#define TYRA_WRAPPER_IMAGE_END (&StaPipVU1As_Is_TD_CodeEnd)
#endif

namespace Tyra {

StaPipAsIsTDVU1Program::StaPipAsIsTDVU1Program()
    : StaPipVU1Program(StaPipAsIsTextureDirLights, TYRA_WRAPPER_IMAGE_START,
                       TYRA_WRAPPER_IMAGE_END,
                       ((u64)GIF_REG_ST) << 0 | ((u64)GIF_REG_RGBAQ) << 4 |
                           ((u64)GIF_REG_XYZF2) << 8,
                       3, 4) {}

StaPipAsIsTDVU1Program::~StaPipAsIsTDVU1Program() {}

std::string StaPipAsIsTDVU1Program::getStringName() const {
  return std::string("StaPip - As is - TD");
}

void StaPipAsIsTDVU1Program::addProgramQBufferDataToPacket(
    packet2_t* packet, StaPipQBuffer* qbuffer) const {
  u32 addr = VU1_STAPIP_VERT_DATA_ADDR;

  // Vertices
  packet2_utils_vu_add_unpack_data(packet, addr, qbuffer->vertices,
                                   qbuffer->size, true);

  // ST
  addr += qbuffer->size;
  packet2_utils_vu_add_unpack_data(packet, addr, qbuffer->sts,
                                   qbuffer->size, true);

  // Normals
  addr += qbuffer->size;
  packet2_utils_vu_add_unpack_data(packet, addr, qbuffer->normals,
                                   qbuffer->size, true);
}

}  // namespace Tyra
