// Generated by TyraX. Do not edit - regenerated on every build.
#pragma once

namespace Endless_runner {

struct LoadingImageData {
  const char* path;  // relative to the game binary (res/ is copied there)
  float x, y;        // normalized screen position, center anchor
  float w, h;        // size in pixels
};

struct LoadingTextData {
  const char* path;  // baked text sprite, relative to the ELF
  float x, y;        // normalized screen position, center anchor
  int w, h;          // texture size (pow2; content centered)
};

struct LoadingBarData {
  int kind;              // 0 = continuous fill, 1 = quantized segments
  float x, y;            // normalized screen position, center anchor
  float w, h;            // total on-screen size in pixels
  float bg[3], fill[3];  // sprite tints, GS range (128 = 1.0)
  int segments;          // quantized only
  float spacing;         // quantized: gap between segments, px
  const char* segPath;   // segment sprite; "" = colored rects
};

struct LoadingScreenData {
  float bg[3];  // clear color, 0..255
  int imgFirst, imgCount;  // slices into LS_IMAGES/LS_TEXTS/LS_BARS
  int txtFirst, txtCount;
  int barFirst, barCount;
};

constexpr int LS_COUNT = 0;
constexpr int LS_IMAGE_TOTAL = 0;
constexpr int LS_TEXT_TOTAL = 0;
constexpr int LS_BAR_TOTAL = 0;
inline const LoadingScreenData LS_SCREENS[LS_COUNT > 0 ? LS_COUNT : 1] = {
    {{0, 0, 0}, 0, 0, 0, 0, 0, 0},
};

inline const LoadingImageData LS_IMAGES[1] = {
    {"", 0, 0, 0, 0},
};

inline const LoadingTextData LS_TEXTS[1] = {
    {"", 0, 0, 0, 0},
};

inline const LoadingBarData LS_BARS[1] = {
    {0, 0, 0, 0, 0, {0, 0, 0}, {0, 0, 0}, 0, 0, ""},
};

constexpr int LS_DEFAULT = -1;  // -1 = built-in fallback
inline const int SCENE_LOADING_SCREEN[1] = {-1};

struct SplashData {
  const char* path;      // relative to the game binary
  float x, y, w, h;      // normalized center anchor + pixel size
  float bg[3];           // clear color behind the image, 0..255
  float seconds;         // time on screen
};

constexpr int SPLASH_COUNT = 0;
inline const SplashData SPLASHES[SPLASH_COUNT > 0 ? SPLASH_COUNT : 1] = {
    {"", 0, 0, 0, 0, {0, 0, 0}, 0},
};

}  // namespace Endless_runner
