// Generated by TyraX. Delete this line to take ownership of this file.
#pragma once

#include <tyra>
#include <map>
#include <memory>
#include <string>
#include <vector>
#include "save_system.gen.hpp"
#include "scripts/script.hpp"

namespace Endless_runner {

class TerrainGame : public Tyra::Game {
 public:
  explicit TerrainGame(Tyra::Engine* engine);
  ~TerrainGame();

  void init() override;
  void loop() override;

 private:
  void buildScene();
  void resetTerrainChunks();
  void buildTerrainChunk(int slot, int cx, int cz);
  // Streams the chunk ring around one or two view foci (two-player modes:
  // P2's avatar is the second focus) - a chunk near EITHER focus stays
  // resident, so the split halves stop evicting each other's terrain.
  void updateTerrainChunks(float focusX, float focusZ, float focus2X,
                           float focus2Z, bool twoFoci, int budget);
  int countPendingChunks(float focusX, float focusZ);
  void renderTerrain();
  void updatePlayer();

  Tyra::Engine* engine;
  Tyra::StaticPipeline stapip;

  Tyra::Vec4 cameraPosition, cameraLookAt;
  // Camera up vector. World up unless a cutscene rolls the camera
  // (Dutch angle); CameraInfo3D takes it and both the view matrix and
  // the frustum planes honour it.
  Tyra::Vec4 cameraUp = Tyra::Vec4(0.0F, 1.0F, 0.0F);
  float playerX, playerZ, yaw, pitch;
  float playerY, playerVelY;  // feet height + vertical velocity (physics)

  // Terrain chunks: the heightmap grid is cut into TERRAIN_CHUNK_CELLS-sized
  // square tiles, one StaPip bag each (see the chunk functions in the .cpp).
  // Slots live in a pool sized once per scene load (resetTerrainChunks) and
  // never move afterwards - each bag points into its own slot's vectors.
  struct TerrainChunk {
    std::vector<Tyra::Vec4> vertices;
    std::vector<Tyra::Color> colors;
    std::vector<Tyra::Vec4> sts;  // texture coordinates (textured terrain)
    std::unique_ptr<Tyra::StaPipBag> bag;
    std::unique_ptr<Tyra::StaPipColorBag> colorBag;
    Tyra::StaPipTextureBag texBag;
    // Painted terrain layers: one extra alpha-blended pass over the base per
    // layer with any weight in this chunk. Shares the chunk's vertices; own
    // tiled STs + shade colors whose alpha carries the painted weight.
    struct LayerPass {
      std::vector<Tyra::Color> colors;
      std::vector<Tyra::Vec4> sts;
      std::unique_ptr<Tyra::StaPipBag> bag;
      std::unique_ptr<Tyra::StaPipColorBag> colorBag;
      Tyra::StaPipTextureBag texBag;
      int layer = -1;
    };
    std::vector<LayerPass> layerPasses;
    // The terrain lightmap passes, both blended over the base (and the
    // layers) and both sampling ONE map with the chunk's extent-normalized
    // STs - texturing is MODULATE, so the vertex color of each pass picks
    // which channels it sees (docs/emissive-materials.md):
    //   aoCols: BLACK -> only the map's alpha reaches the alpha-over blend,
    //     an exact per-pixel multiply (a white color would drag the light
    //     channel into the darkening);
    //   emisCols: the terrain's own base tint -> the map's RGB, added.
    std::vector<Tyra::Vec4> aoSts;
    std::vector<Tyra::Color> aoCols;
    std::unique_ptr<Tyra::StaPipBag> aoBag;
    std::unique_ptr<Tyra::StaPipColorBag> aoColorBag;
    Tyra::StaPipTextureBag aoTexBag;
    std::vector<Tyra::Color> emisCols;
    std::unique_ptr<Tyra::StaPipBag> emisBag;
    std::unique_ptr<Tyra::StaPipColorBag> emisColorBag;
    Tyra::StaPipTextureBag emisTexBag;
    int cx = -1, cz = -1;  // chunk coords; -1 = free pool slot
    float aabbMin[3] = {0, 0, 0}, aabbMax[3] = {0, 0, 0};  // band culling
    // Height extent of this chunk's cells, filled at build - the portal
    // through-view's exact AABB-vs-exit-plane dead-zone test reads it.
    float minY = 0.0F, maxY = 0.0F;
  };
  std::vector<TerrainChunk> terrainChunks;  // slot pool
  std::vector<short> terrainChunkSlot;      // chunk index -> slot, -1 = unbuilt
  int terrainChunksX = 0, terrainChunksZ = 0;

  Tyra::M4x4 model;
  std::unique_ptr<Tyra::StaPipInfoBag> infoBag;  // shared by all chunk bags
  // Same render settings as infoBag but with GS blending on - shared by every
  // chunk's layer passes (the base pass must stay opaque).
  std::unique_ptr<Tyra::StaPipInfoBag> layerInfoBag;
  // Shared info bag of the additive scene-lightmap pass (identity model -
  // only world-space static primitives ever get atlas regions).
  std::unique_ptr<Tyra::StaPipInfoBag> lightAddInfoBag;
  // The per-scene lightmaps: the terrain map + the primitive atlas (acquired
  // in loadScene when the scene has one; nullptr otherwise). Each carries the
  // occlusion in its alpha (an alpha-over pass = exact per-pixel darkening)
  // and the baked emissive light in its RGB (an additive pass).
  Tyra::Texture* aoMapTexture = nullptr;
  Tyra::Texture* aoAtlasTexture = nullptr;
  std::string aoMapTexPath, aoAtlasTexPath;  // for the release on scene swap
  // ...and which of the terrain map's channels actually have content, latched
  // per scene in loadScene. terrainMapLit ALSO switches buildTerrainChunk's
  // vertex shade off the emissive light, so it never lands twice.
  bool terrainMapOcc = false, terrainMapLit = false;

  // Scene objects at runtime (mutable by scripts/physics); geometry per
  // object, one draw part per model material (primitives use parts[0])
  struct GeoPart {
    std::vector<Tyra::Vec4> vertices;
    std::vector<Tyra::Color> colors;
    std::vector<Tyra::Vec4> sts;  // texture coordinates
    std::unique_ptr<Tyra::StaPipBag> bag;
    std::unique_ptr<Tyra::StaPipInfoBag> infoBag;
    std::unique_ptr<Tyra::StaPipColorBag> colorBag;
    std::unique_ptr<Tyra::StaPipTextureBag> texBag;
    // Reflective material (refl in the .mtl): the additive sphere-map second
    // pass. World-space normals are captured at rebuild and ride in the ST
    // slot; the TCE VU1 programs compute the matcap ST from the per-mesh
    // camera basis (refreshed every frame in renderScene). The env bag shares
    // this part's vertex array and bboxVersion. It does NOT necessarily share
    // the base bag's program class - an UNTEXTURED base is the plain color
    // program, which fits more verts per VU1 package than the textured env
    // one - so the two are pinned to one package size (pinPackageSize) or
    // they would split the array differently and disagree about depth.
    std::vector<Tyra::Vec4> envNormals;
    std::vector<Tyra::Color> envColors;  // all-white 128 = unmodulated texel
    std::unique_ptr<Tyra::StaPipBag> envBag;
    std::unique_ptr<Tyra::StaPipInfoBag> envInfoBag;
    std::unique_ptr<Tyra::StaPipColorBag> envColorBag;
    std::unique_ptr<Tyra::StaPipTextureBag> envTexBag;
    // Experimental textured AO: the scene lightmap atlas multiplied over the
    // base pass (alpha-over blend of a black texture = per-pixel darkening).
    // aoSts map this part's vertices into the object's atlas regions; shares
    // the vertices and bboxVersion like the env pass does.
    // Dynamic lighting (docs/global-illumination.md, opt-in per object): this
    // part renders through the LIT VU1 program instead of baked vertex colors,
    // and its four light colors are re-read from the probe grid every frame.
    // The engine refuses per-vertex colors on a lit bag ("Multicolor is not
    // supported with lighting"), so litBase is the ONE base color and every
    // bit of shading is VU1's N.L - exactly the deal animated models take.
    std::vector<Tyra::Vec4> litNormals;
    Tyra::Color litBase;
    float litAlbedo[3] = {1.0F, 1.0F, 1.0F};
    // The color space the finished light lands in. VU1 clamps its sum to 255
    // and the GS reads it raw, so an UNTEXTURED lit surface has to be built in
    // the same 0..255 the baked vertex path uses (pushVert's `scale`); only a
    // TEXTURED one wants 128 = 1.0 modulation. The animated-model precedent is
    // always textured, which is why 128 looked like the whole answer and made
    // every untextured dyn-lit object exactly half as bright as its bake.
    float litScale = 255.0F;
    Tyra::Vec4 litColors[4];
    // Per-object light DIRECTIONS (the transpose - see litColors' fill). Not
    // the shared animLightDirs: this object's one directional slot points
    // where its own probe says the light comes from, which is not the sun.
    Tyra::Vec4 litDirs[3];
    std::unique_ptr<Tyra::StaPipLightingBag> litBag;
    std::unique_ptr<Tyra::PipelineDirLightsBag> litLights;
    std::unique_ptr<Tyra::StaPipColorBag> litColorBag;
    std::vector<Tyra::Vec4> aoSts;
    std::vector<Tyra::Color> aoCols;  // flat BLACK - the texture's alpha is
                                      // the whole occlusion (see the rebuild)
    std::unique_ptr<Tyra::StaPipBag> aoBag;
    std::unique_ptr<Tyra::StaPipColorBag> aoColorBag;
    std::unique_ptr<Tyra::StaPipTextureBag> aoTexBag;
    // Distance LOD tiers of a static model part (docs/model-pipeline.md).
    // Tier 0 is the full mesh in the arrays above; a deeper tier owns its own
    // baked buffers, filled the first time the object renders that far away
    // and kept afterwards - so a tier flip only re-aims the bag pointers, and
    // each tier keeps its own frustum-bbox cache entry (the cache is keyed by
    // vertex pointer, so distinct buffers never invalidate each other).
    struct Lod {
      std::vector<Tyra::Vec4> vertices;
      std::vector<Tyra::Color> colors;
      std::vector<Tyra::Vec4> sts;
      std::vector<Tyra::Vec4> envNormals;
      std::vector<Tyra::Color> envColors;
      u32 stamp = 0;  // bboxVersion of these buffers
    };
    std::vector<Lod> lods;
    int shownLod = 0;  // tier the bags currently point at
    u32 baseStamp = 0;  // tier 0's bboxVersion, to restore on the way back
    // The additive twin of the pass above: same atlas, same STs, WHITE vertex
    // colors, so it sees the baked emissive light in the texture's RGB.
    std::vector<Tyra::Color> emisCols;
    std::unique_ptr<Tyra::StaPipBag> emisBag;
    std::unique_ptr<Tyra::StaPipColorBag> emisColorBag;
    std::unique_ptr<Tyra::StaPipTextureBag> emisTexBag;
  };
  struct ObjectGeometry {
    std::vector<GeoPart> parts;
    // Physics fast path (awake bodies): parts hold LOCAL-space vertices
    // (scale baked in, shading frozen at the wake pose) and every
    // part.infoBag->model points at objMat, rebuilt from position/rotation
    // each frame - VU1 applies the motion, the EE stops re-tessellating and
    // re-shading mid-flight. Any full rebuild (rebuildObjectGeometry default
    // = world-space bake) turns it off; going to sleep forces one, so a
    // settled body gets correct rest-pose shading back.
    Tyra::M4x4 objMat;
    bool matrixMode = false;
    // Reflected-probe mode: the matcap ST basis must be the PROBE camera's
    // right/up, not the main camera's - a probe looking back at the player
    // has its left on the player's right, and sampling its map with the
    // main basis mirrors every reflection horizontally (owner report).
    // Written by renderObjectProbe, consumed by the env pass.
    Tyra::Vec4 probeRight;
    Tyra::Vec4 probeUp;
    bool probeBasis = false;
    // Animated models (.glb): this object's skeletal instance (own
    // playback state + skinned output mesh, samples the shared SkelModel).
    std::unique_ptr<Tyra::SkelInstance> animInst;
    // StaPip bags pointing straight into animInst's skinned arrays; the
    // skinned vertices stay in model space, so the object transform rides
    // in animMat (info bag + light matrix), not in the vertex data.
    struct AnimPart {
      std::unique_ptr<Tyra::StaPipBag> bag;
      std::unique_ptr<Tyra::StaPipColorBag> colorBag;
      std::unique_ptr<Tyra::StaPipTextureBag> texBag;
      std::unique_ptr<Tyra::StaPipLightingBag> lightBag;
      // The lit StaPip VU1 programs (_d/_td) derive the vertex color purely
      // from the directional lights - they never read a base/vertex color -
      // so an untextured mesh would render in the plain scene light color
      // (i.e. gray). This part's material albedo is folded into its own light
      // and ambient colors instead (outputColor = albedo * sceneLighting),
      // matching how the editor viewport tints the .glb. Directions stay
      // shared (animLightDirs); only the colors carry the per-part tint.
      std::unique_ptr<Tyra::PipelineDirLightsBag> animLights;
      Tyra::Vec4 litColors[4];
    };
    std::vector<AnimPart> animParts;
    std::unique_ptr<Tyra::StaPipInfoBag> animInfoBag;
    Tyra::M4x4 animMat;
    u32 animLastTick = 0;  // animLodTick of the last in-view frame; 0 = never
    // Usable-object highlight: terrain-hugging glow ring around the base,
    // built when first highlighted, cleared whenever the object rebuilds
    // (see buildHighlightApron)
    std::vector<Tyra::Vec4> apronVerts;
    std::vector<Tyra::Color> apronCols;
    u32 apronStamp = 0;
    // Low-detail stand-in the highlight shells are drawn from (positions
    // only - shells are single-color flat). Subdividing a primitive never
    // changes its silhouette, so a detail-1 box / low-segment curve gives a
    // pixel-near-identical rim for a fraction of the clip/transform cost
    // (see buildHighlightProxy). Built when first highlighted, cleared
    // whenever the object rebuilds.
    std::vector<Tyra::Vec4> hullProxyVerts;
    u32 hullProxyStamp = 0;
  };
  // Custom .obj models (paths in model_data.gen.hpp): geometry split per MTL
  // material with optional per-material textures, the real mesh AABB for box
  // collision, a CollisionMesh for mesh collision. Loaded on demand by the
  // layer streaming - only models some resident layer uses stay in memory.
  struct GameModelPart {
    std::vector<float> verts;  // 8 floats per vertex: x,y,z,nx,ny,nz,u,v
    // Decimated variants baked into the .tmdl (same layout, coarsest last);
    // empty unless the project's mesh LOD distance is on. Shared by every
    // instance - each object bakes its own shaded copy on demand.
    std::vector<std::vector<float>> lodVerts;
    // baked ambient-occlusion visibility per vertex (255 = open sky), from
    // the model's .aov sidecar; empty when the project bakes no AO
    std::vector<unsigned char> vertexAo;
    Tyra::Texture* texture = nullptr;
    float kd[3] = {1.0F, 1.0F, 1.0F};
    // Ke: emission - the brightness floor pushVert never shades below, so the
    // part keeps its color in a pitch-black scene. {0,0,0} = matte.
    float ke[3] = {0.0F, 0.0F, 0.0F};
    // refl: spherical environment map (nullptr = not reflective).
    // reflDynamic = the "@sky" dynamic env map (engine-owned VRAM texture);
    // reflRounded = "-rounded": env normals radiate from the part centroid.
    Tyra::Texture* reflTexture = nullptr;
    float reflStrength = 0.0F;
    bool reflDynamic = false;
    bool reflRounded = false;
  };
  struct GameModel {
    std::vector<GameModelPart> parts;  // empty = missing/unparseable model
    float mn[3] = {-0.5F, -0.5F, -0.5F};
    float mx[3] = {0.5F, 0.5F, 0.5F};
    Tyra::CollisionMesh collider;  // built only when a scene needs mesh mode
    std::vector<std::string> texPaths;  // texture-cache refs this model holds
  };
  std::vector<GameModel> gameModels;
  void loadModelAsset(int index);
  void freeModelAsset(int index);
  // Animated .glb models: serialized by the editor to .tskl skeletal files
  // (paths in model_data.gen.hpp) - bone keyframe tracks + bind-pose mesh.
  // Poses are evaluated and skinned on the EE/VU0 (SkelInstance) for the
  // in-view instances only; the skinned arrays render through the SAME
  // static pipeline as the rest of the scene (single vertex upload, no VU1
  // program swap, EE clipping). See updateAndRenderAnimObjects for the
  // real-hardware numbers behind this design - PCSX2's fast EE hides them.
  struct GameAnimModel {
    std::unique_ptr<Tyra::SkelModel> src;   // skeleton + mesh + clip tracks
    std::vector<Tyra::Texture*> textures;   // per part, nullptr = untextured
    std::vector<std::string> texPaths;      // texture-cache refs held
    Tyra::CoreBBox cullBox;  // local AABB over all clips + margin (see load)
  };
  std::vector<GameAnimModel> gameAnimModels;
  void loadAnimModelAsset(int index);
  void freeAnimModelAsset(int index);
  void setupAnimObject(int index);  // per-object instance + playback state
  void updateAndRenderAnimObjects();
  // Dynamic lighting (docs/global-illumination.md): refills the light bag
  // of every opt-in object from the probe grid, once per frame.
  void updateDynLitObjects();
  void fillDynLitColors(int index);
  // Directional light for the animated pass, mirroring the baked static
  // look. The manual dir-lights layout: colors[0..2] + ambient in [3].
  Tyra::Vec4 animLightColors[4];
  Tyra::Vec4 animLightDirs[3];
  Tyra::PipelineDirLightsBag animDirLights{true};
  u32 animLodTick = 0;  // frame counter for the ANIM_LOD_DISTANCE stagger

 public:
  // Clip-name lookup for scripts/flow graph (ScriptContext::resolveClip).
  int resolveClipIndex(int objectIndex, const char* clipName) const;
  // Dynamic spawning for scripts/flow graph (ScriptContext::spawnObject /
  // despawnObject): clone an authored object into the spawn pool / free it.
  int spawnObjectAt(int templateIndex, float x, float y, float z, float yaw);
  // Prefabs and runtime procedural volumes reach the graphs the same way, so
  // their verbs live next to the spawn pool's: public because ScriptContext's
  // thunks call them from outside the class.
  // mergeOwner >= 0 folds the instance's static members into THAT procedural
  // volume's chunk grid instead of giving the instance its own bags. That is
  // the difference between 27 scattered rooms costing 27 draw calls and
  // costing four: a volume owns a region, so its prefabs can share the
  // region's chunks. A flow-node spawn passes -1, because Despawn Prefab has
  // to be able to take that one instance's geometry away again.
  int spawnPrefabAt(int prefabIndex, float x, float y, float z, float yaw,
                    float scale, int mergeOwner = -1);
  void despawnPrefabsNamed(int prefabIndex);  // -1 = every instance
  // Generates one runtime volume and builds its geometry. seed: 0 = the
  // authored one, -1 = a fresh one, anything else = use it.
  void procGenerateVolume(int volume, int seed);
  void procClearVolume(int volume);
  void despawnObjectAt(int index);

 private:
  // Primitive materials: .mtl assigned to a box/sphere/... - the file's
  // first material supplies the color (kd) and optional texture.
  struct GameMaterial {
    Tyra::Texture* texture = nullptr;
    float kd[3] = {1.0F, 1.0F, 1.0F};
    // Ke: emission floor (see GameModelPart). {0,0,0} = matte.
    float ke[3] = {0.0F, 0.0F, 0.0F};
    std::string texPath;  // texture-cache ref held ("" = untextured)
    // refl: spherical environment map (nullptr = not reflective).
    // reflDynamic = the "@sky" dynamic env map (engine-owned VRAM texture);
    // reflRounded = "-rounded": env normals radiate from the part centroid.
    Tyra::Texture* reflTexture = nullptr;
    float reflStrength = 0.0F;
    bool reflDynamic = false;
    bool reflRounded = false;
    std::string reflTexPath;  // texture-cache ref held ("" = none)
    // texture atlasing ("# tyra-uvrect" in the baked .mtl): primitive
    // builders map their generated 0..1 UVs onto this sub-rectangle of the
    // (shared page) texture. {0,0,1,1} = no atlas.
    float uvRect[4] = {0.0F, 0.0F, 1.0F, 1.0F};
  };
  std::vector<GameMaterial> gameMaterials;
  void loadMaterialAsset(int index);
  void freeMaterialAsset(int index);
  std::vector<Tyra::Texture*> loadedTextures;

  // Streaming layers (SCENE_LAYER_* tables): an asset is resident only while
  // some active-scene object in a resident layer (or with no layer) uses it.
  // Load Layer queues the layer's missing assets and the queue drains one
  // asset per frame (loads spread out - no long stall); Unload Layer drops
  // the layer's objects immediately and frees whatever nothing else needs.
  // Textures shared between layers/models are reference-counted by path.
  struct TexEntry {
    Tyra::Texture* tex = nullptr;
    int refs = 0;
  };
  std::map<std::string, TexEntry> texCache;
  Tyra::Texture* acquireTexture(const std::string& path);
  void releaseTexture(const std::string& path);
  void loadSceneTexture(int index);
  void freeSceneTexture(int index);
  std::vector<unsigned char> modelLoaded, materialLoaded, animModelLoaded,
      sceneTexLoaded;
  bool layerOn(int layer) const;  // desired residency of an object's layer
  void applyLayerResidency();     // free unneeded assets, queue missing ones
  void processOneStreamJob();
  void activateObject(int index);
  void deactivateObject(int index);
  void updateLayerStreaming();
  std::vector<unsigned char> layerState;   // 0 unloaded, 1 loading, 2 loaded
  std::vector<unsigned char> layerTarget;  // desired residency per layer
  std::vector<signed char> layerRequest;   // script requests (-1 = none)
  std::vector<unsigned char> layerAutoInside;  // auto zones: focus inside?
  std::vector<int> streamQueue;            // (kind << 16) | asset index
  std::vector<RuntimeObject> runtimeObjects;
  std::vector<ObjectGeometry> objectGeometry;
  // Static batching (STATIC_BATCHING, Preferences > Rendering): authored
  // objects flagged batchStatic at build time merge into combined
  // world-space bags at scene load, grouped by material + a coarse world
  // cell - one StaPip submit per batch instead of per object (the fixed
  // ~1 ms per-bag EE cost on real hardware dominates scenes made of many
  // small primitives). Members keep their runtimeObjects entry (collision,
  // raycasts and scripts read data as always) but skip the per-object draw
  // path. Runtime mutation of a member (Live Link edits, Raycast-driven
  // actions, global scripts - all set dirty) DEMOTES it to the solo path
  // and rebuilds the batch once without it; a visibility/residency flip
  // (caught by the shown snapshot - hide/show can skip the dirty flag)
  // only rebuilds the batch in place.
  struct StaticBatch {
    int material = -1;                 // group key (-1 = plain color)
    std::vector<int> members;          // authored object indices
    std::vector<unsigned char> shown;  // per member: baked as visible?
    std::vector<Tyra::Vec4> vertices;  // world-space baked, like terrain
    std::vector<Tyra::Color> colors;
    std::vector<Tyra::Vec4> sts;
    std::unique_ptr<Tyra::StaPipBag> bag;
    std::unique_ptr<Tyra::StaPipColorBag> colorBag;
    std::unique_ptr<Tyra::StaPipTextureBag> texBag;
    float aabbMin[3] = {0, 0, 0}, aabbMax[3] = {0, 0, 0};  // band culling
    bool dirty = true;
  };
  std::vector<StaticBatch> staticBatches;
  std::vector<short> objectBatchOf;  // authored index -> batch, -1 = solo
  std::unique_ptr<Tyra::StaPipInfoBag> batchInfoBag;  // shared by all batches
  void buildStaticBatchList();
  void rebuildStaticBatch(StaticBatch& b);
  void renderStaticBatches();

  // --- Runtime procedural + prefab geometry (docs/procedural-runtime.md,
  // docs/prefabs.md) --------------------------------------------------------
  // Both features end in the same place: a set of world-space vertex bags the
  // game built ITSELF, drawn like a static batch. That is the only shape a
  // PS2 can afford for "many instances" - a submit costs ~1 ms of fixed EE
  // time whatever it contains, so instances are merged per (source mesh,
  // world chunk) and the frame draws a handful of bags instead of hundreds of
  // objects. Nothing here exists unless the project uses it: procrt::ENABLED
  // and PREFAB_COUNT are compile-time constants, so the whole block folds away.
  struct ProcChunk {
    int owner = -1;    // procrt VOLUMES index, or -1 for a prefab instance
    int instance = -1; // prefab instance handle (owner < 0)
    int model = -1;    // gameModels index the vertices came from
    int part = 0;      // that model's material part = this bag's texture
    int material = -1; // primitives: gameMaterials index
    std::vector<Tyra::Vec4> vertices;
    std::vector<Tyra::Color> colors;
    std::vector<Tyra::Vec4> sts;
    std::unique_ptr<Tyra::StaPipBag> bag;
    std::unique_ptr<Tyra::StaPipColorBag> colorBag;
    std::unique_ptr<Tyra::StaPipTextureBag> texBag;
    int cx = 0, cz = 0;  // world chunk cell (cull granularity)
    float aabbMin[3] = {0, 0, 0}, aabbMax[3] = {0, 0, 0};
    float centre[3] = {0, 0, 0};
    float drawDist = 0.0F;  // 0 = always drawn
  };
  std::vector<ProcChunk> procChunks;
  // Collision for generated geometry. Merged geometry has no objects, so a
  // prefab's walls would be scenery you walk through - which is exactly the
  // trade the procedural BAKE makes for vegetation and exactly the wrong one
  // for architecture. Every merged member whose collision is not "none"
  // contributes one world AABB here, and the walker tests them the way it
  // tests an object's box. Axis-aligned on purpose: rooms and blocks are, and
  // an oriented test over hundreds of boxes is not something the EE should be
  // doing every frame.
  struct StaticBox {
    float mn[3];
    float mx[3];
    short owner;     // procedural volume, -1 = a script-spawned prefab
    short instance;  // prefab instance handle, -1 = a volume's own geometry
  };
  std::vector<StaticBox> procColliders;
  // Live prefab instances, so Despawn Prefab can find what it made.
  struct PrefabInstance {
    int prefab = -1;              // PREFAB_NAMES index, -1 = free slot
    int owner = -1;               // procedural volume that spawned it, -1 = a script did
    int spawned[8];               // runtimeObjects slots this instance owns
    int spawnCount = 0;
  };
  std::vector<PrefabInstance> prefabInstances;
  // Block collision field published by a runtime volume's Blocks Fill node.
  // One 32-bit word per column, bit i = level i solid - which is why a block
  // world is capped at 32 levels and why the walker's test is three shifts.
  struct BlockField {
    bool active = false;
    int nx = 0, nz = 0, levels = 0;
    float ox = 0, oz = 0, cell = 1.0F, baseY = 0;
    std::vector<unsigned int> col;
  };
  BlockField procBlocks;
  bool procBlockSolid(float x, float y, float z) const;
  // Highest solid block top at or below `maxY` (-1e30 = nothing under there).
  float procBlockTopAt(float x, float z, float maxY) const;
  // Lowest solid block bottom strictly above `minY` (+1e30 = open sky).
  float procBlockCeilAt(float x, float z, float minY) const;
  // Any solid block inside the vertical band [y0, y1] within `r` of (x, z)?
  bool procBlockBlocks(float x, float z, float y0, float y1, float r) const;
  void despawnPrefabInstance(int handle);
  // Merges a run of instances into procChunks. The two callers (a runtime
  // volume, a prefab instance) differ only in where the transforms come from.
  void procAddMergedObject(int owner, int instance, const SceneObjectData& d,
                           unsigned char faces);
  void procFinishChunks();
  void renderProcChunks();
  GeoPart skyDome;
  // Re-centered on the camera every frame (renderScene) so a large map can
  // never let the player walk (or climb) out from under the sky. The dome
  // geometry stays static; only this translation matrix moves - one matrix
  // set per frame, so following the camera costs nothing measurable.
  Tyra::M4x4 skyMat = Tyra::M4x4::Identity;
  float skyHorizonR = 0, skyHorizonG = 0, skyHorizonB = 0;
  // The zenith the dome was last built with. Without this the runtime cycle
  // could only move the horizon and a midnight sky kept a daylight zenith -
  // the gradient is the half of a sky people actually read.
  float skyTopR = -1, skyTopG = -1, skyTopB = -1;
  std::vector<Tyra::Sprite> hudSprites;

  // Day/night cycle sky bodies (docs/day-night-cycle.md). Two textured quads on
  // the dome radius in the baked SCENE_SUN_* / SCENE_MOON_* directions. Six
  // vertices each, rebuilt per frame from the camera basis so they keep facing
  // the viewer - the same shape the beam coronas use, and the same cost.
  // DAYCYCLE_USED gates the textures; without a cycle nothing here is touched.
  Tyra::Texture* sunDiscTex = nullptr;
  Tyra::Texture* moonDiscTex = nullptr;
  struct SkyBody {
    std::vector<Tyra::Vec4> verts;  // 6
    std::vector<Tyra::Vec4> sts;    // 6
    Tyra::Color color{128.0F, 128.0F, 128.0F, 128.0F};
    Tyra::M4x4 mat = Tyra::M4x4::Identity;
    std::unique_ptr<Tyra::StaPipInfoBag> info;
    std::unique_ptr<Tyra::StaPipColorBag> colorBag;
    std::unique_ptr<Tyra::StaPipTextureBag> texBag;
    std::unique_ptr<Tyra::StaPipBag> bag;
  };
  SkyBody sunBody, moonBody;
  // The night sky: one bag per magnitude tier (STAR_TIERS). Three submits for
  // the whole field, and the brightness/twinkle ride the bags' additive FIX -
  // so fading the stars in at dusk costs three bytes a frame, not a rebuild.
  struct StarBag {
    std::vector<Tyra::Vec4> verts;
    std::vector<Tyra::Vec4> sts;
    std::vector<Tyra::Color> colors;
    std::unique_ptr<Tyra::StaPipInfoBag> info;
    std::unique_ptr<Tyra::StaPipColorBag> colorBag;
    std::unique_ptr<Tyra::StaPipTextureBag> texBag;
    std::unique_ptr<Tyra::StaPipBag> bag;
  };
  StarBag starBags[STAR_TIERS];
  Tyra::M4x4 starMat = Tyra::M4x4::Identity;
  void buildStarField();
  void renderStarField();

  void setupSkyBodies();
  // The runtime day/night cycle (docs/day-night-cycle.md). dayNightTick
  // advances the clock and stages everything the frame needs; the zenith is
  // staged rather than written straight into skyTop* so the dome rebuild stays
  // in one place (the retint check in renderScene).
  float dayNightTopR = -1, dayNightTopG = -1, dayNightTopB = -1;
  void dayNightTick();
  // Placed per VIEW: the discs are billboards on the dome, so a mirror, a
  // portal or a camera feed needs them oriented for ITS eye, not the player's.
  void renderSkyBodies(const Tyra::Vec4& eye, const Tyra::Vec4& look);

  void buildSkyDome();
  // Pins every pass that draws one vertex array to a single VU1 package size -
  // see the implementation for why coplanar passes must classify identically.
  void pinPackageSize(const std::vector<Tyra::StaPipBag*>& bags);
  // localSpace = bake for the physics fast path (ObjectGeometry::objMat).
  void rebuildObjectGeometry(int index, bool localSpace = false);
  // Static mesh LOD: points one model part's bags at distance tier `lod`
  // (0 = the full mesh), baking that tier's shaded buffers on first use.
  void applyGeoLod(int index, int partIndex, int lod);
  // True when this object may swap tiers at all - see the implementation.
  bool modelLodEligible(int index) const;
  // A moving body takes the matrix fast path unless another consumer assumes
  // world-space vertex arrays (usable highlight hull, reflective matcap
  // normals) or it is an animated model (animMat already drives those).
  bool physFastPathEligible(int index) const;
  void updateObjMat(int index);
  // Player-vs-objects collision shared by both walkers: box (scale box or
  // model AABB), mesh (CollisionMesh) or none, per SceneObjectData.collision.
  // ceiling receives the lowest overhead surface so the walkers can keep the
  // camera from poking into geometry from below (jump clamp).
  void collidePlayer(float prevX, float prevZ, float* nextX, float* nextZ,
                     float feetY, float eyeHeight, float* ground,
                     float* ceiling);
  void updateObjectPhysics();
  // Scripted continuous rotation (Spin Object flow node): integrates
  // RuntimeObject::spinRate and promotes spinners onto the per-object
  // matrix path so they cost no per-frame vertex re-bake.
  void updateSpinners();
  // Physics bodies in a walking player's path get shoved along the attempted
  // move (impulse scaled by 1/mass) and woken; called before collidePlayer so
  // a blocked step still transfers its push into the crate.
  void pushPhysicsBodies(float prevX, float prevZ, float nextX, float nextZ,
                         float feetY, float eyeHeight);
  // Physics helpers: world-space AABB half-extents + center offset (models
  // use their mesh AABB, like collidePlayer) and the "solid enough to
  // block/bump a body" filter.
  static void physExtents(const SceneObjectData& d, const GameModel* gm,
                          const Tyra::SkelModel* anim, float* cOff, float* ext);
  static bool physObstacle(const SceneObjectData& d);
  void renderScene();
  // Mirror objects (type 15): re-submit each listed target's live bags
  // under a reflection matrix about the glass plane, then blend the quad
  // over the copies. mirrorMat holds the reflection for the mirror being
  // drawn; mirrorAnimMat composes it with an animated target's animMat.
  void renderMirrors();
  void renderMirroredObject(int index);
  // Live catch areas (docs/areas.md): refill liveCaught with the objects the
  // area at scene index areaIndex holds right now, walking the owner slice of
  // CATCH_CANDIDATES (everything in the scene that can move) plus the runtime
  // spawn pool. The buffer is a member so the per-frame pass never allocates;
  // the caller consumes it before the next call.
  void collectLiveCaught(int areaIndex, int firstCand, int candCount);
  std::vector<int> liveCaught;
  Tyra::M4x4 mirrorMat;
  Tyra::M4x4 mirrorObjMat;  // reflection * objMat for fast-path bodies
  Tyra::M4x4 mirrorAnimMat;
  // Raytraced mirrors (MirrorData::raytraced, experimental VU0 PoC): the
  // reflection is ray-traced on a VU0 MICROPROGRAM into a small texture
  // re-uploaded every frame - sphere proxies of the target list against
  // the sky gradient - instead of re-submitted geometry. See
  // docs/raytraced-reflections.md.
  struct RtMirror {
    int object = -1;                   // the mirror's scene-table index
    int size = 64;                     // traced image edge (MirrorData::rtSize)
    Tyra::Texture* texture = nullptr;  // owns its RGBA32 pixel buffer
  };
  std::vector<RtMirror> rtMirrors;
  Tyra::Vu0Raytracer vu0Rt;
  void buildRtMirrors();
  void freeRtMirrors();
  void renderRtMirror(const MirrorData& mir);
  // Camera texture feed (CCTV, docs/texture-feeds.md): renders the scene's
  // feed camera view into the engine's camFeed VRAM target each frame;
  // objects with an OBJECT_FEEDS row sample it (or a raytraced mirror's
  // traced image) as a live emissive texture.
  void renderCameraFeed();
  void renderFeedObject(int index);
  // Reflected-probe mode (ENV_PROBE_REFLECTED): re-render the shared env
  // map for ONE reflective object - aimed by the eye->center reflection -
  // right before that object draws. Interleaving works on a single VRAM
  // target because the bracket's begin() drains PATH1: the previous
  // object's draws sample THEIR map before it is overwritten.
  void renderObjectProbe(int index);
  // Portal objects (type 16): a linked pair of surfaces. renderPortalView
  // renders the through-view of the best on-screen portal into the engine's
  // portal render target (the player camera mapped through the pair, so the
  // second camera stays in lockstep with the player's); renderPortals blends
  // every portal's tinted quad after the scene and projects the live view
  // onto the winner's surface; updatePortals teleports the player / physics
  // objects that cross a linked surface, carrying position, view angle and
  // vertical velocity through the same mapping - the view and the arrival
  // line up exactly, so stepping through is seamless. Up to four portal
  // views render per frame (nearest qualify, carved farthest-first);
  // portalLiveFlags marks the PORTALS entries whose opening is live.
  void renderPortalView();
  bool renderOnePortalView(int pi);
  void renderPortals();
  bool portalCamera(int pi, Tyra::Vec4* outEye, Tyra::Vec4* outAt);
  bool updatePortals(float prevX, float prevY, float prevZ, float* px,
                     float* py, float* pz, float* pyaw, float* ppitch,
                     float* pvelY, float eyeH);
  // True when the walker's body column at (x, z) sits inside a linked
  // FLOOR portal's rectangle near its plane - the walkers suppress the
  // terrain ground clamp there, so a portal lying on the ground swallows
  // them (the clamp would otherwise rest the feet on the terrain before
  // the crossing plane is ever reached).
  bool portalSwallowsPlayer(float x, float feetY, float z);
  bool portalSwallowZone(const RuntimeObject& m, float hx, float hy, float x,
                         float y, float z);
  // Swept variant for physics bodies: a faller at PHYS_MAX_SPEED (3 u/frame)
  // can step clean over the 2-unit approach zone in one frame - the endpoint
  // test misses, the terrain clamp kills the fall and the infinite-fall loop
  // visibly hangs on the ground before it re-swallows. Tests both frame
  // endpoints plus the segment's plane-crossing point.
  bool portalSwallowSwept(const RuntimeObject& m, float hx, float hy,
                          const Tyra::Vec4& a, const Tyra::Vec4& b);
  // Portal pass-through for the walkers: when the body column sits inside
  // a linked portal's opening near its plane, updatePortalPass publishes
  // that portal's plane and collidePlayer stops colliding with objects
  // fully BEHIND it (exact OBB extent) - the wall a portal is mounted on
  // opens up like a doorway while everything else keeps blocking.
  void updatePortalPass(float x, float feetY, float z);
  float portalPassPlane[4] = {0, 0, 0, 0};
  bool portalPassOn = false;
  // Thrown objects fly through portals too. portalCarryAim finds the
  // linked portal whose opening the motion segment a->b pierces (front
  // face, authored rectangle + slack); -1 = none. forObj gates it through
  // portalCanCross for that object; forObj == -1 is unconditional (the
  // player-released flight). portalCanCross is the owner's rule: whatever
  // a portal SHOWS can also go through it - teleportObjects, viewAll, a
  // view-list member, or the player-released body all qualify.
  // portalCarryCrossing maps position + full velocity through that pair
  // (the same isometry updatePortals applies). While a flight segment
  // aims into an opening, sweepPass* excludes obstacles fully behind that
  // portal's plane from sweepSphere, and the physics pass applies the
  // same exclusion to its static-solid resolution - the mounting wall
  // must not stop a body's center r short of the crossing plane (callers
  // pad the segment end by the body's extent for exactly that reason).
  bool portalCanCross(const PortalData& p, int oi);
  // True when portal pi's through-view actually DRAWS object oi (viewAll, or
  // oi is on its explicit view list) - a carried object may only be mapped
  // through a portal that will render it on the far side.
  bool portalShowsObject(int pi, int oi);
  bool portalLiveHolds(const PortalData& p, int oi);
  // Map a world point through portal pi's pair (source local -> flip about
  // local Y -> target world), the same isometry as the teleport/camera.
  void portalMapPoint(int pi, float& x, float& y, float& z);
  int portalCarryAim(const float* a, const float* b, int forObj);
  bool portalCarryCrossing(const float* a, float* pos, float* vel);
  // Arms sweepPass* when segment a->b pierces a linked opening (pad the
  // end by the swept body's extent). Pair with sweepPassOn = false after
  // the sweep.
  bool armSweepPass(const float* a, const float* b);
  float sweepPassPlane[4] = {0, 0, 0, 0};
  bool sweepPassOn = false;
  // The last player-released rigid body (throw OR drop): portal-free -
  // crosses any linked portal, flag or not - until it settles to sleep.
  // -1 = none. The non-physics thrown arc (thrownIndex) is always free.
  int thrownFreeIndex = -1;
  std::vector<unsigned char> portalLiveFlags;  // per PORTALS entry: view drawn
  std::vector<float> portalPrevPos;  // 3 floats per runtime object (crossings)
  // Per object: frames until it may hop again (set on every hop). Damps
  // frame-scale re-hop jitter (rect-edge bounces, resolution kicks) without
  // touching legit loops - the example's fall re-crosses every ~13 frames.
  std::vector<unsigned char> portalHopCool;
  // Exit-plane of the through-view being rendered (nx, ny, nz, d) - set
  // around the destination render so renderTerrain can drop chunks in the
  // dead zone between the virtual camera and the target portal's plane.
  float portalExitPlane[4] = {0, 0, 0, 0};
  bool portalExitPlaneOn = false;
  void renderHighlightHull(int index);
  void buildHighlightApron(int index, float half);
  void buildHighlightProxy(int index);
  bool highlightInReach(int index) const;
  // Usable-object highlight: one shared bag re-submitted for every part of
  // every shell. The grow about the object center and the pushback about
  // the eye compose into a single scale+translation model matrix (hullMat),
  // so VU1 does all per-vertex work on the object's own vertex arrays.
  // Shell colors need persistent storage - the single-color pointer is
  // DMA-referenced at submit time, not copied.
  Tyra::M4x4 hullMat;
  std::vector<Tyra::Color> hullShellCols;
  std::unique_ptr<Tyra::StaPipBag> hullBag;
  std::unique_ptr<Tyra::StaPipInfoBag> hullInfoBag;
  std::unique_ptr<Tyra::StaPipColorBag> hullColorBag;
  std::unique_ptr<Tyra::StaPipBag> apronBag;
  std::unique_ptr<Tyra::StaPipInfoBag> apronInfoBag;
  std::unique_ptr<Tyra::StaPipColorBag> apronColorBag;

  // Player entities (PLAYER_INDEXES / PLAYER2_INDEXES in scene_data.hpp);
  // override the template camera when present. players[0] is the scene's
  // first Player object (P1), players[1] the second (P2 - only meaningful
  // with MULTIPLAYER_MODE != 0, see docs/multiplayer.md).
  struct PlayerCtl {
    int objIndex = -1;  // scene object index, -1 = this player doesn't exist
    float x = 0, y = 0, z = 0, velY = 0, yaw = 0, pitch = 0;
    // Third-person only: yaw/pitch orbit the camera, faceYaw is the avatar's
    // own facing (turns toward the walk direction). Clip indices are resolved
    // from the model's clip table at scene load; -1 = unmapped.
    float faceYaw = 0;
    int idleClip = -1, walkClip = -1, runClip = -1, jumpClip = -1;
    // Directional locomotion (face-camera / strafe mode only); -1 = unmapped,
    // the walk clip covers that direction.
    int backClip = -1, strafeLClip = -1, strafeRClip = -1;
    // Smoothed spring-arm boom length - snaps in on a hit, eases back out.
    float boom = 0;
    // This player's own view; the dispatcher (or the split-screen render
    // pass) picks which of these drives the frame camera.
    Tyra::Vec4 camPos, camLook;
  };
  PlayerCtl players[2];
  // Dispatcher: walks P1 (and P2 while active), then composes the frame
  // camera. Returns false when the scene has no player.
  bool updatePlayerEntity();
  // Walks one player from its pad and writes its camera into camPos/camLook.
  void updatePlayerWalker(PlayerCtl& P, int pi, Tyra::Pad& pad);
  // Shared-screen camera: orbits (P1's right stick) around the midpoint of
  // both players, boom stretched by their separation. Writes cameraPosition.
  void updateSharedCamera();
  float sharedBoom = 0;
  // Player 2 join/leave, both mid-game: Start on pad 2 (P2_JOIN_ON_START) or
  // a menu Toggle bound to "Player count". Shows/hides the P2 avatar.
  void setPlayerTwoActive(bool active);
  void syncPlayerCountMenuValue();
  bool playerTwoActive = false;
  Tyra::Pad pad2;              // connector 2; optional, hot-join friendly
  int menuPlayerCountPrev = -2;  // edge detect for the menu bind
  // True while renderScene runs inside a split-screen half: the dynamic
  // env-map bracket restores a FULL-screen raster on end(), which would
  // break the active half, so the env pass pauses during split rendering
  // (the VRAM target keeps its last content).
  bool splitPassActive = false;
  // True during the SECOND split half's renderScene: animation playback and
  // skinning already ran this frame (first half), so the animated pass
  // must not advance time again (2x playback speed) nor re-skin the same
  // pose (PC-grade avatars cost real EE ms) - it re-submits the
  // frame's skinned buffers under the second camera instead.
  bool splitSecondPass = false;
  // Split-band culling: the split raster shows only the CENTRAL half of the
  // full-height projection, but the frustum planes the engine classifies
  // against stay full-height - so each half would transform ~2x the geometry
  // it can show. Two extra planes bound the visible vertical band; chunks and
  // static objects entirely outside skip submission before the engine ever
  // sees them. Recomputed per half from the live camera + projection FOV.
  void computeSplitBand();
  bool outsideSplitBand(const float mn[3], const float mx[3]) const;
  bool objectOutsideSplitBand(int i) const;
  bool splitBandActive = false;
  float splitBandN[2][3];  // inward top/bottom plane normals (apex = camera)
  float splitBandP[3];     // the apex
  // Picks the third-person avatar's locomotion clip from its planar speed
  // (fraction of full walk speed), grounded state and - with face-camera
  // (strafe) locomotion - the movement direction relative to the avatar's
  // facing (moveLocal, radians, 0 = straight ahead), cross-fading on change.
  void drivePlayerAnim(PlayerCtl& P, RuntimeObject& body, float speedFrac,
                       bool grounded, float moveLocal);
  // Spring arm: the distance down the boom (from the head, along d) at which
  // the camera would enter geometry or the terrain. camBoom is the smoothed
  // boom length actually used - whisker casts ease it in ahead of a hit, a
  // hard clamp keeps it out of geometry, and it eases back out.
  float springArm(float px, float py, float pz, float dx, float dy, float dz,
                  float maxDist) const;
  // The general sweep behind springArm: first blocked distance along d for a
  // sphere of `radius`, vs object AABBs + the terrain; skipIndex is excluded
  // (the swept object itself). Also carries/throws pickable objects.
  float sweepSphere(float px, float py, float pz, float dx, float dy, float dz,
                    float maxDist, float radius, int skipIndex) const;

  // Multiple scenes: the game starts in scene 0; the flow graph Switch
  // Scene node requests a change applied between frames.
  void loadScene(int sceneIndex);
  // Loads scene 0 + runs scripts' init(); called once from the loop's boot
  // sequence (see bootPhase) so the initial load is vsync-paced.
  void bootFirstScene();
  // Boot state: 0 = boot splash images, 1 = loading-screen hold for the first
  // scene, 2 = gameplay running (the Tyra logo hold lives in the engine's
  // banner). splashIndex/splashFrames step through the splash sequence.
  int bootPhase = 0;
  int splashIndex = 0;
  int splashFrames = 0;
  int currentScene = 0;
  unsigned int sceneGeneration = 0;

  // Particle emitters (type 7): fixed pools sized at scene load, zero
  // per-frame allocations. The EE only SIMULATES; each particle is
  // submitted as a single center vertex plus one qword of 2x2 basis
  // weights and one color, and the VU1 billboard program expands it into
  // a camera-facing quad (textured when the emitter has a material with a
  // map_Kd). One bag per emitter; the camera basis rides on the billboard
  // bag, so another view (a portal pass) can re-render the same centers
  // after swapping billboardBag->right/up.
  struct ParticleSystem {
    int objectIndex = -1;
    unsigned int rng = 1;
    std::vector<Tyra::Vec4> pos, vel;
    std::vector<float> life, maxLife;
    std::vector<Tyra::Vec4> params;  // per-particle (m00, m01, m10, m11)
    std::vector<Tyra::Color> cols;   // one RGBA per particle
    std::unique_ptr<Tyra::StaPipBag> bag;
    std::unique_ptr<Tyra::StaPipInfoBag> infoBag;
    std::unique_ptr<Tyra::StaPipColorBag> colorBag;
    std::unique_ptr<Tyra::StaPipTextureBag> texBag;
    std::unique_ptr<Tyra::StaPipBillboardBag> billboardBag;
  };
  std::vector<ParticleSystem> particles;
  void buildParticles();
  void updateParticles();

  // Sound emitters (type 8): distance-attenuated one-shots on channels 16-23
  std::vector<audsrv_adpcm_t*> sndSamples;  // scene_data.hpp SND_PATHS order
  std::vector<int> sndTimers;               // per-object retrigger countdown
  void updateSoundEmitters();

  // Scene switch target held across the loading-screen frames (the screen
  // itself is drawn by loadingscreen::renderFrame from loading_data.gen.hpp).
  int loadingFrames = 0, loadingTarget = -1;
  // Snapshot of the armed hold length: everyFrames() tracks the measured
  // frame time now, so re-evaluating it in a == comparison against the
  // counter could miss its frame at uncapped FPS.
  int loadingTotal = 0;

  // "Use" interaction: nearest usable object the camera looks at (controls.hpp)
  void updateUseTarget();
  int useTargetIndex = -1;
  // Pickable objects: at most one carried + one in flight. The carried object
  // rides a fixed reach in front of the camera, swept against the world
  // (sweepSphere) so it cannot be pushed through or parked behind geometry.
  void updateCarriedObject();
  // Hands a dropped/thrown object back to the physics sim (waking it), or
  // returns false when it has no rigid body to hand off to.
  bool releaseCarried(RuntimeObject& o, float vx, float vy, float vz);
  float objectHalfExtent(const RuntimeObject& o) const;
  // Blocks the walker from pressing against geometry the carried object no
  // longer fits in front of (the spring arm's sweep, pushing the walker back
  // instead of pulling the camera in).
  void applyCarryWhisker(float* nextX, float* nextZ, float probeY, float yaw,
                         float feetY, float eyeHeight);
  int carryIndex = -1;        // runtimeObjects index being carried, -1 = none
  // The portal the carried object is currently passing THROUGH (its carry ray
  // pierces the opening and that portal renders the object in its
  // through-view), or -1. The object is drawn NORMALLY in the main pass at
  // its real position - the portal's z-cap clips the part inside the opening
  // that is past the surface, and a wall around the opening occludes the
  // rest - while that portal's through-view draws a copy mapped to the far
  // side, so the portion "through" the opening appears coming out the other
  // end. Two-sided, like a real portal; recomputed each carry frame.
  int carryPortalPi = -1;
  bool carryGrabbed = false;  // eats the BTN_USE press that picked it up
  float carryDist = 0;        // smoothed carry reach: snaps in when the sweep
                              // blocks, eases back out (the boom's policy)
  int thrownIndex = -1;       // launched object still in flight, -1 = none
  float thrownVel[3] = {0, 0, 0};  // units/frame
  Tyra::Sprite usePromptSprite;
  Tyra::Sprite pickPromptSprite;  // "PICK UP" variant, same placement

  // Memory card save menu (save_system.gen.hpp): opened by using a Save
  // point object or the Open Save Menu flow node; gameplay pauses while
  // open. updateSaveMenu() returns true while it owns the pad.
  bool updateSaveMenu();
  void renderSaveMenu();
  void captureState(SaveGameData& d);  // fill d with the live game state
  void applyState(SaveGameData& d);    // restore d (sanitizes texts in place)
  void doSave(int slot);
  void doLoad(int slot);
  void applySavedObjects();
  void refreshSlotStates();
  std::vector<float> saveValues;
  std::vector<char> saveTexts;  // SAVE_TEXT_COUNT slots of SAVE_TEXT_LEN bytes
  std::vector<SaveObjectState> pendingObjState;  // applied after a scene load
  int pendingObjScene = -1;
  bool saveMenuOpen = false;
  int saveMenuSlot = 0;
  int saveMenuGrace = 0;  // frames to ignore pad input after opening
  bool slotUsed[SAVE_SLOTS] = {};
  int saveFeedback = 0, saveFeedbackFrames = 0;  // 1 saved, 2 loaded, 3 error
  Tyra::Sprite saveMenuSprite, saveCursorSprite, saveUsedSprite;
  Tyra::Sprite saveFeedbackSprites[3];  // saved / loaded / error
  // Checkpoint: ONE static snapshot of the save payload, in RAM only. The
  // payload is fixed-size and bounded by the save-flagged object count, so
  // this stays a few KB - no checkpoint history is kept by design. The
  // Commit Checkpoint flow node writes it to a card slot on request.
  SaveGameData checkpointData;
  bool checkpointValid = false;
  // Memory card busy overlay ("checking memory card, do not remove..."):
  // every card op goes through beginCardOp so the warning is presented
  // BEFORE the blocking libmc transfer runs, then holds a minimum time.
  void beginCardOp(int op, int slot);  // 0 save, 1 load, 2 commit checkpoint
  int cardOp = -1, cardOpSlot = 0;
  int cardOpDelay = 0;     // frames until the blocking op runs
  int cardBusyFrames = 0;  // minimum overlay hold left
  Tyra::Sprite saveBusySprite;

  // Game menus (menu_data.gen.hpp): panels baked by the editor, opened by
  // the Open Menu flow node, a menu entry, or at boot (title screen).
  // Gameplay pauses while one is open; Triangle walks the submenu stack.
  bool updateGameMenu();
  void renderGameMenu();
  // Ready-made option-block rows (Menu Editor): map each bound Toggle/Choice
  // row's option index onto its engine setting (volume/deadzone/curve/display).
  void applyMenuBindings();
  // Rebind rows (Menu Editor > Rebind key): push each row's saved override
  // into the live input bindings (docs/input-bindings.md).
  void applyInputBindings();
  std::vector<Tyra::Sprite> menuSprites;
  // Toggle/Choice entry values: one sub-rect sprite per menu into its baked
  // value strip (menu_data.gen.hpp; only menus with such entries have one).
  std::vector<Tyra::Sprite> menuValueSprites;

  // On-screen texts (hud_data.gen.hpp): baked text sprites the Set Text
  // Visible flow node flips via ScriptContext; a positive timer auto-hides.
  void updateAndRenderHudTexts();
  std::vector<Tyra::Sprite> hudTextSprites;
  std::vector<signed char> hudTextReq;   // ScriptContext::textRequest
  std::vector<float> hudTextDur;         // ScriptContext::textDuration
  std::vector<unsigned char> hudTextOn;  // visible this frame
  std::vector<float> hudTextTimer;       // seconds left (0 = until hidden)
  // Dynamic point lights (Set Light flow node), per scene-object index.
  std::vector<signed char> lightReq;     // ScriptContext::lightRequest
  std::vector<float> lightIntens;        // ScriptContext::lightIntensity
  // Sun screen effects (POSTFX_FLARE / POSTFX_GODRAYS, Set Flare / Set God
  // Rays): updateSunFx projects the sun + feeds the god-rays pass + eases
  // the flare's occlusion fade; renderFlare draws the additive ghosts.
  Tyra::Sprite flareSprites[4];
  bool flareTexturesLoaded = false;
  float flareVis = 0.0F;  // eased visibility 0..1
  float flareSunX = 0.0F, flareSunY = 0.0F;  // sun screen position, px
  float flareAmt = 0.0F;  // this frame's flare amount 0..1
  bool flarePreDrawn = false;  // main glow drew before the post-fx pass
  void updateSunFx();
  void renderFlare();
  // Visible light beams (Point Light > Beam): additive corona billboards +
  // optional cone shafts at the light source, following the light's runtime
  // state (flicker / Set Light / visibility). Drawn at the end of
  // renderScene so DoF and god rays treat them as scene light.
  struct LightBeam {
    int objIndex = -1;
    int kind = 0;  // 1 glow, 2 glow + cone
    std::vector<Tyra::Vec4> coronaVerts, coronaSts, coneVerts;
    std::vector<Tyra::Color> coneColors;
    Tyra::Color coronaColor;
    Tyra::M4x4 mat;  // identity - geometry is world space
    std::unique_ptr<Tyra::StaPipInfoBag> coronaInfo, coneInfo;
    std::unique_ptr<Tyra::StaPipColorBag> coronaColorBag, coneColorBag;
    std::unique_ptr<Tyra::StaPipTextureBag> coronaTexBag;
    std::unique_ptr<Tyra::StaPipBag> coronaBag, coneBag;
  };
  std::vector<LightBeam> lightBeams;
  Tyra::Texture* beamCoronaTex = nullptr;
  void setupLightBeams();            // per scene load
  void updateAndRenderLightBeams();  // per frame, end of renderScene
  // Ground pools of the DYNAMIC point lights: the terrain opts out of the
  // per-chunk light pick (hard seams at chunk borders), so each dynamic
  // light paints its pool as a smooth additive terrain-conforming patch
  // instead - same corona sprite, same flicker breathing.
  struct LightPool {
    int objIndex = -1;
    std::vector<Tyra::Vec4> verts, sts;
    Tyra::Color color;
    Tyra::M4x4 mat;
    std::unique_ptr<Tyra::StaPipInfoBag> info;
    std::unique_ptr<Tyra::StaPipColorBag> colorBag;
    std::unique_ptr<Tyra::StaPipTextureBag> texBag;
    std::unique_ptr<Tyra::StaPipBag> bag;
  };
  std::vector<LightPool> lightPools;
  // Optional custom sprite for the flashlight's pool (Player > Flashlight >
  // Pool texture). Cached by path - a scene switch must not re-add the same
  // texture to the repository.
  Tyra::Texture* flashPoolTex = nullptr;
  std::string flashPoolTexPath;
  // The last entry (objIndex -1) is the camera flashlight's: per-VERTEX
  // lighting cannot draw a spot smaller than the mesh tessellation, so
  // looking down at your own feet lit nothing (the cone footprint is
  // smaller than a terrain cell). That patch follows the view ray's
  // terrain hit instead.
  void setupLightPools();            // per scene load
  void updateAndRenderLightPools();  // per frame, before the shadows
  void buildPoolPatch(LightPool& b, float cx, float cz, float r, float lift);
  // Blob shadows (BLOB_SHADOWS): a soft dark terrain-conforming quad under
  // each moving object (third-person avatar, animated models, physics
  // objects), fading out as the object rises. Per-caster arrays - the DMA
  // may still be reading a submitted quad, so casters never share buffers.
  struct BlobShadow {
    int objIndex = -1;
    std::vector<Tyra::Vec4> verts, sts;
    Tyra::Color color;
    Tyra::M4x4 mat;
    std::unique_ptr<Tyra::StaPipInfoBag> info;
    std::unique_ptr<Tyra::StaPipColorBag> colorBag;
    std::unique_ptr<Tyra::StaPipTextureBag> texBag;
    std::unique_ptr<Tyra::StaPipBag> bag;
  };
  std::vector<BlobShadow> blobShadows;
  Tyra::Texture* blobShadowTex = nullptr;
  void setupBlobShadows();            // per scene load
  void updateAndRenderBlobShadows();  // per frame, end of renderScene
  // Projected silhouette shadows (per-object "Cast shadow"): the caster's
  // existing bags re-render into a small VRAM target from a light camera,
  // then a terrain patch under it samples the silhouette (renderProjShadows).
  struct ProjShadow {
    std::vector<Tyra::Vec4> verts, sts;  // receiver patch (terrain-conforming)
    Tyra::Color color;
    Tyra::M4x4 mat;
    std::unique_ptr<Tyra::StaPipInfoBag> info;
    std::unique_ptr<Tyra::StaPipColorBag> colorBag;
    std::unique_ptr<Tyra::StaPipTextureBag> texBag;
    std::unique_ptr<Tyra::StaPipBag> bag;
  };
  std::vector<ProjShadow> projShadows;  // one per engine slot in use
  std::vector<int> projCasters;         // authored caster object indices
  void setupProjShadows();   // per scene load
  void renderProjShadows();  // per frame, end of renderScene
  // The floor a shadow lands on. Terrain OR geometry: an indoor level's real
  // floor is boxes metres above the heightfield, and a patch built on the
  // heightfield alone ends up underneath it (see projCollectReceivers).
  void projCollectReceivers(float cx, float cz, float reach, float yMax);
  float projSurfaceAt(float x, float z);

  // Runtime texts (font_data.gen.hpp): one slot per Display Text node, drawn
  // glyph by glyph from a font atlas because the string is only known now.
  void updateAndRenderDynTexts();
  std::vector<signed char> dynTextReq;   // ScriptContext::dynTextRequest
  std::vector<float> dynTextDur;         // ScriptContext::dynTextDuration
  std::vector<char> dynTextBuf;          // DYN_TEXT_COUNT * DYN_TEXT_LEN
  std::vector<unsigned char> dynTextOn;  // visible this frame
  std::vector<float> dynTextTimer;
  Tyra::Sprite menuCursorSprite;
  Tyra::Sprite menuDimSprite;  // fullscreen dim under pausing menus
  int gameMenuIndex = -1;
  int gameMenuCursor = 0;
  int gameMenuGrace = 0;
  int gameMenuStack[4] = {};
  int gameMenuStackDepth = 0;
  // Entry index of the rebind row waiting for a press (-1 = not capturing).
  int menuRebindRow = -1;

  ScriptContext scriptCtx;
};

}  // namespace Endless_runner
