// Generated by TyraX. Do not edit - regenerated on every build.
#pragma once

#include <tyra>

// Custom screen effects (Tools > UI Editor). Each callback appends
// the effect's GS blits over the current framebuffer and returns
// the advanced packet cursor; run via applyCustomPostFx at the
// effect's stack slot. Bodies live in screen_fx.gen.cpp.
namespace Vu_lab {

// (no custom screen effects placed)

}  // namespace Vu_lab
