// Generated by TyraX. Do not edit - regenerated on every build.
//
// The project's own VU1 microprograms (docs/vu-authoring.md).
// vuprog::ENABLED is a compile-time constant: with no custom program
// every call below is an inline no-op and folds away entirely.
#pragma once

#include <tyra>

namespace vuprog {

constexpr bool ENABLED = true;

/** Installs the generated programs over their engine slots and
 * turns on the per-mesh parameter upload. Call once, AFTER
 * setRenderer and setVU1Clipping - both rebuild the program
 * cache, and an override installed first would be rebuilt away. */
void install(Tyra::StaPipCore& core);
/** The clock the time-varying stages read. WRAPPED - the
 * microprogram's range reduction folds through a 2^23 add. */
void setTime(Tyra::StaPipCore& core, float seconds);
/** The four numbers for the mesh about to be submitted. */
void setParams(Tyra::StaPipCore& core, const float* p);

}  // namespace vuprog
