// Generated by TyraX (the project's own VU scripts). Do not edit.
#pragma once

#include <tyra>

namespace vuscript {

constexpr bool ENABLED = true;

// The scripts, in the order the generator found them.
constexpr int kCellShading = 0;
constexpr int COUNT = 1;

/** Installs the scripts marked activeAtBoot(), over the material
 * classes they claim. Call AFTER setRenderer and setVU1Clipping -
 * both rebuild the resident program cache, so an override
 * installed first would be rebuilt away. */
void install(Tyra::StaPipCore& core);

/** Put a script on VU1, or take it off and give the class back to
 * the engine's own program. One pipeline drain and one upload, so
 * this belongs on an EVENT - a trigger, a cutscene beat, entering
 * a room - and not in a per-frame update. Only what is active
 * occupies micro memory, which is what lets a game carry more
 * programs than fit at once. */
void activate(int script);
void deactivate(int script);
void deactivateAll();
bool active(int script);
const char* name(int script);

}  // namespace vuscript
