from pathlib import Path
import json,hashlib,ast
b=Path('F:/Projects/tyrax2-lab-20261001');h=Path(__file__).parent;c=b/'night-main11-batch-controls-v1';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
p=c/'analyze-night.py';s=p.read_text(encoding='utf8');s=s.replace('need=loop.need;n=loop.number','sp=importlib.util.spec_from_file_location("batch",Path(__file__).with_name("batch_controls.py"));batch=importlib.util.module_from_spec(sp);sp.loader.exec_module(batch)\nneed=loop.need;n=loop.number');old="  if kind==29:\n   raise ValueError('kind29 cold geometry/carrier source schema still pending independent review')";new="  if kind==29:\n   for row in fm.values():need(all(n(row,k)==0 for k in('calls','units1','units2','units3','units4','timedCalls','reads','ticks')),'batch adds no producer clocks/counters')\n   r['mainBatchColdControls']=batch.check(stdout,flags,loop)";assert old in s;s=s.replace(old,new);s=s.replace("r['interpretation']='Same-ELF owned TEX1 candidate elapsed contrast; common prepared selector footprint unpriced' if kind==28", "r['interpretation']='Same-ELF main-only batching elapsed contrast; activation/semantic qualification separate from completed capture' if kind==29 else 'Same-ELF owned TEX1 candidate elapsed contrast; common prepared selector footprint unpriced' if kind==28");p.write_bytes(s.encode())
p=c/'analyze-night-cli.py';s=p.read_text(encoding='utf8').replace("Path(__file__).with_name('corona_controls.py'),", "Path(__file__).with_name('corona_controls.py'),Path(__file__).with_name('batch_controls.py'),");p.write_bytes(s.encode())
p=h/'runtime_guard.py';s=p.read_text(encoding='utf8').replace("assert len(host['sourcePins'])==6", "assert len(host['sourcePins'])==7");p.write_bytes(s.encode())
p=h/'host-authority.json';d=json.loads(p.read_text(encoding='utf8'));d['sourcePins']={str(p):sha(p)for p in [c/'analyze-loop.py',c/'analyze-night.py',c/'analyze-night-cli.py',c/'corona_controls.py',c/'batch_controls.py',c/'source-controls/night_plan.hpp',c/'source-controls/stapip_vu1_shared_defines.h']};d['sourceSchemaDraft']=True;d['candidateActivationSeparateFromCompletion']=True;p.write_bytes((json.dumps(d,indent=2)+'\n').encode())
for p in list(c.glob('*.py'))+list(h.glob('*.py')):ast.parse(p.read_text(encoding='utf8'))
(h/'helper-pins.json').write_bytes((json.dumps({p.name:sha(p)for p in h.iterdir()if p.is_file()and p.name!='helper-pins.json'},indent=2)+'\n').encode());print('DRAFT_KIND29_SCHEMA_INTEGRATED_7_PINNED_HOST_INPUTS')
