// Generated by TyraX. Do not edit - regenerated on every build.
//
// The project's own VU1 microprograms (docs/vu-authoring.md).
// vuprog::ENABLED is a compile-time constant: with no custom program
// every call below is an inline no-op and folds away entirely.
#pragma once

#include <tyra>

namespace vuprog {

constexpr bool ENABLED = false;

constexpr int LOOK_COUNT = 0;

void install(Tyra::StaPipCore& core);
inline void activate(int) {}
inline int active() { return -1; }
inline const char* lookName(int) { return ""; }
inline bool movesGeometry() { return false; }
inline void setTime(Tyra::StaPipCore&, float) {}
inline void setParams(Tyra::StaPipCore&, const float*) {}

/** Swap the clipping mode at run time. VU1 clipping is precise and
 * costs about twice the micro memory; the EE clipper hands those
 * slots back and spends EE time instead. Rebuilds the resident
 * program cache, so call it BETWEEN frames, never mid-draw. */
void setVU1Clipping(bool onVU1);
bool vu1Clipping();

/** Narrow or widen the resident material classes at run time.
 * Bits: 1<<0 colour, 1<<1 lights, 1<<2 textured + lights, 1<<3
 * textured, 1<<4 reflective. A dropped class does not crash - the
 * engine walks the mesh down to a resident relative - but it draws
 * in the wrong style, so drop only what the moment does not show.
 * Rebuilds the resident program cache exactly like setVU1Clipping,
 * so this belongs on an event and never in a per-frame update. */
void setResidentClasses(unsigned mask);
unsigned residentClasses();

}  // namespace vuprog
