// Generated by tyra-editor. Delete this line to take ownership of this file.
#include "terrain_game.hpp"
#include "terrain_config.hpp"
#include "controls.hpp"
#include "scene_data.hpp"
#include "model_data.gen.hpp"
#include "hud_data.gen.hpp"
#include "terrain_heights.gen.hpp"
#include "texture_data.gen.hpp"
#include <math.h>

// Active-scene accessors: scene_data.hpp holds one table per scene, indexed
// by g_activeScene (mirrors TerrainGame::currentScene; a file-scope variable
// so free functions like shadeOf see the active scene too).
static int g_activeScene = 0;
#define SCENE_OBJECT_COUNT SCENE_OBJECT_COUNTS[g_activeScene]
#define SCENE_OBJECTS SCENE_OBJECT_TABLES[g_activeScene]
#define PLAYER_INDEX PLAYER_INDEXES[g_activeScene]
#define PLAYER_MODE PLAYER_MODES[g_activeScene]
#define PLAYER_WALK_SPEED PLAYER_WALK_SPEEDS[g_activeScene]
#define PLAYER_LOOK_SPEED PLAYER_LOOK_SPEEDS[g_activeScene]
#define PLAYER_EYE_HEIGHT PLAYER_EYE_HEIGHTS[g_activeScene]
#define PLAYER_JUMP_SPEED PLAYER_JUMP_SPEEDS[g_activeScene]
#define PLAYER_CAN_JUMP PLAYER_CAN_JUMPS[g_activeScene]
#define TERRAIN_WIDTH TERRAIN_WIDTHS[g_activeScene]
#define TERRAIN_DEPTH TERRAIN_DEPTHS[g_activeScene]
#define SCENE_LIGHT_X SCENE_LIGHT_XS[g_activeScene]
#define SCENE_LIGHT_Y SCENE_LIGHT_YS[g_activeScene]
#define SCENE_LIGHT_Z SCENE_LIGHT_ZS[g_activeScene]
#define SCENE_AMBIENT SCENE_AMBIENTS[g_activeScene]
#define SCENE_DIFFUSE SCENE_DIFFUSES[g_activeScene]
#define SCENE_LIGHT_COL_R SCENE_LIGHT_COL_RS[g_activeScene]
#define SCENE_LIGHT_COL_G SCENE_LIGHT_COL_GS[g_activeScene]
#define SCENE_LIGHT_COL_B SCENE_LIGHT_COL_BS[g_activeScene]
#define SCENE_BRIGHTNESS SCENE_BRIGHTNESSES[g_activeScene]
#define HM_W HM_WS[g_activeScene]
#define HM_D HM_DS[g_activeScene]
#define TERRAIN_HEIGHTS TERRAIN_HEIGHTS_TABLES[g_activeScene]
#define TERRAIN_TEXTURE TERRAIN_TEXTURES[g_activeScene]
#define TERRAIN_TEX_SCALE TERRAIN_TEX_SCALES[g_activeScene]
#define terrainHeightAt(x, z) terrainHeightAtScene(g_activeScene, (x), (z))

namespace Script_demo {

using namespace Tyra;

namespace {

constexpr float PI = 3.14159265358979F;

struct V3 {
  float x, y, z;
};

/** Rotation order: X, then Y, then Z (same as the editor viewport). */
V3 rotated(const V3& v, const float* rotDeg) {
  V3 r = v;
  const float rx = rotDeg[0] * PI / 180.0F;
  const float ry = rotDeg[1] * PI / 180.0F;
  const float rz = rotDeg[2] * PI / 180.0F;
  {
    const float c = cosf(rx), s = sinf(rx);
    const float y = r.y * c - r.z * s, z = r.y * s + r.z * c;
    r.y = y, r.z = z;
  }
  {
    const float c = cosf(ry), s = sinf(ry);
    const float x = r.x * c + r.z * s, z = -r.x * s + r.z * c;
    r.x = x, r.z = z;
  }
  {
    const float c = cosf(rz), s = sinf(rz);
    const float x = r.x * c - r.y * s, y = r.x * s + r.y * c;
    r.x = x, r.y = y;
  }
  return r;
}

/** Directional light (Project > Preferences), baked into vertex colors.
 * Returns per-channel multipliers: brightness * (ambient + diffuse*d*lightColor). */
V3 shadeOf(const V3& n) {
  float d = n.x * SCENE_LIGHT_X + n.y * SCENE_LIGHT_Y + n.z * SCENE_LIGHT_Z;
  if (d < 0.0F) d = 0.0F;
  const float base = SCENE_DIFFUSE * d;
  V3 s = {SCENE_BRIGHTNESS * (SCENE_AMBIENT + base * SCENE_LIGHT_COL_R),
          SCENE_BRIGHTNESS * (SCENE_AMBIENT + base * SCENE_LIGHT_COL_G),
          SCENE_BRIGHTNESS * (SCENE_AMBIENT + base * SCENE_LIGHT_COL_B)};
  if (s.x > 1.0F) s.x = 1.0F;
  if (s.y > 1.0F) s.y = 1.0F;
  if (s.z > 1.0F) s.z = 1.0F;
  return s;
}

/** Point lights (SceneObject type 9) in the active scene, baked additively on
 * top of the directional term. Linear distance falloff * N.L, tinted by the
 * light color and scaled by its brightness. wp = world-space vertex position. */
V3 pointLightAt(const V3& wp, const V3& n) {
  V3 add = {0.0F, 0.0F, 0.0F};
  for (int i = 0; i < SCENE_OBJECT_COUNT; ++i) {
    const SceneObjectData& L = SCENE_OBJECTS[i];
    if (L.type != 9) continue;
    const float radius = L.lightRadius > 0.01F ? L.lightRadius : 0.01F;
    V3 d = {L.position[0] - wp.x, L.position[1] - wp.y, L.position[2] - wp.z};
    const float dist = sqrtf(d.x * d.x + d.y * d.y + d.z * d.z);
    if (dist >= radius) continue;
    float atten = 1.0F - dist / radius;
    atten *= atten;  // softer, rounder pool of light
    float ndotl = 1.0F;
    if (dist > 0.0001F) {
      ndotl = (n.x * d.x + n.y * d.y + n.z * d.z) / dist;
      if (ndotl < 0.0F) ndotl = 0.0F;
    }
    const float k = L.lightBright * atten * ndotl;
    add.x += k * L.color[0];
    add.y += k * L.color[1];
    add.z += k * L.color[2];
  }
  return add;
}

void pushVert(std::vector<Vec4>& verts, std::vector<Color>& cols,
              std::vector<Vec4>& sts, const SceneObjectData& o, V3 p, V3 n,
              float u, float v) {
  p.x *= o.scale[0], p.y *= o.scale[1], p.z *= o.scale[2];
  p = rotated(p, o.rotation);
  n = rotated(n, o.rotation);
  const V3 wp = {p.x + o.position[0], p.y + o.position[1], p.z + o.position[2]};
  V3 shade = shadeOf(n);
  const V3 pl = pointLightAt(wp, n);
  shade.x += pl.x, shade.y += pl.y, shade.z += pl.z;
  if (shade.x > 1.0F) shade.x = 1.0F;
  if (shade.y > 1.0F) shade.y = 1.0F;
  if (shade.z > 1.0F) shade.z = 1.0F;
  verts.push_back(Vec4(wp.x, wp.y, wp.z, 1.0F));
  // In textured mode the color modulates the texture (128 = 1.0)
  const float scale = o.texture >= 0 ? 128.0F : 255.0F;
  cols.push_back(Color(o.color[0] * scale * shade.x, o.color[1] * scale * shade.y,
                       o.color[2] * scale * shade.z, 128.0F));
  sts.push_back(Vec4(u, v, 1.0F, 0.0F));
}

void pushQuad(std::vector<Vec4>& verts, std::vector<Color>& cols,
              std::vector<Vec4>& sts, const SceneObjectData& o, V3 a, V3 b, V3 c,
              V3 d, V3 n) {
  pushVert(verts, cols, sts, o, a, n, 0, 0);
  pushVert(verts, cols, sts, o, b, n, 1, 0);
  pushVert(verts, cols, sts, o, c, n, 1, 1);
  pushVert(verts, cols, sts, o, a, n, 0, 0);
  pushVert(verts, cols, sts, o, c, n, 1, 1);
  pushVert(verts, cols, sts, o, d, n, 0, 1);
}

void addBox(std::vector<Vec4>& verts, std::vector<Color>& cols,
            std::vector<Vec4>& sts, const SceneObjectData& o) {
  const float h = 0.5F;
  pushQuad(verts, cols, sts, o, {h, -h, -h}, {h, h, -h}, {h, h, h}, {h, -h, h}, {1, 0, 0});
  pushQuad(verts, cols, sts, o, {-h, -h, h}, {-h, h, h}, {-h, h, -h}, {-h, -h, -h},
           {-1, 0, 0});
  pushQuad(verts, cols, sts, o, {-h, h, -h}, {-h, h, h}, {h, h, h}, {h, h, -h}, {0, 1, 0});
  pushQuad(verts, cols, sts, o, {-h, -h, h}, {-h, -h, -h}, {h, -h, -h}, {h, -h, h},
           {0, -1, 0});
  pushQuad(verts, cols, sts, o, {-h, -h, h}, {h, -h, h}, {h, h, h}, {-h, h, h}, {0, 0, 1});
  pushQuad(verts, cols, sts, o, {h, -h, -h}, {-h, -h, -h}, {-h, h, -h}, {h, h, -h},
           {0, 0, -1});
}

void addSphere(std::vector<Vec4>& verts, std::vector<Color>& cols,
               std::vector<Vec4>& sts, const SceneObjectData& o) {
  const int stacks = 10, slices = 14;
  const float r = 0.5F;
  for (int st = 0; st < stacks; ++st) {
    const float t0 = PI * st / stacks, t1 = PI * (st + 1) / stacks;
    const float tv0 = (float)st / stacks, tv1 = (float)(st + 1) / stacks;
    for (int sl = 0; sl < slices; ++sl) {
      const float p0 = 2.0F * PI * sl / slices, p1 = 2.0F * PI * (sl + 1) / slices;
      const float tu0 = (float)sl / slices, tu1 = (float)(sl + 1) / slices;
      const V3 v00 = {r * sinf(t0) * cosf(p0), r * cosf(t0), r * sinf(t0) * sinf(p0)};
      const V3 v01 = {r * sinf(t0) * cosf(p1), r * cosf(t0), r * sinf(t0) * sinf(p1)};
      const V3 v10 = {r * sinf(t1) * cosf(p0), r * cosf(t1), r * sinf(t1) * sinf(p0)};
      const V3 v11 = {r * sinf(t1) * cosf(p1), r * cosf(t1), r * sinf(t1) * sinf(p1)};
      // Smooth shading: normal of a unit-sphere vertex is the vertex itself.
      const V3 n00 = {v00.x * 2, v00.y * 2, v00.z * 2};
      const V3 n01 = {v01.x * 2, v01.y * 2, v01.z * 2};
      const V3 n10 = {v10.x * 2, v10.y * 2, v10.z * 2};
      const V3 n11 = {v11.x * 2, v11.y * 2, v11.z * 2};
      pushVert(verts, cols, sts, o, v00, n00, tu0, tv0);
      pushVert(verts, cols, sts, o, v10, n10, tu0, tv1);
      pushVert(verts, cols, sts, o, v11, n11, tu1, tv1);
      pushVert(verts, cols, sts, o, v00, n00, tu0, tv0);
      pushVert(verts, cols, sts, o, v11, n11, tu1, tv1);
      pushVert(verts, cols, sts, o, v01, n01, tu1, tv0);
    }
  }
}

void addCylinder(std::vector<Vec4>& verts, std::vector<Color>& cols,
                 std::vector<Vec4>& sts, const SceneObjectData& o) {
  const int seg = 16;
  const float r = 0.5F, h = 0.5F;
  for (int i = 0; i < seg; ++i) {
    const float a0 = 2.0F * PI * i / seg, a1 = 2.0F * PI * (i + 1) / seg;
    const float u0 = (float)i / seg, u1 = (float)(i + 1) / seg;
    const float x0 = r * cosf(a0), z0 = r * sinf(a0);
    const float x1 = r * cosf(a1), z1 = r * sinf(a1);
    const V3 n0 = {cosf(a0), 0, sinf(a0)}, n1 = {cosf(a1), 0, sinf(a1)};
    // side (smooth)
    pushVert(verts, cols, sts, o, {x0, -h, z0}, n0, u0, 1);
    pushVert(verts, cols, sts, o, {x0, h, z0}, n0, u0, 0);
    pushVert(verts, cols, sts, o, {x1, h, z1}, n1, u1, 0);
    pushVert(verts, cols, sts, o, {x0, -h, z0}, n0, u0, 1);
    pushVert(verts, cols, sts, o, {x1, h, z1}, n1, u1, 0);
    pushVert(verts, cols, sts, o, {x1, -h, z1}, n1, u1, 1);
    // caps (planar mapping)
    pushVert(verts, cols, sts, o, {0, h, 0}, {0, 1, 0}, 0.5F, 0.5F);
    pushVert(verts, cols, sts, o, {x1, h, z1}, {0, 1, 0}, x1 + 0.5F, z1 + 0.5F);
    pushVert(verts, cols, sts, o, {x0, h, z0}, {0, 1, 0}, x0 + 0.5F, z0 + 0.5F);
    pushVert(verts, cols, sts, o, {0, -h, 0}, {0, -1, 0}, 0.5F, 0.5F);
    pushVert(verts, cols, sts, o, {x0, -h, z0}, {0, -1, 0}, x0 + 0.5F, z0 + 0.5F);
    pushVert(verts, cols, sts, o, {x1, -h, z1}, {0, -1, 0}, x1 + 0.5F, z1 + 0.5F);
  }
}

void addCone(std::vector<Vec4>& verts, std::vector<Color>& cols,
             std::vector<Vec4>& sts, const SceneObjectData& o) {
  const int seg = 16;
  const float r = 0.5F, h = 0.5F;
  const float nl = 0.894F, ny = 0.447F;  // side normal for r=0.5, h=1
  for (int i = 0; i < seg; ++i) {
    const float a0 = 2.0F * PI * i / seg, a1 = 2.0F * PI * (i + 1) / seg;
    const float am = (a0 + a1) * 0.5F;
    const float u0 = (float)i / seg, u1 = (float)(i + 1) / seg;
    const float x0 = r * cosf(a0), z0 = r * sinf(a0);
    const float x1 = r * cosf(a1), z1 = r * sinf(a1);
    // side
    pushVert(verts, cols, sts, o, {0, h, 0}, {nl * cosf(am), ny, nl * sinf(am)},
             (u0 + u1) * 0.5F, 0);
    pushVert(verts, cols, sts, o, {x1, -h, z1}, {nl * cosf(a1), ny, nl * sinf(a1)}, u1, 1);
    pushVert(verts, cols, sts, o, {x0, -h, z0}, {nl * cosf(a0), ny, nl * sinf(a0)}, u0, 1);
    // base (planar mapping)
    pushVert(verts, cols, sts, o, {0, -h, 0}, {0, -1, 0}, 0.5F, 0.5F);
    pushVert(verts, cols, sts, o, {x0, -h, z0}, {0, -1, 0}, x0 + 0.5F, z0 + 0.5F);
    pushVert(verts, cols, sts, o, {x1, -h, z1}, {0, -1, 0}, x1 + 0.5F, z1 + 0.5F);
  }
}

void addModel(std::vector<Vec4>& verts, std::vector<Color>& cols,
              std::vector<Vec4>& sts, const SceneObjectData& o) {
  if (o.model < 0 || o.model >= MODEL_COUNT) return;
  const ModelData& m = MODELS[o.model];
  for (int i = 0; i < m.vertexCount; ++i) {
    const float* v = m.verts + i * 8;
    pushVert(verts, cols, sts, o, {v[0], v[1], v[2]}, {v[3], v[4], v[5]}, v[6], v[7]);
  }
}

}  // namespace

TerrainGame::TerrainGame(Engine* t_engine)
    : engine(t_engine),
      playerX(0.0F),
      playerZ(0.0F),
      yaw(0.0F),
      pitch(0.0F),
      playerY(0.0F),
      playerVelY(0.0F),
      model(M4x4::Identity) {}

TerrainGame::~TerrainGame() {}

void TerrainGame::init() {
  // Engine clipper fix: the default clipMargin (-10.0F) moves the near
  // clipping plane ~10 units away from the camera, cutting away nearby
  // geometry. Clip right in front of the real near plane instead.
  // (read by the clipper during setRenderer below)
  PlanesClipAlgorithm::clipMargin =
      -(engine->renderer.core.getSettings().getNear() + 0.5F);

  stapip.setRenderer(&engine->renderer.core);

  engine->renderer.core.postFx.setBloom(POSTFX_BLOOM);
  engine->renderer.core.postFx.setGrain(POSTFX_GRAIN);

  engine->renderer.setClearScreenColor(Color(SKY_R, SKY_G, SKY_B));

  // Player start: the first spawn point in the scene (if any)
  for (int i = 0; i < SCENE_OBJECT_COUNT; ++i) {
    if (SCENE_OBJECTS[i].type == 4) {
      playerX = SCENE_OBJECTS[i].position[0];
      playerZ = SCENE_OBJECTS[i].position[2];
      yaw = SCENE_OBJECTS[i].rotation[1] * PI / 180.0F;
      break;
    }
  }
  playerY = terrainHeightAt(playerX, playerZ);

  updatePlayer();
  buildScene();

  scriptCtx.engine = engine;
  scriptCtx.objects = runtimeObjects.data();
  scriptCtx.objectCount = (int)runtimeObjects.size();
  scriptCtx.skyColor = Color(SKY_R, SKY_G, SKY_B);
  scriptCtx.playerPosition = cameraPosition;
  for (Script* script : getScripts()) script->init(scriptCtx);

  // HUD sprites (see hud_data.gen.hpp)
  const auto& screen = engine->renderer.core.getSettings();
  hudSprites.reserve(HUD_COUNT);
  for (int i = 0; i < HUD_COUNT; ++i) {
    const HudImageData& h = HUD_IMAGES[i];
    Sprite sprite;
    sprite.mode = SpriteMode::MODE_STRETCH;
    sprite.size = Vec2(h.w, h.h);
    sprite.position = Vec2(h.x * screen.getWidth() - h.w * 0.5F,
                           h.y * screen.getHeight() - h.h * 0.5F);
    hudSprites.push_back(sprite);
    auto* texture =
        engine->renderer.getTextureRepository().add(FileUtils::fromCwd(h.path));
    texture->addLink(hudSprites.back().id);
  }

  // "USE" prompt (res/hud/use.png), shown while looking at a usable object
  usePromptSprite.mode = SpriteMode::MODE_STRETCH;
  usePromptSprite.size = Vec2(128.0F, 32.0F);
  usePromptSprite.position = Vec2((screen.getWidth() - 128.0F) * 0.5F,
                                  screen.getHeight() * 0.72F);
  auto* useTexture =
      engine->renderer.getTextureRepository().add(FileUtils::fromCwd("hud/use.png"));
  useTexture->addLink(usePromptSprite.id);

  // Loading screen sprite (res/hud/loading.png), shown on scene switches
  loadingSprite.mode = SpriteMode::MODE_STRETCH;
  loadingSprite.size = Vec2(256.0F, 64.0F);
  loadingSprite.position = Vec2((screen.getWidth() - 256.0F) * 0.5F,
                                (screen.getHeight() - 64.0F) * 0.5F);
  auto* loadingTexture = engine->renderer.getTextureRepository().add(
      FileUtils::fromCwd("hud/loading.png"));
  loadingTexture->addLink(loadingSprite.id);

  // Sound emitter samples (adpenc output next to the ELF)
  for (int i = 0; i < SND_COUNT; ++i)
    sndSamples.push_back(
        engine->audio.adpcm.load(FileUtils::fromCwd(SND_PATHS[i])));
}

void TerrainGame::loop() {
  if (!updatePlayerEntity()) updatePlayer();

  updateUseTarget();

  scriptCtx.playerPosition = cameraPosition;
  for (Script* script : getScripts()) script->update(scriptCtx);
  engine->renderer.setClearScreenColor(scriptCtx.skyColor);

  // Scene switch requested by the flow graph / scripts. The built-in FPP
  // player respawns at the new scene's spawn point.
  static bool fppSpawnPending = false;
  if (scriptCtx.requestScene >= 0) {
    const int target = scriptCtx.requestScene;
    scriptCtx.requestScene = -1;
    if (LOADING_SCREEN) {
      loadingTarget = target;
      loadingFrames = 35;  // 0.7s at 50 FPS
    } else {
      loadScene(target);
      fppSpawnPending = true;
    }
  }
  if (loadingFrames > 0) {
    engine->renderer.setClearScreenColor(Color(0.0F, 0.0F, 0.0F));
    engine->renderer.beginFrame();
    engine->renderer.renderer2D.render(loadingSprite);
    engine->renderer.endFrame();
    --loadingFrames;
    if (loadingFrames == 30) {  // a few frames shown before the actual load
      loadScene(loadingTarget);
      fppSpawnPending = true;
    }
    return;
  }
  if (fppSpawnPending) {
    // The built-in FPP player respawns at the new scene's spawn point.
    fppSpawnPending = false;
    playerX = 0.0F;
    playerZ = 0.0F;
    yaw = 0.0F;
    pitch = 0.0F;
    for (int i = 0; i < SCENE_OBJECT_COUNT; ++i) {
      if (SCENE_OBJECTS[i].type == 4) {
        playerX = SCENE_OBJECTS[i].position[0];
        playerZ = SCENE_OBJECTS[i].position[2];
        yaw = SCENE_OBJECTS[i].rotation[1] * PI / 180.0F;
        break;
      }
    }
    playerY = terrainHeightAt(playerX, playerZ);
    playerVelY = 0.0F;
  }

  // Flow graph / script teleport request: move the Player entity when the
  // scene has one, the built-in FPP player otherwise.
  if (scriptCtx.teleport) {
    scriptCtx.teleport = false;
    if (PLAYER_INDEX >= 0) {
      entX = scriptCtx.teleportPos.x;
      entY = scriptCtx.teleportPos.y;
      entZ = scriptCtx.teleportPos.z;
      entVelY = 0.0F;
      entYaw = scriptCtx.teleportYaw * PI / 180.0F;
    } else {
      playerX = scriptCtx.teleportPos.x;
      playerY = scriptCtx.teleportPos.y;
      playerZ = scriptCtx.teleportPos.z;
      playerVelY = 0.0F;
      yaw = scriptCtx.teleportYaw * PI / 180.0F;
    }
  }

  updateObjectPhysics();
  updateParticles();
  updateSoundEmitters();

  engine->renderer.beginFrame(CameraInfo3D(&cameraPosition, &cameraLookAt));
  {
    engine->renderer.renderer3D.usePipeline(stapip);
    renderScene();
    if (scriptCtx.hudVisible)
      for (auto& sprite : hudSprites) engine->renderer.renderer2D.render(sprite);
    if (useTargetIndex >= 0) engine->renderer.renderer2D.render(usePromptSprite);
  }
  engine->renderer.endFrame();
}

void TerrainGame::buildScene() {
  // Load all scene textures once (paths in texture_data.gen.hpp)
  loadedTextures.assign(TEXTURE_COUNT, nullptr);
  for (int i = 0; i < TEXTURE_COUNT; ++i)
    loadedTextures[i] =
        engine->renderer.getTextureRepository().add(FileUtils::fromCwd(TEXTURE_PATHS[i]));

  vertices.clear();
  colors.clear();
  terrainSts.clear();

  generateTerrainGrid();

  infoBag = std::make_unique<StaPipInfoBag>();
  infoBag->model = &model;
  infoBag->shadingType = TyraShadingFlat;
  // Always classify per package against the frustum: packages fully outside
  // are skipped, packages touching a plane get per-triangle clipping
  // (CLIP_PRECISE, Project > Preferences) or per-triangle culling (fast -
  // cheaper, may drop triangles at the screen edge). Raw submission (None)
  // is never safe: geometry behind or far off-screen wraps the GS raster
  // window and smears giant polygons (faithful on real HW / SW renderer).
  infoBag->frustumCulling = PipelineInfoBagFrustumCulling_Precise;
  infoBag->fullClipChecks = CLIP_PRECISE;

  colorBag = std::make_unique<StaPipColorBag>();
  colorBag->many = colors.data();

  bag = std::make_unique<StaPipBag>();
  bag->info = infoBag.get();
  bag->color = colorBag.get();
  bag->vertices = vertices.data();
  bag->count = static_cast<u32>(vertices.size());
  bag->texture = nullptr;
  bag->lighting = nullptr;

  if (TERRAIN_TEXTURE >= 0 && loadedTextures[TERRAIN_TEXTURE]) {
    terrainTexBag.texture = loadedTextures[TERRAIN_TEXTURE];
    terrainTexBag.coordinates = terrainSts.data();
    bag->texture = &terrainTexBag;
  }

  // Runtime copies of the scene objects - scripts and physics mutate these.
  skyHorizonR = SKY_R, skyHorizonG = SKY_G, skyHorizonB = SKY_B;
  buildSkyDome();

  loadScene(0);
}

// Switches the runtime state to a scene from scene_data.hpp. Assets
// (textures, models) are loaded once for all scenes at startup, so this
// only rebuilds the runtime objects: vectors and per-object bags are
// reused/freed here - nothing leaks and the switch takes a frame or two.
void TerrainGame::loadScene(int sceneIndex) {
  if (sceneIndex < 0 || sceneIndex >= SCENE_COUNT) return;
  currentScene = sceneIndex;
  g_activeScene = sceneIndex;
  sceneGeneration++;  // scene scripts see this and reset their state

  // Terrain and lighting are per scene - rebuild the terrain mesh and the
  // sky dome (its radius follows the terrain size). Vectors are reused.
  if (bag) {
    vertices.clear();
    colors.clear();
    terrainSts.clear();
    generateTerrainGrid();
    colorBag->many = colors.data();
    bag->vertices = vertices.data();
    bag->count = static_cast<u32>(vertices.size());
    bag->bboxVersion++;
    if (TERRAIN_TEXTURE >= 0 && loadedTextures[TERRAIN_TEXTURE]) {
      terrainTexBag.texture = loadedTextures[TERRAIN_TEXTURE];
      terrainTexBag.coordinates = terrainSts.data();
      bag->texture = &terrainTexBag;
    } else {
      bag->texture = nullptr;
    }
    buildSkyDome();
  }

  runtimeObjects.assign(SCENE_OBJECT_COUNT, RuntimeObject());
  objectGeometry.clear();
  objectGeometry.resize(SCENE_OBJECT_COUNT);
  for (int i = 0; i < SCENE_OBJECT_COUNT; ++i) {
    runtimeObjects[i].data = SCENE_OBJECTS[i];
    // spawn points and the player are editor markers, not geometry
    runtimeObjects[i].visible =
        SCENE_OBJECTS[i].type != 4 && SCENE_OBJECTS[i].type != 6;
    runtimeObjects[i].dirty = true;
  }
  scriptCtx.objects = runtimeObjects.data();
  scriptCtx.objectCount = (int)runtimeObjects.size();
  scriptCtx.scene = currentScene;
  scriptCtx.sceneGeneration = sceneGeneration;
  scriptCtx.usedObject = -1;
  useTargetIndex = -1;

  // Player entity start state for this scene
  if (PLAYER_INDEX >= 0 && PLAYER_INDEX < SCENE_OBJECT_COUNT) {
    entX = SCENE_OBJECTS[PLAYER_INDEX].position[0];
    entZ = SCENE_OBJECTS[PLAYER_INDEX].position[2];
    entY = PLAYER_MODE == 1 ? SCENE_OBJECTS[PLAYER_INDEX].position[1]
                            : terrainHeightAt(entX, entZ);
    entYaw = SCENE_OBJECTS[PLAYER_INDEX].rotation[1] * PI / 180.0F;
    entVelY = 0.0F;
    entPitch = 0.0F;
  }

  buildParticles();

  // Sound emitters: fresh retrigger state; mute the emitter channels (an
  // ADPCM sample can't be stopped - it plays out, but silently).
  sndTimers.assign(runtimeObjects.size(), 0);
  for (int ch = 16; ch < 24; ++ch) engine->audio.adpcm.setVolume(0, (s8)ch);
}

// --- Sound emitters ----------------------------------------------------
// Volume falls off linearly with the distance to the player. Interval 0
// retriggers every frame: tryPlay() is skipped while the channel is still
// busy, so the sample loops seamlessly. Hide Object mutes the emitter.
void TerrainGame::updateSoundEmitters() {
  if (sndSamples.empty()) return;
  if (sndTimers.size() != runtimeObjects.size())
    sndTimers.assign(runtimeObjects.size(), 0);
  for (int i = 0; i < (int)runtimeObjects.size(); ++i) {
    const RuntimeObject& o = runtimeObjects[i];
    if (o.data.type != 8 || !o.data.sndAuto) continue;
    if (o.data.snd < 0 || o.data.snd >= (int)sndSamples.size()) continue;
    const s8 ch = (s8)(16 + (i & 7));  // emitters own channels 16-23
    if (!o.visible) {
      engine->audio.adpcm.setVolume(0, ch);
      continue;
    }
    const float dx = o.data.position[0] - scriptCtx.playerPosition.x;
    const float dy = o.data.position[1] - scriptCtx.playerPosition.y;
    const float dz = o.data.position[2] - scriptCtx.playerPosition.z;
    const float dist = sqrtf(dx * dx + dy * dy + dz * dz);
    const float range = o.data.sndRange > 0.5F ? o.data.sndRange : 0.5F;
    const int vol = dist >= range ? 0 : (int)(100.0F * (1.0F - dist / range));
    engine->audio.adpcm.setVolume((u8)vol, ch);
    if (vol <= 0) continue;
    if (sndTimers[i] > 0) {
      --sndTimers[i];
      continue;
    }
    engine->audio.adpcm.tryPlay(sndSamples[o.data.snd], ch);
    sndTimers[i] = (int)(o.data.sndInterval * 50.0F);
  }
}

// --- Particle emitters ------------------------------------------------
// 2002-style particles: fixed pools sized at scene load, one cheap LCG,
// no trig and no allocations in the per-frame path. Camera-facing quads
// colored per vertex (no textures) - alpha does the softness.
static float prand(unsigned int& s) {  // 0..1
  s = s * 1664525u + 1013904223u;
  return (float)(s >> 8) * (1.0F / 16777216.0F);
}

void TerrainGame::buildParticles() {
  particles.clear();
  for (int i = 0; i < (int)runtimeObjects.size(); ++i) {
    if (runtimeObjects[i].data.type != 7) continue;
    ParticleSystem ps;
    ps.objectIndex = i;
    ps.rng = 12345u + (unsigned int)i * 7919u;
    int n = SCENE_OBJECTS[i].emitCount;
    if (n < 1) n = 1;
    if (n > 128) n = 128;
    ps.pos.assign(n, Vec4(0.0F, 0.0F, 0.0F, 1.0F));
    ps.vel.assign(n, Vec4(0.0F, 0.0F, 0.0F, 0.0F));
    ps.life.assign(n, 0.0F);  // dead -> staggered respawn over the first frames
    ps.maxLife.assign(n, 1.0F);
    ps.verts.assign((size_t)n * 6, Vec4(0.0F, 0.0F, 0.0F, 1.0F));
    ps.cols.assign((size_t)n * 6, Color(0.0F, 0.0F, 0.0F, 0.0F));
    ps.infoBag = std::make_unique<StaPipInfoBag>();
    ps.infoBag->model = &model;
    ps.infoBag->shadingType = TyraShadingGouraud;
    ps.infoBag->frustumCulling = PipelineInfoBagFrustumCulling_Precise;
    ps.infoBag->fullClipChecks = true;
    ps.colorBag = std::make_unique<StaPipColorBag>();
    ps.bag = std::make_unique<StaPipBag>();
    ps.bag->info = ps.infoBag.get();
    ps.bag->color = ps.colorBag.get();
    ps.bag->texture = nullptr;
    ps.bag->lighting = nullptr;
    ps.bag->count = 0;
    particles.push_back(std::move(ps));
  }
}

void TerrainGame::updateParticles() {
  if (particles.empty()) return;
  const float dt = 1.0F / 50.0F;

  // camera right/up shared by every billboard this frame
  Vec4 fwd = cameraLookAt - cameraPosition;
  const float fl = sqrtf(fwd.x * fwd.x + fwd.y * fwd.y + fwd.z * fwd.z);
  if (fl > 0.0001F) fwd.x /= fl, fwd.y /= fl, fwd.z /= fl;
  float rx = fwd.z, rz = -fwd.x;
  const float rl = sqrtf(rx * rx + rz * rz);
  if (rl > 0.0001F) rx /= rl, rz /= rl;
  else rx = 1.0F, rz = 0.0F;
  const float ux = -rz * fwd.y;
  const float uy = rz * fwd.x - rx * fwd.z;
  const float uz = rx * fwd.y;

  for (ParticleSystem& ps : particles) {
    const RuntimeObject& o = runtimeObjects[ps.objectIndex];
    if (!o.visible) {
      ps.bag->count = 0;  // Hide Object turns the emitter off
      continue;
    }
    const SceneObjectData& d = o.data;
    const int kind = d.emitKind;
    const int n = (int)ps.life.size();

    for (int i = 0; i < n; ++i) {
      ps.life[i] -= dt;
      if (ps.life[i] <= 0.0F) {
        const float r1 = prand(ps.rng), r2 = prand(ps.rng), r3 = prand(ps.rng);
        ps.pos[i] = Vec4(d.position[0] + (r1 - 0.5F) * d.scale[0], d.position[1],
                         d.position[2] + (r3 - 0.5F) * d.scale[2], 1.0F);
        if (kind == 0) {  // fire: rises and flickers
          ps.vel[i] = Vec4((r1 - 0.5F) * 0.8F, 1.2F + r2 * 1.2F, (r3 - 0.5F) * 0.8F, 0.0F);
          ps.maxLife[i] = 0.5F + r2 * 0.6F;
        } else if (kind == 1) {  // smoke: slow rise with drift
          ps.vel[i] = Vec4((r1 - 0.5F) * 0.5F, 0.5F + r2 * 0.5F, (r3 - 0.5F) * 0.5F, 0.0F);
          ps.maxLife[i] = 2.0F + r2 * 1.5F;
        } else if (kind == 2) {  // fog: big lazy puffs hugging the ground
          ps.vel[i] = Vec4((r1 - 0.5F) * 0.25F, 0.02F, (r3 - 0.5F) * 0.25F, 0.0F);
          ps.maxLife[i] = 3.0F + r2 * 3.0F;
        } else {  // sparks: radial burst pulled down by gravity
          ps.vel[i] = Vec4((r1 - 0.5F) * 5.0F, 1.5F + r2 * 2.5F, (r3 - 0.5F) * 5.0F, 0.0F);
          ps.maxLife[i] = 0.35F + r2 * 0.5F;
        }
        ps.life[i] = ps.maxLife[i] * (0.05F + 0.95F * prand(ps.rng));  // stagger
      }
      if (kind == 3) ps.vel[i].y -= 6.0F * dt;
      ps.pos[i].x += ps.vel[i].x * dt;
      ps.pos[i].y += ps.vel[i].y * dt;
      ps.pos[i].z += ps.vel[i].z * dt;

      // life fraction drives size, alpha (0-128) and the color ramp
      const float t = ps.life[i] / ps.maxLife[i];
      float size = d.emitSize;
      float alpha;
      float cr = d.color[0] * 128.0F, cg = d.color[1] * 128.0F, cb = d.color[2] * 128.0F;
      if (kind == 0) {
        size *= 0.5F + 0.8F * t;
        alpha = 90.0F * t;
        cg *= 0.35F + 0.65F * t;  // orange cools to red as it dies
        cb *= 0.25F * t;
      } else if (kind == 1) {
        size *= 1.6F - t;  // smoke grows while fading
        alpha = 40.0F * t;
      } else if (kind == 2) {
        size *= 3.0F;
        alpha = 18.0F * (t < 0.5F ? t * 2.0F : (1.0F - t) * 2.0F);  // fade in+out
      } else {
        size *= 0.35F;
        alpha = 110.0F * t;
      }

      const float Rx = rx * size, Rz = rz * size;
      const float Ux = ux * size, Uy = uy * size, Uz = uz * size;
      const Vec4& P = ps.pos[i];
      const Vec4 v0(P.x - Rx - Ux, P.y - Uy, P.z - Rz - Uz, 1.0F);
      const Vec4 v1(P.x + Rx - Ux, P.y - Uy, P.z + Rz - Uz, 1.0F);
      const Vec4 v2(P.x + Rx + Ux, P.y + Uy, P.z + Rz + Uz, 1.0F);
      const Vec4 v3(P.x - Rx + Ux, P.y + Uy, P.z - Rz + Uz, 1.0F);
      const int b = i * 6;
      ps.verts[b] = v0;
      ps.verts[b + 1] = v1;
      ps.verts[b + 2] = v2;
      ps.verts[b + 3] = v0;
      ps.verts[b + 4] = v2;
      ps.verts[b + 5] = v3;
      const Color c(cr, cg, cb, alpha);
      for (int k = 0; k < 6; ++k) ps.cols[b + k] = c;
    }
    ps.colorBag->many = ps.cols.data();
    ps.bag->vertices = ps.verts.data();
    ps.bag->count = (u32)ps.verts.size();
    ps.bag->bboxVersion++;  // moving cloud - refresh the frustum bbox
  }
}
// Picks the nearest usable object the camera is close to and looking at
// (thresholds in controls.hpp). BTN_USE on it -> scriptCtx.usedObject for
// one frame, which fires the flow graph "On Used" trigger.
void TerrainGame::updateUseTarget() {
  useTargetIndex = -1;
  scriptCtx.usedObject = -1;

  Vec4 dir = cameraLookAt - cameraPosition;
  const float dirLen = sqrtf(dir.x * dir.x + dir.y * dir.y + dir.z * dir.z);
  if (dirLen < 0.0001F) return;
  dir.x /= dirLen, dir.y /= dirLen, dir.z /= dirLen;

  float bestDist = 0.0F;
  for (int i = 0; i < (int)runtimeObjects.size(); ++i) {
    const RuntimeObject& o = runtimeObjects[i];
    if (!o.data.usable || !o.visible) continue;
    if (o.data.type == 4 || o.data.type == 6 || o.data.type == 7 ||
        o.data.type == 8 || o.data.type == 9)
      continue;

    const float dx = o.data.position[0] - cameraPosition.x;
    const float dy = o.data.position[1] - cameraPosition.y;
    const float dz = o.data.position[2] - cameraPosition.z;
    const float dist = sqrtf(dx * dx + dy * dy + dz * dz);
    float half = o.data.scale[0];
    if (o.data.scale[1] > half) half = o.data.scale[1];
    if (o.data.scale[2] > half) half = o.data.scale[2];
    half *= 0.5F;
    if (dist > USE_DISTANCE + half || dist < 0.001F) continue;

    const float dot = (dx * dir.x + dy * dir.y + dz * dir.z) / dist;
    if (dot < USE_LOOK_DOT && dist > half) continue;  // inside = always "looking"

    if (useTargetIndex < 0 || dist < bestDist) {
      useTargetIndex = i;
      bestDist = dist;
    }
  }

  if (useTargetIndex >= 0 && engine->pad.getClicked().BTN_USE)
    scriptCtx.usedObject = useTargetIndex;
}

bool TerrainGame::updatePlayerEntity() {
  if (PLAYER_INDEX < 0) return false;

  const auto& leftJoy = engine->pad.getLeftJoyPad();
  const auto& rightJoy = engine->pad.getRightJoyPad();
  auto axis = [](const u8& raw) {
    const float v = (raw - 128.0F) / 128.0F;
    return (v > -0.20F && v < 0.20F) ? 0.0F : v;  // deadzone
  };

  // Right stick: look around (stick right = turn right)
  entYaw -= axis(rightJoy.h) * 0.05F * PLAYER_LOOK_SPEED;
  entPitch -= axis(rightJoy.v) * 0.035F * PLAYER_LOOK_SPEED;
  if (entPitch > 1.35F) entPitch = 1.35F;
  if (entPitch < -1.35F) entPitch = -1.35F;

  const float fx = sinf(entYaw);
  const float fz = cosf(entYaw);
  const float forward = -axis(leftJoy.v);
  const float strafe = axis(leftJoy.h);

  if (PLAYER_MODE == 1) {
    // Noclip: fly where the camera looks; X up, Square down.
    const float cp = cosf(entPitch);
    entX += (fx * cp * forward - fz * strafe) * PLAYER_WALK_SPEED;
    entZ += (fz * cp * forward + fx * strafe) * PLAYER_WALK_SPEED;
    entY += sinf(entPitch) * forward * PLAYER_WALK_SPEED;
    if (engine->pad.getPressed().BTN_FLY_UP) entY += PLAYER_WALK_SPEED;
    if (engine->pad.getPressed().BTN_FLY_DOWN) entY -= PLAYER_WALK_SPEED;

    cameraPosition = Vec4(entX, entY, entZ);
    cameraLookAt = Vec4(entX + fx * cp, entY + sinf(entPitch), entZ + fz * cp);
    return true;
  }

  // Walk mode: terrain bounds, object collision, gravity + jump.
  float nextX = entX + (fx * forward - fz * strafe) * PLAYER_WALK_SPEED;
  float nextZ = entZ + (fz * forward + fx * strafe) * PLAYER_WALK_SPEED;

  const float limX = TERRAIN_WIDTH * 0.5F - 1.0F;
  const float limZ = TERRAIN_DEPTH * 0.5F - 1.0F;
  if (nextX > limX) nextX = limX;
  if (nextX < -limX) nextX = -limX;
  if (nextZ > limZ) nextZ = limZ;
  if (nextZ < -limZ) nextZ = -limZ;

  const float playerRadius = 0.35F;
  float ground = terrainHeightAt(nextX, nextZ);
  for (const RuntimeObject& o : runtimeObjects) {
    if (!o.visible || o.data.type == 4 || o.data.type == 6 ||
        o.data.type == 7 || o.data.type == 8 || o.data.type == 9)
      continue;
    const float ox = o.data.position[0];
    const float oz = o.data.position[2];
    const float hx = 0.5F * o.data.scale[0] + playerRadius;
    const float hz = 0.5F * o.data.scale[2] + playerRadius;
    const float top = o.data.position[1] + 0.5F * o.data.scale[1];
    const float bottom = o.data.position[1] - 0.5F * o.data.scale[1];

    const bool nextInside =
        nextX > ox - hx && nextX < ox + hx && nextZ > oz - hz && nextZ < oz + hz;
    if (!nextInside) continue;

    if (entY + 0.5F >= top) {
      if (top > ground) ground = top;
    } else if (entY < top && entY + PLAYER_EYE_HEIGHT > bottom) {
      const bool wasInsideX = entX > ox - hx && entX < ox + hx;
      const bool wasInsideZ = entZ > oz - hz && entZ < oz + hz;
      if (!wasInsideX) nextX = entX;
      if (!wasInsideZ) nextZ = entZ;
      if (wasInsideX && wasInsideZ) {
        nextX = entX;
        nextZ = entZ;
      }
    }
  }
  entX = nextX;
  entZ = nextZ;

  entVelY -= GRAVITY / (50.0F * 50.0F);
  entY += entVelY;
  if (entY <= ground) {
    entY = ground;
    entVelY = 0.0F;
    if (PLAYER_CAN_JUMP && engine->pad.getClicked().BTN_JUMP)
      entVelY = PLAYER_JUMP_SPEED / 50.0F;
  }

  const float eyeY = entY + PLAYER_EYE_HEIGHT;
  cameraPosition = Vec4(entX, eyeY, entZ);
  cameraLookAt = Vec4(entX + fx * cosf(entPitch), eyeY + sinf(entPitch),
                      entZ + fz * cosf(entPitch));
  return true;
}

void TerrainGame::buildSkyDome() {
  if (!SKY_DOME) return;

  const float diag = TERRAIN_WIDTH > TERRAIN_DEPTH ? TERRAIN_WIDTH : TERRAIN_DEPTH;
  float radius = diag * 1.5F;
  if (radius < 60.0F) radius = 60.0F;
  if (radius > 450.0F) radius = 450.0F;

  const int stacks = 6, slices = 14;
  auto skyAt = [&](float t) {  // t: 0 = horizon, 1 = zenith
    return Color(skyHorizonR + (SKY_TOP_R - skyHorizonR) * t,
                 skyHorizonG + (SKY_TOP_G - skyHorizonG) * t,
                 skyHorizonB + (SKY_TOP_B - skyHorizonB) * t, 128.0F);
  };
  auto domeVert = [&](int stack, int slice) {
    // Start slightly below the horizon so the seam is never visible
    const float lat = -0.06F + (PI * 0.5F + 0.06F) * stack / stacks;
    const float lon = 2.0F * PI * slice / slices;
    return Vec4(radius * cosf(lat) * cosf(lon), radius * sinf(lat),
                radius * cosf(lat) * sinf(lon), 1.0F);
  };

  skyDome.vertices.clear();
  skyDome.colors.clear();
  for (int st = 0; st < stacks; ++st) {
    const float t0 = (float)st / stacks, t1 = (float)(st + 1) / stacks;
    for (int sl = 0; sl < slices; ++sl) {
      const Vec4 v00 = domeVert(st, sl), v01 = domeVert(st, sl + 1);
      const Vec4 v10 = domeVert(st + 1, sl), v11 = domeVert(st + 1, sl + 1);
      skyDome.vertices.push_back(v00);
      skyDome.vertices.push_back(v10);
      skyDome.vertices.push_back(v11);
      skyDome.vertices.push_back(v00);
      skyDome.vertices.push_back(v11);
      skyDome.vertices.push_back(v01);
      skyDome.colors.push_back(skyAt(t0));
      skyDome.colors.push_back(skyAt(t1));
      skyDome.colors.push_back(skyAt(t1));
      skyDome.colors.push_back(skyAt(t0));
      skyDome.colors.push_back(skyAt(t1));
      skyDome.colors.push_back(skyAt(t0));
    }
  }

  skyDome.infoBag = std::make_unique<StaPipInfoBag>();
  skyDome.infoBag->model = &model;
  skyDome.infoBag->shadingType = TyraShadingGouraud;
  // Static geometry crossing the screen edges all the time - needs clipping
  skyDome.infoBag->frustumCulling = PipelineInfoBagFrustumCulling_Precise;
  skyDome.infoBag->fullClipChecks = true;
  skyDome.colorBag = std::make_unique<StaPipColorBag>();
  skyDome.colorBag->many = skyDome.colors.data();
  skyDome.bag = std::make_unique<StaPipBag>();
  skyDome.bag->info = skyDome.infoBag.get();
  skyDome.bag->color = skyDome.colorBag.get();
  skyDome.bag->vertices = skyDome.vertices.data();
  skyDome.bag->count = static_cast<u32>(skyDome.vertices.size());
  skyDome.bag->texture = nullptr;
  skyDome.bag->lighting = nullptr;
  static u32 domeVersion = 0;  // dome rebuilds on retint - skip stale bboxes
  skyDome.bag->bboxVersion = ++domeVersion;
}

void TerrainGame::rebuildObjectGeometry(int index) {
  RuntimeObject& o = runtimeObjects[index];
  ObjectGeometry& g = objectGeometry[index];
  o.dirty = false;

  g.vertices.clear();
  g.colors.clear();
  g.sts.clear();
  switch (o.data.type) {
    case 1: addSphere(g.vertices, g.colors, g.sts, o.data); break;
    case 2: addCylinder(g.vertices, g.colors, g.sts, o.data); break;
    case 3: addCone(g.vertices, g.colors, g.sts, o.data); break;
    case 4: break;  // spawn point - marker only
    case 5: addModel(g.vertices, g.colors, g.sts, o.data); break;
    case 6: break;  // player - marker only
    case 7: break;  // emitter - particles are built by updateParticles()
    case 8: break;  // sound emitter - marker only, no geometry
    case 9: break;  // point light - invisible source, no geometry
    default: addBox(g.vertices, g.colors, g.sts, o.data); break;
  }
  if (g.vertices.empty()) {
    g.bag.reset();
    return;
  }

  if (!g.bag) {
    g.infoBag = std::make_unique<StaPipInfoBag>();
    g.infoBag->model = &model;
    g.infoBag->shadingType = TyraShadingFlat;
    // Objects go through frustum classification too - raw submission (None)
    // wraps the GS raster window for anything behind/off-screen. The bbox
    // cache is keyed by pointer + bboxVersion, bumped on every rebuild, so
    // moving objects never reuse a stale box.
    g.infoBag->frustumCulling = PipelineInfoBagFrustumCulling_Precise;
    g.infoBag->fullClipChecks = true;
    g.colorBag = std::make_unique<StaPipColorBag>();
    g.bag = std::make_unique<StaPipBag>();
    g.bag->info = g.infoBag.get();
    g.bag->color = g.colorBag.get();
    g.bag->texture = nullptr;
    g.bag->lighting = nullptr;
  }
  g.colorBag->many = g.colors.data();
  g.bag->vertices = g.vertices.data();
  g.bag->count = static_cast<u32>(g.vertices.size());
  g.bag->bboxVersion++;  // geometry changed - refresh the frustum bbox cache

  if (o.data.texture >= 0 && o.data.texture < TEXTURE_COUNT &&
      loadedTextures[o.data.texture]) {
    if (!g.texBag) g.texBag = std::make_unique<StaPipTextureBag>();
    g.texBag->texture = loadedTextures[o.data.texture];
    g.texBag->coordinates = g.sts.data();
    g.bag->texture = g.texBag.get();
  } else {
    g.bag->texture = nullptr;
  }
}

void TerrainGame::updateObjectPhysics() {
  // GRAVITY is units/s^2; the game runs at 50 FPS
  const float gravityPerFrame = GRAVITY / (50.0F * 50.0F);
  for (RuntimeObject& o : runtimeObjects) {
    if (!o.data.physics) continue;
    const float half = 0.5F * o.data.scale[1];
    const float floorY =
        terrainHeightAt(o.data.position[0], o.data.position[2]) + half;
    if (o.velocityY == 0.0F && o.data.position[1] <= floorY) continue;  // resting

    o.velocityY -= gravityPerFrame;
    o.data.position[1] += o.velocityY;
    if (o.data.position[1] <= floorY) {
      o.data.position[1] = floorY;
      o.velocityY = 0.0F;
    }
    o.dirty = true;
  }
}

void TerrainGame::renderScene() {
  // Scripts changing ctx.skyColor retint the dome horizon
  if (skyDome.bag && (scriptCtx.skyColor.r != skyHorizonR ||
                      scriptCtx.skyColor.g != skyHorizonG ||
                      scriptCtx.skyColor.b != skyHorizonB)) {
    skyHorizonR = scriptCtx.skyColor.r;
    skyHorizonG = scriptCtx.skyColor.g;
    skyHorizonB = scriptCtx.skyColor.b;
    buildSkyDome();
  }
  if (skyDome.bag) stapip.core.render(skyDome.bag.get());
  stapip.core.render(bag.get());
  for (int i = 0; i < (int)runtimeObjects.size(); ++i) {
    if (runtimeObjects[i].dirty) rebuildObjectGeometry(i);
    if (runtimeObjects[i].visible && objectGeometry[i].bag)
      stapip.core.render(objectGeometry[i].bag.get());
  }
  // Highlight rims after every object so their depth is in the z-buffer:
  // the rim is depth-tested against the finished scene and can no longer be
  // punched through by an object drawn later in the loop.
  if (HIGHLIGHT_USABLE)
    for (int i = 0; i < (int)runtimeObjects.size(); ++i)
      if (runtimeObjects[i].visible && runtimeObjects[i].data.usable &&
          objectGeometry[i].bag)
        renderHighlightHull(i);  // proximity-checked inside; no-op when far
  // particles last - alpha blended over the scene
  for (ParticleSystem& ps : particles)
    if (ps.bag && ps.bag->count > 0) stapip.core.render(ps.bag.get());
}

// Usable-object highlight (Project > Preferences): a soft colored rim around
// the object silhouette. Three concentric copies of the object, grown around
// its center with fading alpha, drawn after the scene with z-test but no
// z-write (PipelineZTest_TestOnly). Each shell is additionally pushed away
// from the camera by a uniform scale around the eye point - that keeps its
// screen silhouette identical but places it behind the object's own depth,
// so the z-buffer rejects the interior and only the rim survives, correctly
// occluded by anything nearer. Proximity uses the same reference point as
// the USE interaction (the camera / player eye).
void TerrainGame::renderHighlightHull(int index) {
  const RuntimeObject& o = runtimeObjects[index];
  ObjectGeometry& g = objectGeometry[index];
  if (g.vertices.empty()) return;

  float half = o.data.scale[0];
  if (o.data.scale[1] > half) half = o.data.scale[1];
  if (o.data.scale[2] > half) half = o.data.scale[2];
  half *= 0.5F;
  if (half < 0.01F) half = 0.01F;

  const float dx = o.data.position[0] - cameraPosition.x;
  const float dy = o.data.position[1] - cameraPosition.y;
  const float dz = o.data.position[2] - cameraPosition.z;
  const float dist2 = dx * dx + dy * dy + dz * dz;
  const float reach = HIGHLIGHT_DISTANCE + half;
  if (dist2 > reach * reach) return;
  const float dist = sqrtf(dist2);

  // HIGHLIGHT_STEPS concentric shells up to HIGHLIGHT_WIDTH wide (both from
  // Project > Preferences), alpha roughly halving outward. Near the
  // silhouette all shells overlap - solid color fading outward.
  const float cx = o.data.position[0], cy = o.data.position[1],
              cz = o.data.position[2];
  // How far in front of the object the camera is - the pushback must move
  // the shell past the object's front surface without reaching things
  // right behind it.
  float behind = dist - half;
  if (behind < 0.5F) behind = 0.5F;

  const size_t n = g.vertices.size();
  g.hullVerts.resize(n * HIGHLIGHT_STEPS);
  g.hullCols.resize(n * HIGHLIGHT_STEPS);
  // One pushback for all shells (sized for the widest) - per-shell depths
  // would make the terrain/scene cut each shell on a different line and the
  // rim edge turns into visible steps.
  float growMax = HIGHLIGHT_WIDTH / half;
  if (growMax > 0.6F) growMax = 0.6F;
  const float k = 1.0F + (growMax * half + 0.15F) / behind;
  float alpha = HIGHLIGHT_STEPS > 1 ? 72.0F : 100.0F;  // single step = solid
  for (int s = 0; s < HIGHLIGHT_STEPS; ++s) {
    // uniform growth - rotated objects stay unskewed
    float grow = (HIGHLIGHT_WIDTH * (s + 1)) / (HIGHLIGHT_STEPS * half);
    if (grow > 0.6F) grow = 0.6F;
    const float f = 1.0F + grow;
    const Color c(HIGHLIGHT_R, HIGHLIGHT_G, HIGHLIGHT_B, alpha);
    alpha *= 0.55F;
    for (size_t v = 0; v < n; ++v) {
      const Vec4& p = g.vertices[v];
      float hx = cx + (p.x - cx) * f;
      float hy = cy + (p.y - cy) * f;
      float hz = cz + (p.z - cz) * f;
      hx = cameraPosition.x + (hx - cameraPosition.x) * k;
      hy = cameraPosition.y + (hy - cameraPosition.y) * k;
      hz = cameraPosition.z + (hz - cameraPosition.z) * k;
      // Shell parts of grounded objects dip below the terrain and the
      // ground in front z-rejects them (no bottom rim from a low camera).
      // Lift them just above the surface - the bottom rim becomes a glow
      // apron hugging the ground around the base.
      const float ground = terrainHeightAt(hx, hz) + 0.02F;
      if (hy < ground) hy = ground;
      g.hullVerts[s * n + v] = Vec4(hx, hy, hz, 1.0F);
      g.hullCols[s * n + v] = c;
    }
  }

  if (!g.hullBag) {
    g.hullInfoBag = std::make_unique<StaPipInfoBag>();
    g.hullInfoBag->model = &model;
    g.hullInfoBag->shadingType = TyraShadingFlat;
    g.hullInfoBag->frustumCulling = PipelineInfoBagFrustumCulling_Precise;
    g.hullInfoBag->fullClipChecks = true;
    g.hullInfoBag->zTestType = PipelineZTest_TestOnly;
    g.hullColorBag = std::make_unique<StaPipColorBag>();
    g.hullBag = std::make_unique<StaPipBag>();
    g.hullBag->info = g.hullInfoBag.get();
    g.hullBag->color = g.hullColorBag.get();
    g.hullBag->texture = nullptr;
    g.hullBag->lighting = nullptr;
  }
  g.hullColorBag->many = g.hullCols.data();
  g.hullBag->vertices = g.hullVerts.data();
  g.hullBag->count = static_cast<u32>(g.hullVerts.size());
  g.hullBag->bboxVersion++;  // rebuilt every frame while highlighted
  stapip.core.render(g.hullBag.get());
  // The pushback clears the object's front face but not its receding side
  // faces - shells still blend over those at glancing angles. Repainting
  // the object wins the equal-depth test (GEQUAL) and erases the wash
  // without touching the rim outside the silhouette.
  stapip.core.render(g.bag.get());
}

void TerrainGame::generateTerrainGrid() {
  // The grid follows the heightmap (terrain_heights.gen.hpp): one cell per
  // heightmap quad, vertex heights sampled directly, per-vertex shading
  // from the height gradient.
  const u32 cellsX = HM_W - 1;
  const u32 cellsZ = HM_D - 1;
  const float stepX = TERRAIN_WIDTH / cellsX;
  const float stepZ = TERRAIN_DEPTH / cellsZ;
  const float startX = -TERRAIN_WIDTH * 0.5F;
  const float startZ = -TERRAIN_DEPTH * 0.5F;

  auto hAt = [&](int ix, int iz) {
    if (ix < 0) ix = 0;
    if (iz < 0) iz = 0;
    if (ix > HM_W - 1) ix = HM_W - 1;
    if (iz > HM_D - 1) iz = HM_D - 1;
    return TERRAIN_HEIGHTS[iz * HM_W + ix];
  };
  auto shadeAt = [&](int ix, int iz) -> V3 {
    V3 n = {hAt(ix - 1, iz) - hAt(ix + 1, iz), 2.0F * (stepX < stepZ ? stepX : stepZ),
            hAt(ix, iz - 1) - hAt(ix, iz + 1)};
    const float len = sqrtf(n.x * n.x + n.y * n.y + n.z * n.z);
    if (len > 0.00001F) n.x /= len, n.y /= len, n.z /= len;
    V3 s = shadeOf(n);
    const V3 wp = {startX + ix * stepX, hAt(ix, iz), startZ + iz * stepZ};
    const V3 pl = pointLightAt(wp, n);
    s.x += pl.x, s.y += pl.y, s.z += pl.z;
    if (s.x > 1.0F) s.x = 1.0F;
    if (s.y > 1.0F) s.y = 1.0F;
    if (s.z > 1.0F) s.z = 1.0F;
    return s;
  };

  // Untextured: two greens in a checker pattern. Textured: a neutral gray
  // that modulates the texture 1:1 (PS2 modulation: 128 = 1.0).
  const bool textured = TERRAIN_TEXTURE >= 0;
  const float baseA[3] = {textured ? 128.0F : 96.0F, textured ? 128.0F : 160.0F,
                          textured ? 128.0F : 72.0F};
  const float baseB[3] = {textured ? 128.0F : 74.0F, textured ? 128.0F : 128.0F,
                          textured ? 128.0F : 56.0F};

  for (u32 z = 0; z < cellsZ; ++z) {
    for (u32 x = 0; x < cellsX; ++x) {
      const float x0 = startX + x * stepX;
      const float x1 = x0 + stepX;
      const float z0 = startZ + z * stepZ;
      const float z1 = z0 + stepZ;
      const float* base = ((x + z) % 2 == 0) ? baseA : baseB;

      const float h00 = hAt(x, z), h10 = hAt(x + 1, z);
      const float h01 = hAt(x, z + 1), h11 = hAt(x + 1, z + 1);
      const V3 s00 = shadeAt(x, z), s10 = shadeAt(x + 1, z);
      const V3 s01 = shadeAt(x, z + 1), s11 = shadeAt(x + 1, z + 1);
      auto shaded = [&](const V3& s) {
        return Color(base[0] * s.x, base[1] * s.y, base[2] * s.z, 128.0F);
      };
      auto st = [&](float wx, float wz) {
        terrainSts.push_back(
            Vec4(wx / TERRAIN_TEX_SCALE, wz / TERRAIN_TEX_SCALE, 1.0F, 0.0F));
      };

      vertices.push_back(Vec4(x0, h00, z0, 1.0F));
      vertices.push_back(Vec4(x1, h10, z0, 1.0F));
      vertices.push_back(Vec4(x0, h01, z1, 1.0F));
      vertices.push_back(Vec4(x1, h10, z0, 1.0F));
      vertices.push_back(Vec4(x1, h11, z1, 1.0F));
      vertices.push_back(Vec4(x0, h01, z1, 1.0F));

      st(x0, z0);
      st(x1, z0);
      st(x0, z1);
      st(x1, z0);
      st(x1, z1);
      st(x0, z1);

      colors.push_back(shaded(s00));
      colors.push_back(shaded(s10));
      colors.push_back(shaded(s01));
      colors.push_back(shaded(s10));
      colors.push_back(shaded(s11));
      colors.push_back(shaded(s01));
    }
  }
}

namespace {

float axisValue(const u8& raw) {
  const float v = (raw - 128.0F) / 128.0F;
  return (v > -0.20F && v < 0.20F) ? 0.0F : v;  // deadzone
}

}  // namespace

void TerrainGame::updatePlayer() {
  const auto& leftJoy = engine->pad.getLeftJoyPad();
  const auto& rightJoy = engine->pad.getRightJoyPad();

  // Right stick: look around (stick right = turn right)
  yaw -= axisValue(rightJoy.h) * 0.05F * LOOK_SPEED;
  pitch -= axisValue(rightJoy.v) * 0.035F * LOOK_SPEED;
  if (pitch > 1.2F) pitch = 1.2F;
  if (pitch < -1.2F) pitch = -1.2F;

  // Left stick: walk. Forward is where the camera looks (flat).
  const float fx = sinf(yaw);
  const float fz = cosf(yaw);
  const float forward = -axisValue(leftJoy.v);
  const float strafe = axisValue(leftJoy.h);
  float nextX = playerX + (fx * forward - fz * strafe) * WALK_SPEED;
  float nextZ = playerZ + (fz * forward + fx * strafe) * WALK_SPEED;

  // Keep the player on the terrain
  const float limX = TERRAIN_WIDTH * 0.5F - 1.0F;
  const float limZ = TERRAIN_DEPTH * 0.5F - 1.0F;
  if (nextX > limX) nextX = limX;
  if (nextX < -limX) nextX = -limX;
  if (nextZ > limZ) nextZ = limZ;
  if (nextZ < -limZ) nextZ = -limZ;

  // Collision with scene objects (XZ, boxes expanded by the player radius)
  // + standing on top of them. Player can step ~0.5 units up.
  // The floor is the sculpted terrain.
  const float playerRadius = 0.35F;
  float ground = terrainHeightAt(nextX, nextZ);
  for (const RuntimeObject& o : runtimeObjects) {
    if (!o.visible || o.data.type == 4 || o.data.type == 9) continue;
    const float ox = o.data.position[0];
    const float oz = o.data.position[2];
    const float hx = 0.5F * o.data.scale[0] + playerRadius;
    const float hz = 0.5F * o.data.scale[2] + playerRadius;
    const float top = o.data.position[1] + 0.5F * o.data.scale[1];
    const float bottom = o.data.position[1] - 0.5F * o.data.scale[1];

    const bool nextInside =
        nextX > ox - hx && nextX < ox + hx && nextZ > oz - hz && nextZ < oz + hz;
    if (!nextInside) continue;

    if (playerY + 0.5F >= top) {
      // Low enough to walk onto - candidate floor
      if (top > ground) ground = top;
    } else if (playerY < top && playerY + EYE_HEIGHT > bottom) {
      // Blocked - cancel the axes that entered the box this frame
      const bool wasInsideX = playerX > ox - hx && playerX < ox + hx;
      const bool wasInsideZ = playerZ > oz - hz && playerZ < oz + hz;
      if (!wasInsideX) nextX = playerX;
      if (!wasInsideZ) nextZ = playerZ;
      if (wasInsideX && wasInsideZ) {
        nextX = playerX;
        nextZ = playerZ;
      }
    }
  }
  playerX = nextX;
  playerZ = nextZ;

  // Gravity & jumping (X). GRAVITY: units/s^2, JUMP_SPEED: units/s, 50 FPS.
  playerVelY -= GRAVITY / (50.0F * 50.0F);
  playerY += playerVelY;
  if (playerY <= ground) {
    playerY = ground;
    playerVelY = 0.0F;
    if (engine->pad.getClicked().BTN_JUMP) playerVelY = JUMP_SPEED / 50.0F;
  }

  const float eyeY = playerY + EYE_HEIGHT;
  cameraPosition = Vec4(playerX, eyeY, playerZ);
  cameraLookAt = Vec4(playerX + fx * cosf(pitch), eyeY + sinf(pitch),
                      playerZ + fz * cosf(pitch));
}

}  // namespace Script_demo
