// Generated by tyra-editor. Delete this line to take ownership of this file.
#include "terrain_game.hpp"
#include "terrain_config.hpp"
#include "scene_data.hpp"
#include "model_data.gen.hpp"
#include "hud_data.gen.hpp"
#include <math.h>

namespace Script_demo {

using namespace Tyra;

namespace {

constexpr float PI = 3.14159265358979F;

struct V3 {
  float x, y, z;
};

/** Rotation order: X, then Y, then Z (same as the editor viewport). */
V3 rotated(const V3& v, const float* rotDeg) {
  V3 r = v;
  const float rx = rotDeg[0] * PI / 180.0F;
  const float ry = rotDeg[1] * PI / 180.0F;
  const float rz = rotDeg[2] * PI / 180.0F;
  {
    const float c = cosf(rx), s = sinf(rx);
    const float y = r.y * c - r.z * s, z = r.y * s + r.z * c;
    r.y = y, r.z = z;
  }
  {
    const float c = cosf(ry), s = sinf(ry);
    const float x = r.x * c + r.z * s, z = -r.x * s + r.z * c;
    r.x = x, r.z = z;
  }
  {
    const float c = cosf(rz), s = sinf(rz);
    const float x = r.x * c - r.y * s, y = r.x * s + r.y * c;
    r.x = x, r.y = y;
  }
  return r;
}

/** Directional light (Project > Preferences), baked into vertex colors. */
float shadeOf(const V3& n) {
  float d = n.x * SCENE_LIGHT_X + n.y * SCENE_LIGHT_Y + n.z * SCENE_LIGHT_Z;
  if (d < 0.0F) d = 0.0F;
  float s = SCENE_AMBIENT + SCENE_DIFFUSE * d;
  return s > 1.0F ? 1.0F : s;
}

void pushVert(std::vector<Vec4>& verts, std::vector<Color>& cols,
              const SceneObjectData& o, V3 p, V3 n) {
  p.x *= o.scale[0], p.y *= o.scale[1], p.z *= o.scale[2];
  p = rotated(p, o.rotation);
  n = rotated(n, o.rotation);
  const float shade = shadeOf(n);
  verts.push_back(Vec4(p.x + o.position[0], p.y + o.position[1],
                       p.z + o.position[2], 1.0F));
  cols.push_back(Color(o.color[0] * 255.0F * shade, o.color[1] * 255.0F * shade,
                       o.color[2] * 255.0F * shade, 128.0F));
}

void pushQuad(std::vector<Vec4>& verts, std::vector<Color>& cols,
              const SceneObjectData& o, V3 a, V3 b, V3 c, V3 d, V3 n) {
  pushVert(verts, cols, o, a, n);
  pushVert(verts, cols, o, b, n);
  pushVert(verts, cols, o, c, n);
  pushVert(verts, cols, o, a, n);
  pushVert(verts, cols, o, c, n);
  pushVert(verts, cols, o, d, n);
}

void addBox(std::vector<Vec4>& verts, std::vector<Color>& cols,
            const SceneObjectData& o) {
  const float h = 0.5F;
  pushQuad(verts, cols, o, {h, -h, -h}, {h, h, -h}, {h, h, h}, {h, -h, h}, {1, 0, 0});
  pushQuad(verts, cols, o, {-h, -h, h}, {-h, h, h}, {-h, h, -h}, {-h, -h, -h}, {-1, 0, 0});
  pushQuad(verts, cols, o, {-h, h, -h}, {-h, h, h}, {h, h, h}, {h, h, -h}, {0, 1, 0});
  pushQuad(verts, cols, o, {-h, -h, h}, {-h, -h, -h}, {h, -h, -h}, {h, -h, h}, {0, -1, 0});
  pushQuad(verts, cols, o, {-h, -h, h}, {h, -h, h}, {h, h, h}, {-h, h, h}, {0, 0, 1});
  pushQuad(verts, cols, o, {h, -h, -h}, {-h, -h, -h}, {-h, h, -h}, {h, h, -h}, {0, 0, -1});
}

void addSphere(std::vector<Vec4>& verts, std::vector<Color>& cols,
               const SceneObjectData& o) {
  const int stacks = 10, slices = 14;
  const float r = 0.5F;
  for (int st = 0; st < stacks; ++st) {
    const float t0 = PI * st / stacks, t1 = PI * (st + 1) / stacks;
    for (int sl = 0; sl < slices; ++sl) {
      const float p0 = 2.0F * PI * sl / slices, p1 = 2.0F * PI * (sl + 1) / slices;
      const V3 v00 = {r * sinf(t0) * cosf(p0), r * cosf(t0), r * sinf(t0) * sinf(p0)};
      const V3 v01 = {r * sinf(t0) * cosf(p1), r * cosf(t0), r * sinf(t0) * sinf(p1)};
      const V3 v10 = {r * sinf(t1) * cosf(p0), r * cosf(t1), r * sinf(t1) * sinf(p0)};
      const V3 v11 = {r * sinf(t1) * cosf(p1), r * cosf(t1), r * sinf(t1) * sinf(p1)};
      // Smooth shading: normal of a unit-sphere vertex is the vertex itself.
      const V3 n00 = {v00.x * 2, v00.y * 2, v00.z * 2};
      const V3 n01 = {v01.x * 2, v01.y * 2, v01.z * 2};
      const V3 n10 = {v10.x * 2, v10.y * 2, v10.z * 2};
      const V3 n11 = {v11.x * 2, v11.y * 2, v11.z * 2};
      pushVert(verts, cols, o, v00, n00);
      pushVert(verts, cols, o, v10, n10);
      pushVert(verts, cols, o, v11, n11);
      pushVert(verts, cols, o, v00, n00);
      pushVert(verts, cols, o, v11, n11);
      pushVert(verts, cols, o, v01, n01);
    }
  }
}

void addCylinder(std::vector<Vec4>& verts, std::vector<Color>& cols,
                 const SceneObjectData& o) {
  const int seg = 16;
  const float r = 0.5F, h = 0.5F;
  for (int i = 0; i < seg; ++i) {
    const float a0 = 2.0F * PI * i / seg, a1 = 2.0F * PI * (i + 1) / seg;
    const float x0 = r * cosf(a0), z0 = r * sinf(a0);
    const float x1 = r * cosf(a1), z1 = r * sinf(a1);
    const V3 n0 = {cosf(a0), 0, sinf(a0)}, n1 = {cosf(a1), 0, sinf(a1)};
    // side (smooth)
    pushVert(verts, cols, o, {x0, -h, z0}, n0);
    pushVert(verts, cols, o, {x0, h, z0}, n0);
    pushVert(verts, cols, o, {x1, h, z1}, n1);
    pushVert(verts, cols, o, {x0, -h, z0}, n0);
    pushVert(verts, cols, o, {x1, h, z1}, n1);
    pushVert(verts, cols, o, {x1, -h, z1}, n1);
    // caps
    pushVert(verts, cols, o, {0, h, 0}, {0, 1, 0});
    pushVert(verts, cols, o, {x1, h, z1}, {0, 1, 0});
    pushVert(verts, cols, o, {x0, h, z0}, {0, 1, 0});
    pushVert(verts, cols, o, {0, -h, 0}, {0, -1, 0});
    pushVert(verts, cols, o, {x0, -h, z0}, {0, -1, 0});
    pushVert(verts, cols, o, {x1, -h, z1}, {0, -1, 0});
  }
}

void addCone(std::vector<Vec4>& verts, std::vector<Color>& cols,
             const SceneObjectData& o) {
  const int seg = 16;
  const float r = 0.5F, h = 0.5F;
  const float nl = 0.894F, ny = 0.447F;  // side normal for r=0.5, h=1
  for (int i = 0; i < seg; ++i) {
    const float a0 = 2.0F * PI * i / seg, a1 = 2.0F * PI * (i + 1) / seg;
    const float am = (a0 + a1) * 0.5F;
    const float x0 = r * cosf(a0), z0 = r * sinf(a0);
    const float x1 = r * cosf(a1), z1 = r * sinf(a1);
    // side
    pushVert(verts, cols, o, {0, h, 0}, {nl * cosf(am), ny, nl * sinf(am)});
    pushVert(verts, cols, o, {x1, -h, z1}, {nl * cosf(a1), ny, nl * sinf(a1)});
    pushVert(verts, cols, o, {x0, -h, z0}, {nl * cosf(a0), ny, nl * sinf(a0)});
    // base
    pushVert(verts, cols, o, {0, -h, 0}, {0, -1, 0});
    pushVert(verts, cols, o, {x0, -h, z0}, {0, -1, 0});
    pushVert(verts, cols, o, {x1, -h, z1}, {0, -1, 0});
  }
}

void addModel(std::vector<Vec4>& verts, std::vector<Color>& cols,
              const SceneObjectData& o) {
  if (o.model < 0 || o.model >= MODEL_COUNT) return;
  const ModelData& m = MODELS[o.model];
  for (int i = 0; i < m.vertexCount; ++i) {
    const float* v = m.verts + i * 6;
    pushVert(verts, cols, o, {v[0], v[1], v[2]}, {v[3], v[4], v[5]});
  }
}

}  // namespace

TerrainGame::TerrainGame(Engine* t_engine)
    : engine(t_engine),
      playerX(0.0F),
      playerZ(0.0F),
      yaw(0.0F),
      pitch(0.0F),
      playerY(0.0F),
      playerVelY(0.0F),
      model(M4x4::Identity) {}

TerrainGame::~TerrainGame() {}

void TerrainGame::init() {
  // Engine clipper fix: the default clipMargin (-10.0F) moves the near
  // clipping plane ~10 units away from the camera, cutting away nearby
  // geometry. Clip right in front of the real near plane instead.
  // (read by the clipper during setRenderer below)
  PlanesClipAlgorithm::clipMargin =
      -(engine->renderer.core.getSettings().getNear() + 0.5F);

  stapip.setRenderer(&engine->renderer.core);

  engine->renderer.setClearScreenColor(Color(SKY_R, SKY_G, SKY_B));

  // Player start: the first spawn point in the scene (if any)
  for (int i = 0; i < SCENE_OBJECT_COUNT; ++i) {
    if (SCENE_OBJECTS[i].type == 4) {
      playerX = SCENE_OBJECTS[i].position[0];
      playerZ = SCENE_OBJECTS[i].position[2];
      yaw = SCENE_OBJECTS[i].rotation[1] * PI / 180.0F;
      break;
    }
  }

  updatePlayer();
  buildScene();

  scriptCtx.engine = engine;
  scriptCtx.objects = runtimeObjects.data();
  scriptCtx.objectCount = (int)runtimeObjects.size();
  scriptCtx.skyColor = Color(SKY_R, SKY_G, SKY_B);
  scriptCtx.playerPosition = cameraPosition;
  for (Script* script : getScripts()) script->init(scriptCtx);

  // HUD sprites (see hud_data.gen.hpp)
  const auto& screen = engine->renderer.core.getSettings();
  hudSprites.reserve(HUD_COUNT);
  for (int i = 0; i < HUD_COUNT; ++i) {
    const HudImageData& h = HUD_IMAGES[i];
    Sprite sprite;
    sprite.mode = SpriteMode::MODE_STRETCH;
    sprite.size = Vec2(h.w, h.h);
    sprite.position = Vec2(h.x * screen.getWidth() - h.w * 0.5F,
                           h.y * screen.getHeight() - h.h * 0.5F);
    hudSprites.push_back(sprite);
    auto* texture =
        engine->renderer.getTextureRepository().add(FileUtils::fromCwd(h.path));
    texture->addLink(hudSprites.back().id);
  }
}

void TerrainGame::loop() {
  updatePlayer();

  scriptCtx.playerPosition = cameraPosition;
  for (Script* script : getScripts()) script->update(scriptCtx);
  engine->renderer.setClearScreenColor(scriptCtx.skyColor);

  updateObjectPhysics();

  engine->renderer.beginFrame(CameraInfo3D(&cameraPosition, &cameraLookAt));
  {
    engine->renderer.renderer3D.usePipeline(stapip);
    renderScene();
    for (auto& sprite : hudSprites) engine->renderer.renderer2D.render(sprite);
  }
  engine->renderer.endFrame();
}

void TerrainGame::buildScene() {
  vertices.clear();
  colors.clear();

  generateTerrainGrid();

  infoBag = std::make_unique<StaPipInfoBag>();
  infoBag->model = &model;
  infoBag->shadingType = TyraShadingFlat;
  // CLIP_PRECISE (Project > Preferences): real per-triangle clipping - no
  // holes at screen edges, but costs EE time. The fast path drops whole
  // triangles that extend far beyond the screen, but is much cheaper.
  infoBag->frustumCulling = CLIP_PRECISE ? PipelineInfoBagFrustumCulling_Precise
                                         : PipelineInfoBagFrustumCulling_None;
  infoBag->fullClipChecks = CLIP_PRECISE;

  colorBag = std::make_unique<StaPipColorBag>();
  colorBag->many = colors.data();

  bag = std::make_unique<StaPipBag>();
  bag->info = infoBag.get();
  bag->color = colorBag.get();
  bag->vertices = vertices.data();
  bag->count = static_cast<u32>(vertices.size());
  bag->texture = nullptr;
  bag->lighting = nullptr;

  // Runtime copies of the scene objects - scripts and physics mutate these.
  skyHorizonR = SKY_R, skyHorizonG = SKY_G, skyHorizonB = SKY_B;
  buildSkyDome();

  runtimeObjects.assign(SCENE_OBJECT_COUNT, RuntimeObject());
  objectGeometry.clear();
  objectGeometry.resize(SCENE_OBJECT_COUNT);
  for (int i = 0; i < SCENE_OBJECT_COUNT; ++i) {
    runtimeObjects[i].data = SCENE_OBJECTS[i];
    runtimeObjects[i].visible = SCENE_OBJECTS[i].type != 4;  // spawn = marker
    runtimeObjects[i].dirty = true;
  }
}

void TerrainGame::buildSkyDome() {
  if (!SKY_DOME) return;

  const float diag = TERRAIN_WIDTH > TERRAIN_DEPTH ? TERRAIN_WIDTH : TERRAIN_DEPTH;
  float radius = diag * 1.5F;
  if (radius < 60.0F) radius = 60.0F;
  if (radius > 450.0F) radius = 450.0F;

  const int stacks = 6, slices = 14;
  auto skyAt = [&](float t) {  // t: 0 = horizon, 1 = zenith
    return Color(skyHorizonR + (SKY_TOP_R - skyHorizonR) * t,
                 skyHorizonG + (SKY_TOP_G - skyHorizonG) * t,
                 skyHorizonB + (SKY_TOP_B - skyHorizonB) * t, 128.0F);
  };
  auto domeVert = [&](int stack, int slice) {
    // Start slightly below the horizon so the seam is never visible
    const float lat = -0.06F + (PI * 0.5F + 0.06F) * stack / stacks;
    const float lon = 2.0F * PI * slice / slices;
    return Vec4(radius * cosf(lat) * cosf(lon), radius * sinf(lat),
                radius * cosf(lat) * sinf(lon), 1.0F);
  };

  skyDome.vertices.clear();
  skyDome.colors.clear();
  for (int st = 0; st < stacks; ++st) {
    const float t0 = (float)st / stacks, t1 = (float)(st + 1) / stacks;
    for (int sl = 0; sl < slices; ++sl) {
      const Vec4 v00 = domeVert(st, sl), v01 = domeVert(st, sl + 1);
      const Vec4 v10 = domeVert(st + 1, sl), v11 = domeVert(st + 1, sl + 1);
      skyDome.vertices.push_back(v00);
      skyDome.vertices.push_back(v10);
      skyDome.vertices.push_back(v11);
      skyDome.vertices.push_back(v00);
      skyDome.vertices.push_back(v11);
      skyDome.vertices.push_back(v01);
      skyDome.colors.push_back(skyAt(t0));
      skyDome.colors.push_back(skyAt(t1));
      skyDome.colors.push_back(skyAt(t1));
      skyDome.colors.push_back(skyAt(t0));
      skyDome.colors.push_back(skyAt(t1));
      skyDome.colors.push_back(skyAt(t0));
    }
  }

  skyDome.infoBag = std::make_unique<StaPipInfoBag>();
  skyDome.infoBag->model = &model;
  skyDome.infoBag->shadingType = TyraShadingGouraud;
  // Static geometry crossing the screen edges all the time - needs clipping
  skyDome.infoBag->frustumCulling = PipelineInfoBagFrustumCulling_Precise;
  skyDome.infoBag->fullClipChecks = true;
  skyDome.colorBag = std::make_unique<StaPipColorBag>();
  skyDome.colorBag->many = skyDome.colors.data();
  skyDome.bag = std::make_unique<StaPipBag>();
  skyDome.bag->info = skyDome.infoBag.get();
  skyDome.bag->color = skyDome.colorBag.get();
  skyDome.bag->vertices = skyDome.vertices.data();
  skyDome.bag->count = static_cast<u32>(skyDome.vertices.size());
  skyDome.bag->texture = nullptr;
  skyDome.bag->lighting = nullptr;
}

void TerrainGame::rebuildObjectGeometry(int index) {
  RuntimeObject& o = runtimeObjects[index];
  ObjectGeometry& g = objectGeometry[index];
  o.dirty = false;

  g.vertices.clear();
  g.colors.clear();
  switch (o.data.type) {
    case 1: addSphere(g.vertices, g.colors, o.data); break;
    case 2: addCylinder(g.vertices, g.colors, o.data); break;
    case 3: addCone(g.vertices, g.colors, o.data); break;
    case 4: break;  // spawn point - marker only
    case 5: addModel(g.vertices, g.colors, o.data); break;
    default: addBox(g.vertices, g.colors, o.data); break;
  }
  if (g.vertices.empty()) {
    g.bag.reset();
    return;
  }

  if (!g.bag) {
    g.infoBag = std::make_unique<StaPipInfoBag>();
    g.infoBag->model = &model;
    g.infoBag->shadingType = TyraShadingFlat;
    // Objects can move at runtime, but the engine caches frustum bboxes by
    // the vertex pointer (stale bbox = object culled at its old position).
    // Objects are small, so skip culling/clipping for them entirely;
    // the terrain keeps CLIP_PRECISE.
    g.infoBag->frustumCulling = PipelineInfoBagFrustumCulling_None;
    g.infoBag->fullClipChecks = false;
    g.colorBag = std::make_unique<StaPipColorBag>();
    g.bag = std::make_unique<StaPipBag>();
    g.bag->info = g.infoBag.get();
    g.bag->color = g.colorBag.get();
    g.bag->texture = nullptr;
    g.bag->lighting = nullptr;
  }
  g.colorBag->many = g.colors.data();
  g.bag->vertices = g.vertices.data();
  g.bag->count = static_cast<u32>(g.vertices.size());
}

void TerrainGame::updateObjectPhysics() {
  // GRAVITY is units/s^2; the game runs at 50 FPS
  const float gravityPerFrame = GRAVITY / (50.0F * 50.0F);
  for (RuntimeObject& o : runtimeObjects) {
    if (!o.data.physics) continue;
    const float half = 0.5F * o.data.scale[1];
    if (o.velocityY == 0.0F && o.data.position[1] <= half) continue;  // resting

    o.velocityY -= gravityPerFrame;
    o.data.position[1] += o.velocityY;
    if (o.data.position[1] <= half) {
      o.data.position[1] = half;
      o.velocityY = 0.0F;
    }
    o.dirty = true;
  }
}

void TerrainGame::renderScene() {
  // Scripts changing ctx.skyColor retint the dome horizon
  if (skyDome.bag && (scriptCtx.skyColor.r != skyHorizonR ||
                      scriptCtx.skyColor.g != skyHorizonG ||
                      scriptCtx.skyColor.b != skyHorizonB)) {
    skyHorizonR = scriptCtx.skyColor.r;
    skyHorizonG = scriptCtx.skyColor.g;
    skyHorizonB = scriptCtx.skyColor.b;
    buildSkyDome();
  }
  if (skyDome.bag) stapip.core.render(skyDome.bag.get());
  stapip.core.render(bag.get());
  for (int i = 0; i < (int)runtimeObjects.size(); ++i) {
    if (runtimeObjects[i].dirty) rebuildObjectGeometry(i);
    if (runtimeObjects[i].visible && objectGeometry[i].bag)
      stapip.core.render(objectGeometry[i].bag.get());
  }
}

void TerrainGame::generateTerrainGrid() {
  // Cap the amount of quads so big terrains stay PS2-friendly.
  // Cell size grows with terrain size instead.
  const u32 maxCells = (u32)TERRAIN_MAX_CELLS;
  const u32 cellsX = TERRAIN_WIDTH > maxCells ? maxCells : (u32)TERRAIN_WIDTH;
  const u32 cellsZ = TERRAIN_DEPTH > maxCells ? maxCells : (u32)TERRAIN_DEPTH;
  const float stepX = TERRAIN_WIDTH / cellsX;
  const float stepZ = TERRAIN_DEPTH / cellsZ;
  const float startX = -TERRAIN_WIDTH * 0.5F;
  const float startZ = -TERRAIN_DEPTH * 0.5F;

  // Two greens in a checker pattern, so the grid is visible.
  // PS2 colors: RGB 0-255, alpha 0-128. Lit by the directional light (up normal).
  const float sUp = shadeOf({0.0F, 1.0F, 0.0F});
  const Color colorA(96.0F * sUp, 160.0F * sUp, 72.0F * sUp, 128.0F);
  const Color colorB(74.0F * sUp, 128.0F * sUp, 56.0F * sUp, 128.0F);

  for (u32 z = 0; z < cellsZ; ++z) {
    for (u32 x = 0; x < cellsX; ++x) {
      const float x0 = startX + x * stepX;
      const float x1 = x0 + stepX;
      const float z0 = startZ + z * stepZ;
      const float z1 = z0 + stepZ;
      const Color& c = ((x + z) % 2 == 0) ? colorA : colorB;

      vertices.push_back(Vec4(x0, 0.0F, z0, 1.0F));
      vertices.push_back(Vec4(x1, 0.0F, z0, 1.0F));
      vertices.push_back(Vec4(x0, 0.0F, z1, 1.0F));
      vertices.push_back(Vec4(x1, 0.0F, z0, 1.0F));
      vertices.push_back(Vec4(x1, 0.0F, z1, 1.0F));
      vertices.push_back(Vec4(x0, 0.0F, z1, 1.0F));

      for (int i = 0; i < 6; ++i) colors.push_back(c);
    }
  }
}

namespace {

float axisValue(const u8& raw) {
  const float v = (raw - 128.0F) / 128.0F;
  return (v > -0.20F && v < 0.20F) ? 0.0F : v;  // deadzone
}

}  // namespace

void TerrainGame::updatePlayer() {
  const auto& leftJoy = engine->pad.getLeftJoyPad();
  const auto& rightJoy = engine->pad.getRightJoyPad();

  // Right stick: look around (stick right = turn right)
  yaw -= axisValue(rightJoy.h) * 0.05F * LOOK_SPEED;
  pitch -= axisValue(rightJoy.v) * 0.035F * LOOK_SPEED;
  if (pitch > 1.2F) pitch = 1.2F;
  if (pitch < -1.2F) pitch = -1.2F;

  // Left stick: walk. Forward is where the camera looks (flat).
  const float fx = sinf(yaw);
  const float fz = cosf(yaw);
  const float forward = -axisValue(leftJoy.v);
  const float strafe = axisValue(leftJoy.h);
  float nextX = playerX + (fx * forward - fz * strafe) * WALK_SPEED;
  float nextZ = playerZ + (fz * forward + fx * strafe) * WALK_SPEED;

  // Keep the player on the terrain
  const float limX = TERRAIN_WIDTH * 0.5F - 1.0F;
  const float limZ = TERRAIN_DEPTH * 0.5F - 1.0F;
  if (nextX > limX) nextX = limX;
  if (nextX < -limX) nextX = -limX;
  if (nextZ > limZ) nextZ = limZ;
  if (nextZ < -limZ) nextZ = -limZ;

  // Collision with scene objects (XZ, boxes expanded by the player radius)
  // + standing on top of them. Player can step ~0.5 units up.
  const float playerRadius = 0.35F;
  float ground = 0.0F;
  for (const RuntimeObject& o : runtimeObjects) {
    if (!o.visible || o.data.type == 4) continue;
    const float ox = o.data.position[0];
    const float oz = o.data.position[2];
    const float hx = 0.5F * o.data.scale[0] + playerRadius;
    const float hz = 0.5F * o.data.scale[2] + playerRadius;
    const float top = o.data.position[1] + 0.5F * o.data.scale[1];
    const float bottom = o.data.position[1] - 0.5F * o.data.scale[1];

    const bool nextInside =
        nextX > ox - hx && nextX < ox + hx && nextZ > oz - hz && nextZ < oz + hz;
    if (!nextInside) continue;

    if (playerY + 0.5F >= top) {
      // Low enough to walk onto - candidate floor
      if (top > ground) ground = top;
    } else if (playerY < top && playerY + EYE_HEIGHT > bottom) {
      // Blocked - cancel the axes that entered the box this frame
      const bool wasInsideX = playerX > ox - hx && playerX < ox + hx;
      const bool wasInsideZ = playerZ > oz - hz && playerZ < oz + hz;
      if (!wasInsideX) nextX = playerX;
      if (!wasInsideZ) nextZ = playerZ;
      if (wasInsideX && wasInsideZ) {
        nextX = playerX;
        nextZ = playerZ;
      }
    }
  }
  playerX = nextX;
  playerZ = nextZ;

  // Gravity & jumping (X). GRAVITY: units/s^2, JUMP_SPEED: units/s, 50 FPS.
  playerVelY -= GRAVITY / (50.0F * 50.0F);
  playerY += playerVelY;
  if (playerY <= ground) {
    playerY = ground;
    playerVelY = 0.0F;
    if (engine->pad.getClicked().Cross) playerVelY = JUMP_SPEED / 50.0F;
  }

  const float eyeY = playerY + EYE_HEIGHT;
  cameraPosition = Vec4(playerX, eyeY, playerZ);
  cameraLookAt = Vec4(playerX + fx * cosf(pitch), eyeY + sinf(pitch),
                      playerZ + fz * cosf(pitch));
}

}  // namespace Script_demo
