// Generated by TyraX. Do not edit - regenerated on every build.
// Live Logic hooks, compiled out: this is a release build or the "Live Logic"
// preference is off, so flow graphs run only as the C++ they were compiled to
// and `patched()` is a compile-time false. See docs/live-logic.md.
#pragma once

#include "scripts/script.hpp"

namespace Video_modes {
namespace livelogic {

inline void tick(ScriptContext&) {}
inline bool patched(int, int) { return false; }

}  // namespace livelogic
}  // namespace Video_modes
