// Generated by TyraX (src/vugen.cpp). Do not edit - regenerate from
// the C++ description with: tyrax-editor --vu-emit <dir>
//
// The unpack layout below and the microprogram's addressing come from
// ONE description, so they cannot drift apart - which is the whole
// reason this file is generated (docs/vu-framework.md).

#include "debug/debug.hpp"
#include "renderer/3d/pipeline/static/core/programs/as_is/stapip_as_is_tce_vu1_program.hpp"

extern u32 StaPipVU1AsIs_TCE_CodeStart __attribute__((section(".vudata")));
extern u32 StaPipVU1AsIs_TCE_CodeEnd __attribute__((section(".vudata")));

namespace Tyra {

StaPipAsIsTCEVU1Program::StaPipAsIsTCEVU1Program()
    : StaPipVU1Program(StaPipAsIsTextureEnv, &StaPipVU1AsIs_TCE_CodeStart,
                       &StaPipVU1AsIs_TCE_CodeEnd,
                       ((u64)GIF_REG_ST) << 0 | ((u64)GIF_REG_RGBAQ) << 4 |
                           ((u64)GIF_REG_XYZF2) << 8,
                       3, 3) {}

StaPipAsIsTCEVU1Program::~StaPipAsIsTCEVU1Program() {}

std::string StaPipAsIsTCEVU1Program::getStringName() const {
  return std::string("StaPip - As is - TCE");
}

void StaPipAsIsTCEVU1Program::addProgramQBufferDataToPacket(
    packet2_t* packet, StaPipQBuffer* qbuffer) const {
  u32 addr = VU1_STAPIP_VERT_DATA_ADDR;

  // Vertices
  packet2_utils_vu_add_unpack_data(packet, addr, qbuffer->vertices,
                                   qbuffer->size, true);

  // Normals - they ride in the ST slot (StaPipTextureBag)
  addr += qbuffer->size;
  packet2_utils_vu_add_unpack_data(packet, addr, qbuffer->sts,
                                   qbuffer->size, true);

  // Colors - absent when the mesh draws in a single colour
  if (qbuffer->bag->color->single == nullptr) {
    addr += qbuffer->size;
    packet2_utils_vu_add_unpack_data(packet, addr, qbuffer->colors,
                                     qbuffer->size, true);
  }
}

}  // namespace Tyra
