# Build ONE arm of the road lateral-budget A/B (docs/roads.md, "The lateral
# budget"; docs/ee-submission-rearchitecture.md, "Order of work" item 5).
#
# THE ARM IS THE EDITOR, not an engine macro. This change lives in the editor's
# codegen (src/roadgen.cpp and its buildRoads twin in src/templates.cpp), so
# the two arms are two EDITOR binaries generating the same example, and the
# engine, the toolchain and the project are identical between them.
#
# Both editors must be built FROM THIS WORKTREE. An editor binary sitting in
# build/ is not "the editor at the tree's commit" - it can be older than HEAD
# and nothing in a build log says so, and `--refresh-gen` will faithfully
# regenerate a fixture with a stale baker. That is what produced round one's
# 72-run control (see ../ee-probes-2026-09-16/README.md, "Fixture identity").
# Build them like this, and record both hashes:
#
#   ./build.ps1                                  # -> candidate editor
#   cp build/tyrax-editor.exe <somewhere>/cand.exe
#   git checkout HEAD~1 -- src/roadgen.cpp src/roadgen.hpp src/templates.cpp
#   ./build.ps1                                  # -> control editor
#   cp build/tyrax-editor.exe <somewhere>/ctl.exe
#   git checkout HEAD -- src/roadgen.cpp src/roadgen.hpp src/templates.cpp
#
# The fixture is regenerated by the arm's OWN editor before the instrumenter
# runs, then compiled with tools/toolchain/native-build.ps1 DIRECTLY - an
# editor --build would regenerate the instrumentation away.
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$Arm,
    [Parameter(Mandatory = $true)][string]$Editor,
    # `quiet-debug`, not `debug`: the live tools' host: pollers cost 6.44 ms of
    # `work` and produce `update` outliers no arm's code can explain.
    [ValidateSet('debug', 'quiet-debug', 'release')][string]$Profile = 'quiet-debug',
    # The authored LOD distances, which the district ships at ZERO. The earlier
    # trials (model 64, model 64 / terrain 96) were rejected because they
    # repeated 25 / 25 / 50 / 50 displayed FPS - measured while the EE was the
    # limiter and the frame was pinned to a vsync rung, where no reduction in
    # VU1 work could possibly show. These arms re-run them against `work_ms`
    # and the triangle counter instead.
    [float]$MeshLod = 0,
    [float]$TerrainLod = 0,
    [string]$Root = 'D:/tyra-roadlod-0916'
)
$ErrorActionPreference = 'Stop'

$worktree = (Resolve-Path (Join-Path $PSScriptRoot '../../../..')).Path
$example  = Join-Path $worktree 'examples/vehicle-playground'
$cache    = Join-Path $env:LOCALAPPDATA 'tyra-editor/native-build/roadlod-0916'
$toolchain= Join-Path $env:LOCALAPPDATA 'tyra-editor/toolchain/ps2dev'
$fixture  = Join-Path $Root "arms/$Arm"

if (!(Test-Path -LiteralPath $Editor)) { throw "No editor at $Editor" }
if (Test-Path -LiteralPath $fixture) { throw "Archive $fixture before re-running this arm" }
New-Item -ItemType Directory -Force -Path (Join-Path $Root 'arms') | Out-Null

# --- 1. fixture from the example, with the baked tree copied in -----------
& python (Join-Path $example 'authoring/benchmark-district.py') $fixture --profile $Profile `
    --mesh-lod $MeshLod --terrain-lod $TerrainLod
if ($LASTEXITCODE -ne 0) { throw 'benchmark-district.py failed' }
# The baked asset tree is held CONSTANT across the arms - baked once with one
# editor and copied into both - so the only thing that differs between them is
# the generated road geometry. A fresh worktree has no .res-baked at all (it is
# a build artefact), so bake it first with either editor:
#   tyrax-editor --build examples/vehicle-playground
# and then restore the example's committed generated sources, which that run
# also rewrites:
#   git checkout -- examples/vehicle-playground/inc examples/vehicle-playground/res examples/vehicle-playground/src
if (!(Test-Path -LiteralPath (Join-Path $example '.res-baked'))) {
    throw "No .res-baked in $example - see the note above this line"
}
Copy-Item -Recurse -Force (Join-Path $example '.res-baked') (Join-Path $fixture '.res-baked')
New-Item -ItemType Directory -Force -Path (Join-Path $fixture 'bin') | Out-Null
foreach ($d in 'aoatlas', 'aomap') {
    $src = Join-Path $example "bin/$d"
    if (Test-Path -LiteralPath $src) { Copy-Item -Recurse -Force $src (Join-Path $fixture "bin/$d") }
}

# --- 2. regenerate with THIS ARM'S editor, THEN instrument ----------------
& $Editor --refresh-gen $fixture
if ($LASTEXITCODE -ne 0) { throw '--refresh-gen failed' }
& python (Join-Path $example 'authoring/instrument-frame-cost.py') $fixture
if ($LASTEXITCODE -ne 0) { throw 'instrument-frame-cost.py failed' }

# --- 3. FIXTURE IDENTITY, before anything is compiled --------------------
# The baked constants, read out of the generated source. A capture hash is a
# PICTURE check and never a fixture check: changing how a surface is cut into
# runs does not change which pixels it covers, so a fixture built by the wrong
# editor still hashes to the expected frame. These lines do catch it - and
# THIS arm's ROADSTRIP is expected to MOVE, which is the point of the round.
$gen = Get-ChildItem -LiteralPath (Join-Path $fixture 'src') -Recurse -Filter '*.cpp' |
       Select-String -Pattern 'stripRun\s*=\s*(\d+)u' -AllMatches
$runs = ($gen.Matches | ForEach-Object { $_.Groups[1].Value } | Sort-Object -Unique) -join ','
Write-Output "stripRun in generated source: $runs (expect 75 at the branch tip)"

# --- 4. compile with the native toolchain directly -----------------------
& (Join-Path $worktree 'tools/toolchain/native-build.ps1') `
    -Project $fixture -Engine (Join-Path $worktree 'vendor/tyra') `
    -Cache $cache -Toolchain $toolchain
if ($LASTEXITCODE -ne 0) { throw 'native-build failed' }

$elf = Join-Path $fixture 'bin/vehicle-playground.elf'
if (!(Test-Path -LiteralPath $elf)) { throw 'No ELF produced' }
$hash = (Get-FileHash -LiteralPath $elf -Algorithm SHA256).Hash
[pscustomobject]@{
    arm = $Arm; profile = $Profile; stripRun = $runs
    meshLod = $MeshLod; terrainLod = $TerrainLod
    elfSha256 = $hash; built = (Get-Date).ToString('o')
    editor = $Editor
    editorSha256 = (Get-FileHash -LiteralPath $Editor -Algorithm SHA256).Hash
    commit = (& git -C $worktree rev-parse HEAD)
} | ConvertTo-Json | Set-Content -LiteralPath (Join-Path $fixture 'ARM.json')
Write-Output "ELF sha256 $hash"
