// Generated by tyra-editor. Do not edit - regenerated on every build.
#pragma once

namespace Cutscene_demo {

struct HudImageData {
  const char* path;  // relative to the game binary (res/ is copied there)
  float x, y;        // normalized screen position, center anchor
  float w, h;        // size in pixels
};

constexpr int HUD_COUNT = 0;
inline const HudImageData HUD_IMAGES[HUD_COUNT > 0 ? HUD_COUNT : 1] = {
    {"", 0, 0, 0, 0},
};

// Screen-stack positions of the full-screen effects (Tools > UI
// Editor). The effect applies right before the HUD sprite at this
// index, so lower-index sprites get it and higher ones draw crisp on
// top. -1 = at end of frame, over everything including menus. Bloom
// carries color grading; film grain is placed independently.
constexpr int HUD_BLOOM_LAYER = -1;
constexpr int HUD_GRAIN_LAYER = -1;

}  // namespace Cutscene_demo
