// Generated by TyraX. Do not edit - regenerated on every build.
#pragma once

namespace Nav_ai {

struct SceneObjectData {
  int type;  // 0=box 1=sphere 2=cylinder 3=cone 4=spawn-point 5=model
             // 6=player 7=emitter 8=sound 9=point-light 10=save-point
             // 11=empty (pure transform, no geometry/collision)
             // 12=plane 13=decal 14=camera (cutscene shot marker)
             // 15=mirror (glass quad; reflections via MIRRORS below)
             // 16=portal (linked surface; through-view + teleport
             //    via PORTALS below)
  float position[3];
  float rotation[3];  // degrees
  float scale[3];
  float color[3];  // 0..1
  int physics;  // 1 = rigid body: gravity, bounces, tumbles, collides
  float physMass;     // relative mass (impulse exchange, player push)
  float physBounce;   // restitution 0..1: 0 = thud, 1 = superball
  float physFriction; // ground drag 0..1: 0 = ice, 1 = sticky
  int physTumble;     // 1 = ground contact converts slide into roll
  float physSleep;    // seconds of near-rest before the body sleeps
  int model;    // index into MODEL_PATHS / gameModels, -1 = none
  int material; // primitives: index into MATERIAL_PATHS, -1 = plain color
  int usable;   // 1 = shows the USE prompt up close (see controls.hpp)
  int pickable; // 1 = BTN_USE picks it up and carries it in front of
                // the camera; BTN_USE again drops it
  int pickThrow; // 1 = a carried object launches with BTN_THROW
  int emitKind;   // emitters: 0 fire, 1 smoke, 2 fog, 3 sparks, 4 rain,
                  // 5 custom (physics below)
  int emitCount;  // emitters: particle pool size (density)
  float emitSize; // emitters: base particle size
  int emitEnabled; // emitters: 0 = starts disabled (Show Object enables)
  int emitFollow;  // emitters: 1 = position is an offset from the player
  float emitSpeed;   // custom: emission speed along rotated +Y, units/s
  float emitSpread;  // custom: cone half-angle, degrees
  float emitGravity; // custom: units/s^2, negative = rises
  float emitWeight;  // custom: air drag ~ 1/weight
  float emitLife;    // custom: particle lifetime, seconds
  float emitGrow;    // custom: size multiplier at end of life
  float emitOpacity; // custom: base alpha 0..1
  int emitDieGround; // custom: 1 = particle dies on the terrain
  int snd;        // sound emitters: index into SND_PATHS, -1 = none
  int sndAuto;    // sound emitters: 1 = plays while in range
  float sndRange;    // sound emitters: audible distance
  float sndInterval; // sound emitters: retrigger period (s), 0 = loop
  int sndOnPlayer;   // sound emitters: 1 = centered on the player
                     // (plain stereo, full volume, no distance/pan)
  float lightBright; // point lights (type 9): baked intensity
  float lightRadius; // point lights (type 9): falloff radius
  int saveState;  // 1 = position/color/visibility persisted in saves
  int collision;  // 0 = box (models: mesh AABB), 1 = mesh, 2 = none
  float drawDistance;  // not drawn farther than this from the camera;
                       // 0 = unlimited (collision/logic always run)
  int reflected;  // 1 = rendered into the dynamic ("@sky") env map
  int animModel;  // animated models: index into ANIM_MODEL_PATHS, -1 = none
  const char* animClip;  // animated models: starting clip ("" = first)
  int animAutoplay;      // animated models: 1 = play at scene start
  int animLoop;          // animated models: 1 = starting clip loops
  float animSpeed;       // animated models: playback speed multiplier
  float animLod;  // per-object animation-LOD distance override:
                  // -1 = project ANIM_LOD_DISTANCE, 0 = off, >0 = custom
  float meshLod;  // per-object mesh-LOD distance override (same coding)
  float modelYaw; // content-forward correction (deg around model Y),
                  // between scale and rotation - X-forward-authored models
                  // set +-90; runtime facing (faceYaw/AI) stays pure
  int primDetail;        // segments (curved) or box subdivisions/edge
  int layer;      // streaming layer (SCENE_LAYER_* tables), -1 = none:
                  // always resident, never streamed out
  int batchStatic; // 1 = may merge into a combined static batch bag
                   // (build-time verdict: non-moving primitive with
                   // no physics/logic/graph refs/save-state/layer)
};

constexpr int SCENE_COUNT = 1;

// scene "main"
constexpr SceneObjectData SCENE_0_OBJECTS[7] = {
    {6, {24.0F, 0.0F, 24.0F}, {0.0F, 0.0F, 0.0F}, {1.0F, 1.0F, 1.0F}, {0.15F, 0.9F, 0.9F}, 0, 1.0F, 0.35F, 0.5F, 1, 3.0F, -1, -1, 0, 0, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, 0, -1, "", 1, 1, 1.0F, -1.0F, -1.0F, 0.0F, 16, -1, 0},  // player-1
    {0, {10.0F, 0.5F, 10.0F}, {0.0F, 0.0F, 0.0F}, {1.0F, 1.0F, 1.0F}, {0.9F, 0.2F, 0.2F}, 0, 1.0F, 0.35F, 0.5F, 1, 3.0F, -1, -1, 0, 0, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 2, 0.0F, 0, -1, "", 1, 1, 1.0F, -1.0F, -1.0F, 0.0F, 1, -1, 0},  // guard
    {0, {18.0F, 0.35F, 18.0F}, {0.0F, 0.0F, 0.0F}, {0.7F, 0.7F, 0.7F}, {0.95F, 0.85F, 0.2F}, 0, 1.0F, 0.35F, 0.5F, 1, 3.0F, -1, -1, 0, 0, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 2, 0.0F, 0, -1, "", 1, 1, 1.0F, -1.0F, -1.0F, 0.0F, 1, -1, 0},  // rabbit
    {11, {-20.0F, 0.0F, -20.0F}, {0.0F, 0.0F, 0.0F}, {1.0F, 1.0F, 1.0F}, {0.3F, 0.9F, 0.4F}, 0, 1.0F, 0.35F, 0.5F, 1, 3.0F, -1, -1, 0, 0, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, 0, -1, "", 1, 1, 1.0F, -1.0F, -1.0F, 0.0F, 16, -1, 0},  // wp1
    {11, {0.0F, 0.0F, -14.0F}, {0.0F, 0.0F, 0.0F}, {1.0F, 1.0F, 1.0F}, {0.3F, 0.9F, 0.4F}, 0, 1.0F, 0.35F, 0.5F, 1, 3.0F, -1, -1, 0, 0, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, 0, -1, "", 1, 1, 1.0F, -1.0F, -1.0F, 0.0F, 16, -1, 0},  // wp2
    {11, {0.0F, 0.0F, 20.0F}, {0.0F, 0.0F, 0.0F}, {1.0F, 1.0F, 1.0F}, {0.3F, 0.9F, 0.4F}, 0, 1.0F, 0.35F, 0.5F, 1, 3.0F, -1, -1, 0, 0, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, 0, -1, "", 1, 1, 1.0F, -1.0F, -1.0F, 0.0F, 16, -1, 0},  // wp3
    {0, {0.0F, 1.0F, -8.0F}, {0.0F, 0.0F, 0.0F}, {16.0F, 2.0F, 1.0F}, {0.45F, 0.45F, 0.55F}, 0, 1.0F, 0.35F, 0.5F, 1, 3.0F, -1, -1, 0, 0, 0, 0, 24, 0.5F, 1, 0, 3.0F, 20.0F, 9.8F, 1.0F, 1.5F, 1.0F, 0.6F, 0, -1, 1, 15.0F, 0.0F, 0, 1.0F, 8.0F, 0, 0, 0.0F, 0, -1, "", 1, 1, 1.0F, -1.0F, -1.0F, 0.0F, 1, -1, 1},  // wall
};

constexpr int SCENE_OBJECT_COUNTS[SCENE_COUNT] = {7};
inline const SceneObjectData* SCENE_OBJECT_TABLES[SCENE_COUNT] = {SCENE_0_OBJECTS};

constexpr unsigned long long SCENE_0_OBJECT_ID_HASHES[7] = {0x8ab5915f8af04b8bULL, 0xd236913880e4efffULL, 0xd232913880e10728ULL, 0xd230913880e08451ULL, 0xd22c913880dc9b7aULL, 0xd228913880d8b2a3ULL, 0xd224913880d4c9ccULL};
inline const unsigned long long* SCENE_OBJECT_ID_TABLES[SCENE_COUNT] = {SCENE_0_OBJECT_ID_HASHES};

constexpr int SCENE_LAYER_COUNTS[SCENE_COUNT] = {0};
constexpr int SCENE_MAX_LAYERS = 1;
constexpr bool SCENE_LAYER_STARTS[SCENE_COUNT][SCENE_MAX_LAYERS] = {{true}};
constexpr float SCENE_LAYER_STREAM_XS[SCENE_COUNT][SCENE_MAX_LAYERS] = {{0.0F}};
constexpr float SCENE_LAYER_STREAM_ZS[SCENE_COUNT][SCENE_MAX_LAYERS] = {{0.0F}};
constexpr float SCENE_LAYER_STREAM_RADII[SCENE_COUNT][SCENE_MAX_LAYERS] = {{0.0F}};

// Mirrors (type 15): each entry re-draws its target objects
// reflected across the mirror plane (renderMirrors in the game
// cpp). Targets index the mirror's own scene object table.
struct MirrorData {
  int scene;          // scene index
  int object;         // the mirror's index in its scene table
  float opacity;      // glass alpha 0..1 (tint = object color)
  int reflectPlayer;  // 1 = also reflect the third-person avatar
  int firstTarget;    // first entry in MIRROR_TARGETS
  int targetCount;
  int raytraced;      // 1 = VU0-raytraced sphere proxies (PoC)
  int rtSize;         // traced image edge, texels (32..512)
};
constexpr int MIRROR_COUNT = 0;
constexpr MirrorData MIRRORS[1] = {
    {0, -1, 0.0F, 0, 0, 0, 0, 64}
};
constexpr int MIRROR_TARGETS[1] = {-1};

// Raytraced-mirror model proxies: decimated triangle lists
// in MODEL LOCAL space, 15 floats per triangle (pos + uv
// per corner). The game transforms them by the target's
// live transform each frame (renderRtMirror).
struct RtProxyData {
  int scene;       // scene index
  int mirror;      // the mirror's index in its scene table
  int target;      // the model object's index
  int part;        // model part whose texture shades hits
  int firstFloat;  // offset into RT_PROXY_VERTS
  int triCount;
};
constexpr int RT_PROXY_COUNT = 0;
constexpr RtProxyData RT_PROXIES[1] = {
    {0, -1, -1, 0, 0, 0}
};
constexpr float RT_PROXY_VERTS[1] = {
  0.0F
};
// Animated-model proxies: fixed VERTEX indices (3 per
// triangle, a connected medoid-decimated coarse mesh) into
// the part's skinned buffers - the game reads the LIVE
// skinned vertices (and their resident STs) at these
// indices every frame, so the reflection plays the clip
// (renderRtMirror).
struct RtAnimProxyData {
  int scene;      // scene index
  int mirror;     // the mirror's index in its scene table
  int target;     // the animated model object's index
  int part;       // animParts index (texture + skinned mesh)
  int firstIdx;   // offset into RT_ANIM_PROXY_TRIS (3/tri)
  int triCount;
};
constexpr int RT_ANIM_PROXY_COUNT = 0;
constexpr RtAnimProxyData RT_ANIM_PROXIES[1] = {
    {0, -1, -1, 0, 0, 0}
};
constexpr int RT_ANIM_PROXY_TRIS[1] = {
  0
};

// Camera texture feeds: one active feed camera per scene.
struct CamFeedData {
  int scene;        // scene index
  int camera;       // the feed camera's scene-table index
  float fov;        // baked - the fov does not animate
  int showTerrain;  // 1 = sky + terrain under the view list
  int firstView;    // first entry in CAM_FEED_VIEWS
  int viewCount;
};
constexpr int CAM_FEED_COUNT = 0;
constexpr CamFeedData CAM_FEEDS[1] = {
    {0, -1, 60.0F, 1, 0, 0}
};
constexpr int CAM_FEED_VIEWS[1] = {-1};
// Surfaces showing a live feed: kind 0 = the scene's camera
// feed, kind 1 = a raytraced mirror's traced image (src =
// the mirror's scene-table index).
struct ObjectFeedData {
  int scene;
  int object;
  int kind;
  int src;
};
constexpr int OBJECT_FEED_COUNT = 0;
constexpr ObjectFeedData OBJECT_FEEDS[1] = {
    {0, -1, 0, -1}
};

// Portals (type 16): each entry links a surface to its target
// portal. The game renders the through-view of the nearest one
// into a VRAM target every frame and teleports whatever crosses
// the surface (renderPortalView/renderPortals/updatePortals in
// the game cpp). Indices index the portal's own scene table.
struct PortalData {
  int scene;            // scene index
  int object;           // the portal's index in its scene table
  int target;           // linked portal's index, -1 = inactive
  int showTerrain;      // 1 = sky dome + terrain in the view
  int teleportObjects;  // 1 = physics objects teleport too
  int viewAll;          // 1 = EVERY object in the view
                        //     (experimental; list ignored)
  int firstView;        // first entry in PORTAL_VIEW_OBJECTS
  int viewCount;
};
constexpr int PORTAL_COUNT = 0;
constexpr PortalData PORTALS[1] = {
    {0, -1, -1, 0, 0, 0, 0, 0}
};
constexpr int PORTAL_VIEW_OBJECTS[1] = {-1};

constexpr int SND_COUNT = 0;
inline const char* SND_PATHS[1] = {""};

constexpr int PLAYER_INDEXES[SCENE_COUNT] = {0};
constexpr int PLAYER_MODES[SCENE_COUNT] = {0};
constexpr float PLAYER_WALK_SPEEDS[SCENE_COUNT] = {0.4F};
constexpr float PLAYER_LOOK_SPEEDS[SCENE_COUNT] = {1.0F};
constexpr float PLAYER_EYE_HEIGHTS[SCENE_COUNT] = {1.8F};
constexpr float PLAYER_JUMP_SPEEDS[SCENE_COUNT] = {4.5F};
constexpr bool PLAYER_CAN_JUMPS[SCENE_COUNT] = {true};
constexpr float PLAYER_RUN_THRESHOLDS[SCENE_COUNT] = {0.55F};
constexpr float PLAYER_CAM_DISTS[SCENE_COUNT] = {6.0F};
constexpr float PLAYER_CAM_HEIGHTS[SCENE_COUNT] = {1.6F};
constexpr float PLAYER_CAM_SHOULDERS[SCENE_COUNT] = {0.0F};
constexpr float PLAYER_TURN_RATES[SCENE_COUNT] = {0.25F};
constexpr int PLAYER_CAM_STYLES[SCENE_COUNT] = {0};
constexpr float PLAYER_CAM_PITCHES[SCENE_COUNT] = {0.959931F};
constexpr float PLAYER_CAM_YAWS[SCENE_COUNT] = {0.785398F};
constexpr bool PLAYER_CAM_YAW_ROTATES[SCENE_COUNT] = {false};
constexpr const char* PLAYER_IDLE_CLIPS[SCENE_COUNT] = {""};
constexpr const char* PLAYER_WALK_CLIPS[SCENE_COUNT] = {""};
constexpr const char* PLAYER_RUN_CLIPS[SCENE_COUNT] = {""};
constexpr const char* PLAYER_JUMP_CLIPS[SCENE_COUNT] = {""};
constexpr int PLAYER2_INDEXES[SCENE_COUNT] = {-1};
constexpr int PLAYER2_MODES[SCENE_COUNT] = {0};
constexpr float PLAYER2_WALK_SPEEDS[SCENE_COUNT] = {0.4F};
constexpr float PLAYER2_LOOK_SPEEDS[SCENE_COUNT] = {1.0F};
constexpr float PLAYER2_EYE_HEIGHTS[SCENE_COUNT] = {1.8F};
constexpr float PLAYER2_JUMP_SPEEDS[SCENE_COUNT] = {4.5F};
constexpr bool PLAYER2_CAN_JUMPS[SCENE_COUNT] = {true};
constexpr float PLAYER2_RUN_THRESHOLDS[SCENE_COUNT] = {0.55F};
constexpr float PLAYER2_CAM_DISTS[SCENE_COUNT] = {6.0F};
constexpr float PLAYER2_CAM_HEIGHTS[SCENE_COUNT] = {1.6F};
constexpr float PLAYER2_CAM_SHOULDERS[SCENE_COUNT] = {0.0F};
constexpr float PLAYER2_TURN_RATES[SCENE_COUNT] = {0.25F};
constexpr int PLAYER2_CAM_STYLES[SCENE_COUNT] = {0};
constexpr float PLAYER2_CAM_PITCHES[SCENE_COUNT] = {0.959931F};
constexpr float PLAYER2_CAM_YAWS[SCENE_COUNT] = {0.785398F};
constexpr bool PLAYER2_CAM_YAW_ROTATES[SCENE_COUNT] = {false};
constexpr const char* PLAYER2_IDLE_CLIPS[SCENE_COUNT] = {""};
constexpr const char* PLAYER2_WALK_CLIPS[SCENE_COUNT] = {""};
constexpr const char* PLAYER2_RUN_CLIPS[SCENE_COUNT] = {""};
constexpr const char* PLAYER2_JUMP_CLIPS[SCENE_COUNT] = {""};

constexpr float TERRAIN_WIDTHS[SCENE_COUNT] = {64.0F};
constexpr float TERRAIN_DEPTHS[SCENE_COUNT] = {64.0F};
constexpr float SCENE_LIGHT_XS[SCENE_COUNT] = {0.369465F};
constexpr float SCENE_LIGHT_YS[SCENE_COUNT] = {0.818814F};
constexpr float SCENE_LIGHT_ZS[SCENE_COUNT] = {0.439363F};
constexpr float SCENE_AMBIENTS[SCENE_COUNT] = {0.55F};
constexpr float SCENE_DIFFUSES[SCENE_COUNT] = {0.45F};
constexpr float SCENE_LIGHT_COL_RS[SCENE_COUNT] = {1.0F};
constexpr float SCENE_LIGHT_COL_GS[SCENE_COUNT] = {1.0F};
constexpr float SCENE_LIGHT_COL_BS[SCENE_COUNT] = {1.0F};
constexpr float SCENE_BRIGHTNESSES[SCENE_COUNT] = {1.0F};
constexpr bool SCENE_AO_ENABLEDS[SCENE_COUNT] = {false};
constexpr float SCENE_AO_STRENGTHS[SCENE_COUNT] = {0.55F};
constexpr float SCENE_AO_RADII[SCENE_COUNT] = {2.5F};
constexpr bool CLIP_PRECISES[SCENE_COUNT] = {true};
constexpr bool CLIP_VU1S[SCENE_COUNT] = {false};
constexpr float SKY_RS[SCENE_COUNT] = {63.75F};
constexpr float SKY_GS[SCENE_COUNT] = {140.25F};
constexpr float SKY_BS[SCENE_COUNT] = {198.9F};
constexpr bool SKY_DOMES[SCENE_COUNT] = {true};
constexpr float SKY_ZENITH_EXPS[SCENE_COUNT] = {1.0F};
constexpr float SKY_TOP_RS[SCENE_COUNT] = {20.4F};
constexpr float SKY_TOP_GS[SCENE_COUNT] = {76.5F};
constexpr float SKY_TOP_BS[SCENE_COUNT] = {165.75F};
constexpr int POSTFX_BLOOMS[SCENE_COUNT] = {0};
constexpr int POSTFX_GRAINS[SCENE_COUNT] = {0};
constexpr int POSTFX_DOFS[SCENE_COUNT] = {0};
constexpr float POSTFX_DOF_FOCUSES[SCENE_COUNT] = {20.0F};
constexpr float POSTFX_DOF_RANGES[SCENE_COUNT] = {15.0F};
constexpr bool FOG_ENABLEDS[SCENE_COUNT] = {false};
constexpr float FOG_RS[SCENE_COUNT] = {127.5F};
constexpr float FOG_GS[SCENE_COUNT] = {127.5F};
constexpr float FOG_BS[SCENE_COUNT] = {140.25F};
constexpr float FOG_STARTS[SCENE_COUNT] = {15.0F};
constexpr float FOG_ENDS[SCENE_COUNT] = {120.0F};
constexpr bool FLASHLIGHT_ENABLEDS[SCENE_COUNT] = {false};
constexpr float FLASHLIGHT_RS[SCENE_COUNT] = {96.0F};
constexpr float FLASHLIGHT_GS[SCENE_COUNT] = {96.0F};
constexpr float FLASHLIGHT_BS[SCENE_COUNT] = {79.36F};
constexpr float FLASHLIGHT_RANGES[SCENE_COUNT] = {30.0F};
constexpr float FLASHLIGHT_ANGLES[SCENE_COUNT] = {20.0F};
constexpr bool HIGHLIGHT_USABLES[SCENE_COUNT] = {false};
constexpr float HIGHLIGHT_DISTANCES[SCENE_COUNT] = {6.0F};
constexpr float HIGHLIGHT_RS[SCENE_COUNT] = {255.0F};
constexpr float HIGHLIGHT_GS[SCENE_COUNT] = {216.75F};
constexpr float HIGHLIGHT_BS[SCENE_COUNT] = {38.25F};
constexpr float HIGHLIGHT_WIDTHS[SCENE_COUNT] = {0.35F};
constexpr int HIGHLIGHT_STEPS_S[SCENE_COUNT] = {4};
constexpr float HIGHLIGHT_OPACITIES[SCENE_COUNT] = {0.56F};
constexpr bool HIGHLIGHT_OVERLAYS[SCENE_COUNT] = {false};

constexpr int GRADING_COUNT = 0;
inline const char* GRADING_NAMES[GRADING_COUNT > 0 ? GRADING_COUNT : 1] = {""};
constexpr unsigned char GRADING_GAINS[GRADING_COUNT > 0 ? GRADING_COUNT : 1][3] = {{0, 0, 0}};
constexpr short GRADING_LIFTS[GRADING_COUNT > 0 ? GRADING_COUNT : 1][3] = {{0, 0, 0}};
constexpr unsigned char GRADING_MIX_COLORS[GRADING_COUNT > 0 ? GRADING_COUNT : 1][3] = {{0, 0, 0}};
constexpr unsigned char GRADING_MIX_AMTS[GRADING_COUNT > 0 ? GRADING_COUNT : 1] = {0};
constexpr int GRADING_DEFAULT = -1;

// Template so this header stays engine-include-free; instantiated
// where Tyra::Engine is complete. index -1 (or any out of range)
// is a no-op.
template <typename TEngine>
inline void applySceneGrading(TEngine* engine, int index) {
  if (index < 0 || index >= GRADING_COUNT) return;
  engine->renderer.core.postFx.setGrading(
      GRADING_GAINS[index], GRADING_LIFTS[index],
      GRADING_MIX_COLORS[index], GRADING_MIX_AMTS[index]);
}

constexpr int SAVE_VALUE_COUNT = 0;
inline const char* SAVE_VALUE_NAMES[SAVE_VALUE_COUNT > 0 ? SAVE_VALUE_COUNT : 1] = {""};
constexpr float SAVE_VALUE_DEFAULTS[SAVE_VALUE_COUNT > 0 ? SAVE_VALUE_COUNT : 1] = {0.0F};
constexpr int SAVE_TEXT_COUNT = 0;
constexpr int SAVE_TEXT_LEN = 32;  // incl. the terminating NUL
inline const char* SAVE_TEXT_NAMES[SAVE_TEXT_COUNT > 0 ? SAVE_TEXT_COUNT : 1] = {""};
inline const char* SAVE_TEXT_DEFAULTS[SAVE_TEXT_COUNT > 0 ? SAVE_TEXT_COUNT : 1] = {""};
constexpr int SAVE_OBJECT_MAX = 7;

}  // namespace Nav_ai

// Index of the scene the game is currently in (defined in the game cpp).
extern int g_activeScene;

// Wall-clock normalization (defined in the game cpp, set at init from the
// video mode): the game logic is tuned per-frame at PAL's 50 Hz, so on a
// 60 Hz NTSC signal every per-frame step is multiplied by g_frameScale
// (50/60) to cover the same distance per real second. g_frameDt is the real
// seconds-per-frame for code that works in units/s.
extern float g_frameRate;   // vsync rate: 50 (PAL) or 60 (NTSC)
extern float g_frameDt;     // 1 / g_frameRate
extern float g_frameScale;  // 50 / g_frameRate

// Camera flashlight runtime state (a Player object property), defined in the
// game cpp. g_flashEnabled is the master switch (Set Flashlight flow node);
// g_flashOn is the on/off toggle state the player controls with the optional
// toggle button. The beam shows only while both are set.
extern bool g_flashEnabled;
extern bool g_flashOn;
template <typename TEngine>
inline bool flashlightTogglePressed(TEngine* engine) {
  (void)engine;
  switch (g_activeScene) {
    default: break;
  }
  return false;
}
// Frames per `seconds` of wall-clock time (>= 1), for frame-counter timers.
// Uses the MEASURED frame time, not the nominal vsync rate: with vsync
// disabled the loop free-runs way past 50 FPS and a nominal-rate count would
// make every timer (Delay, Every N Seconds, splash holds, sound retriggers)
// fire that much too fast - the disableVsync contract is "faster picture,
// same gameplay speed". At vsync the measured dt snaps to nominal, so this
// is bit-identical to the old seconds * g_frameRate there.
inline int everyFrames(float seconds) {
  const int f = (int)(seconds / (g_frameDt > 0.0001F ? g_frameDt : 0.02F));
  return f < 1 ? 1 : f;
}
#define SCENE_OBJECT_COUNT SCENE_OBJECT_COUNTS[g_activeScene]
#define SCENE_OBJECTS SCENE_OBJECT_TABLES[g_activeScene]
#define SCENE_LAYER_COUNT SCENE_LAYER_COUNTS[g_activeScene]
#define SCENE_LAYER_START SCENE_LAYER_STARTS[g_activeScene]
#define SCENE_LAYER_STREAM_X SCENE_LAYER_STREAM_XS[g_activeScene]
#define SCENE_LAYER_STREAM_Z SCENE_LAYER_STREAM_ZS[g_activeScene]
#define SCENE_LAYER_STREAM_R SCENE_LAYER_STREAM_RADII[g_activeScene]
#define PLAYER_INDEX PLAYER_INDEXES[g_activeScene]
#define PLAYER_MODE PLAYER_MODES[g_activeScene]
#define PLAYER_WALK_SPEED PLAYER_WALK_SPEEDS[g_activeScene]
#define PLAYER_LOOK_SPEED PLAYER_LOOK_SPEEDS[g_activeScene]
#define PLAYER_EYE_HEIGHT PLAYER_EYE_HEIGHTS[g_activeScene]
#define PLAYER_JUMP_SPEED PLAYER_JUMP_SPEEDS[g_activeScene]
#define PLAYER_CAN_JUMP PLAYER_CAN_JUMPS[g_activeScene]
#define PLAYER_RUN_THRESHOLD PLAYER_RUN_THRESHOLDS[g_activeScene]
#define PLAYER_CAM_DIST PLAYER_CAM_DISTS[g_activeScene]
#define PLAYER_CAM_HEIGHT PLAYER_CAM_HEIGHTS[g_activeScene]
#define PLAYER_CAM_SHOULDER PLAYER_CAM_SHOULDERS[g_activeScene]
#define PLAYER_TURN_RATE PLAYER_TURN_RATES[g_activeScene]
#define PLAYER_CAM_STYLE PLAYER_CAM_STYLES[g_activeScene]
#define PLAYER_CAM_PITCH PLAYER_CAM_PITCHES[g_activeScene]
#define PLAYER_CAM_YAW PLAYER_CAM_YAWS[g_activeScene]
#define PLAYER_CAM_YAW_ROTATE PLAYER_CAM_YAW_ROTATES[g_activeScene]
#define PLAYER_IDLE_CLIP PLAYER_IDLE_CLIPS[g_activeScene]
#define PLAYER_WALK_CLIP PLAYER_WALK_CLIPS[g_activeScene]
#define PLAYER_RUN_CLIP PLAYER_RUN_CLIPS[g_activeScene]
#define PLAYER_JUMP_CLIP PLAYER_JUMP_CLIPS[g_activeScene]
#define PLAYER2_INDEX PLAYER2_INDEXES[g_activeScene]
// Per-player table selection for the shared walker (pi: 0 = P1, 1 = P2).
#define PP_TBL(pi, T) \
  ((pi) == 0 ? PLAYER_##T[g_activeScene] : PLAYER2_##T[g_activeScene])
#define PP_INDEX(pi) PP_TBL(pi, INDEXES)
#define PP_MODE(pi) PP_TBL(pi, MODES)
#define PP_WALK_SPEED(pi) PP_TBL(pi, WALK_SPEEDS)
#define PP_LOOK_SPEED(pi) PP_TBL(pi, LOOK_SPEEDS)
#define PP_EYE_HEIGHT(pi) PP_TBL(pi, EYE_HEIGHTS)
#define PP_JUMP_SPEED(pi) PP_TBL(pi, JUMP_SPEEDS)
#define PP_CAN_JUMP(pi) PP_TBL(pi, CAN_JUMPS)
#define PP_RUN_THRESHOLD(pi) PP_TBL(pi, RUN_THRESHOLDS)
#define PP_CAM_DIST(pi) PP_TBL(pi, CAM_DISTS)
#define PP_CAM_HEIGHT(pi) PP_TBL(pi, CAM_HEIGHTS)
#define PP_CAM_SHOULDER(pi) PP_TBL(pi, CAM_SHOULDERS)
#define PP_TURN_RATE(pi) PP_TBL(pi, TURN_RATES)
#define PP_CAM_STYLE(pi) PP_TBL(pi, CAM_STYLES)
#define PP_CAM_PITCH(pi) PP_TBL(pi, CAM_PITCHES)
#define PP_CAM_YAW(pi) PP_TBL(pi, CAM_YAWS)
#define PP_CAM_YAW_ROTATE(pi) PP_TBL(pi, CAM_YAW_ROTATES)
#define PP_IDLE_CLIP(pi) PP_TBL(pi, IDLE_CLIPS)
#define PP_WALK_CLIP(pi) PP_TBL(pi, WALK_CLIPS)
#define PP_RUN_CLIP(pi) PP_TBL(pi, RUN_CLIPS)
#define PP_JUMP_CLIP(pi) PP_TBL(pi, JUMP_CLIPS)
#define TERRAIN_WIDTH TERRAIN_WIDTHS[g_activeScene]
#define TERRAIN_DEPTH TERRAIN_DEPTHS[g_activeScene]
#define SCENE_LIGHT_X SCENE_LIGHT_XS[g_activeScene]
#define SCENE_LIGHT_Y SCENE_LIGHT_YS[g_activeScene]
#define SCENE_LIGHT_Z SCENE_LIGHT_ZS[g_activeScene]
#define SCENE_AMBIENT SCENE_AMBIENTS[g_activeScene]
#define SCENE_DIFFUSE SCENE_DIFFUSES[g_activeScene]
#define SCENE_LIGHT_COL_R SCENE_LIGHT_COL_RS[g_activeScene]
#define SCENE_LIGHT_COL_G SCENE_LIGHT_COL_GS[g_activeScene]
#define SCENE_LIGHT_COL_B SCENE_LIGHT_COL_BS[g_activeScene]
#define SCENE_BRIGHTNESS SCENE_BRIGHTNESSES[g_activeScene]
// Baked ambient occlusion (docs/ambient-occlusion.md)
#define SCENE_AO_ENABLED SCENE_AO_ENABLEDS[g_activeScene]
#define SCENE_AO_STRENGTH SCENE_AO_STRENGTHS[g_activeScene]
#define SCENE_AO_RADIUS SCENE_AO_RADII[g_activeScene]
#define HM_W HM_WS[g_activeScene]
#define HM_D HM_DS[g_activeScene]
#define TERRAIN_HEIGHTS TERRAIN_HEIGHTS_TABLES[g_activeScene]
#define TERRAIN_TEXTURE TERRAIN_TEXTURES[g_activeScene]
// Painted terrain layers (two-pass splatting; docs/terrain-painting.md)
#define TERRAIN_LAYER_COUNT TERRAIN_LAYER_COUNTS[g_activeScene]
#define TERRAIN_SPLAT_WEIGHTS TERRAIN_SPLAT_TABLES[g_activeScene]
#define TERRAIN_TILE_U TERRAIN_TILE_US[g_activeScene]
#define TERRAIN_TILE_V TERRAIN_TILE_VS[g_activeScene]
#define TERRAIN_HAS_MATERIAL TERRAIN_HAS_MATERIALS[g_activeScene]
#define TERRAIN_TINT_R TERRAIN_TINTS[g_activeScene][0]
#define TERRAIN_TINT_G TERRAIN_TINTS[g_activeScene][1]
#define TERRAIN_TINT_B TERRAIN_TINTS[g_activeScene][2]
#define TERRAIN_TINT_VARIATION TERRAIN_TINT_VARIATIONS[g_activeScene]
#define TERRAIN_TINT_SCALE TERRAIN_TINT_SCALES[g_activeScene]
// Per-scene sky / clipping / post-FX / usable-highlight (Scene > Preferences)
#define CLIP_PRECISE CLIP_PRECISES[g_activeScene]
#define CLIP_VU1 CLIP_VU1S[g_activeScene]
#define SKY_R SKY_RS[g_activeScene]
#define SKY_G SKY_GS[g_activeScene]
#define SKY_B SKY_BS[g_activeScene]
#define SKY_DOME SKY_DOMES[g_activeScene]
#define SKY_ZENITH_EXP SKY_ZENITH_EXPS[g_activeScene]
#define SKY_TOP_R SKY_TOP_RS[g_activeScene]
#define SKY_TOP_G SKY_TOP_GS[g_activeScene]
#define SKY_TOP_B SKY_TOP_BS[g_activeScene]
#define POSTFX_BLOOM POSTFX_BLOOMS[g_activeScene]
#define POSTFX_GRAIN POSTFX_GRAINS[g_activeScene]
#define POSTFX_DOF POSTFX_DOFS[g_activeScene]
#define POSTFX_DOF_FOCUS POSTFX_DOF_FOCUSES[g_activeScene]
#define POSTFX_DOF_RANGE POSTFX_DOF_RANGES[g_activeScene]
#define FOG_ENABLED FOG_ENABLEDS[g_activeScene]
#define FOG_R FOG_RS[g_activeScene]
#define FOG_G FOG_GS[g_activeScene]
#define FOG_B FOG_BS[g_activeScene]
#define FOG_START FOG_STARTS[g_activeScene]
#define FOG_END FOG_ENDS[g_activeScene]
#define FLASHLIGHT_ENABLED FLASHLIGHT_ENABLEDS[g_activeScene]
#define FLASHLIGHT_R FLASHLIGHT_RS[g_activeScene]
#define FLASHLIGHT_G FLASHLIGHT_GS[g_activeScene]
#define FLASHLIGHT_B FLASHLIGHT_BS[g_activeScene]
#define FLASHLIGHT_RANGE FLASHLIGHT_RANGES[g_activeScene]
#define FLASHLIGHT_ANGLE FLASHLIGHT_ANGLES[g_activeScene]
#define HIGHLIGHT_USABLE HIGHLIGHT_USABLES[g_activeScene]
#define HIGHLIGHT_DISTANCE HIGHLIGHT_DISTANCES[g_activeScene]
#define HIGHLIGHT_R HIGHLIGHT_RS[g_activeScene]
#define HIGHLIGHT_G HIGHLIGHT_GS[g_activeScene]
#define HIGHLIGHT_B HIGHLIGHT_BS[g_activeScene]
#define HIGHLIGHT_WIDTH HIGHLIGHT_WIDTHS[g_activeScene]
#define HIGHLIGHT_STEPS HIGHLIGHT_STEPS_S[g_activeScene]
#define HIGHLIGHT_OPACITY HIGHLIGHT_OPACITIES[g_activeScene]
#define HIGHLIGHT_OVERLAY HIGHLIGHT_OVERLAYS[g_activeScene]
#define terrainHeightAt(x, z) terrainHeightAtScene(g_activeScene, (x), (z))
