#include "aisupport.hpp"

#include "platform.hpp"

#include <filesystem>
#include <fstream>
#include <sstream>

#include "ai_support_gen.hpp"  // kEmbeddedFiles (built from ai-support/)

namespace fs = std::filesystem;

namespace aisupport {

// Destination inside the project for an embedded file. Claude skills live
// under .claude/ (CLAUDE.md at the root); Copilot files under .github/.
static fs::path destFor(const std::string& provider, const std::string& rel) {
    if (provider == "claude")
        return rel == "CLAUDE.md" ? fs::path(rel) : fs::path(".claude") / rel;
    return fs::path(".github") / rel;  // copilot
}

static const char* kMarker = "Generated by TyraX";

// Ownership rule for the installed markdown: rewrite when the file is absent
// or still carries the marker near the top. SKILL.md files hold the marker
// below their YAML frontmatter, so search the head instead of line 1 only.
static bool mayOverwrite(const fs::path& path) {
    std::ifstream f(path, std::ios::binary);
    if (!f) return true;  // absent / unreadable = fresh install
    std::string head(512, '\0');
    f.read(head.data(), (std::streamsize)head.size());
    head.resize((size_t)f.gcount());
    return head.find(kMarker) != std::string::npos;
}

static std::string exePath() {
    const std::string p = platform::exePath();
    return p.empty() ? std::string("tyrax-editor") + platform::exeSuffix() : p;
}

static std::string replaceAll(std::string s, const std::string& from,
                              const std::string& to) {
    size_t pos = 0;
    while ((pos = s.find(from, pos)) != std::string::npos) {
        s.replace(pos, from.size(), to);
        pos += to.size();
    }
    return s;
}

bool installed(const std::string& projectDir, const std::string& provider) {
    // The provider's anchor file is enough - install() writes all-or-nothing
    // per provider (barring disk errors, which it reports).
    const fs::path anchor =
        provider == "claude"
            ? fs::path(projectDir) / ".claude" / "skills" / "tyra-project" /
                  "SKILL.md"
            : fs::path(projectDir) / ".github" / "copilot-instructions.md";
    std::error_code ec;
    return fs::exists(anchor, ec);
}

std::string install(const std::string& projectDir, bool claude, bool copilot) {
    if (!claude && !copilot) return "nothing to install";
    const std::string exe = exePath();
    int written = 0, kept = 0, failed = 0;
    for (const EmbeddedFile& f : kEmbeddedFiles) {
        const bool wanted = (claude && std::string(f.provider) == "claude") ||
                            (copilot && std::string(f.provider) == "copilot");
        if (!wanted) continue;
        const fs::path dest = fs::path(projectDir) / destFor(f.provider, f.relPath);
        if (!mayOverwrite(dest)) {
            ++kept;  // user took ownership - leave their version alone
            continue;
        }
        std::error_code ec;
        fs::create_directories(dest.parent_path(), ec);
        std::ofstream out(dest, std::ios::binary | std::ios::trunc);
        if (!out) {
            ++failed;
            continue;
        }
        out << replaceAll(f.content, "{TYRAX_EXE}", exe);
        ++written;
    }
    std::ostringstream msg;
    if (failed) msg << "error: " << failed << " file(s) could not be written; ";
    msg << "AI support: " << written << " file(s) installed";
    if (kept) msg << ", " << kept << " user-owned file(s) kept";
    return msg.str();
}

}  // namespace aisupport
