#include "aisupport.hpp"

#include "platform.hpp"

#include <filesystem>
#include <fstream>
#include <sstream>

#include "ai_support_gen.hpp"  // kEmbeddedFiles (built from ai-support/)

namespace fs = std::filesystem;

namespace aisupport {

// Destination inside the project for an embedded file. Claude skills live
// under .claude/ (CLAUDE.md at the root); Copilot files under .github/.
static fs::path destFor(const std::string& provider, const std::string& rel) {
    if (provider == "claude")
        return rel == "CLAUDE.md" ? fs::path(rel) : fs::path(".claude") / rel;
    if (provider == "codex")
        return rel == "CLAUDE.md" ? fs::path("AGENTS.md") : fs::path(".agents") / rel;
    return fs::path(".github") / rel;  // copilot
}

static const char* kMarker = "Generated by TyraX";

// Ownership rule for the installed markdown: rewrite when the file is absent
// or still carries the marker near the top. SKILL.md files hold the marker
// below their YAML frontmatter, so search the head instead of line 1 only - and
// generously, because a skill's `description:` is what makes an assistant reach
// for it and can legitimately run long. At 512 bytes a new skill whose marker
// landed at byte 829 read as user-owned the moment it was installed and was
// never refreshed again; nothing reported that, it simply stopped updating.
static bool mayOverwrite(const fs::path& path) {
    std::ifstream f(path, std::ios::binary);
    if (!f) return true;  // absent / unreadable = fresh install
    std::string head(4096, '\0');
    f.read(head.data(), (std::streamsize)head.size());
    head.resize((size_t)f.gcount());
    return head.find(kMarker) != std::string::npos;
}

static std::string exePath() {
    const std::string p = platform::exePath();
    return p.empty() ? std::string("tyrax-editor") + platform::exeSuffix() : p;
}

static std::string replaceAll(std::string s, const std::string& from,
                              const std::string& to) {
    size_t pos = 0;
    while ((pos = s.find(from, pos)) != std::string::npos) {
        s.replace(pos, from.size(), to);
        pos += to.size();
    }
    return s;
}

// The Claude content, re-pointed at where Codex looks. Only self-references
// change - a guide that says "see .claude/skills/x" must say ".agents/skills/x"
// in the copy that lives there, exactly like this repo's own mirrored skills.
static std::string forCodex(std::string text) {
    text = replaceAll(text, ".claude/skills", ".agents/skills");
    text = replaceAll(text, "CLAUDE.md", "AGENTS.md");
    return text;
}


bool installed(const std::string& projectDir, const std::string& provider) {
    // The provider's anchor file is enough - install() writes all-or-nothing
    // per provider (barring disk errors, which it reports).
    const fs::path anchor =
        provider == "claude"
            ? fs::path(projectDir) / ".claude" / "skills" / "tyra-project" /
                  "SKILL.md"
        : provider == "codex"
            ? fs::path(projectDir) / ".agents" / "skills" / "tyra-project" /
                  "SKILL.md"
            : fs::path(projectDir) / ".github" / "copilot-instructions.md";
    std::error_code ec;
    return fs::exists(anchor, ec);
}

// One embedded file, written for one provider. Split out because Codex reuses
// the Claude content, so the same file is written to two destinations and the
// ownership rule has to be applied per destination.
static void writeOne(const std::string& projectDir, const std::string& as,
                     const EmbeddedFile& f, const std::string& exe, int& written,
                     int& kept, int& failed) {
    const fs::path dest = fs::path(projectDir) / destFor(as, f.relPath);
    if (!mayOverwrite(dest)) {
        ++kept;  // user took ownership - leave their version alone
        return;
    }
    std::error_code ec;
    fs::create_directories(dest.parent_path(), ec);
    std::ofstream out(dest, std::ios::binary | std::ios::trunc);
    if (!out) {
        ++failed;
        return;
    }
    std::string text = replaceAll(f.content, "{TYRAX_EXE}", exe);
    if (as == "codex") text = forCodex(std::move(text));
    out << text;
    ++written;
}

std::string install(const std::string& projectDir, bool claude, bool copilot,
                    bool codex) {
    if (!claude && !copilot && !codex) return "nothing to install";
    const std::string exe = exePath();
    int written = 0, kept = 0, failed = 0;
    for (const EmbeddedFile& f : kEmbeddedFiles) {
        const std::string src = f.provider;
        if (claude && src == "claude") writeOne(projectDir, "claude", f, exe, written, kept, failed);
        // Codex is a second DESTINATION for the Claude files, not a second copy
        // of them - a copy in ai-support/ would drift the day one side is edited.
        if (codex && src == "claude") writeOne(projectDir, "codex", f, exe, written, kept, failed);
        if (copilot && src == "copilot") writeOne(projectDir, "copilot", f, exe, written, kept, failed);
    }
    std::ostringstream msg;
    if (failed) msg << "error: " << failed << " file(s) could not be written; ";
    msg << "AI support: " << written << " file(s) installed";
    if (kept) msg << ", " << kept << " user-owned file(s) kept";
    return msg.str();
}
}  // namespace aisupport
