#pragma once

#include <string>
#include <vector>

struct TerrainConfig {
    int width = 64;   // world units, X axis
    int depth = 64;   // world units, Z axis
};

enum class PrimitiveType { Box = 0, Sphere = 1, Cylinder = 2, Cone = 3 };

// Unit primitives fit a 1x1x1 cube centered at origin and are transformed by
// scale -> rotation (X, then Y, then Z) -> translation.
struct SceneObject {
    std::string name;
    PrimitiveType type = PrimitiveType::Box;
    float position[3] = {0.0f, 0.5f, 0.0f};
    float rotation[3] = {0.0f, 0.0f, 0.0f};  // degrees
    float scale[3] = {1.0f, 1.0f, 1.0f};
    float color[3] = {0.8f, 0.35f, 0.25f};
};

const char* primitiveTypeName(PrimitiveType t);

struct Project {
    std::string name;
    std::string dir;  // absolute path to project root
    TerrainConfig terrain;
    std::vector<std::string> scenes{"main"};
    std::vector<SceneObject> objects;

    bool valid() const { return !name.empty() && !dir.empty(); }
    std::string elfName() const { return name + ".elf"; }
    std::string elfPath() const { return dir + "\\bin\\" + elfName(); }
};

namespace project {

// Creates the project directory, generates all Tyra game sources / build files
// and project.json. Returns empty string on success, error message otherwise.
std::string create(Project& out, const std::string& name, const std::string& parentDir,
                   const TerrainConfig& terrain);

// Loads project.json from an existing project directory.
std::string load(Project& out, const std::string& projectDir);

std::string save(const Project& p);

// Rewrites editor-owned files from the current templates and project data:
// docker infra (Dockerfile, docker-compose.yml) and generated headers
// (terrain_config.hpp, scene_data.hpp) are always rewritten; game sources
// are rewritten only while they still carry the "Generated by tyra-editor"
// marker in the first line (delete it to take ownership of a file).
// Called before every build.
std::string refreshGenerated(const Project& p);

}  // namespace project
