#include "templates.hpp"

#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <sstream>

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#include "project.hpp"

namespace templates {

static std::string replaceAll(std::string s, const std::string& from, const std::string& to) {
    size_t pos = 0;
    while ((pos = s.find(from, pos)) != std::string::npos) {
        s.replace(pos, from.size(), to);
        pos += to.size();
    }
    return s;
}

// ---------------------------------------------------------------------------
// Tyra game project templates. Placeholders: {{NAME}}, {{WIDTH}}, {{DEPTH}}
// ---------------------------------------------------------------------------

static const char* TPL_MAKEFILE = R"(TARGET      := {{NAME}}.elf
ENGINEDIR	:= /tyra/engine

#The Directories, Source, Includes, Objects, Binary and Resources
SRCDIR      := src
INCDIR      := inc
BUILDDIR    := obj
TARGETDIR   := bin
RESDIR      := res
SRCEXT      := cpp
VSMEXT		:= vsm
VCLEXT		:= vcl
VCLPPEXT	:= vclpp
DEPEXT      := d
OBJEXT      := o

#Flags, Libraries and Includes
CFLAGS      :=
LIB         := -ltyra
LIBDIRS     := -L$(ENGINEDIR)/bin
INC         := -I$(INCDIR) -I$(ENGINEDIR)/inc
INCDEP      := -I$(INCDIR) -I$(ENGINEDIR)/inc

include /tyra/Makefile.base
)";

static const char* TPL_DOCKERFILE = R"(# syntax=docker/dockerfile:1
FROM h4570/tyra

RUN apt-get update
RUN apt-get install git -y

WORKDIR /src
CMD ["/bin/bash"]
)";

// Per-project container (no fixed container_name - avoids conflicts between
// projects). The Tyra engine lives in a volume shared by all projects, so it
// is cloned & compiled only once.
static const char* TPL_COMPOSE = R"(name: {{NAME_LOWER}}
volumes:
  tyra-game-volume:
  tyra-engine:
    name: tyra-engine-shared
services:
  compiler:
    environment:
      TERM: xterm-256color
    network_mode: host
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    volumes:
      - tyra-game-volume:/src
      - tyra-engine:/tyra
      - ./:/host
)";

static const char* TPL_MAIN_CPP = R"(#include <tyra>
#include "terrain_game.hpp"

int main() {
  Tyra::Engine engine;
  {{NAME_UPPER_NS}}::TerrainGame game(&engine);
  engine.run(&game);
  SleepThread();
  return 0;
}
)";

static const char* TPL_TERRAIN_CONFIG_HPP =
    R"(// Generated by tyra-editor. Do not edit - regenerated on every build.
#pragma once

namespace {{NAME_UPPER_NS}} {

constexpr float TERRAIN_WIDTH = {{WIDTH}}.0F;  // world units, X axis
constexpr float TERRAIN_DEPTH = {{DEPTH}}.0F;  // world units, Z axis

// Project preferences (Project > Preferences in the editor)
constexpr int TERRAIN_MAX_CELLS = {{DETAIL}};
constexpr bool CLIP_PRECISE = {{CLIP_PRECISE}};
constexpr float SKY_R = {{SKY_R}};  // 0-255
constexpr float SKY_G = {{SKY_G}};
constexpr float SKY_B = {{SKY_B}};
constexpr float EYE_HEIGHT = {{EYE_HEIGHT}};
constexpr float WALK_SPEED = {{WALK_SPEED}};
constexpr float LOOK_SPEED = {{LOOK_SPEED}};    // multiplier
constexpr float ORBIT_SPEED = {{ORBIT_SPEED}};  // multiplier
constexpr float GRAVITY = {{GRAVITY}};          // units/s^2
constexpr float JUMP_SPEED = {{JUMP_SPEED}};    // units/s
constexpr bool SKY_DOME = {{SKY_DOME}};
constexpr float SKY_TOP_R = {{SKY_TOP_R}};  // 0-255, dome zenith color
constexpr float SKY_TOP_G = {{SKY_TOP_G}};
constexpr float SKY_TOP_B = {{SKY_TOP_B}};

}  // namespace {{NAME_UPPER_NS}}
)";

static const char* TPL_GAME_HPP_ORBIT =
    R"(// Generated by tyra-editor. Delete this line to take ownership of this file.
#pragma once

#include <tyra>
#include <memory>
#include <vector>
#include "scripts/script.hpp"

namespace {{NAME_UPPER_NS}} {

class TerrainGame : public Tyra::Game {
 public:
  explicit TerrainGame(Tyra::Engine* engine);
  ~TerrainGame();

  void init() override;
  void loop() override;

 private:
  void buildScene();
  void generateTerrainGrid();
  void updateCameraOrbit();

  Tyra::Engine* engine;
  Tyra::StaticPipeline stapip;

  Tyra::Vec4 cameraPosition, cameraLookAt;
  float orbitAngle;

  std::vector<Tyra::Vec4> vertices;
  std::vector<Tyra::Color> colors;

  Tyra::M4x4 model;
  std::unique_ptr<Tyra::StaPipBag> bag;
  std::unique_ptr<Tyra::StaPipInfoBag> infoBag;
  std::unique_ptr<Tyra::StaPipColorBag> colorBag;

  // Scene objects at runtime (mutable by scripts/physics); geometry per object
  struct ObjectGeometry {
    std::vector<Tyra::Vec4> vertices;
    std::vector<Tyra::Color> colors;
    std::unique_ptr<Tyra::StaPipBag> bag;
    std::unique_ptr<Tyra::StaPipInfoBag> infoBag;
    std::unique_ptr<Tyra::StaPipColorBag> colorBag;
  };
  std::vector<RuntimeObject> runtimeObjects;
  std::vector<ObjectGeometry> objectGeometry;
  ObjectGeometry skyDome;
  float skyHorizonR = 0, skyHorizonG = 0, skyHorizonB = 0;

  void buildSkyDome();
  void rebuildObjectGeometry(int index);
  void updateObjectPhysics();
  void renderScene();

  ScriptContext scriptCtx;
};

}  // namespace {{NAME_UPPER_NS}}
)";

static const char* TPL_GAME_HPP_FPP =
    R"(// Generated by tyra-editor. Delete this line to take ownership of this file.
#pragma once

#include <tyra>
#include <memory>
#include <vector>
#include "scripts/script.hpp"

namespace {{NAME_UPPER_NS}} {

class TerrainGame : public Tyra::Game {
 public:
  explicit TerrainGame(Tyra::Engine* engine);
  ~TerrainGame();

  void init() override;
  void loop() override;

 private:
  void buildScene();
  void generateTerrainGrid();
  void updatePlayer();

  Tyra::Engine* engine;
  Tyra::StaticPipeline stapip;

  Tyra::Vec4 cameraPosition, cameraLookAt;
  float playerX, playerZ, yaw, pitch;
  float playerY, playerVelY;  // feet height + vertical velocity (physics)

  std::vector<Tyra::Vec4> vertices;
  std::vector<Tyra::Color> colors;

  Tyra::M4x4 model;
  std::unique_ptr<Tyra::StaPipBag> bag;
  std::unique_ptr<Tyra::StaPipInfoBag> infoBag;
  std::unique_ptr<Tyra::StaPipColorBag> colorBag;

  // Scene objects at runtime (mutable by scripts/physics); geometry per object
  struct ObjectGeometry {
    std::vector<Tyra::Vec4> vertices;
    std::vector<Tyra::Color> colors;
    std::unique_ptr<Tyra::StaPipBag> bag;
    std::unique_ptr<Tyra::StaPipInfoBag> infoBag;
    std::unique_ptr<Tyra::StaPipColorBag> colorBag;
  };
  std::vector<RuntimeObject> runtimeObjects;
  std::vector<ObjectGeometry> objectGeometry;
  ObjectGeometry skyDome;
  float skyHorizonR = 0, skyHorizonG = 0, skyHorizonB = 0;

  void buildSkyDome();
  void rebuildObjectGeometry(int index);
  void updateObjectPhysics();
  void renderScene();

  ScriptContext scriptCtx;
};

}  // namespace {{NAME_UPPER_NS}}
)";

// Game .cpp is composed as: PROLOG + <template>_HEAD + SCENE + <template>_TAIL + FOOTER
static const char* TPL_GAME_CPP_PROLOG =
    R"(// Generated by tyra-editor. Delete this line to take ownership of this file.
#include "terrain_game.hpp"
#include "terrain_config.hpp"
#include "scene_data.hpp"
#include <math.h>

namespace {{NAME_UPPER_NS}} {

using namespace Tyra;

namespace {

constexpr float PI = 3.14159265358979F;

struct V3 {
  float x, y, z;
};

/** Rotation order: X, then Y, then Z (same as the editor viewport). */
V3 rotated(const V3& v, const float* rotDeg) {
  V3 r = v;
  const float rx = rotDeg[0] * PI / 180.0F;
  const float ry = rotDeg[1] * PI / 180.0F;
  const float rz = rotDeg[2] * PI / 180.0F;
  {
    const float c = cosf(rx), s = sinf(rx);
    const float y = r.y * c - r.z * s, z = r.y * s + r.z * c;
    r.y = y, r.z = z;
  }
  {
    const float c = cosf(ry), s = sinf(ry);
    const float x = r.x * c + r.z * s, z = -r.x * s + r.z * c;
    r.x = x, r.z = z;
  }
  {
    const float c = cosf(rz), s = sinf(rz);
    const float x = r.x * c - r.y * s, y = r.x * s + r.y * c;
    r.x = x, r.y = y;
  }
  return r;
}

/** Fake directional light, baked into vertex colors. */
float shadeOf(const V3& n) {
  float d = n.x * 0.37F + n.y * 0.82F + n.z * 0.44F;
  if (d < 0.0F) d = 0.0F;
  return 0.55F + 0.45F * d;
}

void pushVert(std::vector<Vec4>& verts, std::vector<Color>& cols,
              const SceneObjectData& o, V3 p, V3 n) {
  p.x *= o.scale[0], p.y *= o.scale[1], p.z *= o.scale[2];
  p = rotated(p, o.rotation);
  n = rotated(n, o.rotation);
  const float shade = shadeOf(n);
  verts.push_back(Vec4(p.x + o.position[0], p.y + o.position[1],
                       p.z + o.position[2], 1.0F));
  cols.push_back(Color(o.color[0] * 255.0F * shade, o.color[1] * 255.0F * shade,
                       o.color[2] * 255.0F * shade, 128.0F));
}

void pushQuad(std::vector<Vec4>& verts, std::vector<Color>& cols,
              const SceneObjectData& o, V3 a, V3 b, V3 c, V3 d, V3 n) {
  pushVert(verts, cols, o, a, n);
  pushVert(verts, cols, o, b, n);
  pushVert(verts, cols, o, c, n);
  pushVert(verts, cols, o, a, n);
  pushVert(verts, cols, o, c, n);
  pushVert(verts, cols, o, d, n);
}

void addBox(std::vector<Vec4>& verts, std::vector<Color>& cols,
            const SceneObjectData& o) {
  const float h = 0.5F;
  pushQuad(verts, cols, o, {h, -h, -h}, {h, h, -h}, {h, h, h}, {h, -h, h}, {1, 0, 0});
  pushQuad(verts, cols, o, {-h, -h, h}, {-h, h, h}, {-h, h, -h}, {-h, -h, -h}, {-1, 0, 0});
  pushQuad(verts, cols, o, {-h, h, -h}, {-h, h, h}, {h, h, h}, {h, h, -h}, {0, 1, 0});
  pushQuad(verts, cols, o, {-h, -h, h}, {-h, -h, -h}, {h, -h, -h}, {h, -h, h}, {0, -1, 0});
  pushQuad(verts, cols, o, {-h, -h, h}, {h, -h, h}, {h, h, h}, {-h, h, h}, {0, 0, 1});
  pushQuad(verts, cols, o, {h, -h, -h}, {-h, -h, -h}, {-h, h, -h}, {h, h, -h}, {0, 0, -1});
}

void addSphere(std::vector<Vec4>& verts, std::vector<Color>& cols,
               const SceneObjectData& o) {
  const int stacks = 10, slices = 14;
  const float r = 0.5F;
  for (int st = 0; st < stacks; ++st) {
    const float t0 = PI * st / stacks, t1 = PI * (st + 1) / stacks;
    for (int sl = 0; sl < slices; ++sl) {
      const float p0 = 2.0F * PI * sl / slices, p1 = 2.0F * PI * (sl + 1) / slices;
      const V3 v00 = {r * sinf(t0) * cosf(p0), r * cosf(t0), r * sinf(t0) * sinf(p0)};
      const V3 v01 = {r * sinf(t0) * cosf(p1), r * cosf(t0), r * sinf(t0) * sinf(p1)};
      const V3 v10 = {r * sinf(t1) * cosf(p0), r * cosf(t1), r * sinf(t1) * sinf(p0)};
      const V3 v11 = {r * sinf(t1) * cosf(p1), r * cosf(t1), r * sinf(t1) * sinf(p1)};
      // Smooth shading: normal of a unit-sphere vertex is the vertex itself.
      const V3 n00 = {v00.x * 2, v00.y * 2, v00.z * 2};
      const V3 n01 = {v01.x * 2, v01.y * 2, v01.z * 2};
      const V3 n10 = {v10.x * 2, v10.y * 2, v10.z * 2};
      const V3 n11 = {v11.x * 2, v11.y * 2, v11.z * 2};
      pushVert(verts, cols, o, v00, n00);
      pushVert(verts, cols, o, v10, n10);
      pushVert(verts, cols, o, v11, n11);
      pushVert(verts, cols, o, v00, n00);
      pushVert(verts, cols, o, v11, n11);
      pushVert(verts, cols, o, v01, n01);
    }
  }
}

void addCylinder(std::vector<Vec4>& verts, std::vector<Color>& cols,
                 const SceneObjectData& o) {
  const int seg = 16;
  const float r = 0.5F, h = 0.5F;
  for (int i = 0; i < seg; ++i) {
    const float a0 = 2.0F * PI * i / seg, a1 = 2.0F * PI * (i + 1) / seg;
    const float x0 = r * cosf(a0), z0 = r * sinf(a0);
    const float x1 = r * cosf(a1), z1 = r * sinf(a1);
    const V3 n0 = {cosf(a0), 0, sinf(a0)}, n1 = {cosf(a1), 0, sinf(a1)};
    // side (smooth)
    pushVert(verts, cols, o, {x0, -h, z0}, n0);
    pushVert(verts, cols, o, {x0, h, z0}, n0);
    pushVert(verts, cols, o, {x1, h, z1}, n1);
    pushVert(verts, cols, o, {x0, -h, z0}, n0);
    pushVert(verts, cols, o, {x1, h, z1}, n1);
    pushVert(verts, cols, o, {x1, -h, z1}, n1);
    // caps
    pushVert(verts, cols, o, {0, h, 0}, {0, 1, 0});
    pushVert(verts, cols, o, {x1, h, z1}, {0, 1, 0});
    pushVert(verts, cols, o, {x0, h, z0}, {0, 1, 0});
    pushVert(verts, cols, o, {0, -h, 0}, {0, -1, 0});
    pushVert(verts, cols, o, {x0, -h, z0}, {0, -1, 0});
    pushVert(verts, cols, o, {x1, -h, z1}, {0, -1, 0});
  }
}

void addCone(std::vector<Vec4>& verts, std::vector<Color>& cols,
             const SceneObjectData& o) {
  const int seg = 16;
  const float r = 0.5F, h = 0.5F;
  const float nl = 0.894F, ny = 0.447F;  // side normal for r=0.5, h=1
  for (int i = 0; i < seg; ++i) {
    const float a0 = 2.0F * PI * i / seg, a1 = 2.0F * PI * (i + 1) / seg;
    const float am = (a0 + a1) * 0.5F;
    const float x0 = r * cosf(a0), z0 = r * sinf(a0);
    const float x1 = r * cosf(a1), z1 = r * sinf(a1);
    // side
    pushVert(verts, cols, o, {0, h, 0}, {nl * cosf(am), ny, nl * sinf(am)});
    pushVert(verts, cols, o, {x1, -h, z1}, {nl * cosf(a1), ny, nl * sinf(a1)});
    pushVert(verts, cols, o, {x0, -h, z0}, {nl * cosf(a0), ny, nl * sinf(a0)});
    // base
    pushVert(verts, cols, o, {0, -h, 0}, {0, -1, 0});
    pushVert(verts, cols, o, {x0, -h, z0}, {0, -1, 0});
    pushVert(verts, cols, o, {x1, -h, z1}, {0, -1, 0});
  }
}

}  // namespace
)";

// Orbit template: the camera slowly circles the terrain center.
static const char* TPL_GAME_CPP_ORBIT_HEAD = R"(
TerrainGame::TerrainGame(Engine* t_engine)
    : engine(t_engine), orbitAngle(0.0F), model(M4x4::Identity) {}

TerrainGame::~TerrainGame() {}

void TerrainGame::init() {
  // Engine clipper fix: the default clipMargin (-10.0F) moves the near
  // clipping plane ~10 units away from the camera, cutting away nearby
  // geometry. Clip right in front of the real near plane instead.
  // (read by the clipper during setRenderer below)
  PlanesClipAlgorithm::clipMargin =
      -(engine->renderer.core.getSettings().getNear() + 0.5F);

  stapip.setRenderer(&engine->renderer.core);

  engine->renderer.setClearScreenColor(Color(SKY_R, SKY_G, SKY_B));

  cameraLookAt = Vec4(0.0F, 0.0F, 0.0F);
  updateCameraOrbit();

  buildScene();

  scriptCtx.engine = engine;
  scriptCtx.objects = runtimeObjects.data();
  scriptCtx.objectCount = (int)runtimeObjects.size();
  scriptCtx.skyColor = Color(SKY_R, SKY_G, SKY_B);
  scriptCtx.playerPosition = cameraPosition;
  for (Script* script : getScripts()) script->init(scriptCtx);
}

void TerrainGame::loop() {
  updateCameraOrbit();

  scriptCtx.playerPosition = cameraPosition;
  for (Script* script : getScripts()) script->update(scriptCtx);
  engine->renderer.setClearScreenColor(scriptCtx.skyColor);

  updateObjectPhysics();

  engine->renderer.beginFrame(CameraInfo3D(&cameraPosition, &cameraLookAt));
  {
    engine->renderer.renderer3D.usePipeline(stapip);
    renderScene();
  }
  engine->renderer.endFrame();
}
)";

// Shared scene/terrain mesh building and runtime object management.
static const char* TPL_GAME_CPP_SCENE = R"(
void TerrainGame::buildScene() {
  vertices.clear();
  colors.clear();

  generateTerrainGrid();

  infoBag = std::make_unique<StaPipInfoBag>();
  infoBag->model = &model;
  infoBag->shadingType = TyraShadingFlat;
  // CLIP_PRECISE (Project > Preferences): real per-triangle clipping - no
  // holes at screen edges, but costs EE time. The fast path drops whole
  // triangles that extend far beyond the screen, but is much cheaper.
  infoBag->frustumCulling = CLIP_PRECISE ? PipelineInfoBagFrustumCulling_Precise
                                         : PipelineInfoBagFrustumCulling_None;
  infoBag->fullClipChecks = CLIP_PRECISE;

  colorBag = std::make_unique<StaPipColorBag>();
  colorBag->many = colors.data();

  bag = std::make_unique<StaPipBag>();
  bag->info = infoBag.get();
  bag->color = colorBag.get();
  bag->vertices = vertices.data();
  bag->count = static_cast<u32>(vertices.size());
  bag->texture = nullptr;
  bag->lighting = nullptr;

  // Runtime copies of the scene objects - scripts and physics mutate these.
  skyHorizonR = SKY_R, skyHorizonG = SKY_G, skyHorizonB = SKY_B;
  buildSkyDome();

  runtimeObjects.assign(SCENE_OBJECT_COUNT, RuntimeObject());
  objectGeometry.clear();
  objectGeometry.resize(SCENE_OBJECT_COUNT);
  for (int i = 0; i < SCENE_OBJECT_COUNT; ++i) {
    runtimeObjects[i].data = SCENE_OBJECTS[i];
    runtimeObjects[i].visible = SCENE_OBJECTS[i].type != 4;  // spawn = marker
    runtimeObjects[i].dirty = true;
  }
}

void TerrainGame::buildSkyDome() {
  if (!SKY_DOME) return;

  const float diag = TERRAIN_WIDTH > TERRAIN_DEPTH ? TERRAIN_WIDTH : TERRAIN_DEPTH;
  float radius = diag * 1.5F;
  if (radius < 60.0F) radius = 60.0F;
  if (radius > 450.0F) radius = 450.0F;

  const int stacks = 6, slices = 14;
  auto skyAt = [&](float t) {  // t: 0 = horizon, 1 = zenith
    return Color(skyHorizonR + (SKY_TOP_R - skyHorizonR) * t,
                 skyHorizonG + (SKY_TOP_G - skyHorizonG) * t,
                 skyHorizonB + (SKY_TOP_B - skyHorizonB) * t, 128.0F);
  };
  auto domeVert = [&](int stack, int slice) {
    // Start slightly below the horizon so the seam is never visible
    const float lat = -0.06F + (PI * 0.5F + 0.06F) * stack / stacks;
    const float lon = 2.0F * PI * slice / slices;
    return Vec4(radius * cosf(lat) * cosf(lon), radius * sinf(lat),
                radius * cosf(lat) * sinf(lon), 1.0F);
  };

  skyDome.vertices.clear();
  skyDome.colors.clear();
  for (int st = 0; st < stacks; ++st) {
    const float t0 = (float)st / stacks, t1 = (float)(st + 1) / stacks;
    for (int sl = 0; sl < slices; ++sl) {
      const Vec4 v00 = domeVert(st, sl), v01 = domeVert(st, sl + 1);
      const Vec4 v10 = domeVert(st + 1, sl), v11 = domeVert(st + 1, sl + 1);
      skyDome.vertices.push_back(v00);
      skyDome.vertices.push_back(v10);
      skyDome.vertices.push_back(v11);
      skyDome.vertices.push_back(v00);
      skyDome.vertices.push_back(v11);
      skyDome.vertices.push_back(v01);
      skyDome.colors.push_back(skyAt(t0));
      skyDome.colors.push_back(skyAt(t1));
      skyDome.colors.push_back(skyAt(t1));
      skyDome.colors.push_back(skyAt(t0));
      skyDome.colors.push_back(skyAt(t1));
      skyDome.colors.push_back(skyAt(t0));
    }
  }

  skyDome.infoBag = std::make_unique<StaPipInfoBag>();
  skyDome.infoBag->model = &model;
  skyDome.infoBag->shadingType = TyraShadingGouraud;
  // Static geometry crossing the screen edges all the time - needs clipping
  skyDome.infoBag->frustumCulling = PipelineInfoBagFrustumCulling_Precise;
  skyDome.infoBag->fullClipChecks = true;
  skyDome.colorBag = std::make_unique<StaPipColorBag>();
  skyDome.colorBag->many = skyDome.colors.data();
  skyDome.bag = std::make_unique<StaPipBag>();
  skyDome.bag->info = skyDome.infoBag.get();
  skyDome.bag->color = skyDome.colorBag.get();
  skyDome.bag->vertices = skyDome.vertices.data();
  skyDome.bag->count = static_cast<u32>(skyDome.vertices.size());
  skyDome.bag->texture = nullptr;
  skyDome.bag->lighting = nullptr;
}

void TerrainGame::rebuildObjectGeometry(int index) {
  RuntimeObject& o = runtimeObjects[index];
  ObjectGeometry& g = objectGeometry[index];
  o.dirty = false;

  g.vertices.clear();
  g.colors.clear();
  switch (o.data.type) {
    case 1: addSphere(g.vertices, g.colors, o.data); break;
    case 2: addCylinder(g.vertices, g.colors, o.data); break;
    case 3: addCone(g.vertices, g.colors, o.data); break;
    case 4: break;  // spawn point - marker only
    default: addBox(g.vertices, g.colors, o.data); break;
  }
  if (g.vertices.empty()) {
    g.bag.reset();
    return;
  }

  if (!g.bag) {
    g.infoBag = std::make_unique<StaPipInfoBag>();
    g.infoBag->model = &model;
    g.infoBag->shadingType = TyraShadingFlat;
    // Objects can move at runtime, but the engine caches frustum bboxes by
    // the vertex pointer (stale bbox = object culled at its old position).
    // Objects are small, so skip culling/clipping for them entirely;
    // the terrain keeps CLIP_PRECISE.
    g.infoBag->frustumCulling = PipelineInfoBagFrustumCulling_None;
    g.infoBag->fullClipChecks = false;
    g.colorBag = std::make_unique<StaPipColorBag>();
    g.bag = std::make_unique<StaPipBag>();
    g.bag->info = g.infoBag.get();
    g.bag->color = g.colorBag.get();
    g.bag->texture = nullptr;
    g.bag->lighting = nullptr;
  }
  g.colorBag->many = g.colors.data();
  g.bag->vertices = g.vertices.data();
  g.bag->count = static_cast<u32>(g.vertices.size());
}

void TerrainGame::updateObjectPhysics() {
  // GRAVITY is units/s^2; the game runs at 50 FPS
  const float gravityPerFrame = GRAVITY / (50.0F * 50.0F);
  for (RuntimeObject& o : runtimeObjects) {
    if (!o.data.physics) continue;
    const float half = 0.5F * o.data.scale[1];
    if (o.velocityY == 0.0F && o.data.position[1] <= half) continue;  // resting

    o.velocityY -= gravityPerFrame;
    o.data.position[1] += o.velocityY;
    if (o.data.position[1] <= half) {
      o.data.position[1] = half;
      o.velocityY = 0.0F;
    }
    o.dirty = true;
  }
}

void TerrainGame::renderScene() {
  // Scripts changing ctx.skyColor retint the dome horizon
  if (skyDome.bag && (scriptCtx.skyColor.r != skyHorizonR ||
                      scriptCtx.skyColor.g != skyHorizonG ||
                      scriptCtx.skyColor.b != skyHorizonB)) {
    skyHorizonR = scriptCtx.skyColor.r;
    skyHorizonG = scriptCtx.skyColor.g;
    skyHorizonB = scriptCtx.skyColor.b;
    buildSkyDome();
  }
  if (skyDome.bag) stapip.core.render(skyDome.bag.get());
  stapip.core.render(bag.get());
  for (int i = 0; i < (int)runtimeObjects.size(); ++i) {
    if (runtimeObjects[i].dirty) rebuildObjectGeometry(i);
    if (runtimeObjects[i].visible && objectGeometry[i].bag)
      stapip.core.render(objectGeometry[i].bag.get());
  }
}

void TerrainGame::generateTerrainGrid() {
  // Cap the amount of quads so big terrains stay PS2-friendly.
  // Cell size grows with terrain size instead.
  const u32 maxCells = (u32)TERRAIN_MAX_CELLS;
  const u32 cellsX = TERRAIN_WIDTH > maxCells ? maxCells : (u32)TERRAIN_WIDTH;
  const u32 cellsZ = TERRAIN_DEPTH > maxCells ? maxCells : (u32)TERRAIN_DEPTH;
  const float stepX = TERRAIN_WIDTH / cellsX;
  const float stepZ = TERRAIN_DEPTH / cellsZ;
  const float startX = -TERRAIN_WIDTH * 0.5F;
  const float startZ = -TERRAIN_DEPTH * 0.5F;

  // Two greens in a checker pattern, so the grid is visible.
  // PS2 colors: RGB 0-255, alpha 0-128.
  const Color colorA(96.0F, 160.0F, 72.0F, 128.0F);
  const Color colorB(74.0F, 128.0F, 56.0F, 128.0F);

  for (u32 z = 0; z < cellsZ; ++z) {
    for (u32 x = 0; x < cellsX; ++x) {
      const float x0 = startX + x * stepX;
      const float x1 = x0 + stepX;
      const float z0 = startZ + z * stepZ;
      const float z1 = z0 + stepZ;
      const Color& c = ((x + z) % 2 == 0) ? colorA : colorB;

      vertices.push_back(Vec4(x0, 0.0F, z0, 1.0F));
      vertices.push_back(Vec4(x1, 0.0F, z0, 1.0F));
      vertices.push_back(Vec4(x0, 0.0F, z1, 1.0F));
      vertices.push_back(Vec4(x1, 0.0F, z0, 1.0F));
      vertices.push_back(Vec4(x1, 0.0F, z1, 1.0F));
      vertices.push_back(Vec4(x0, 0.0F, z1, 1.0F));

      for (int i = 0; i < 6; ++i) colors.push_back(c);
    }
  }
}
)";

static const char* TPL_GAME_CPP_ORBIT_TAIL = R"(
void TerrainGame::updateCameraOrbit() {
  orbitAngle += 0.005F * ORBIT_SPEED;
  const float diag = TERRAIN_WIDTH > TERRAIN_DEPTH ? TERRAIN_WIDTH : TERRAIN_DEPTH;
  const float orbitRadius = diag * 0.9F;
  const float orbitHeight = diag * 0.55F;

  cameraPosition.x = orbitRadius * cosf(orbitAngle);
  cameraPosition.y = orbitHeight;
  cameraPosition.z = orbitRadius * sinf(orbitAngle);
}
)";

// FPP template: walk with the left stick, look around with the right stick.
// Axis conventions follow the official Tyra demo (v<128 = stick up).
static const char* TPL_GAME_CPP_FPP_HEAD = R"(
TerrainGame::TerrainGame(Engine* t_engine)
    : engine(t_engine),
      playerX(0.0F),
      playerZ(0.0F),
      yaw(0.0F),
      pitch(0.0F),
      playerY(0.0F),
      playerVelY(0.0F),
      model(M4x4::Identity) {}

TerrainGame::~TerrainGame() {}

void TerrainGame::init() {
  // Engine clipper fix: the default clipMargin (-10.0F) moves the near
  // clipping plane ~10 units away from the camera, cutting away nearby
  // geometry. Clip right in front of the real near plane instead.
  // (read by the clipper during setRenderer below)
  PlanesClipAlgorithm::clipMargin =
      -(engine->renderer.core.getSettings().getNear() + 0.5F);

  stapip.setRenderer(&engine->renderer.core);

  engine->renderer.setClearScreenColor(Color(SKY_R, SKY_G, SKY_B));

  // Player start: the first spawn point in the scene (if any)
  for (int i = 0; i < SCENE_OBJECT_COUNT; ++i) {
    if (SCENE_OBJECTS[i].type == 4) {
      playerX = SCENE_OBJECTS[i].position[0];
      playerZ = SCENE_OBJECTS[i].position[2];
      yaw = SCENE_OBJECTS[i].rotation[1] * PI / 180.0F;
      break;
    }
  }

  updatePlayer();
  buildScene();

  scriptCtx.engine = engine;
  scriptCtx.objects = runtimeObjects.data();
  scriptCtx.objectCount = (int)runtimeObjects.size();
  scriptCtx.skyColor = Color(SKY_R, SKY_G, SKY_B);
  scriptCtx.playerPosition = cameraPosition;
  for (Script* script : getScripts()) script->init(scriptCtx);
}

void TerrainGame::loop() {
  updatePlayer();

  scriptCtx.playerPosition = cameraPosition;
  for (Script* script : getScripts()) script->update(scriptCtx);
  engine->renderer.setClearScreenColor(scriptCtx.skyColor);

  updateObjectPhysics();

  engine->renderer.beginFrame(CameraInfo3D(&cameraPosition, &cameraLookAt));
  {
    engine->renderer.renderer3D.usePipeline(stapip);
    renderScene();
  }
  engine->renderer.endFrame();
}
)";

static const char* TPL_GAME_CPP_FPP_TAIL = R"(
namespace {

float axisValue(const u8& raw) {
  const float v = (raw - 128.0F) / 128.0F;
  return (v > -0.20F && v < 0.20F) ? 0.0F : v;  // deadzone
}

}  // namespace

void TerrainGame::updatePlayer() {
  const auto& leftJoy = engine->pad.getLeftJoyPad();
  const auto& rightJoy = engine->pad.getRightJoyPad();

  // Right stick: look around (stick right = turn right)
  yaw -= axisValue(rightJoy.h) * 0.05F * LOOK_SPEED;
  pitch -= axisValue(rightJoy.v) * 0.035F * LOOK_SPEED;
  if (pitch > 1.2F) pitch = 1.2F;
  if (pitch < -1.2F) pitch = -1.2F;

  // Left stick: walk. Forward is where the camera looks (flat).
  const float fx = sinf(yaw);
  const float fz = cosf(yaw);
  const float forward = -axisValue(leftJoy.v);
  const float strafe = axisValue(leftJoy.h);
  float nextX = playerX + (fx * forward - fz * strafe) * WALK_SPEED;
  float nextZ = playerZ + (fz * forward + fx * strafe) * WALK_SPEED;

  // Keep the player on the terrain
  const float limX = TERRAIN_WIDTH * 0.5F - 1.0F;
  const float limZ = TERRAIN_DEPTH * 0.5F - 1.0F;
  if (nextX > limX) nextX = limX;
  if (nextX < -limX) nextX = -limX;
  if (nextZ > limZ) nextZ = limZ;
  if (nextZ < -limZ) nextZ = -limZ;

  // Collision with scene objects (XZ, boxes expanded by the player radius)
  // + standing on top of them. Player can step ~0.5 units up.
  const float playerRadius = 0.35F;
  float ground = 0.0F;
  for (const RuntimeObject& o : runtimeObjects) {
    if (!o.visible || o.data.type == 4) continue;
    const float ox = o.data.position[0];
    const float oz = o.data.position[2];
    const float hx = 0.5F * o.data.scale[0] + playerRadius;
    const float hz = 0.5F * o.data.scale[2] + playerRadius;
    const float top = o.data.position[1] + 0.5F * o.data.scale[1];
    const float bottom = o.data.position[1] - 0.5F * o.data.scale[1];

    const bool nextInside =
        nextX > ox - hx && nextX < ox + hx && nextZ > oz - hz && nextZ < oz + hz;
    if (!nextInside) continue;

    if (playerY + 0.5F >= top) {
      // Low enough to walk onto - candidate floor
      if (top > ground) ground = top;
    } else if (playerY < top && playerY + EYE_HEIGHT > bottom) {
      // Blocked - cancel the axes that entered the box this frame
      const bool wasInsideX = playerX > ox - hx && playerX < ox + hx;
      const bool wasInsideZ = playerZ > oz - hz && playerZ < oz + hz;
      if (!wasInsideX) nextX = playerX;
      if (!wasInsideZ) nextZ = playerZ;
      if (wasInsideX && wasInsideZ) {
        nextX = playerX;
        nextZ = playerZ;
      }
    }
  }
  playerX = nextX;
  playerZ = nextZ;

  // Gravity & jumping (X). GRAVITY: units/s^2, JUMP_SPEED: units/s, 50 FPS.
  playerVelY -= GRAVITY / (50.0F * 50.0F);
  playerY += playerVelY;
  if (playerY <= ground) {
    playerY = ground;
    playerVelY = 0.0F;
    if (engine->pad.getClicked().Cross) playerVelY = JUMP_SPEED / 50.0F;
  }

  const float eyeY = playerY + EYE_HEIGHT;
  cameraPosition = Vec4(playerX, eyeY, playerZ);
  cameraLookAt = Vec4(playerX + fx * cosf(pitch), eyeY + sinf(pitch),
                      playerZ + fz * cosf(pitch));
}
)";

static const char* TPL_GAME_CPP_FOOTER = R"(
}  // namespace {{NAME_UPPER_NS}}
)";

// ---------------------------------------------------------------------------
// Legacy templates (v1, before scene objects). Kept verbatim so that projects
// generated by older editor versions can be recognized as unedited and safely
// regenerated. Do not modify.
// ---------------------------------------------------------------------------

static const char* TPL_GAME_HPP_V1 = R"(#pragma once

#include <tyra>
#include <memory>
#include <vector>

namespace {{NAME_UPPER_NS}} {

class TerrainGame : public Tyra::Game {
 public:
  explicit TerrainGame(Tyra::Engine* engine);
  ~TerrainGame();

  void init() override;
  void loop() override;

 private:
  void generateTerrainGrid();
  void updateCameraOrbit();

  Tyra::Engine* engine;
  Tyra::StaticPipeline stapip;

  Tyra::Vec4 cameraPosition, cameraLookAt;
  float orbitAngle;

  std::vector<Tyra::Vec4> vertices;
  std::vector<Tyra::Color> colors;

  Tyra::M4x4 model;
  std::unique_ptr<Tyra::StaPipBag> bag;
  std::unique_ptr<Tyra::StaPipInfoBag> infoBag;
  std::unique_ptr<Tyra::StaPipColorBag> colorBag;
};

}  // namespace {{NAME_UPPER_NS}}
)";

static const char* TPL_GAME_CPP_V1 = R"(#include "terrain_game.hpp"
#include "terrain_config.hpp"
#include <math.h>

namespace {{NAME_UPPER_NS}} {

using namespace Tyra;

TerrainGame::TerrainGame(Engine* t_engine)
    : engine(t_engine), orbitAngle(0.0F), model(M4x4::Identity) {}

TerrainGame::~TerrainGame() {}

void TerrainGame::init() {
  stapip.setRenderer(&engine->renderer.core);

  // Sky blue background
  engine->renderer.setClearScreenColor(Color(64.0F, 140.0F, 200.0F));

  cameraLookAt = Vec4(0.0F, 0.0F, 0.0F);
  updateCameraOrbit();

  generateTerrainGrid();
}

void TerrainGame::loop() {
  updateCameraOrbit();

  engine->renderer.beginFrame(CameraInfo3D(&cameraPosition, &cameraLookAt));
  {
    engine->renderer.renderer3D.usePipeline(stapip);
    stapip.core.render(bag.get());
  }
  engine->renderer.endFrame();
}

void TerrainGame::generateTerrainGrid() {
  // Cap the amount of quads so big terrains stay PS2-friendly.
  // Cell size grows with terrain size instead.
  const u32 maxCells = 32;
  const u32 cellsX = TERRAIN_WIDTH > maxCells ? maxCells : (u32)TERRAIN_WIDTH;
  const u32 cellsZ = TERRAIN_DEPTH > maxCells ? maxCells : (u32)TERRAIN_DEPTH;
  const float stepX = TERRAIN_WIDTH / cellsX;
  const float stepZ = TERRAIN_DEPTH / cellsZ;
  const float startX = -TERRAIN_WIDTH * 0.5F;
  const float startZ = -TERRAIN_DEPTH * 0.5F;

  // Two greens in a checker pattern, so the grid is visible.
  // PS2 colors: RGB 0-255, alpha 0-128.
  const Color colorA(96.0F, 160.0F, 72.0F, 128.0F);
  const Color colorB(74.0F, 128.0F, 56.0F, 128.0F);

  vertices.clear();
  colors.clear();
  vertices.reserve(cellsX * cellsZ * 6);
  colors.reserve(cellsX * cellsZ * 6);

  for (u32 z = 0; z < cellsZ; ++z) {
    for (u32 x = 0; x < cellsX; ++x) {
      const float x0 = startX + x * stepX;
      const float x1 = x0 + stepX;
      const float z0 = startZ + z * stepZ;
      const float z1 = z0 + stepZ;
      const Color& c = ((x + z) % 2 == 0) ? colorA : colorB;

      const Vec4 v00(x0, 0.0F, z0, 1.0F);
      const Vec4 v10(x1, 0.0F, z0, 1.0F);
      const Vec4 v01(x0, 0.0F, z1, 1.0F);
      const Vec4 v11(x1, 0.0F, z1, 1.0F);

      vertices.push_back(v00);
      vertices.push_back(v10);
      vertices.push_back(v01);
      vertices.push_back(v10);
      vertices.push_back(v11);
      vertices.push_back(v01);

      for (int i = 0; i < 6; ++i) colors.push_back(c);
    }
  }

  infoBag = std::make_unique<StaPipInfoBag>();
  infoBag->model = &model;
  infoBag->shadingType = TyraShadingFlat;
  infoBag->fullClipChecks = false;

  colorBag = std::make_unique<StaPipColorBag>();
  colorBag->many = colors.data();

  bag = std::make_unique<StaPipBag>();
  bag->info = infoBag.get();
  bag->color = colorBag.get();
  bag->vertices = vertices.data();
  bag->count = static_cast<u32>(vertices.size());
  bag->texture = nullptr;
  bag->lighting = nullptr;
}

void TerrainGame::updateCameraOrbit() {
  orbitAngle += 0.005F;
  const float diag = TERRAIN_WIDTH > TERRAIN_DEPTH ? TERRAIN_WIDTH : TERRAIN_DEPTH;
  const float orbitRadius = diag * 0.9F;
  const float orbitHeight = diag * 0.55F;

  cameraPosition.x = orbitRadius * cosf(orbitAngle);
  cameraPosition.y = orbitHeight;
  cameraPosition.z = orbitRadius * sinf(orbitAngle);
}

}  // namespace {{NAME_UPPER_NS}}
)";

// Script API header (inc/scripts/script.hpp). Marker-owned: regenerated on
// build while the marker is present, so the API can evolve with the editor.
static const char* TPL_SCRIPT_HPP =
    R"(// Generated by tyra-editor. Delete this line to take ownership of this file.
#pragma once

#include <tyra>
#include <vector>
#include "scene_data.hpp"

namespace {{NAME_UPPER_NS}} {

/** A scene object at runtime. Mutate `data` (position/rotation/scale/color),
 * `visible` or `velocityY`, then set `dirty = true` so the geometry gets
 * rebuilt on the next frame. */
struct RuntimeObject {
  SceneObjectData data;
  bool visible = true;
  float velocityY = 0.0F;  // vertical velocity (object physics)
  bool dirty = true;
};

/** Everything a script can see and touch each frame. */
struct ScriptContext {
  Tyra::Engine* engine = nullptr;  // pad, renderer, audio, ...
  Tyra::Vec4 playerPosition;       // camera/player position this frame
  RuntimeObject* objects = nullptr;  // mutable scene objects
  int objectCount = 0;
  Tyra::Color skyColor;  // write to change the clear color
};

/** Base class for game scripts. Put .cpp files in src/scripts/. */
class Script {
 public:
  virtual ~Script() {}
  virtual void init(ScriptContext&) {}
  virtual void update(ScriptContext&) {}
};

inline std::vector<Script*>& getScripts() {
  static std::vector<Script*> scripts;
  return scripts;
}

}  // namespace {{NAME_UPPER_NS}}

/** Registers a script class. Put TYRA_SCRIPT(MyScript); at file scope. */
#define TYRA_SCRIPT_CONCAT_INNER(a, b) a##b
#define TYRA_SCRIPT_CONCAT(a, b) TYRA_SCRIPT_CONCAT_INNER(a, b)
#define TYRA_SCRIPT(ClassName)                                             \
  static const bool TYRA_SCRIPT_CONCAT(_tyraScript_, __COUNTER__) = []() { \
    {{NAME_UPPER_NS}}::getScripts().push_back(new ClassName());            \
    return true;                                                           \
  }()
)";

// Example script for FPP projects - user-owned, written only at creation.
static const char* TPL_EXAMPLE_SCRIPT_FPP =
    R"(// Example tyra-editor script. This file is yours - it is never regenerated.
// Walk close to the box and press X: the sky changes color (and a message
// lands in the PCSX2 log via TYRA_LOG).
#include "scripts/script.hpp"
#include "terrain_config.hpp"

namespace {{NAME_UPPER_NS}} {

class ExampleInteraction : public Script {
 public:
  void update(ScriptContext& ctx) override {
    // Find the first box in the scene
    RuntimeObject* box = nullptr;
    for (int i = 0; i < ctx.objectCount; ++i) {
      if (ctx.objects[i].data.type == 0) {  // 0 = box
        box = &ctx.objects[i];
        break;
      }
    }
    if (!box) return;

    const float dx = ctx.playerPosition.x - box->data.position[0];
    const float dz = ctx.playerPosition.z - box->data.position[2];
    const bool nearBox = (dx * dx + dz * dz) < 8.0F * 8.0F;

    if (nearBox && ctx.engine->pad.getClicked().Cross) {
      toggled = !toggled;
      TYRA_LOG("Box says hello! Sky toggled: ", (int)toggled);
      ctx.skyColor = toggled ? Tyra::Color(230.0F, 120.0F, 60.0F)
                             : Tyra::Color(SKY_R, SKY_G, SKY_B);
    }
  }

 private:
  bool toggled = false;
};

}  // namespace {{NAME_UPPER_NS}}

TYRA_SCRIPT({{NAME_UPPER_NS}}::ExampleInteraction);
)";

// Example script for orbit projects (no player to walk around with).
static const char* TPL_EXAMPLE_SCRIPT_ORBIT =
    R"(// Example tyra-editor script. This file is yours - it is never regenerated.
// Press X on the pad: the sky changes color (and a message lands in the
// PCSX2 log via TYRA_LOG).
#include "scripts/script.hpp"
#include "terrain_config.hpp"

namespace {{NAME_UPPER_NS}} {

class ExampleInteraction : public Script {
 public:
  void update(ScriptContext& ctx) override {
    if (ctx.engine->pad.getClicked().Cross) {
      toggled = !toggled;
      TYRA_LOG("X pressed! Sky toggled: ", (int)toggled);
      ctx.skyColor = toggled ? Tyra::Color(230.0F, 120.0F, 60.0F)
                             : Tyra::Color(SKY_R, SKY_G, SKY_B);
    }
  }

 private:
  bool toggled = false;
};

}  // namespace {{NAME_UPPER_NS}}

TYRA_SCRIPT({{NAME_UPPER_NS}}::ExampleInteraction);
)";

// Stub for "New script..." in the editor.
static const char* TPL_SCRIPT_STUB =
    R"(// {{SCRIPT_FILE}} - created by tyra-editor. This file is yours.
#include "scripts/script.hpp"

namespace {{NAME_UPPER_NS}} {

class {{SCRIPT_CLASS}} : public Script {
 public:
  void init(ScriptContext& ctx) override {
    // Called once at game start.
  }

  void update(ScriptContext& ctx) override {
    // Called every frame. Examples:
    //   ctx.engine->pad.getClicked().Cross  - X pressed this frame
    //   ctx.playerPosition                  - camera/player position
    //   ctx.skyColor = Tyra::Color(255.0F, 0.0F, 0.0F);
  }
};

}  // namespace {{NAME_UPPER_NS}}

TYRA_SCRIPT({{NAME_UPPER_NS}}::{{SCRIPT_CLASS}});
)";

static const char* TPL_RUN_PS1 = R"($ConfigFile = Join-Path $PSScriptRoot './windows-pcsx2.ps1'
. $ConfigFile

RunPCSX2
)";

static const char* TPL_PCSX2_PS1 = R"PS1(# =======================
$CUSTOM_PCSX2_PATH = "" # "D:/My/Path/To/PCSX2"
# =======================

function GetTargetELFName {
    return (Select-String -Path './Makefile' -Pattern "[^ ]*.elf").Matches.Value
}

function FindPCSX2Directory {
    if (-not [string]::IsNullOrEmpty($CUSTOM_PCSX2_PATH)) {
        return $CUSTOM_PCSX2_PATH
    }
    else {
        $pcsx2Path = "${Env:ProgramFiles}/PCSX2"
        $pcsx2Pathx86 = "${Env:ProgramFiles(x86)}/PCSX2"

        if (Test-Path -Path $pcsx2Path) {
            return $pcsx2Path
        }
        elseif (Test-Path -Path $pcsx2Pathx86) {
            return $pcsx2Pathx86
        }
        else {
            throw "PCSX2 directory not found!"
        }
    }
}

function FindPCSX2Executable {
    param ([string]$directory)

    foreach ($name in 'pcsx2.exe', 'pcsx2-qt.exe') {
        if (Test-Path -Path (Join-Path $directory $name)) { return $name }
    }
    throw "PCSX2 executable not found in: $directory!"
}

function RunPCSX2 {
    $dirPath = FindPCSX2Directory
    $isNewVersion = Test-Path -Path "$dirPath/qt.conf"
    $executableName = FindPCSX2Executable -directory $dirPath
    $executableNameWithoutExt = (Split-Path $executableName -Leaf).Split('.')[0]
    $targetFileName = "$PWD/bin/$(GetTargetELFName)"

    Stop-Process -Name $executableNameWithoutExt -ErrorAction 'SilentlyContinue'

    if ($isNewVersion) {
        Start-Process -FilePath "$dirPath/$executableName" -ArgumentList "-elf", $targetFileName
    }
    else {
        Start-Process -FilePath "$dirPath/$executableName" -ArgumentList "--elf=$targetFileName"
    }
}
)PS1";

static const char* TPL_GITIGNORE = R"(obj/
bin/*.elf
*.tyra
.vscode/
)";

static const char* TPL_DIR_KEEP = "*\n!.gitignore\n";

static std::string floatLit(float v) {
    char buf[40];
    std::snprintf(buf, sizeof(buf), "%.6g", (double)v);
    std::string s = buf;
    // "8" -> "8.0": the F suffix is only valid on floating-point literals
    if (s.find('.') == std::string::npos && s.find('e') == std::string::npos &&
        s.find("inf") == std::string::npos && s.find("nan") == std::string::npos)
        s += ".0";
    return s + "F";
}

static std::string vec3Init(const float* v) {
    return "{" + floatLit(v[0]) + ", " + floatLit(v[1]) + ", " + floatLit(v[2]) + "}";
}

// inc/scene_data.hpp - pure data mirror of project.json, regenerated on build
static std::string sceneDataContent(const Project& p, const std::string& ns) {
    std::ostringstream out;
    out << "// Generated by tyra-editor. Do not edit - regenerated on every build.\n"
           "#pragma once\n"
           "\n"
           "namespace "
        << ns
        << " {\n"
           "\n"
           "struct SceneObjectData {\n"
           "  int type;  // 0=box 1=sphere 2=cylinder 3=cone 4=spawn-point\n"
           "  float position[3];\n"
           "  float rotation[3];  // degrees\n"
           "  float scale[3];\n"
           "  float color[3];  // 0..1\n"
           "  int physics;  // 1 = falls with gravity\n"
           "};\n"
           "\n"
           "constexpr int SCENE_OBJECT_COUNT = "
        << p.objects.size() << ";\n"
        << "constexpr SceneObjectData SCENE_OBJECTS[SCENE_OBJECT_COUNT > 0 ? "
           "SCENE_OBJECT_COUNT : 1] = {\n";
    if (p.objects.empty()) {
        out << "    {0, {0, 0, 0}, {0, 0, 0}, {1, 1, 1}, {1, 1, 1}, 0},\n";
    } else {
        for (const SceneObject& o : p.objects) {
            out << "    {" << (int)o.type << ", " << vec3Init(o.position) << ", "
                << vec3Init(o.rotation) << ", " << vec3Init(o.scale) << ", "
                << vec3Init(o.color) << ", " << (o.physics ? 1 : 0) << "},  // " << o.name
                << "\n";
        }
    }
    out << "};\n"
           "\n"
           "}  // namespace "
        << ns << "\n";
    return out.str();
}

static std::string sanitizeNamespace(const std::string& name) {
    // Project name -> valid C++ namespace: letters/digits/underscore, no leading digit
    std::string ns;
    for (char c : name) {
        if (isalnum((unsigned char)c) || c == '_')
            ns += c;
        else
            ns += '_';
    }
    if (ns.empty() || isdigit((unsigned char)ns[0])) ns = "Game" + ns;
    if (!ns.empty() && islower((unsigned char)ns[0])) ns[0] = (char)toupper((unsigned char)ns[0]);
    return ns;
}

static std::string fillTemplate(const Project& p, const char* tpl) {
    // docker compose project name: lowercase, must start with letter/digit
    std::string nameLower;
    for (char c : p.name) nameLower += (char)tolower((unsigned char)c);
    if (nameLower.empty() || !isalnum((unsigned char)nameLower[0]))
        nameLower = "tyra-" + nameLower;

    std::string s = tpl;
    s = replaceAll(s, "{{NAME_LOWER}}", nameLower);
    s = replaceAll(s, "{{NAME}}", p.name);
    s = replaceAll(s, "{{NAME_UPPER_NS}}", sanitizeNamespace(p.name));
    s = replaceAll(s, "{{WIDTH}}", std::to_string(p.terrain.width));
    s = replaceAll(s, "{{DEPTH}}", std::to_string(p.terrain.depth));

    const ProjectSettings& st = p.settings;
    s = replaceAll(s, "{{DETAIL}}", std::to_string(st.terrainDetail));
    s = replaceAll(s, "{{CLIP_PRECISE}}", st.clipping == "fast" ? "false" : "true");
    s = replaceAll(s, "{{SKY_R}}", floatLit(st.skyColor[0] * 255.0f));
    s = replaceAll(s, "{{SKY_G}}", floatLit(st.skyColor[1] * 255.0f));
    s = replaceAll(s, "{{SKY_B}}", floatLit(st.skyColor[2] * 255.0f));
    s = replaceAll(s, "{{EYE_HEIGHT}}", floatLit(st.eyeHeight));
    s = replaceAll(s, "{{WALK_SPEED}}", floatLit(st.walkSpeed));
    s = replaceAll(s, "{{LOOK_SPEED}}", floatLit(st.lookSpeed));
    s = replaceAll(s, "{{ORBIT_SPEED}}", floatLit(st.orbitSpeed));
    s = replaceAll(s, "{{GRAVITY}}", floatLit(st.gravity));
    s = replaceAll(s, "{{JUMP_SPEED}}", floatLit(st.jumpSpeed));
    s = replaceAll(s, "{{SKY_DOME}}", st.skyDome ? "true" : "false");
    s = replaceAll(s, "{{SKY_TOP_R}}", floatLit(st.skyTopColor[0] * 255.0f));
    s = replaceAll(s, "{{SKY_TOP_G}}", floatLit(st.skyTopColor[1] * 255.0f));
    s = replaceAll(s, "{{SKY_TOP_B}}", floatLit(st.skyTopColor[2] * 255.0f));
    return s;
}

bool matchesLegacy(const Project& p, const std::string& relativePath,
                   const std::string& content) {
    const char* tpl = nullptr;
    if (relativePath == "src\\terrain_game.cpp")
        tpl = TPL_GAME_CPP_V1;
    else if (relativePath == "inc\\terrain_game.hpp")
        tpl = TPL_GAME_HPP_V1;
    if (!tpl) return false;
    return content == fillTemplate(p, tpl);
}

// ---------------------------------------------------------------------------
// Flow graph -> C++ script. Object names are resolved to indices at codegen
// time; unknown names produce a comment instead of code.
// ---------------------------------------------------------------------------
std::string flowGraphScript(const Project& p) {
    const std::string ns = sanitizeNamespace(p.name);

    auto objectIndex = [&](const std::string& name) {
        for (size_t i = 0; i < p.objects.size(); ++i)
            if (p.objects[i].name == name) return (int)i;
        return -1;
    };

    // action node -> inline statements
    auto actionCode = [&](const FlowNode& n, const std::string& pad) -> std::string {
        std::ostringstream c;
        const int idx = objectIndex(n.str);
        const bool needsObject = flowNodeType(n.type)->strKind == FlowParamKind::ObjectName;
        if (needsObject && idx < 0) {
            c << pad << "// node " << n.id << " (" << n.type << "): unknown object '"
              << n.str << "'\n";
            return c.str();
        }
        const std::string obj = "ctx.objects[" + std::to_string(idx) + "]";
        if (n.type == "SetSky") {
            c << pad << "ctx.skyColor = Tyra::Color(" << floatLit(n.num[0] * 255.0f) << ", "
              << floatLit(n.num[1] * 255.0f) << ", " << floatLit(n.num[2] * 255.0f) << ");\n";
        } else if (n.type == "ShowObject") {
            c << pad << obj << ".visible = true;\n";
        } else if (n.type == "HideObject") {
            c << pad << obj << ".visible = false;\n";
        } else if (n.type == "ToggleObject") {
            c << pad << obj << ".visible = !" << obj << ".visible;\n";
        } else if (n.type == "MoveObjectBy") {
            for (int a = 0; a < 3; ++a)
                if (n.num[a] != 0.0f)
                    c << pad << obj << ".data.position[" << a << "] += " << floatLit(n.num[a])
                      << ";\n";
            c << pad << obj << ".dirty = true;\n";
        } else if (n.type == "SetObjectColor") {
            for (int a = 0; a < 3; ++a)
                c << pad << obj << ".data.color[" << a << "] = " << floatLit(n.num[a]) << ";\n";
            c << pad << obj << ".dirty = true;\n";
        } else if (n.type == "Log") {
            std::string text = n.str;
            text = replaceAll(text, "\\", "\\\\");
            text = replaceAll(text, "\"", "\\\"");
            c << pad << "TYRA_LOG(\"" << text << "\");\n";
        }
        return c.str();
    };

    // all actions linked to a trigger
    auto linkedActions = [&](int triggerId, const std::string& pad) {
        std::ostringstream c;
        for (const FlowLink& l : p.flowGraph.links) {
            if (l.fromNode != triggerId) continue;
            for (const FlowNode& n : p.flowGraph.nodes) {
                if (n.id != l.toNode) continue;
                const FlowNodeType* t = flowNodeType(n.type);
                if (t && !t->trigger) c << actionCode(n, pad);
            }
        }
        return c.str();
    };

    std::ostringstream out;
    out << "// Generated by tyra-editor from the Flow Graph. Do not edit -\n"
           "// regenerated on every build. Edit the graph in the editor instead.\n"
           "#include \"scripts/script.hpp\"\n\n"
           "namespace "
        << ns
        << " {\n\n"
           "class FlowGraphScript : public Script {\n"
           " public:\n"
           "  void update(ScriptContext& ctx) override {\n"
           "    frame++;\n";

    std::ostringstream members;
    for (const FlowNode& n : p.flowGraph.nodes) {
        const FlowNodeType* t = flowNodeType(n.type);
        if (!t || !t->trigger) continue;
        const std::string body = linkedActions(n.id, "      ");
        if (body.empty()) continue;

        if (n.type == "OnStart") {
            out << "    if (!started) {\n      started = true;\n" << body << "    }\n";
        } else if (n.type == "OnButton") {
            std::string btn = n.str.empty() ? "Cross" : n.str;
            out << "    if (ctx.engine->pad.getClicked()." << btn << ") {\n" << body
                << "    }\n";
        } else if (n.type == "NearObject") {
            const int idx = objectIndex(n.str);
            if (idx < 0) {
                out << "    // node " << n.id << " (NearObject): unknown object '" << n.str
                    << "'\n";
                continue;
            }
            const std::string flag = "near" + std::to_string(n.id);
            members << "  bool " << flag << " = false;\n";
            const float r = n.num[0] > 0.01f ? n.num[0] : 3.0f;
            out << "    {\n      const float dx = ctx.playerPosition.x - ctx.objects[" << idx
                << "].data.position[0];\n      const float dz = ctx.playerPosition.z - "
                   "ctx.objects["
                << idx << "].data.position[2];\n      const bool isNear = dx * dx + dz * dz < "
                << floatLit(r * r) << ";\n      if (isNear && !" << flag << ") {\n"
                << body << "      }\n      " << flag << " = isNear;\n    }\n";
        } else if (n.type == "EverySeconds") {
            int frames = (int)(n.num[0] * 50.0f);
            if (frames < 1) frames = 1;
            out << "    if (frame % " << frames << " == 0) {\n" << body << "    }\n";
        }
    }

    out << "  }\n\n"
           " private:\n"
           "  int frame = 0;\n"
           "  bool started = false;\n"
        << members.str()
        << "};\n\n"
           "}  // namespace "
        << ns << "\n\nTYRA_SCRIPT(" << ns << "::FlowGraphScript);\n";
    return out.str();
}

std::string scriptStub(const Project& p, const std::string& className,
                       const std::string& fileName) {
    std::string s = fillTemplate(p, TPL_SCRIPT_STUB);
    s = replaceAll(s, "{{SCRIPT_CLASS}}", className);
    s = replaceAll(s, "{{SCRIPT_FILE}}", fileName);
    return s;
}

// .vscode/c_cpp_properties.json - IntelliSense for scripts in VS Code.
// Uses the editor's bundled Tyra engine headers and the PS2SDK headers
// exported from the docker toolchain (see Runner). Machine-specific paths,
// hence regenerated on every build.
static std::string vscodeCppProperties() {
    auto slashes = [](std::string s) {
        for (auto& c : s)
            if (c == '\\') c = '/';
        return s;
    };

    std::string engineInc;
    char exePath[MAX_PATH] = {};
    if (GetModuleFileNameA(nullptr, exePath, MAX_PATH) > 0) {
        std::filesystem::path candidate = std::filesystem::path(exePath).parent_path() /
                                          ".." / "vendor" / "tyra" / "engine" / "inc";
        std::error_code ec;
        if (std::filesystem::exists(candidate, ec))
            engineInc = slashes(std::filesystem::weakly_canonical(candidate, ec).string());
    }

    std::string sdk;
    if (const char* lad = getenv("LOCALAPPDATA"))
        sdk = slashes(std::string(lad) + "\\tyra-editor\\ps2sdk");

    std::ostringstream out;
    out << "{\n"
           "  \"configurations\": [\n"
           "    {\n"
           "      \"name\": \"PS2 (Tyra)\",\n"
           "      \"includePath\": [\n"
           "        \"${workspaceFolder}/inc\",\n"
           "        \"${workspaceFolder}/src\"";
    if (!engineInc.empty()) out << ",\n        \"" << engineInc << "\"";
    if (!sdk.empty())
        out << ",\n        \"" << sdk << "/ee/include\",\n        \"" << sdk
            << "/common/include\"";
    out << "\n      ],\n"
           "      \"defines\": [\"_EE\"],\n"
           "      \"cStandard\": \"c11\",\n"
           "      \"cppStandard\": \"c++20\",\n"
           "      \"intelliSenseMode\": \"linux-gcc-x86\"\n"
           "    }\n"
           "  ],\n"
           "  \"version\": 4\n"
           "}\n";
    return out.str();
}

std::vector<File> generate(const Project& p) {
    const std::string ns = sanitizeNamespace(p.name);
    auto fill = [&](const char* tpl) { return fillTemplate(p, tpl); };

    const bool fpp = p.gameTemplate == "fpp";
    const std::string gameCpp =
        fill(TPL_GAME_CPP_PROLOG) +
        fill(fpp ? TPL_GAME_CPP_FPP_HEAD : TPL_GAME_CPP_ORBIT_HEAD) +
        fill(TPL_GAME_CPP_SCENE) +
        fill(fpp ? TPL_GAME_CPP_FPP_TAIL : TPL_GAME_CPP_ORBIT_TAIL) +
        fill(TPL_GAME_CPP_FOOTER);

    return {
        {"Makefile", fill(TPL_MAKEFILE)},
        {"Dockerfile", fill(TPL_DOCKERFILE)},
        {"docker-compose.yml", fill(TPL_COMPOSE)},
        {"src\\main.cpp", fill(TPL_MAIN_CPP)},
        {"src\\terrain_game.cpp", gameCpp},
        {"inc\\terrain_game.hpp", fill(fpp ? TPL_GAME_HPP_FPP : TPL_GAME_HPP_ORBIT)},
        {"inc\\terrain_config.hpp", fill(TPL_TERRAIN_CONFIG_HPP)},
        {"inc\\scene_data.hpp", sceneDataContent(p, ns)},
        {"inc\\scripts\\script.hpp", fill(TPL_SCRIPT_HPP)},
        {"src\\scripts\\flow_graph.gen.cpp", flowGraphScript(p)},
        {"src\\scripts\\example_interaction.cpp",
         fill(fpp ? TPL_EXAMPLE_SCRIPT_FPP : TPL_EXAMPLE_SCRIPT_ORBIT)},
        {".vscode\\c_cpp_properties.json", vscodeCppProperties()},
        {"run.ps1", fill(TPL_RUN_PS1)},
        {"windows-pcsx2.ps1", fill(TPL_PCSX2_PS1)},
        {".gitignore", fill(TPL_GITIGNORE)},
        {"res\\.gitignore", TPL_DIR_KEEP},
        {"bin\\.gitignore", TPL_DIR_KEEP},
        {"obj\\.gitignore", TPL_DIR_KEEP},
    };
}

}  // namespace templates
