#include "templates.hpp"

#include <cstdio>
#include <sstream>

#include "project.hpp"

namespace templates {

static std::string replaceAll(std::string s, const std::string& from, const std::string& to) {
    size_t pos = 0;
    while ((pos = s.find(from, pos)) != std::string::npos) {
        s.replace(pos, from.size(), to);
        pos += to.size();
    }
    return s;
}

// ---------------------------------------------------------------------------
// Tyra game project templates. Placeholders: {{NAME}}, {{WIDTH}}, {{DEPTH}}
// ---------------------------------------------------------------------------

static const char* TPL_MAKEFILE = R"(TARGET      := {{NAME}}.elf
ENGINEDIR	:= /tyra/engine

#The Directories, Source, Includes, Objects, Binary and Resources
SRCDIR      := src
INCDIR      := inc
BUILDDIR    := obj
TARGETDIR   := bin
RESDIR      := res
SRCEXT      := cpp
VSMEXT		:= vsm
VCLEXT		:= vcl
VCLPPEXT	:= vclpp
DEPEXT      := d
OBJEXT      := o

#Flags, Libraries and Includes
CFLAGS      :=
LIB         := -ltyra
LIBDIRS     := -L$(ENGINEDIR)/bin
INC         := -I$(INCDIR) -I$(ENGINEDIR)/inc
INCDEP      := -I$(INCDIR) -I$(ENGINEDIR)/inc

include /tyra/Makefile.base
)";

static const char* TPL_DOCKERFILE = R"(# syntax=docker/dockerfile:1
FROM h4570/tyra

RUN apt-get update
RUN apt-get install git -y

WORKDIR /src
CMD ["/bin/bash"]
)";

// Per-project container (no fixed container_name - avoids conflicts between
// projects). The Tyra engine lives in a volume shared by all projects, so it
// is cloned & compiled only once.
static const char* TPL_COMPOSE = R"(name: {{NAME_LOWER}}
volumes:
  tyra-game-volume:
  tyra-engine:
    name: tyra-engine-shared
services:
  compiler:
    environment:
      TERM: xterm-256color
    network_mode: host
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    volumes:
      - tyra-game-volume:/src
      - tyra-engine:/tyra
      - ./:/host
)";

static const char* TPL_MAIN_CPP = R"(#include <tyra>
#include "terrain_game.hpp"

int main() {
  Tyra::Engine engine;
  {{NAME_UPPER_NS}}::TerrainGame game(&engine);
  engine.run(&game);
  SleepThread();
  return 0;
}
)";

static const char* TPL_TERRAIN_CONFIG_HPP = R"(// Generated by tyra-editor. Terrain settings for this project.
#pragma once

namespace {{NAME_UPPER_NS}} {

constexpr float TERRAIN_WIDTH = {{WIDTH}}.0F;  // world units, X axis
constexpr float TERRAIN_DEPTH = {{DEPTH}}.0F;  // world units, Z axis

}  // namespace {{NAME_UPPER_NS}}
)";

static const char* TPL_GAME_HPP =
    R"(// Generated by tyra-editor. Delete this line to take ownership of this file.
#pragma once

#include <tyra>
#include <memory>
#include <vector>

namespace {{NAME_UPPER_NS}} {

class TerrainGame : public Tyra::Game {
 public:
  explicit TerrainGame(Tyra::Engine* engine);
  ~TerrainGame();

  void init() override;
  void loop() override;

 private:
  void buildScene();
  void generateTerrainGrid();
  void updateCameraOrbit();

  Tyra::Engine* engine;
  Tyra::StaticPipeline stapip;

  Tyra::Vec4 cameraPosition, cameraLookAt;
  float orbitAngle;

  std::vector<Tyra::Vec4> vertices;
  std::vector<Tyra::Color> colors;

  Tyra::M4x4 model;
  std::unique_ptr<Tyra::StaPipBag> bag;
  std::unique_ptr<Tyra::StaPipInfoBag> infoBag;
  std::unique_ptr<Tyra::StaPipColorBag> colorBag;
};

}  // namespace {{NAME_UPPER_NS}}
)";

static const char* TPL_GAME_CPP =
    R"(// Generated by tyra-editor. Delete this line to take ownership of this file.
#include "terrain_game.hpp"
#include "terrain_config.hpp"
#include "scene_data.hpp"
#include <math.h>

namespace {{NAME_UPPER_NS}} {

using namespace Tyra;

namespace {

constexpr float PI = 3.14159265358979F;

struct V3 {
  float x, y, z;
};

/** Rotation order: X, then Y, then Z (same as the editor viewport). */
V3 rotated(const V3& v, const float* rotDeg) {
  V3 r = v;
  const float rx = rotDeg[0] * PI / 180.0F;
  const float ry = rotDeg[1] * PI / 180.0F;
  const float rz = rotDeg[2] * PI / 180.0F;
  {
    const float c = cosf(rx), s = sinf(rx);
    const float y = r.y * c - r.z * s, z = r.y * s + r.z * c;
    r.y = y, r.z = z;
  }
  {
    const float c = cosf(ry), s = sinf(ry);
    const float x = r.x * c + r.z * s, z = -r.x * s + r.z * c;
    r.x = x, r.z = z;
  }
  {
    const float c = cosf(rz), s = sinf(rz);
    const float x = r.x * c - r.y * s, y = r.x * s + r.y * c;
    r.x = x, r.y = y;
  }
  return r;
}

/** Fake directional light, baked into vertex colors. */
float shadeOf(const V3& n) {
  float d = n.x * 0.37F + n.y * 0.82F + n.z * 0.44F;
  if (d < 0.0F) d = 0.0F;
  return 0.55F + 0.45F * d;
}

void pushVert(std::vector<Vec4>& verts, std::vector<Color>& cols,
              const SceneObjectData& o, V3 p, V3 n) {
  p.x *= o.scale[0], p.y *= o.scale[1], p.z *= o.scale[2];
  p = rotated(p, o.rotation);
  n = rotated(n, o.rotation);
  const float shade = shadeOf(n);
  verts.push_back(Vec4(p.x + o.position[0], p.y + o.position[1],
                       p.z + o.position[2], 1.0F));
  cols.push_back(Color(o.color[0] * 255.0F * shade, o.color[1] * 255.0F * shade,
                       o.color[2] * 255.0F * shade, 128.0F));
}

void pushQuad(std::vector<Vec4>& verts, std::vector<Color>& cols,
              const SceneObjectData& o, V3 a, V3 b, V3 c, V3 d, V3 n) {
  pushVert(verts, cols, o, a, n);
  pushVert(verts, cols, o, b, n);
  pushVert(verts, cols, o, c, n);
  pushVert(verts, cols, o, a, n);
  pushVert(verts, cols, o, c, n);
  pushVert(verts, cols, o, d, n);
}

void addBox(std::vector<Vec4>& verts, std::vector<Color>& cols,
            const SceneObjectData& o) {
  const float h = 0.5F;
  pushQuad(verts, cols, o, {h, -h, -h}, {h, h, -h}, {h, h, h}, {h, -h, h}, {1, 0, 0});
  pushQuad(verts, cols, o, {-h, -h, h}, {-h, h, h}, {-h, h, -h}, {-h, -h, -h}, {-1, 0, 0});
  pushQuad(verts, cols, o, {-h, h, -h}, {-h, h, h}, {h, h, h}, {h, h, -h}, {0, 1, 0});
  pushQuad(verts, cols, o, {-h, -h, h}, {-h, -h, -h}, {h, -h, -h}, {h, -h, h}, {0, -1, 0});
  pushQuad(verts, cols, o, {-h, -h, h}, {h, -h, h}, {h, h, h}, {-h, h, h}, {0, 0, 1});
  pushQuad(verts, cols, o, {h, -h, -h}, {-h, -h, -h}, {-h, h, -h}, {h, h, -h}, {0, 0, -1});
}

void addSphere(std::vector<Vec4>& verts, std::vector<Color>& cols,
               const SceneObjectData& o) {
  const int stacks = 10, slices = 14;
  const float r = 0.5F;
  for (int st = 0; st < stacks; ++st) {
    const float t0 = PI * st / stacks, t1 = PI * (st + 1) / stacks;
    for (int sl = 0; sl < slices; ++sl) {
      const float p0 = 2.0F * PI * sl / slices, p1 = 2.0F * PI * (sl + 1) / slices;
      const V3 v00 = {r * sinf(t0) * cosf(p0), r * cosf(t0), r * sinf(t0) * sinf(p0)};
      const V3 v01 = {r * sinf(t0) * cosf(p1), r * cosf(t0), r * sinf(t0) * sinf(p1)};
      const V3 v10 = {r * sinf(t1) * cosf(p0), r * cosf(t1), r * sinf(t1) * sinf(p0)};
      const V3 v11 = {r * sinf(t1) * cosf(p1), r * cosf(t1), r * sinf(t1) * sinf(p1)};
      // Smooth shading: normal of a unit-sphere vertex is the vertex itself.
      const V3 n00 = {v00.x * 2, v00.y * 2, v00.z * 2};
      const V3 n01 = {v01.x * 2, v01.y * 2, v01.z * 2};
      const V3 n10 = {v10.x * 2, v10.y * 2, v10.z * 2};
      const V3 n11 = {v11.x * 2, v11.y * 2, v11.z * 2};
      pushVert(verts, cols, o, v00, n00);
      pushVert(verts, cols, o, v10, n10);
      pushVert(verts, cols, o, v11, n11);
      pushVert(verts, cols, o, v00, n00);
      pushVert(verts, cols, o, v11, n11);
      pushVert(verts, cols, o, v01, n01);
    }
  }
}

void addCylinder(std::vector<Vec4>& verts, std::vector<Color>& cols,
                 const SceneObjectData& o) {
  const int seg = 16;
  const float r = 0.5F, h = 0.5F;
  for (int i = 0; i < seg; ++i) {
    const float a0 = 2.0F * PI * i / seg, a1 = 2.0F * PI * (i + 1) / seg;
    const float x0 = r * cosf(a0), z0 = r * sinf(a0);
    const float x1 = r * cosf(a1), z1 = r * sinf(a1);
    const V3 n0 = {cosf(a0), 0, sinf(a0)}, n1 = {cosf(a1), 0, sinf(a1)};
    // side (smooth)
    pushVert(verts, cols, o, {x0, -h, z0}, n0);
    pushVert(verts, cols, o, {x0, h, z0}, n0);
    pushVert(verts, cols, o, {x1, h, z1}, n1);
    pushVert(verts, cols, o, {x0, -h, z0}, n0);
    pushVert(verts, cols, o, {x1, h, z1}, n1);
    pushVert(verts, cols, o, {x1, -h, z1}, n1);
    // caps
    pushVert(verts, cols, o, {0, h, 0}, {0, 1, 0});
    pushVert(verts, cols, o, {x1, h, z1}, {0, 1, 0});
    pushVert(verts, cols, o, {x0, h, z0}, {0, 1, 0});
    pushVert(verts, cols, o, {0, -h, 0}, {0, -1, 0});
    pushVert(verts, cols, o, {x0, -h, z0}, {0, -1, 0});
    pushVert(verts, cols, o, {x1, -h, z1}, {0, -1, 0});
  }
}

void addCone(std::vector<Vec4>& verts, std::vector<Color>& cols,
             const SceneObjectData& o) {
  const int seg = 16;
  const float r = 0.5F, h = 0.5F;
  const float nl = 0.894F, ny = 0.447F;  // side normal for r=0.5, h=1
  for (int i = 0; i < seg; ++i) {
    const float a0 = 2.0F * PI * i / seg, a1 = 2.0F * PI * (i + 1) / seg;
    const float am = (a0 + a1) * 0.5F;
    const float x0 = r * cosf(a0), z0 = r * sinf(a0);
    const float x1 = r * cosf(a1), z1 = r * sinf(a1);
    // side
    pushVert(verts, cols, o, {0, h, 0}, {nl * cosf(am), ny, nl * sinf(am)});
    pushVert(verts, cols, o, {x1, -h, z1}, {nl * cosf(a1), ny, nl * sinf(a1)});
    pushVert(verts, cols, o, {x0, -h, z0}, {nl * cosf(a0), ny, nl * sinf(a0)});
    // base
    pushVert(verts, cols, o, {0, -h, 0}, {0, -1, 0});
    pushVert(verts, cols, o, {x0, -h, z0}, {0, -1, 0});
    pushVert(verts, cols, o, {x1, -h, z1}, {0, -1, 0});
  }
}

}  // namespace

TerrainGame::TerrainGame(Engine* t_engine)
    : engine(t_engine), orbitAngle(0.0F), model(M4x4::Identity) {}

TerrainGame::~TerrainGame() {}

void TerrainGame::init() {
  stapip.setRenderer(&engine->renderer.core);

  // Sky blue background
  engine->renderer.setClearScreenColor(Color(64.0F, 140.0F, 200.0F));

  cameraLookAt = Vec4(0.0F, 0.0F, 0.0F);
  updateCameraOrbit();

  buildScene();
}

void TerrainGame::loop() {
  updateCameraOrbit();

  engine->renderer.beginFrame(CameraInfo3D(&cameraPosition, &cameraLookAt));
  {
    engine->renderer.renderer3D.usePipeline(stapip);
    stapip.core.render(bag.get());
  }
  engine->renderer.endFrame();
}

void TerrainGame::buildScene() {
  vertices.clear();
  colors.clear();

  generateTerrainGrid();

  for (int i = 0; i < SCENE_OBJECT_COUNT; ++i) {
    const SceneObjectData& o = SCENE_OBJECTS[i];
    switch (o.type) {
      case 1: addSphere(vertices, colors, o); break;
      case 2: addCylinder(vertices, colors, o); break;
      case 3: addCone(vertices, colors, o); break;
      default: addBox(vertices, colors, o); break;
    }
  }

  infoBag = std::make_unique<StaPipInfoBag>();
  infoBag->model = &model;
  infoBag->shadingType = TyraShadingFlat;
  infoBag->fullClipChecks = false;

  colorBag = std::make_unique<StaPipColorBag>();
  colorBag->many = colors.data();

  bag = std::make_unique<StaPipBag>();
  bag->info = infoBag.get();
  bag->color = colorBag.get();
  bag->vertices = vertices.data();
  bag->count = static_cast<u32>(vertices.size());
  bag->texture = nullptr;
  bag->lighting = nullptr;
}

void TerrainGame::generateTerrainGrid() {
  // Cap the amount of quads so big terrains stay PS2-friendly.
  // Cell size grows with terrain size instead.
  const u32 maxCells = 32;
  const u32 cellsX = TERRAIN_WIDTH > maxCells ? maxCells : (u32)TERRAIN_WIDTH;
  const u32 cellsZ = TERRAIN_DEPTH > maxCells ? maxCells : (u32)TERRAIN_DEPTH;
  const float stepX = TERRAIN_WIDTH / cellsX;
  const float stepZ = TERRAIN_DEPTH / cellsZ;
  const float startX = -TERRAIN_WIDTH * 0.5F;
  const float startZ = -TERRAIN_DEPTH * 0.5F;

  // Two greens in a checker pattern, so the grid is visible.
  // PS2 colors: RGB 0-255, alpha 0-128.
  const Color colorA(96.0F, 160.0F, 72.0F, 128.0F);
  const Color colorB(74.0F, 128.0F, 56.0F, 128.0F);

  for (u32 z = 0; z < cellsZ; ++z) {
    for (u32 x = 0; x < cellsX; ++x) {
      const float x0 = startX + x * stepX;
      const float x1 = x0 + stepX;
      const float z0 = startZ + z * stepZ;
      const float z1 = z0 + stepZ;
      const Color& c = ((x + z) % 2 == 0) ? colorA : colorB;

      vertices.push_back(Vec4(x0, 0.0F, z0, 1.0F));
      vertices.push_back(Vec4(x1, 0.0F, z0, 1.0F));
      vertices.push_back(Vec4(x0, 0.0F, z1, 1.0F));
      vertices.push_back(Vec4(x1, 0.0F, z0, 1.0F));
      vertices.push_back(Vec4(x1, 0.0F, z1, 1.0F));
      vertices.push_back(Vec4(x0, 0.0F, z1, 1.0F));

      for (int i = 0; i < 6; ++i) colors.push_back(c);
    }
  }
}

void TerrainGame::updateCameraOrbit() {
  orbitAngle += 0.005F;
  const float diag = TERRAIN_WIDTH > TERRAIN_DEPTH ? TERRAIN_WIDTH : TERRAIN_DEPTH;
  const float orbitRadius = diag * 0.9F;
  const float orbitHeight = diag * 0.55F;

  cameraPosition.x = orbitRadius * cosf(orbitAngle);
  cameraPosition.y = orbitHeight;
  cameraPosition.z = orbitRadius * sinf(orbitAngle);
}

}  // namespace {{NAME_UPPER_NS}}
)";

// ---------------------------------------------------------------------------
// Legacy templates (v1, before scene objects). Kept verbatim so that projects
// generated by older editor versions can be recognized as unedited and safely
// regenerated. Do not modify.
// ---------------------------------------------------------------------------

static const char* TPL_GAME_HPP_V1 = R"(#pragma once

#include <tyra>
#include <memory>
#include <vector>

namespace {{NAME_UPPER_NS}} {

class TerrainGame : public Tyra::Game {
 public:
  explicit TerrainGame(Tyra::Engine* engine);
  ~TerrainGame();

  void init() override;
  void loop() override;

 private:
  void generateTerrainGrid();
  void updateCameraOrbit();

  Tyra::Engine* engine;
  Tyra::StaticPipeline stapip;

  Tyra::Vec4 cameraPosition, cameraLookAt;
  float orbitAngle;

  std::vector<Tyra::Vec4> vertices;
  std::vector<Tyra::Color> colors;

  Tyra::M4x4 model;
  std::unique_ptr<Tyra::StaPipBag> bag;
  std::unique_ptr<Tyra::StaPipInfoBag> infoBag;
  std::unique_ptr<Tyra::StaPipColorBag> colorBag;
};

}  // namespace {{NAME_UPPER_NS}}
)";

static const char* TPL_GAME_CPP_V1 = R"(#include "terrain_game.hpp"
#include "terrain_config.hpp"
#include <math.h>

namespace {{NAME_UPPER_NS}} {

using namespace Tyra;

TerrainGame::TerrainGame(Engine* t_engine)
    : engine(t_engine), orbitAngle(0.0F), model(M4x4::Identity) {}

TerrainGame::~TerrainGame() {}

void TerrainGame::init() {
  stapip.setRenderer(&engine->renderer.core);

  // Sky blue background
  engine->renderer.setClearScreenColor(Color(64.0F, 140.0F, 200.0F));

  cameraLookAt = Vec4(0.0F, 0.0F, 0.0F);
  updateCameraOrbit();

  generateTerrainGrid();
}

void TerrainGame::loop() {
  updateCameraOrbit();

  engine->renderer.beginFrame(CameraInfo3D(&cameraPosition, &cameraLookAt));
  {
    engine->renderer.renderer3D.usePipeline(stapip);
    stapip.core.render(bag.get());
  }
  engine->renderer.endFrame();
}

void TerrainGame::generateTerrainGrid() {
  // Cap the amount of quads so big terrains stay PS2-friendly.
  // Cell size grows with terrain size instead.
  const u32 maxCells = 32;
  const u32 cellsX = TERRAIN_WIDTH > maxCells ? maxCells : (u32)TERRAIN_WIDTH;
  const u32 cellsZ = TERRAIN_DEPTH > maxCells ? maxCells : (u32)TERRAIN_DEPTH;
  const float stepX = TERRAIN_WIDTH / cellsX;
  const float stepZ = TERRAIN_DEPTH / cellsZ;
  const float startX = -TERRAIN_WIDTH * 0.5F;
  const float startZ = -TERRAIN_DEPTH * 0.5F;

  // Two greens in a checker pattern, so the grid is visible.
  // PS2 colors: RGB 0-255, alpha 0-128.
  const Color colorA(96.0F, 160.0F, 72.0F, 128.0F);
  const Color colorB(74.0F, 128.0F, 56.0F, 128.0F);

  vertices.clear();
  colors.clear();
  vertices.reserve(cellsX * cellsZ * 6);
  colors.reserve(cellsX * cellsZ * 6);

  for (u32 z = 0; z < cellsZ; ++z) {
    for (u32 x = 0; x < cellsX; ++x) {
      const float x0 = startX + x * stepX;
      const float x1 = x0 + stepX;
      const float z0 = startZ + z * stepZ;
      const float z1 = z0 + stepZ;
      const Color& c = ((x + z) % 2 == 0) ? colorA : colorB;

      const Vec4 v00(x0, 0.0F, z0, 1.0F);
      const Vec4 v10(x1, 0.0F, z0, 1.0F);
      const Vec4 v01(x0, 0.0F, z1, 1.0F);
      const Vec4 v11(x1, 0.0F, z1, 1.0F);

      vertices.push_back(v00);
      vertices.push_back(v10);
      vertices.push_back(v01);
      vertices.push_back(v10);
      vertices.push_back(v11);
      vertices.push_back(v01);

      for (int i = 0; i < 6; ++i) colors.push_back(c);
    }
  }

  infoBag = std::make_unique<StaPipInfoBag>();
  infoBag->model = &model;
  infoBag->shadingType = TyraShadingFlat;
  infoBag->fullClipChecks = false;

  colorBag = std::make_unique<StaPipColorBag>();
  colorBag->many = colors.data();

  bag = std::make_unique<StaPipBag>();
  bag->info = infoBag.get();
  bag->color = colorBag.get();
  bag->vertices = vertices.data();
  bag->count = static_cast<u32>(vertices.size());
  bag->texture = nullptr;
  bag->lighting = nullptr;
}

void TerrainGame::updateCameraOrbit() {
  orbitAngle += 0.005F;
  const float diag = TERRAIN_WIDTH > TERRAIN_DEPTH ? TERRAIN_WIDTH : TERRAIN_DEPTH;
  const float orbitRadius = diag * 0.9F;
  const float orbitHeight = diag * 0.55F;

  cameraPosition.x = orbitRadius * cosf(orbitAngle);
  cameraPosition.y = orbitHeight;
  cameraPosition.z = orbitRadius * sinf(orbitAngle);
}

}  // namespace {{NAME_UPPER_NS}}
)";

static const char* TPL_RUN_PS1 = R"($ConfigFile = Join-Path $PSScriptRoot './windows-pcsx2.ps1'
. $ConfigFile

RunPCSX2
)";

static const char* TPL_PCSX2_PS1 = R"PS1(# =======================
$CUSTOM_PCSX2_PATH = "" # "D:/My/Path/To/PCSX2"
# =======================

function GetTargetELFName {
    return (Select-String -Path './Makefile' -Pattern "[^ ]*.elf").Matches.Value
}

function FindPCSX2Directory {
    if (-not [string]::IsNullOrEmpty($CUSTOM_PCSX2_PATH)) {
        return $CUSTOM_PCSX2_PATH
    }
    else {
        $pcsx2Path = "${Env:ProgramFiles}/PCSX2"
        $pcsx2Pathx86 = "${Env:ProgramFiles(x86)}/PCSX2"

        if (Test-Path -Path $pcsx2Path) {
            return $pcsx2Path
        }
        elseif (Test-Path -Path $pcsx2Pathx86) {
            return $pcsx2Pathx86
        }
        else {
            throw "PCSX2 directory not found!"
        }
    }
}

function FindPCSX2Executable {
    param ([string]$directory)

    foreach ($name in 'pcsx2.exe', 'pcsx2-qt.exe') {
        if (Test-Path -Path (Join-Path $directory $name)) { return $name }
    }
    throw "PCSX2 executable not found in: $directory!"
}

function RunPCSX2 {
    $dirPath = FindPCSX2Directory
    $isNewVersion = Test-Path -Path "$dirPath/qt.conf"
    $executableName = FindPCSX2Executable -directory $dirPath
    $executableNameWithoutExt = (Split-Path $executableName -Leaf).Split('.')[0]
    $targetFileName = "$PWD/bin/$(GetTargetELFName)"

    Stop-Process -Name $executableNameWithoutExt -ErrorAction 'SilentlyContinue'

    if ($isNewVersion) {
        Start-Process -FilePath "$dirPath/$executableName" -ArgumentList "-elf", $targetFileName
    }
    else {
        Start-Process -FilePath "$dirPath/$executableName" -ArgumentList "--elf=$targetFileName"
    }
}
)PS1";

static const char* TPL_GITIGNORE = R"(obj/
bin/*.elf
)";

static const char* TPL_DIR_KEEP = "*\n!.gitignore\n";

static std::string floatLit(float v) {
    char buf[40];
    std::snprintf(buf, sizeof(buf), "%.6g", (double)v);
    std::string s = buf;
    // "8" -> "8.0": the F suffix is only valid on floating-point literals
    if (s.find('.') == std::string::npos && s.find('e') == std::string::npos &&
        s.find("inf") == std::string::npos && s.find("nan") == std::string::npos)
        s += ".0";
    return s + "F";
}

static std::string vec3Init(const float* v) {
    return "{" + floatLit(v[0]) + ", " + floatLit(v[1]) + ", " + floatLit(v[2]) + "}";
}

// inc/scene_data.hpp - pure data mirror of project.json, regenerated on build
static std::string sceneDataContent(const Project& p, const std::string& ns) {
    std::ostringstream out;
    out << "// Generated by tyra-editor. Do not edit - regenerated on every build.\n"
           "#pragma once\n"
           "\n"
           "namespace "
        << ns
        << " {\n"
           "\n"
           "struct SceneObjectData {\n"
           "  int type;  // 0=box 1=sphere 2=cylinder 3=cone\n"
           "  float position[3];\n"
           "  float rotation[3];  // degrees\n"
           "  float scale[3];\n"
           "  float color[3];  // 0..1\n"
           "};\n"
           "\n"
           "constexpr int SCENE_OBJECT_COUNT = "
        << p.objects.size() << ";\n"
        << "constexpr SceneObjectData SCENE_OBJECTS[SCENE_OBJECT_COUNT > 0 ? "
           "SCENE_OBJECT_COUNT : 1] = {\n";
    if (p.objects.empty()) {
        out << "    {0, {0, 0, 0}, {0, 0, 0}, {1, 1, 1}, {1, 1, 1}},\n";
    } else {
        for (const SceneObject& o : p.objects) {
            out << "    {" << (int)o.type << ", " << vec3Init(o.position) << ", "
                << vec3Init(o.rotation) << ", " << vec3Init(o.scale) << ", "
                << vec3Init(o.color) << "},  // " << o.name << "\n";
        }
    }
    out << "};\n"
           "\n"
           "}  // namespace "
        << ns << "\n";
    return out.str();
}

static std::string sanitizeNamespace(const std::string& name) {
    // Project name -> valid C++ namespace: letters/digits/underscore, no leading digit
    std::string ns;
    for (char c : name) {
        if (isalnum((unsigned char)c) || c == '_')
            ns += c;
        else
            ns += '_';
    }
    if (ns.empty() || isdigit((unsigned char)ns[0])) ns = "Game" + ns;
    if (!ns.empty() && islower((unsigned char)ns[0])) ns[0] = (char)toupper((unsigned char)ns[0]);
    return ns;
}

static std::string fillTemplate(const Project& p, const char* tpl) {
    // docker compose project name: lowercase, must start with letter/digit
    std::string nameLower;
    for (char c : p.name) nameLower += (char)tolower((unsigned char)c);
    if (nameLower.empty() || !isalnum((unsigned char)nameLower[0]))
        nameLower = "tyra-" + nameLower;

    std::string s = tpl;
    s = replaceAll(s, "{{NAME_LOWER}}", nameLower);
    s = replaceAll(s, "{{NAME}}", p.name);
    s = replaceAll(s, "{{NAME_UPPER_NS}}", sanitizeNamespace(p.name));
    s = replaceAll(s, "{{WIDTH}}", std::to_string(p.terrain.width));
    s = replaceAll(s, "{{DEPTH}}", std::to_string(p.terrain.depth));
    return s;
}

bool matchesLegacy(const Project& p, const std::string& relativePath,
                   const std::string& content) {
    const char* tpl = nullptr;
    if (relativePath == "src\\terrain_game.cpp")
        tpl = TPL_GAME_CPP_V1;
    else if (relativePath == "inc\\terrain_game.hpp")
        tpl = TPL_GAME_HPP_V1;
    if (!tpl) return false;
    return content == fillTemplate(p, tpl);
}

std::vector<File> generate(const Project& p) {
    const std::string ns = sanitizeNamespace(p.name);
    auto fill = [&](const char* tpl) { return fillTemplate(p, tpl); };

    return {
        {"Makefile", fill(TPL_MAKEFILE)},
        {"Dockerfile", fill(TPL_DOCKERFILE)},
        {"docker-compose.yml", fill(TPL_COMPOSE)},
        {"src\\main.cpp", fill(TPL_MAIN_CPP)},
        {"src\\terrain_game.cpp", fill(TPL_GAME_CPP)},
        {"inc\\terrain_game.hpp", fill(TPL_GAME_HPP)},
        {"inc\\terrain_config.hpp", fill(TPL_TERRAIN_CONFIG_HPP)},
        {"inc\\scene_data.hpp", sceneDataContent(p, ns)},
        {"run.ps1", fill(TPL_RUN_PS1)},
        {"windows-pcsx2.ps1", fill(TPL_PCSX2_PS1)},
        {".gitignore", fill(TPL_GITIGNORE)},
        {"res\\.gitignore", TPL_DIR_KEEP},
        {"bin\\.gitignore", TPL_DIR_KEEP},
        {"obj\\.gitignore", TPL_DIR_KEEP},
    };
}

}  // namespace templates
