#include "templates.hpp"

#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <sstream>

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#include "objparser.hpp"
#include "project.hpp"

namespace templates {

// Unique model paths referenced by the scene, in first-use order.
// The index in this list == SceneObjectData::model in the generated code.
static std::vector<std::string> collectModelPaths(const Project& p) {
    std::vector<std::string> paths;
    for (const SceneObject& o : p.objects) {
        if (o.type != PrimitiveType::Model || o.modelPath.empty()) continue;
        bool seen = false;
        for (const auto& e : paths) seen |= (e == o.modelPath);
        if (!seen) paths.push_back(o.modelPath);
    }
    return paths;
}

static int modelIndexOf(const Project& p, const SceneObject& o) {
    if (o.type != PrimitiveType::Model || o.modelPath.empty()) return -1;
    const auto paths = collectModelPaths(p);
    for (size_t i = 0; i < paths.size(); ++i)
        if (paths[i] == o.modelPath) return (int)i;
    return -1;
}

static std::string replaceAll(std::string s, const std::string& from, const std::string& to) {
    size_t pos = 0;
    while ((pos = s.find(from, pos)) != std::string::npos) {
        s.replace(pos, from.size(), to);
        pos += to.size();
    }
    return s;
}

// ---------------------------------------------------------------------------
// Tyra game project templates. Placeholders: {{NAME}}, {{WIDTH}}, {{DEPTH}}
// ---------------------------------------------------------------------------

static const char* TPL_MAKEFILE = R"(TARGET      := {{NAME}}.elf
ENGINEDIR	:= /tyra/engine

#The Directories, Source, Includes, Objects, Binary and Resources
SRCDIR      := src
INCDIR      := inc
BUILDDIR    := obj
TARGETDIR   := bin
RESDIR      := res
SRCEXT      := cpp
VSMEXT		:= vsm
VCLEXT		:= vcl
VCLPPEXT	:= vclpp
DEPEXT      := d
OBJEXT      := o

#Flags, Libraries and Includes
CFLAGS      :=
LIB         := -ltyra
LIBDIRS     := -L$(ENGINEDIR)/bin
INC         := -I$(INCDIR) -I$(ENGINEDIR)/inc
INCDEP      := -I$(INCDIR) -I$(ENGINEDIR)/inc

include /tyra/Makefile.base
)";

static const char* TPL_DOCKERFILE = R"(# syntax=docker/dockerfile:1
FROM h4570/tyra

RUN apt-get update
RUN apt-get install git -y

WORKDIR /src
CMD ["/bin/bash"]
)";

// Per-project container (no fixed container_name - avoids conflicts between
// projects). The Tyra engine lives in a volume shared by all projects, so it
// is cloned & compiled only once.
static const char* TPL_COMPOSE = R"(name: {{NAME_LOWER}}
volumes:
  tyra-game-volume:
  tyra-engine:
    name: tyra-engine-shared
services:
  compiler:
    environment:
      TERM: xterm-256color
    network_mode: host
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    volumes:
      - tyra-game-volume:/src
      - tyra-engine:/tyra
      - ./:/host
)";

static const char* TPL_MAIN_CPP = R"(#include <tyra>
#include "terrain_game.hpp"

int main() {
  Tyra::Engine engine;
  {{NAME_UPPER_NS}}::TerrainGame game(&engine);
  engine.run(&game);
  SleepThread();
  return 0;
}
)";

static const char* TPL_TERRAIN_CONFIG_HPP =
    R"(// Generated by tyra-editor. Do not edit - regenerated on every build.
#pragma once

namespace {{NAME_UPPER_NS}} {

constexpr float TERRAIN_WIDTH = {{WIDTH}}.0F;  // world units, X axis
constexpr float TERRAIN_DEPTH = {{DEPTH}}.0F;  // world units, Z axis

// Project preferences (Project > Preferences in the editor)
constexpr int TERRAIN_MAX_CELLS = {{DETAIL}};
constexpr bool CLIP_PRECISE = {{CLIP_PRECISE}};
constexpr float SKY_R = {{SKY_R}};  // 0-255
constexpr float SKY_G = {{SKY_G}};
constexpr float SKY_B = {{SKY_B}};
constexpr float EYE_HEIGHT = {{EYE_HEIGHT}};
constexpr float WALK_SPEED = {{WALK_SPEED}};
constexpr float LOOK_SPEED = {{LOOK_SPEED}};    // multiplier
constexpr float ORBIT_SPEED = {{ORBIT_SPEED}};  // multiplier
constexpr float GRAVITY = {{GRAVITY}};          // units/s^2
constexpr float JUMP_SPEED = {{JUMP_SPEED}};    // units/s
constexpr bool SKY_DOME = {{SKY_DOME}};
constexpr float SKY_TOP_R = {{SKY_TOP_R}};  // 0-255, dome zenith color
constexpr float SKY_TOP_G = {{SKY_TOP_G}};
constexpr float SKY_TOP_B = {{SKY_TOP_B}};
// (SCENE_ prefix: the PS2SDK math3d.h already claims LIGHT_AMBIENT etc.)
constexpr float SCENE_LIGHT_X = {{LIGHT_X}};  // normalized, points TO the light
constexpr float SCENE_LIGHT_Y = {{LIGHT_Y}};
constexpr float SCENE_LIGHT_Z = {{LIGHT_Z}};
constexpr float SCENE_AMBIENT = {{AMBIENT}};  // 0..1
constexpr float SCENE_DIFFUSE = {{DIFFUSE}};  // 0..1

}  // namespace {{NAME_UPPER_NS}}
)";

static const char* TPL_GAME_HPP_ORBIT =
    R"(// Generated by tyra-editor. Delete this line to take ownership of this file.
#pragma once

#include <tyra>
#include <memory>
#include <vector>
#include "scripts/script.hpp"

namespace {{NAME_UPPER_NS}} {

class TerrainGame : public Tyra::Game {
 public:
  explicit TerrainGame(Tyra::Engine* engine);
  ~TerrainGame();

  void init() override;
  void loop() override;

 private:
  void buildScene();
  void generateTerrainGrid();
  void updateCameraOrbit();

  Tyra::Engine* engine;
  Tyra::StaticPipeline stapip;

  Tyra::Vec4 cameraPosition, cameraLookAt;
  float orbitAngle;

  std::vector<Tyra::Vec4> vertices;
  std::vector<Tyra::Color> colors;

  Tyra::M4x4 model;
  std::unique_ptr<Tyra::StaPipBag> bag;
  std::unique_ptr<Tyra::StaPipInfoBag> infoBag;
  std::unique_ptr<Tyra::StaPipColorBag> colorBag;

  // Scene objects at runtime (mutable by scripts/physics); geometry per object
  struct ObjectGeometry {
    std::vector<Tyra::Vec4> vertices;
    std::vector<Tyra::Color> colors;
    std::unique_ptr<Tyra::StaPipBag> bag;
    std::unique_ptr<Tyra::StaPipInfoBag> infoBag;
    std::unique_ptr<Tyra::StaPipColorBag> colorBag;
  };
  std::vector<RuntimeObject> runtimeObjects;
  std::vector<ObjectGeometry> objectGeometry;
  ObjectGeometry skyDome;
  float skyHorizonR = 0, skyHorizonG = 0, skyHorizonB = 0;
  std::vector<Tyra::Sprite> hudSprites;

  void buildSkyDome();
  void rebuildObjectGeometry(int index);
  void updateObjectPhysics();
  void renderScene();

  ScriptContext scriptCtx;
};

}  // namespace {{NAME_UPPER_NS}}
)";

static const char* TPL_GAME_HPP_FPP =
    R"(// Generated by tyra-editor. Delete this line to take ownership of this file.
#pragma once

#include <tyra>
#include <memory>
#include <vector>
#include "scripts/script.hpp"

namespace {{NAME_UPPER_NS}} {

class TerrainGame : public Tyra::Game {
 public:
  explicit TerrainGame(Tyra::Engine* engine);
  ~TerrainGame();

  void init() override;
  void loop() override;

 private:
  void buildScene();
  void generateTerrainGrid();
  void updatePlayer();

  Tyra::Engine* engine;
  Tyra::StaticPipeline stapip;

  Tyra::Vec4 cameraPosition, cameraLookAt;
  float playerX, playerZ, yaw, pitch;
  float playerY, playerVelY;  // feet height + vertical velocity (physics)

  std::vector<Tyra::Vec4> vertices;
  std::vector<Tyra::Color> colors;

  Tyra::M4x4 model;
  std::unique_ptr<Tyra::StaPipBag> bag;
  std::unique_ptr<Tyra::StaPipInfoBag> infoBag;
  std::unique_ptr<Tyra::StaPipColorBag> colorBag;

  // Scene objects at runtime (mutable by scripts/physics); geometry per object
  struct ObjectGeometry {
    std::vector<Tyra::Vec4> vertices;
    std::vector<Tyra::Color> colors;
    std::unique_ptr<Tyra::StaPipBag> bag;
    std::unique_ptr<Tyra::StaPipInfoBag> infoBag;
    std::unique_ptr<Tyra::StaPipColorBag> colorBag;
  };
  std::vector<RuntimeObject> runtimeObjects;
  std::vector<ObjectGeometry> objectGeometry;
  ObjectGeometry skyDome;
  float skyHorizonR = 0, skyHorizonG = 0, skyHorizonB = 0;
  std::vector<Tyra::Sprite> hudSprites;

  void buildSkyDome();
  void rebuildObjectGeometry(int index);
  void updateObjectPhysics();
  void renderScene();

  ScriptContext scriptCtx;
};

}  // namespace {{NAME_UPPER_NS}}
)";

// Game .cpp is composed as: PROLOG + <template>_HEAD + SCENE + <template>_TAIL + FOOTER
static const char* TPL_GAME_CPP_PROLOG =
    R"(// Generated by tyra-editor. Delete this line to take ownership of this file.
#include "terrain_game.hpp"
#include "terrain_config.hpp"
#include "scene_data.hpp"
#include "model_data.gen.hpp"
#include "hud_data.gen.hpp"
#include <math.h>

namespace {{NAME_UPPER_NS}} {

using namespace Tyra;

namespace {

constexpr float PI = 3.14159265358979F;

struct V3 {
  float x, y, z;
};

/** Rotation order: X, then Y, then Z (same as the editor viewport). */
V3 rotated(const V3& v, const float* rotDeg) {
  V3 r = v;
  const float rx = rotDeg[0] * PI / 180.0F;
  const float ry = rotDeg[1] * PI / 180.0F;
  const float rz = rotDeg[2] * PI / 180.0F;
  {
    const float c = cosf(rx), s = sinf(rx);
    const float y = r.y * c - r.z * s, z = r.y * s + r.z * c;
    r.y = y, r.z = z;
  }
  {
    const float c = cosf(ry), s = sinf(ry);
    const float x = r.x * c + r.z * s, z = -r.x * s + r.z * c;
    r.x = x, r.z = z;
  }
  {
    const float c = cosf(rz), s = sinf(rz);
    const float x = r.x * c - r.y * s, y = r.x * s + r.y * c;
    r.x = x, r.y = y;
  }
  return r;
}

/** Directional light (Project > Preferences), baked into vertex colors. */
float shadeOf(const V3& n) {
  float d = n.x * SCENE_LIGHT_X + n.y * SCENE_LIGHT_Y + n.z * SCENE_LIGHT_Z;
  if (d < 0.0F) d = 0.0F;
  float s = SCENE_AMBIENT + SCENE_DIFFUSE * d;
  return s > 1.0F ? 1.0F : s;
}

void pushVert(std::vector<Vec4>& verts, std::vector<Color>& cols,
              const SceneObjectData& o, V3 p, V3 n) {
  p.x *= o.scale[0], p.y *= o.scale[1], p.z *= o.scale[2];
  p = rotated(p, o.rotation);
  n = rotated(n, o.rotation);
  const float shade = shadeOf(n);
  verts.push_back(Vec4(p.x + o.position[0], p.y + o.position[1],
                       p.z + o.position[2], 1.0F));
  cols.push_back(Color(o.color[0] * 255.0F * shade, o.color[1] * 255.0F * shade,
                       o.color[2] * 255.0F * shade, 128.0F));
}

void pushQuad(std::vector<Vec4>& verts, std::vector<Color>& cols,
              const SceneObjectData& o, V3 a, V3 b, V3 c, V3 d, V3 n) {
  pushVert(verts, cols, o, a, n);
  pushVert(verts, cols, o, b, n);
  pushVert(verts, cols, o, c, n);
  pushVert(verts, cols, o, a, n);
  pushVert(verts, cols, o, c, n);
  pushVert(verts, cols, o, d, n);
}

void addBox(std::vector<Vec4>& verts, std::vector<Color>& cols,
            const SceneObjectData& o) {
  const float h = 0.5F;
  pushQuad(verts, cols, o, {h, -h, -h}, {h, h, -h}, {h, h, h}, {h, -h, h}, {1, 0, 0});
  pushQuad(verts, cols, o, {-h, -h, h}, {-h, h, h}, {-h, h, -h}, {-h, -h, -h}, {-1, 0, 0});
  pushQuad(verts, cols, o, {-h, h, -h}, {-h, h, h}, {h, h, h}, {h, h, -h}, {0, 1, 0});
  pushQuad(verts, cols, o, {-h, -h, h}, {-h, -h, -h}, {h, -h, -h}, {h, -h, h}, {0, -1, 0});
  pushQuad(verts, cols, o, {-h, -h, h}, {h, -h, h}, {h, h, h}, {-h, h, h}, {0, 0, 1});
  pushQuad(verts, cols, o, {h, -h, -h}, {-h, -h, -h}, {-h, h, -h}, {h, h, -h}, {0, 0, -1});
}

void addSphere(std::vector<Vec4>& verts, std::vector<Color>& cols,
               const SceneObjectData& o) {
  const int stacks = 10, slices = 14;
  const float r = 0.5F;
  for (int st = 0; st < stacks; ++st) {
    const float t0 = PI * st / stacks, t1 = PI * (st + 1) / stacks;
    for (int sl = 0; sl < slices; ++sl) {
      const float p0 = 2.0F * PI * sl / slices, p1 = 2.0F * PI * (sl + 1) / slices;
      const V3 v00 = {r * sinf(t0) * cosf(p0), r * cosf(t0), r * sinf(t0) * sinf(p0)};
      const V3 v01 = {r * sinf(t0) * cosf(p1), r * cosf(t0), r * sinf(t0) * sinf(p1)};
      const V3 v10 = {r * sinf(t1) * cosf(p0), r * cosf(t1), r * sinf(t1) * sinf(p0)};
      const V3 v11 = {r * sinf(t1) * cosf(p1), r * cosf(t1), r * sinf(t1) * sinf(p1)};
      // Smooth shading: normal of a unit-sphere vertex is the vertex itself.
      const V3 n00 = {v00.x * 2, v00.y * 2, v00.z * 2};
      const V3 n01 = {v01.x * 2, v01.y * 2, v01.z * 2};
      const V3 n10 = {v10.x * 2, v10.y * 2, v10.z * 2};
      const V3 n11 = {v11.x * 2, v11.y * 2, v11.z * 2};
      pushVert(verts, cols, o, v00, n00);
      pushVert(verts, cols, o, v10, n10);
      pushVert(verts, cols, o, v11, n11);
      pushVert(verts, cols, o, v00, n00);
      pushVert(verts, cols, o, v11, n11);
      pushVert(verts, cols, o, v01, n01);
    }
  }
}

void addCylinder(std::vector<Vec4>& verts, std::vector<Color>& cols,
                 const SceneObjectData& o) {
  const int seg = 16;
  const float r = 0.5F, h = 0.5F;
  for (int i = 0; i < seg; ++i) {
    const float a0 = 2.0F * PI * i / seg, a1 = 2.0F * PI * (i + 1) / seg;
    const float x0 = r * cosf(a0), z0 = r * sinf(a0);
    const float x1 = r * cosf(a1), z1 = r * sinf(a1);
    const V3 n0 = {cosf(a0), 0, sinf(a0)}, n1 = {cosf(a1), 0, sinf(a1)};
    // side (smooth)
    pushVert(verts, cols, o, {x0, -h, z0}, n0);
    pushVert(verts, cols, o, {x0, h, z0}, n0);
    pushVert(verts, cols, o, {x1, h, z1}, n1);
    pushVert(verts, cols, o, {x0, -h, z0}, n0);
    pushVert(verts, cols, o, {x1, h, z1}, n1);
    pushVert(verts, cols, o, {x1, -h, z1}, n1);
    // caps
    pushVert(verts, cols, o, {0, h, 0}, {0, 1, 0});
    pushVert(verts, cols, o, {x1, h, z1}, {0, 1, 0});
    pushVert(verts, cols, o, {x0, h, z0}, {0, 1, 0});
    pushVert(verts, cols, o, {0, -h, 0}, {0, -1, 0});
    pushVert(verts, cols, o, {x0, -h, z0}, {0, -1, 0});
    pushVert(verts, cols, o, {x1, -h, z1}, {0, -1, 0});
  }
}

void addCone(std::vector<Vec4>& verts, std::vector<Color>& cols,
             const SceneObjectData& o) {
  const int seg = 16;
  const float r = 0.5F, h = 0.5F;
  const float nl = 0.894F, ny = 0.447F;  // side normal for r=0.5, h=1
  for (int i = 0; i < seg; ++i) {
    const float a0 = 2.0F * PI * i / seg, a1 = 2.0F * PI * (i + 1) / seg;
    const float am = (a0 + a1) * 0.5F;
    const float x0 = r * cosf(a0), z0 = r * sinf(a0);
    const float x1 = r * cosf(a1), z1 = r * sinf(a1);
    // side
    pushVert(verts, cols, o, {0, h, 0}, {nl * cosf(am), ny, nl * sinf(am)});
    pushVert(verts, cols, o, {x1, -h, z1}, {nl * cosf(a1), ny, nl * sinf(a1)});
    pushVert(verts, cols, o, {x0, -h, z0}, {nl * cosf(a0), ny, nl * sinf(a0)});
    // base
    pushVert(verts, cols, o, {0, -h, 0}, {0, -1, 0});
    pushVert(verts, cols, o, {x0, -h, z0}, {0, -1, 0});
    pushVert(verts, cols, o, {x1, -h, z1}, {0, -1, 0});
  }
}

void addModel(std::vector<Vec4>& verts, std::vector<Color>& cols,
              const SceneObjectData& o) {
  if (o.model < 0 || o.model >= MODEL_COUNT) return;
  const ModelData& m = MODELS[o.model];
  for (int i = 0; i < m.vertexCount; ++i) {
    const float* v = m.verts + i * 6;
    pushVert(verts, cols, o, {v[0], v[1], v[2]}, {v[3], v[4], v[5]});
  }
}

}  // namespace
)";

// Orbit template: the camera slowly circles the terrain center.
static const char* TPL_GAME_CPP_ORBIT_HEAD = R"(
TerrainGame::TerrainGame(Engine* t_engine)
    : engine(t_engine), orbitAngle(0.0F), model(M4x4::Identity) {}

TerrainGame::~TerrainGame() {}

void TerrainGame::init() {
  // Engine clipper fix: the default clipMargin (-10.0F) moves the near
  // clipping plane ~10 units away from the camera, cutting away nearby
  // geometry. Clip right in front of the real near plane instead.
  // (read by the clipper during setRenderer below)
  PlanesClipAlgorithm::clipMargin =
      -(engine->renderer.core.getSettings().getNear() + 0.5F);

  stapip.setRenderer(&engine->renderer.core);

  engine->renderer.setClearScreenColor(Color(SKY_R, SKY_G, SKY_B));

  cameraLookAt = Vec4(0.0F, 0.0F, 0.0F);
  updateCameraOrbit();

  buildScene();

  scriptCtx.engine = engine;
  scriptCtx.objects = runtimeObjects.data();
  scriptCtx.objectCount = (int)runtimeObjects.size();
  scriptCtx.skyColor = Color(SKY_R, SKY_G, SKY_B);
  scriptCtx.playerPosition = cameraPosition;
  for (Script* script : getScripts()) script->init(scriptCtx);

  // HUD sprites (see hud_data.gen.hpp)
  const auto& screen = engine->renderer.core.getSettings();
  hudSprites.reserve(HUD_COUNT);
  for (int i = 0; i < HUD_COUNT; ++i) {
    const HudImageData& h = HUD_IMAGES[i];
    Sprite sprite;
    sprite.mode = SpriteMode::MODE_STRETCH;
    sprite.size = Vec2(h.w, h.h);
    sprite.position = Vec2(h.x * screen.getWidth() - h.w * 0.5F,
                           h.y * screen.getHeight() - h.h * 0.5F);
    hudSprites.push_back(sprite);
    auto* texture =
        engine->renderer.getTextureRepository().add(FileUtils::fromCwd(h.path));
    texture->addLink(hudSprites.back().id);
  }
}

void TerrainGame::loop() {
  updateCameraOrbit();

  scriptCtx.playerPosition = cameraPosition;
  for (Script* script : getScripts()) script->update(scriptCtx);
  engine->renderer.setClearScreenColor(scriptCtx.skyColor);

  updateObjectPhysics();

  engine->renderer.beginFrame(CameraInfo3D(&cameraPosition, &cameraLookAt));
  {
    engine->renderer.renderer3D.usePipeline(stapip);
    renderScene();
    for (auto& sprite : hudSprites) engine->renderer.renderer2D.render(sprite);
  }
  engine->renderer.endFrame();
}
)";

// Shared scene/terrain mesh building and runtime object management.
static const char* TPL_GAME_CPP_SCENE = R"(
void TerrainGame::buildScene() {
  vertices.clear();
  colors.clear();

  generateTerrainGrid();

  infoBag = std::make_unique<StaPipInfoBag>();
  infoBag->model = &model;
  infoBag->shadingType = TyraShadingFlat;
  // CLIP_PRECISE (Project > Preferences): real per-triangle clipping - no
  // holes at screen edges, but costs EE time. The fast path drops whole
  // triangles that extend far beyond the screen, but is much cheaper.
  infoBag->frustumCulling = CLIP_PRECISE ? PipelineInfoBagFrustumCulling_Precise
                                         : PipelineInfoBagFrustumCulling_None;
  infoBag->fullClipChecks = CLIP_PRECISE;

  colorBag = std::make_unique<StaPipColorBag>();
  colorBag->many = colors.data();

  bag = std::make_unique<StaPipBag>();
  bag->info = infoBag.get();
  bag->color = colorBag.get();
  bag->vertices = vertices.data();
  bag->count = static_cast<u32>(vertices.size());
  bag->texture = nullptr;
  bag->lighting = nullptr;

  // Runtime copies of the scene objects - scripts and physics mutate these.
  skyHorizonR = SKY_R, skyHorizonG = SKY_G, skyHorizonB = SKY_B;
  buildSkyDome();

  runtimeObjects.assign(SCENE_OBJECT_COUNT, RuntimeObject());
  objectGeometry.clear();
  objectGeometry.resize(SCENE_OBJECT_COUNT);
  for (int i = 0; i < SCENE_OBJECT_COUNT; ++i) {
    runtimeObjects[i].data = SCENE_OBJECTS[i];
    runtimeObjects[i].visible = SCENE_OBJECTS[i].type != 4;  // spawn = marker
    runtimeObjects[i].dirty = true;
  }
}

void TerrainGame::buildSkyDome() {
  if (!SKY_DOME) return;

  const float diag = TERRAIN_WIDTH > TERRAIN_DEPTH ? TERRAIN_WIDTH : TERRAIN_DEPTH;
  float radius = diag * 1.5F;
  if (radius < 60.0F) radius = 60.0F;
  if (radius > 450.0F) radius = 450.0F;

  const int stacks = 6, slices = 14;
  auto skyAt = [&](float t) {  // t: 0 = horizon, 1 = zenith
    return Color(skyHorizonR + (SKY_TOP_R - skyHorizonR) * t,
                 skyHorizonG + (SKY_TOP_G - skyHorizonG) * t,
                 skyHorizonB + (SKY_TOP_B - skyHorizonB) * t, 128.0F);
  };
  auto domeVert = [&](int stack, int slice) {
    // Start slightly below the horizon so the seam is never visible
    const float lat = -0.06F + (PI * 0.5F + 0.06F) * stack / stacks;
    const float lon = 2.0F * PI * slice / slices;
    return Vec4(radius * cosf(lat) * cosf(lon), radius * sinf(lat),
                radius * cosf(lat) * sinf(lon), 1.0F);
  };

  skyDome.vertices.clear();
  skyDome.colors.clear();
  for (int st = 0; st < stacks; ++st) {
    const float t0 = (float)st / stacks, t1 = (float)(st + 1) / stacks;
    for (int sl = 0; sl < slices; ++sl) {
      const Vec4 v00 = domeVert(st, sl), v01 = domeVert(st, sl + 1);
      const Vec4 v10 = domeVert(st + 1, sl), v11 = domeVert(st + 1, sl + 1);
      skyDome.vertices.push_back(v00);
      skyDome.vertices.push_back(v10);
      skyDome.vertices.push_back(v11);
      skyDome.vertices.push_back(v00);
      skyDome.vertices.push_back(v11);
      skyDome.vertices.push_back(v01);
      skyDome.colors.push_back(skyAt(t0));
      skyDome.colors.push_back(skyAt(t1));
      skyDome.colors.push_back(skyAt(t1));
      skyDome.colors.push_back(skyAt(t0));
      skyDome.colors.push_back(skyAt(t1));
      skyDome.colors.push_back(skyAt(t0));
    }
  }

  skyDome.infoBag = std::make_unique<StaPipInfoBag>();
  skyDome.infoBag->model = &model;
  skyDome.infoBag->shadingType = TyraShadingGouraud;
  // Static geometry crossing the screen edges all the time - needs clipping
  skyDome.infoBag->frustumCulling = PipelineInfoBagFrustumCulling_Precise;
  skyDome.infoBag->fullClipChecks = true;
  skyDome.colorBag = std::make_unique<StaPipColorBag>();
  skyDome.colorBag->many = skyDome.colors.data();
  skyDome.bag = std::make_unique<StaPipBag>();
  skyDome.bag->info = skyDome.infoBag.get();
  skyDome.bag->color = skyDome.colorBag.get();
  skyDome.bag->vertices = skyDome.vertices.data();
  skyDome.bag->count = static_cast<u32>(skyDome.vertices.size());
  skyDome.bag->texture = nullptr;
  skyDome.bag->lighting = nullptr;
}

void TerrainGame::rebuildObjectGeometry(int index) {
  RuntimeObject& o = runtimeObjects[index];
  ObjectGeometry& g = objectGeometry[index];
  o.dirty = false;

  g.vertices.clear();
  g.colors.clear();
  switch (o.data.type) {
    case 1: addSphere(g.vertices, g.colors, o.data); break;
    case 2: addCylinder(g.vertices, g.colors, o.data); break;
    case 3: addCone(g.vertices, g.colors, o.data); break;
    case 4: break;  // spawn point - marker only
    case 5: addModel(g.vertices, g.colors, o.data); break;
    default: addBox(g.vertices, g.colors, o.data); break;
  }
  if (g.vertices.empty()) {
    g.bag.reset();
    return;
  }

  if (!g.bag) {
    g.infoBag = std::make_unique<StaPipInfoBag>();
    g.infoBag->model = &model;
    g.infoBag->shadingType = TyraShadingFlat;
    // Objects can move at runtime, but the engine caches frustum bboxes by
    // the vertex pointer (stale bbox = object culled at its old position).
    // Objects are small, so skip culling/clipping for them entirely;
    // the terrain keeps CLIP_PRECISE.
    g.infoBag->frustumCulling = PipelineInfoBagFrustumCulling_None;
    g.infoBag->fullClipChecks = false;
    g.colorBag = std::make_unique<StaPipColorBag>();
    g.bag = std::make_unique<StaPipBag>();
    g.bag->info = g.infoBag.get();
    g.bag->color = g.colorBag.get();
    g.bag->texture = nullptr;
    g.bag->lighting = nullptr;
  }
  g.colorBag->many = g.colors.data();
  g.bag->vertices = g.vertices.data();
  g.bag->count = static_cast<u32>(g.vertices.size());
}

void TerrainGame::updateObjectPhysics() {
  // GRAVITY is units/s^2; the game runs at 50 FPS
  const float gravityPerFrame = GRAVITY / (50.0F * 50.0F);
  for (RuntimeObject& o : runtimeObjects) {
    if (!o.data.physics) continue;
    const float half = 0.5F * o.data.scale[1];
    if (o.velocityY == 0.0F && o.data.position[1] <= half) continue;  // resting

    o.velocityY -= gravityPerFrame;
    o.data.position[1] += o.velocityY;
    if (o.data.position[1] <= half) {
      o.data.position[1] = half;
      o.velocityY = 0.0F;
    }
    o.dirty = true;
  }
}

void TerrainGame::renderScene() {
  // Scripts changing ctx.skyColor retint the dome horizon
  if (skyDome.bag && (scriptCtx.skyColor.r != skyHorizonR ||
                      scriptCtx.skyColor.g != skyHorizonG ||
                      scriptCtx.skyColor.b != skyHorizonB)) {
    skyHorizonR = scriptCtx.skyColor.r;
    skyHorizonG = scriptCtx.skyColor.g;
    skyHorizonB = scriptCtx.skyColor.b;
    buildSkyDome();
  }
  if (skyDome.bag) stapip.core.render(skyDome.bag.get());
  stapip.core.render(bag.get());
  for (int i = 0; i < (int)runtimeObjects.size(); ++i) {
    if (runtimeObjects[i].dirty) rebuildObjectGeometry(i);
    if (runtimeObjects[i].visible && objectGeometry[i].bag)
      stapip.core.render(objectGeometry[i].bag.get());
  }
}

void TerrainGame::generateTerrainGrid() {
  // Cap the amount of quads so big terrains stay PS2-friendly.
  // Cell size grows with terrain size instead.
  const u32 maxCells = (u32)TERRAIN_MAX_CELLS;
  const u32 cellsX = TERRAIN_WIDTH > maxCells ? maxCells : (u32)TERRAIN_WIDTH;
  const u32 cellsZ = TERRAIN_DEPTH > maxCells ? maxCells : (u32)TERRAIN_DEPTH;
  const float stepX = TERRAIN_WIDTH / cellsX;
  const float stepZ = TERRAIN_DEPTH / cellsZ;
  const float startX = -TERRAIN_WIDTH * 0.5F;
  const float startZ = -TERRAIN_DEPTH * 0.5F;

  // Two greens in a checker pattern, so the grid is visible.
  // PS2 colors: RGB 0-255, alpha 0-128. Lit by the directional light (up normal).
  const float sUp = shadeOf({0.0F, 1.0F, 0.0F});
  const Color colorA(96.0F * sUp, 160.0F * sUp, 72.0F * sUp, 128.0F);
  const Color colorB(74.0F * sUp, 128.0F * sUp, 56.0F * sUp, 128.0F);

  for (u32 z = 0; z < cellsZ; ++z) {
    for (u32 x = 0; x < cellsX; ++x) {
      const float x0 = startX + x * stepX;
      const float x1 = x0 + stepX;
      const float z0 = startZ + z * stepZ;
      const float z1 = z0 + stepZ;
      const Color& c = ((x + z) % 2 == 0) ? colorA : colorB;

      vertices.push_back(Vec4(x0, 0.0F, z0, 1.0F));
      vertices.push_back(Vec4(x1, 0.0F, z0, 1.0F));
      vertices.push_back(Vec4(x0, 0.0F, z1, 1.0F));
      vertices.push_back(Vec4(x1, 0.0F, z0, 1.0F));
      vertices.push_back(Vec4(x1, 0.0F, z1, 1.0F));
      vertices.push_back(Vec4(x0, 0.0F, z1, 1.0F));

      for (int i = 0; i < 6; ++i) colors.push_back(c);
    }
  }
}
)";

static const char* TPL_GAME_CPP_ORBIT_TAIL = R"(
void TerrainGame::updateCameraOrbit() {
  orbitAngle += 0.005F * ORBIT_SPEED;
  const float diag = TERRAIN_WIDTH > TERRAIN_DEPTH ? TERRAIN_WIDTH : TERRAIN_DEPTH;
  const float orbitRadius = diag * 0.9F;
  const float orbitHeight = diag * 0.55F;

  cameraPosition.x = orbitRadius * cosf(orbitAngle);
  cameraPosition.y = orbitHeight;
  cameraPosition.z = orbitRadius * sinf(orbitAngle);
}
)";

// FPP template: walk with the left stick, look around with the right stick.
// Axis conventions follow the official Tyra demo (v<128 = stick up).
static const char* TPL_GAME_CPP_FPP_HEAD = R"(
TerrainGame::TerrainGame(Engine* t_engine)
    : engine(t_engine),
      playerX(0.0F),
      playerZ(0.0F),
      yaw(0.0F),
      pitch(0.0F),
      playerY(0.0F),
      playerVelY(0.0F),
      model(M4x4::Identity) {}

TerrainGame::~TerrainGame() {}

void TerrainGame::init() {
  // Engine clipper fix: the default clipMargin (-10.0F) moves the near
  // clipping plane ~10 units away from the camera, cutting away nearby
  // geometry. Clip right in front of the real near plane instead.
  // (read by the clipper during setRenderer below)
  PlanesClipAlgorithm::clipMargin =
      -(engine->renderer.core.getSettings().getNear() + 0.5F);

  stapip.setRenderer(&engine->renderer.core);

  engine->renderer.setClearScreenColor(Color(SKY_R, SKY_G, SKY_B));

  // Player start: the first spawn point in the scene (if any)
  for (int i = 0; i < SCENE_OBJECT_COUNT; ++i) {
    if (SCENE_OBJECTS[i].type == 4) {
      playerX = SCENE_OBJECTS[i].position[0];
      playerZ = SCENE_OBJECTS[i].position[2];
      yaw = SCENE_OBJECTS[i].rotation[1] * PI / 180.0F;
      break;
    }
  }

  updatePlayer();
  buildScene();

  scriptCtx.engine = engine;
  scriptCtx.objects = runtimeObjects.data();
  scriptCtx.objectCount = (int)runtimeObjects.size();
  scriptCtx.skyColor = Color(SKY_R, SKY_G, SKY_B);
  scriptCtx.playerPosition = cameraPosition;
  for (Script* script : getScripts()) script->init(scriptCtx);

  // HUD sprites (see hud_data.gen.hpp)
  const auto& screen = engine->renderer.core.getSettings();
  hudSprites.reserve(HUD_COUNT);
  for (int i = 0; i < HUD_COUNT; ++i) {
    const HudImageData& h = HUD_IMAGES[i];
    Sprite sprite;
    sprite.mode = SpriteMode::MODE_STRETCH;
    sprite.size = Vec2(h.w, h.h);
    sprite.position = Vec2(h.x * screen.getWidth() - h.w * 0.5F,
                           h.y * screen.getHeight() - h.h * 0.5F);
    hudSprites.push_back(sprite);
    auto* texture =
        engine->renderer.getTextureRepository().add(FileUtils::fromCwd(h.path));
    texture->addLink(hudSprites.back().id);
  }
}

void TerrainGame::loop() {
  updatePlayer();

  scriptCtx.playerPosition = cameraPosition;
  for (Script* script : getScripts()) script->update(scriptCtx);
  engine->renderer.setClearScreenColor(scriptCtx.skyColor);

  updateObjectPhysics();

  engine->renderer.beginFrame(CameraInfo3D(&cameraPosition, &cameraLookAt));
  {
    engine->renderer.renderer3D.usePipeline(stapip);
    renderScene();
    for (auto& sprite : hudSprites) engine->renderer.renderer2D.render(sprite);
  }
  engine->renderer.endFrame();
}
)";

static const char* TPL_GAME_CPP_FPP_TAIL = R"(
namespace {

float axisValue(const u8& raw) {
  const float v = (raw - 128.0F) / 128.0F;
  return (v > -0.20F && v < 0.20F) ? 0.0F : v;  // deadzone
}

}  // namespace

void TerrainGame::updatePlayer() {
  const auto& leftJoy = engine->pad.getLeftJoyPad();
  const auto& rightJoy = engine->pad.getRightJoyPad();

  // Right stick: look around (stick right = turn right)
  yaw -= axisValue(rightJoy.h) * 0.05F * LOOK_SPEED;
  pitch -= axisValue(rightJoy.v) * 0.035F * LOOK_SPEED;
  if (pitch > 1.2F) pitch = 1.2F;
  if (pitch < -1.2F) pitch = -1.2F;

  // Left stick: walk. Forward is where the camera looks (flat).
  const float fx = sinf(yaw);
  const float fz = cosf(yaw);
  const float forward = -axisValue(leftJoy.v);
  const float strafe = axisValue(leftJoy.h);
  float nextX = playerX + (fx * forward - fz * strafe) * WALK_SPEED;
  float nextZ = playerZ + (fz * forward + fx * strafe) * WALK_SPEED;

  // Keep the player on the terrain
  const float limX = TERRAIN_WIDTH * 0.5F - 1.0F;
  const float limZ = TERRAIN_DEPTH * 0.5F - 1.0F;
  if (nextX > limX) nextX = limX;
  if (nextX < -limX) nextX = -limX;
  if (nextZ > limZ) nextZ = limZ;
  if (nextZ < -limZ) nextZ = -limZ;

  // Collision with scene objects (XZ, boxes expanded by the player radius)
  // + standing on top of them. Player can step ~0.5 units up.
  const float playerRadius = 0.35F;
  float ground = 0.0F;
  for (const RuntimeObject& o : runtimeObjects) {
    if (!o.visible || o.data.type == 4) continue;
    const float ox = o.data.position[0];
    const float oz = o.data.position[2];
    const float hx = 0.5F * o.data.scale[0] + playerRadius;
    const float hz = 0.5F * o.data.scale[2] + playerRadius;
    const float top = o.data.position[1] + 0.5F * o.data.scale[1];
    const float bottom = o.data.position[1] - 0.5F * o.data.scale[1];

    const bool nextInside =
        nextX > ox - hx && nextX < ox + hx && nextZ > oz - hz && nextZ < oz + hz;
    if (!nextInside) continue;

    if (playerY + 0.5F >= top) {
      // Low enough to walk onto - candidate floor
      if (top > ground) ground = top;
    } else if (playerY < top && playerY + EYE_HEIGHT > bottom) {
      // Blocked - cancel the axes that entered the box this frame
      const bool wasInsideX = playerX > ox - hx && playerX < ox + hx;
      const bool wasInsideZ = playerZ > oz - hz && playerZ < oz + hz;
      if (!wasInsideX) nextX = playerX;
      if (!wasInsideZ) nextZ = playerZ;
      if (wasInsideX && wasInsideZ) {
        nextX = playerX;
        nextZ = playerZ;
      }
    }
  }
  playerX = nextX;
  playerZ = nextZ;

  // Gravity & jumping (X). GRAVITY: units/s^2, JUMP_SPEED: units/s, 50 FPS.
  playerVelY -= GRAVITY / (50.0F * 50.0F);
  playerY += playerVelY;
  if (playerY <= ground) {
    playerY = ground;
    playerVelY = 0.0F;
    if (engine->pad.getClicked().Cross) playerVelY = JUMP_SPEED / 50.0F;
  }

  const float eyeY = playerY + EYE_HEIGHT;
  cameraPosition = Vec4(playerX, eyeY, playerZ);
  cameraLookAt = Vec4(playerX + fx * cosf(pitch), eyeY + sinf(pitch),
                      playerZ + fz * cosf(pitch));
}
)";

static const char* TPL_GAME_CPP_FOOTER = R"(
}  // namespace {{NAME_UPPER_NS}}
)";

// ---------------------------------------------------------------------------
// Engine patch v2: fast EE clipper. Replaces two engine .cpp files (headers
// untouched, ABI identical). Copied into /tyra by the Runner and the engine
// is rebuilt once per shared volume.
//
// What it fixes:
// - Cohen-Sutherland outcodes: fully-visible triangles skip the 6-plane
//   Sutherland-Hodgman entirely (1 byte per vertex instead of ~6 passes of
//   64-byte struct copies), fully-outside triangles are rejected instantly.
// - clipAgainstPlane edge loop used BY-VALUE copies of two 64-byte structs
//   per edge per plane - now const references.
// - StaPipClipper::clip allocated a std::vector on the heap per call, per
//   subpackage, per frame - now a static pool (render is single-threaded).
// ---------------------------------------------------------------------------

static const char* TPL_ENGINE_PATCH_ALGO = R"(/*
# Patched by tyra-editor (engine patch v2) - fast clipping via outcodes.
# Based on the original by Sandro Sobczynski (h4570/tyra), Apache License 2.0.
*/

#include "renderer/core/3d/clipper/planes_clip_algorithm.hpp"

namespace Tyra {

PlanesClipAlgorithm::PlanesClipAlgorithm() {
  tempVertices = new PlanesClipVertex[9];
}

PlanesClipAlgorithm::~PlanesClipAlgorithm() { delete[] tempVertices; }

float PlanesClipAlgorithm::clipMargin = -10.0F;

void PlanesClipAlgorithm::init(const RendererSettings& settings) {
  halfWidth = 0.5F;
  halfHeight = 0.5F;
  near = settings.getNear() - (-clipMargin);
  far = -settings.getFar();
}

u8 PlanesClipAlgorithm::clip(PlanesClipVertex* o_vertices,
                             PlanesClipVertexPtrs* i_vertices,
                             const EEClipAlgorithmSettings& settings) {
  // Cohen-Sutherland outcodes: one byte per vertex, six plane bits.
  u8 codes[3];
  for (int i = 0; i < 3; i++) {
    const Vec4& p = *i_vertices[i].position;
    if (p.w <= 0.0F) {
      codes[i] = 16;  // behind the eye plane - never trivially accepted
      continue;
    }
    u8 c = 0;
    if (p.x > halfWidth * p.w) c |= 1;
    if (p.x < -halfWidth * p.w) c |= 2;
    if (p.y > halfHeight * p.w) c |= 4;
    if (p.y < -halfHeight * p.w) c |= 8;
    if (p.z > near) c |= 16;
    if (p.z < far) c |= 32;
    codes[i] = c;
  }

  // Trivial reject: all three vertices outside the same plane.
  if (codes[0] & codes[1] & codes[2]) return 0;

  for (int i = 0; i < 3; i++) {
    o_vertices[i].position = *i_vertices[i].position;
    if (settings.lerpColors) o_vertices[i].color = *i_vertices[i].color;
    if (settings.lerpNormals) o_vertices[i].normal = *i_vertices[i].normal;
    if (settings.lerpTexCoords) o_vertices[i].st = *i_vertices[i].st;
  }

  // Trivial accept: all three vertices fully inside - no clipping needed.
  if ((codes[0] | codes[1] | codes[2]) == 0) return 3;

  // Real work only for triangles that actually cross a plane.
  u8 tempVerticesSize = 0;
  u8 outputSize = 0;

  tempVerticesSize =
      clipAgainstPlane(o_vertices, 3, tempVertices, 1, halfWidth, settings);

  outputSize = clipAgainstPlane(tempVertices, tempVerticesSize, o_vertices, 1,
                                -halfWidth, settings);

  tempVerticesSize = clipAgainstPlane(o_vertices, outputSize, tempVertices, 2,
                                      halfHeight, settings);

  outputSize = clipAgainstPlane(tempVertices, tempVerticesSize, o_vertices, 2,
                                -halfHeight, settings);

  tempVerticesSize =
      clipAgainstPlane(o_vertices, outputSize, tempVertices, 3, near, settings);

  outputSize = clipAgainstPlane(tempVertices, tempVerticesSize, o_vertices, 4,
                                far, settings);

  return outputSize;
}

float PlanesClipAlgorithm::getValueByPlane(const PlanesClipVertex& v,
                                           const int& plane) {
  switch (plane) {
    case 1:
      return v.position.x;  // x plane
    case 2:
      return v.position.y;  // y plane
    case 3:                 // z near
    case 4:
      return v.position.z;  // z far
    default:
      return 0;
  }
}

bool PlanesClipAlgorithm::isInside(const int& plane, const float& v,
                                   const float& w,
                                   const float& planeLimitValue) {
  switch (plane) {
    case 3:
      return v <= planeLimitValue;  // near z plane
    case 4:
      return v >= planeLimitValue;  // far z plane
    default:
      return (planeLimitValue < 0) ? (v >= planeLimitValue * w)
                                   : (v <= planeLimitValue * w);
  }
}

u8 PlanesClipAlgorithm::clipAgainstPlane(
    PlanesClipVertex* original, const u8& originalSize,
    PlanesClipVertex* clipped, const int& plane, const float& planeLimitValue,
    const EEClipAlgorithmSettings& settings) {
  int clippedSize = 0;

  for (u32 i = 0; i < originalSize; i++) {
    // const references - the original copied two 64-byte structs per edge
    const auto& a = original[i];
    const auto& b = original[(i + 1) % originalSize];
    const float apx = getValueByPlane(a, plane);
    const float bpx = getValueByPlane(b, plane);
    const bool aIsInside = isInside(plane, apx, a.position.w, planeLimitValue);
    const bool bIsInside = isInside(plane, bpx, b.position.w, planeLimitValue);

    if (aIsInside) {
      clipped[clippedSize++] = a;
    }

    if (aIsInside != bIsInside) {
      const float p =
          (plane >= 3)
              ? (planeLimitValue - a.position.z) / (b.position.z - a.position.z)
              : (-a.position.w * planeLimitValue + apx) /
                    ((b.position.w - a.position.w) * planeLimitValue -
                     (bpx - apx));

      const auto index = clippedSize++;

      clipped[index].position = Vec4::getByLerp(a.position, b.position, p);

      if (settings.lerpNormals)
        clipped[index].normal = Vec4::getByLerp(a.normal, b.normal, p);

      if (settings.lerpTexCoords)
        clipped[index].st = Vec4::getByLerp(a.st, b.st, p);

      if (settings.lerpColors)
        clipped[index].color = Vec4::getByLerp(a.color, b.color, p);
    }
  }

  return clippedSize;
}

}  // namespace Tyra
)";

static const char* TPL_ENGINE_PATCH_CLIPPER = R"(/*
# Patched by tyra-editor (engine patch v2) - no heap allocations per clip call.
# Based on the original by Sandro Sobczynski (h4570/tyra), Apache License 2.0.
*/

#include "renderer/3d/pipeline/static/core/stapip_clipper.hpp"

namespace Tyra {

namespace {
// Rendering is single-threaded on the EE - one static pool is enough.
constexpr u32 kMaxClippedVerts = 1024;
PlanesClipVertex clippedPool[kMaxClippedVerts];
}  // namespace

StaPipClipper::StaPipClipper() {}
StaPipClipper::~StaPipClipper() {}

void StaPipClipper::setMVP(M4x4* t_mvp) { mvp = t_mvp; }

void StaPipClipper::init(const RendererSettings& settings) {
  algorithm.init(settings);
}

void StaPipClipper::setMaxVertCount(const u32& count) { maxVertCount = count; }

void StaPipClipper::clip(StaPipQBuffer* buffer) {
  TYRA_ASSERT(buffer->size <= maxVertCount / 3, "Buffer should have max ",
              maxVertCount / 3, " verts if we want to clip it.");

  EEClipAlgorithmSettings algoSettings = {buffer->bag->lighting != nullptr,
                                          buffer->bag->texture != nullptr,
                                          buffer->bag->color->many != nullptr};

  u32 outCount = 0;

  for (u32 i = 0; i < buffer->size / 3; i++) {
    for (u8 j = 0; j < 3; j++) {
      inputVerts[j] = *mvp * buffer->vertices[i * 3 + j];

      inputTriangle[j] = {
          &inputVerts[j],
          buffer->bag->lighting ? &buffer->normals[i * 3 + j] : nullptr,
          buffer->bag->texture ? &buffer->sts[i * 3 + j] : nullptr,
          buffer->bag->color->many ? &buffer->colors[i * 3 + j] : nullptr};
    }

    const u8 clippedSize =
        algorithm.clip(clippedTriangle, inputTriangle, algoSettings);
    if (clippedSize < 3) continue;

    for (u8 j = 1; j <= (u8)(clippedSize - 2); j++) {
      if (outCount + 3 > kMaxClippedVerts) break;
      clippedPool[outCount++] = clippedTriangle[0];
      clippedPool[outCount++] = clippedTriangle[j];
      clippedPool[outCount++] = clippedTriangle[(j + 1) % clippedSize];
    }
  }

  for (u32 i = 0; i < outCount; i++)
    clippedPool[i].position /= clippedPool[i].position.w;

  buffer->reallocateManually(outCount);
  for (u32 i = 0; i < outCount; i++) {
    buffer->vertices[i] = clippedPool[i].position;
    if (buffer->bag->texture) buffer->sts[i] = clippedPool[i].st;
    if (buffer->bag->color->many) buffer->colors[i] = clippedPool[i].color;
    if (buffer->bag->lighting) buffer->normals[i] = clippedPool[i].normal;
  }
}

// Kept only to satisfy the class declaration (unused after the patch).
void StaPipClipper::perspectiveDivide(std::vector<PlanesClipVertex>* vertices) {
  for (u32 i = 0; i < vertices->size(); i++) {
    (*vertices)[i].position /= (*vertices)[i].position.w;
  }
}

void StaPipClipper::moveDataToBuffer(
    const std::vector<PlanesClipVertex>& vertices, StaPipQBuffer* buffer) {
  buffer->reallocateManually(vertices.size());

  for (u32 i = 0; i < vertices.size(); i++) {
    auto& vertex = vertices.at(i);
    buffer->vertices[i] = vertex.position;

    if (buffer->bag->texture) buffer->sts[i] = vertex.st;
    if (buffer->bag->color->many) buffer->colors[i] = vertex.color;
    if (buffer->bag->lighting) buffer->normals[i] = vertex.normal;
  }
}

}  // namespace Tyra
)";

static const char* TPL_ENGINE_PATCH_QBUFFER = R"QBUF(/*
# Patched by tyra-editor (engine patch v2) - persistent qbuffer pools.
# The original allocated and freed up to four Vec4 arrays PER FILL CALL,
# per subpackage, per frame. Arrays are now allocated once per buffer at
# maxVertCount capacity and reused. Based on the original by
# Sandro Sobczynski (h4570/tyra), Apache License 2.0.
*/

#include "renderer/3d/pipeline/static/core/stapip_qbuffer.hpp"
#include <sstream>
#include <iomanip>

namespace Tyra {

namespace {

struct QBufferPool {
  const void* owner = nullptr;
  Vec4* vertices = nullptr;
  Vec4* sts = nullptr;
  Vec4* colors = nullptr;
  Vec4* normals = nullptr;
  u16 capacity = 0;
};

constexpr int kMaxPools = 32;
QBufferPool pools[kMaxPools];

QBufferPool* poolFor(const void* owner) {
  for (int i = 0; i < kMaxPools; i++)
    if (pools[i].owner == owner) return &pools[i];
  for (int i = 0; i < kMaxPools; i++)
    if (pools[i].owner == nullptr) {
      pools[i].owner = owner;
      return &pools[i];
    }
  return nullptr;  // more buffers than pools - fall back to plain new[]
}

}  // namespace

StaPipQBuffer::StaPipQBuffer() {
  size = 0;
  _isDynamicallyAllocated = false;
  _stAllocated = false;
  _colorAllocated = false;
  _normalAllocated = false;

  vertices = nullptr;
  colors = nullptr;
  sts = nullptr;
  normals = nullptr;
}

StaPipQBuffer::~StaPipQBuffer() { deallocateDynamicData(); }

void StaPipQBuffer::setMaxVertCount(const u32& count) { maxVertCount = count; }

void StaPipQBuffer::fillByPointer(const StaPipBagPackage& pkg) {
  TYRA_ASSERT(pkg.size <= maxVertCount, "VU1 buffer supports only ",
              maxVertCount, " verts. Provided: ", pkg.size);

  deallocateDynamicData();

  // Too bad, but in reality const is not violated.
  // This class needs refactor
  vertices = const_cast<Vec4*>(pkg.vertices);
  sts = const_cast<Vec4*>(pkg.sts);
  colors = const_cast<Vec4*>(pkg.colors);
  normals = const_cast<Vec4*>(pkg.normals);
  size = pkg.size;
  bag = pkg.bag;
}

void StaPipQBuffer::fillByCopyMax(const StaPipBagPackage& pkg1,
                                  const StaPipBagPackage& pkg2,
                                  const StaPipBagPackage& pkg3) {
  TYRA_ASSERT(pkg1.size <= maxVertCount / 3,
              "Wrong package size (1). Provided: ", pkg1.size);
  TYRA_ASSERT(pkg2.size <= maxVertCount / 3,
              "Wrong package size (2). Provided: ", pkg2.size);
  TYRA_ASSERT(pkg3.size <= maxVertCount / 3,
              "Wrong package size (3). Provided: ", pkg3.size);

  deallocateDynamicData();
  size = pkg1.size + pkg2.size + pkg3.size;
  allocateDynamicData(size, pkg1.bag);

  for (u16 i = 0; i < pkg1.size; i++) {
    vertices[i].set(pkg1.vertices[i]);

    if (pkg1.bag->texture) sts[i].set(pkg1.sts[i]);

    if (pkg1.bag->color->many)
      colors[i].set(reinterpret_cast<const Vec4&>(pkg1.colors[i]));

    if (pkg1.bag->lighting) normals[i].set(pkg1.normals[i]);
  }

  for (u16 i = 0; i < pkg2.size; i++) {
    vertices[i + pkg1.size].set(pkg2.vertices[i]);

    if (pkg1.bag->texture) sts[i + pkg1.size].set(pkg2.sts[i]);

    if (pkg1.bag->color->many)
      colors[i + pkg1.size].set(reinterpret_cast<const Vec4&>(pkg2.colors[i]));

    if (pkg1.bag->lighting) normals[i + pkg1.size].set(pkg2.normals[i]);
  }

  for (u16 i = 0; i < pkg3.size; i++) {
    vertices[i + pkg1.size + pkg2.size].set(pkg3.vertices[i]);

    if (pkg1.bag->texture) sts[i + pkg1.size + pkg2.size].set(pkg3.sts[i]);

    if (pkg1.bag->color->many)
      colors[i + pkg1.size + pkg2.size].set(
          reinterpret_cast<const Vec4&>(pkg3.colors[i]));

    if (pkg1.bag->lighting)
      normals[i + pkg1.size + pkg2.size].set(pkg3.normals[i]);
  }

  bag = pkg1.bag;
}

void StaPipQBuffer::fillByCopy1By2(const StaPipBagPackage& pkg1,
                                   const StaPipBagPackage& pkg2) {
  TYRA_ASSERT(pkg1.size <= maxVertCount / 3,
              "Wrong package size (1). Provided: ", pkg1.size);
  TYRA_ASSERT(pkg2.size <= maxVertCount / 3,
              "Wrong package size (2). Provided: ", pkg2.size);

  deallocateDynamicData();
  size = pkg1.size + pkg2.size;
  allocateDynamicData(size, pkg1.bag);

  for (u16 i = 0; i < pkg1.size; i++) {
    vertices[i].set(pkg1.vertices[i]);

    if (pkg1.bag->texture) sts[i].set(pkg1.sts[i]);

    if (pkg1.bag->color->many)
      colors[i].set(reinterpret_cast<const Vec4&>(pkg1.colors[i]));

    if (pkg1.bag->lighting) normals[i].set(pkg1.normals[i]);
  }

  for (u16 i = 0; i < pkg2.size; i++) {
    vertices[i + pkg1.size].set(pkg2.vertices[i]);

    if (pkg1.bag->texture) sts[i + pkg1.size].set(pkg2.sts[i]);

    if (pkg1.bag->color->many)
      colors[i + pkg1.size].set(reinterpret_cast<const Vec4&>(pkg2.colors[i]));

    if (pkg1.bag->lighting) normals[i + pkg1.size].set(pkg2.normals[i]);
  }

  bag = pkg1.bag;
}

void StaPipQBuffer::fillByCopy1By3(const StaPipBagPackage& pkg) {
  TYRA_ASSERT(pkg.size <= maxVertCount / 3,
              "Wrong package size (1). Provided: ", pkg.size);

  deallocateDynamicData();
  size = pkg.size;
  allocateDynamicData(size, pkg.bag);

  for (u16 i = 0; i < pkg.size; i++) {
    vertices[i].set(pkg.vertices[i]);

    if (pkg.bag->texture) sts[i].set(pkg.sts[i]);

    if (pkg.bag->color->many)
      colors[i].set(reinterpret_cast<const Vec4&>(pkg.colors[i]));

    if (pkg.bag->lighting) normals[i].set(pkg.normals[i]);
  }

  bag = pkg.bag;
}

void StaPipQBuffer::reallocateManually(const u16& t_size) {
  deallocateDynamicData();
  allocateDynamicData(t_size, bag);
  size = t_size;
}

void StaPipQBuffer::deallocateDynamicData() {
  if (!_isDynamicallyAllocated) return;

  // Pooled arrays are kept for reuse - only true heap fallbacks are freed.
  QBufferPool* pool = poolFor(this);
  const bool pooled = pool && vertices == pool->vertices;

  if (!pooled) {
    delete[] vertices;

    if (_stAllocated) delete[] sts;
    if (_colorAllocated) delete[] colors;
    if (_normalAllocated) delete[] normals;
  }

  _stAllocated = false;
  _colorAllocated = false;
  _normalAllocated = false;
  _isDynamicallyAllocated = false;
}

void StaPipQBuffer::allocateDynamicData(u16 size, StaPipBag* bag) {
  TYRA_ASSERT(size <= maxVertCount, "Wrong size. Max buffer size in VU1 is ",
              maxVertCount, ". Provided: ", size);
  TYRA_ASSERT(!_isDynamicallyAllocated, "Buffer is already allocated");

  if (size == 0) return;

  QBufferPool* pool = poolFor(this);
  if (pool) {
    const u16 needed = maxVertCount > size ? (u16)maxVertCount : size;
    if (pool->capacity < needed) {
      delete[] pool->vertices;
      delete[] pool->sts;
      delete[] pool->colors;
      delete[] pool->normals;
      pool->vertices = new Vec4[needed];
      pool->sts = new Vec4[needed];
      pool->colors = new Vec4[needed];
      pool->normals = new Vec4[needed];
      pool->capacity = needed;
    }
    vertices = pool->vertices;
    if (bag->texture != nullptr) {
      sts = pool->sts;
      _stAllocated = true;
    }
    if (bag->color->many != nullptr) {
      colors = pool->colors;
      _colorAllocated = true;
    }
    if (bag->lighting != nullptr) {
      normals = pool->normals;
      _normalAllocated = true;
    }
    _isDynamicallyAllocated = true;
    return;
  }

  // Fallback: original behavior
  vertices = new Vec4[size];

  if (bag->texture != nullptr) {
    sts = new Vec4[size];
    _stAllocated = true;
  }

  if (bag->color->many != nullptr) {
    colors = new Vec4[size];
    _colorAllocated = true;
  }

  if (bag->lighting != nullptr) {
    normals = new Vec4[size];
    _normalAllocated = true;
  }

  _isDynamicallyAllocated = true;
}

bool StaPipQBuffer::any() const { return size > 0; }

void StaPipQBuffer::print() const {
  auto text = getPrint(nullptr);
  printf("%s\n", text.c_str());
}

void StaPipQBuffer::print(const char* name) const {
  auto text = getPrint(name);
  printf("%s\n", text.c_str());
}

std::string StaPipQBuffer::getPrint(const char* name) const {
  std::stringstream res;
  if (name) {
    res << name << "(";
  } else {
    res << "StaPipQBuffer(";
  }
  res << std::fixed << std::setprecision(2);
  res << std::endl;
  res << "Size: " << static_cast<int>(size) << std::endl;

  res << "Vertices: " << std::endl;
  for (u32 i = 0; i < size; i++)
    res << i << ": " << vertices[i].getPrint() << std::endl;

  if (bag->texture != nullptr) {
    res << "STs: " << std::endl;
    for (u32 i = 0; i < size; i++)
      res << i << ": " << sts[i].getPrint() << std::endl;
  }

  if (bag->color->many != nullptr) {
    res << "Colors: " << std::endl;
    for (u32 i = 0; i < size; i++)
      res << i << ": " << colors[i].getPrint() << std::endl;
  }

  if (bag->lighting != nullptr) {
    res << "Normals: " << std::endl;
    for (u32 i = 0; i < size; i++) {
      res << i << ": " << normals[i].getPrint();
      if (i < size - 1) {
        res << std::endl;
      }
    }
  }

  res << ")";

  return res.str();
}

}  // namespace Tyra
)QBUF";

// Engine patch v3: clipping leaves the EE. The VU1 cull programs get a 3x
// wider XY accept window (the GS scissor trims pixels in hardware, so
// edge-crossing triangles need no geometric clipping at all), and the bbox
// "second chance" reclassifies side-crossing packages as cullable. The EE
// clipper stays only for geometry near the camera plane, where perspective
// division would explode - the one case a scissor cannot fix.

static const char* TPL_ENGINE_PATCH_BBOX = R"(/*
# Patched by tyra-editor (engine patch v3) - guard-band aware frustum check.
# Based on the original by Sandro Sobczynski (h4570/tyra), Apache License 2.0.
*/

#include <string>
#include <sstream>
#include "renderer/core/3d/bbox/render_bbox.hpp"

namespace Tyra {

RenderBBox::RenderBBox(CoreBBox** t_bboxes, const u32& count)
    : CoreBBox(t_bboxes, count) {}

RenderBBox::RenderBBox(const std::vector<CoreBBox>& t_bboxes,
                       const u32& startIndex, const u32& stopIndex)
    : CoreBBox(t_bboxes, startIndex, stopIndex) {}

RenderBBox::RenderBBox(const Vec4* t_vertices, const u32* faces,
                       const u32& count)
    : CoreBBox(t_vertices, faces, count) {}

RenderBBox::RenderBBox(const Vec4* t_vertices, const u32& count)
    : CoreBBox(t_vertices, count) {}

RenderBBox::RenderBBox(const Vec4* t_vertices) : CoreBBox(t_vertices) {}

RenderBBox::RenderBBox(const RenderBBox& t_bbox, const M4x4& t_matrix)
    : CoreBBox(t_bbox, t_matrix) {}

RenderBBox RenderBBox::getTransformed(const M4x4& t_matrix) const {
  return RenderBBox(*this, t_matrix);
}

/**
 * Frustum check for the renderer.
 *
 * The VU1 cull programs accept a 3x wider XY window than the screen
 * (tyra-editor guard band patch) and the GS scissor trims the pixels, so
 * packages crossing the LEFT/RIGHT/TOP/BOTTOM planes render correctly on the
 * fast cull path with no geometric clipping.
 *
 * Only geometry close to the NEAR plane really needs the clipper: vertices
 * behind the eye cannot be scissored, they must be cut before the
 * perspective division.
 */
CoreBBoxFrustum RenderBBox::clipFrustumCheck(const Plane* frustumPlanes,
                                             const M4x4& model) const {
  auto result = frustumCheck(frustumPlanes, model);

  if (result != PARTIALLY_IN_FRUSTUM) {
    return result;
  }

  float guardBand[6];

  guardBand[0] = -100000.0F;  // Top    - handled by the GS scissor
  guardBand[1] = -100000.0F;  // Bottom - handled by the GS scissor
  guardBand[2] = -100000.0F;  // Left   - handled by the GS scissor
  guardBand[3] = -100000.0F;  // Right  - handled by the GS scissor
  guardBand[4] = 1.5F;        // Near   - the clipper must handle this band
  guardBand[5] = 0.0F;        // Far

  const auto withMargins = frustumCheck(frustumPlanes, model, guardBand);

  // Never skip on the second chance - worst case is a bit of extra clipping.
  return withMargins == OUTSIDE_FRUSTUM ? PARTIALLY_IN_FRUSTUM : withMargins;
}

}  // namespace Tyra
)";

// Shell script applied inside the container: swaps the PerformClipCheck VU1
// macro for a guard-band version (XY widened 3x, Z/W test untouched).
static const char* TPL_ENGINE_PATCH_VU1_SH = R"SH(#!/bin/sh
# tyra-editor engine patch v3: guard-band clip check in the VU1 cull programs.
set -e
F=/tyra/engine/src/renderer/3d/pipeline/shared/vcl_sml.i

if grep -q "tyra-editor guard band" "$F"; then
  echo "vu1 guard band already applied"
  exit 0
fi

awk '
/#macro PerformClipCheck/ {
  print "#macro PerformClipCheck: t_vertex, t_destAddress, t_destAddressOffset";
  print "   ; tyra-editor guard band: accept XY up to 3x outside the clip";
  print "   ; volume - the GS scissor trims the pixels, so edge-crossing";
  print "   ; triangles render correctly without geometric clipping.";
  print "   loi         0.3333333";
  print "   muli.xy     scaledClipVtx, t_vertex, i";
  print "   move.zw     scaledClipVtx, t_vertex";
  print "   clipw.xyz   scaledClipVtx, scaledClipVtx";
  print "   fcand       VI01,       0x3FFFF";
  print "   iaddiu      adcBit,     VI01, 0x7FFF";
  print "   isw.w       adcBit,     t_destAddressOffset(t_destAddress)";
  skip = 1; next
}
skip && /#endmacro/ { print "#endmacro"; skip = 0; next }
skip { next }
{ print }
' "$F" > "$F.new"
mv "$F.new" "$F"

# VU1 microprograms are not covered by the C++ dependency tracking -
# force their rebuild.
find /tyra/engine/obj -name "*vu1.o*" -delete 2>/dev/null || true
echo "vu1 guard band applied"
)SH";

// ---------------------------------------------------------------------------
// Built-in assets for the "FPP showcase" template
// ---------------------------------------------------------------------------

const char* houseObjText() {
    return R"(# simple house: cube walls + pyramid roof (tyra-editor built-in)
v -1 0 -1
v  1 0 -1
v  1 0  1
v -1 0  1
v -1 1.2 -1
v  1 1.2 -1
v  1 1.2  1
v -1 1.2  1
v  0 2.2  0
f 1 2 6
f 1 6 5
f 2 3 7
f 2 7 6
f 3 4 8
f 3 8 7
f 4 1 5
f 4 5 8
f 5 6 9
f 6 7 9
f 7 8 9
f 8 5 9
f 4 3 2
f 4 2 1
)";
}

// 64x64 white crosshair, PNG (372 bytes)
const unsigned char* crosshairPng(size_t& size) {
    static const unsigned char data[] = {
        137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,64,
        0,0,0,64,8,6,0,0,0,170,105,113,222,0,0,0,1,115,82,71,
        66,0,174,206,28,233,0,0,0,4,103,65,77,65,0,0,177,143,11,252,
        97,5,0,0,0,9,112,72,89,115,0,0,14,195,0,0,14,195,1,199,
        111,168,100,0,0,1,9,73,68,65,84,120,94,237,211,209,106,194,64,24,
        132,209,188,255,75,183,101,57,12,181,88,73,83,81,216,249,207,157,159,201,
        154,17,61,198,24,99,140,49,94,237,227,7,185,135,221,33,247,176,59,228,
        30,118,135,220,195,238,144,123,216,29,114,15,187,67,238,97,119,200,61,236,
        14,185,135,221,33,247,176,59,228,30,118,135,220,195,238,144,123,216,29,114,
        15,187,67,238,97,119,200,99,140,2,254,246,119,185,100,95,118,62,228,210,
        253,216,119,138,91,222,207,243,92,230,152,69,58,197,45,79,253,252,75,156,
        115,153,99,22,41,228,69,10,121,159,47,192,203,27,222,90,164,27,191,245,
        191,88,135,255,135,115,46,115,204,34,133,188,72,33,191,255,11,120,38,207,
        116,138,91,246,98,219,41,110,217,143,125,15,185,116,95,118,222,229,146,30,
        149,163,199,151,245,123,255,70,238,97,119,200,61,236,14,185,135,221,33,247,
        176,59,228,30,118,135,220,195,238,144,123,216,29,114,15,187,67,238,97,119,
        200,61,236,14,185,135,221,33,247,176,59,228,30,118,135,220,195,238,144,123,
        216,29,242,24,99,140,49,198,139,28,199,39,208,62,150,176,24,28,75,254,
        0,0,0,0,73,69,78,68,174,66,96,130,
    };
    size = sizeof(data);
    return data;
}

// ---------------------------------------------------------------------------
// Legacy templates (v1, before scene objects). Kept verbatim so that projects
// generated by older editor versions can be recognized as unedited and safely
// regenerated. Do not modify.
// ---------------------------------------------------------------------------

static const char* TPL_GAME_HPP_V1 = R"(#pragma once

#include <tyra>
#include <memory>
#include <vector>

namespace {{NAME_UPPER_NS}} {

class TerrainGame : public Tyra::Game {
 public:
  explicit TerrainGame(Tyra::Engine* engine);
  ~TerrainGame();

  void init() override;
  void loop() override;

 private:
  void generateTerrainGrid();
  void updateCameraOrbit();

  Tyra::Engine* engine;
  Tyra::StaticPipeline stapip;

  Tyra::Vec4 cameraPosition, cameraLookAt;
  float orbitAngle;

  std::vector<Tyra::Vec4> vertices;
  std::vector<Tyra::Color> colors;

  Tyra::M4x4 model;
  std::unique_ptr<Tyra::StaPipBag> bag;
  std::unique_ptr<Tyra::StaPipInfoBag> infoBag;
  std::unique_ptr<Tyra::StaPipColorBag> colorBag;
};

}  // namespace {{NAME_UPPER_NS}}
)";

static const char* TPL_GAME_CPP_V1 = R"(#include "terrain_game.hpp"
#include "terrain_config.hpp"
#include <math.h>

namespace {{NAME_UPPER_NS}} {

using namespace Tyra;

TerrainGame::TerrainGame(Engine* t_engine)
    : engine(t_engine), orbitAngle(0.0F), model(M4x4::Identity) {}

TerrainGame::~TerrainGame() {}

void TerrainGame::init() {
  stapip.setRenderer(&engine->renderer.core);

  // Sky blue background
  engine->renderer.setClearScreenColor(Color(64.0F, 140.0F, 200.0F));

  cameraLookAt = Vec4(0.0F, 0.0F, 0.0F);
  updateCameraOrbit();

  generateTerrainGrid();
}

void TerrainGame::loop() {
  updateCameraOrbit();

  engine->renderer.beginFrame(CameraInfo3D(&cameraPosition, &cameraLookAt));
  {
    engine->renderer.renderer3D.usePipeline(stapip);
    stapip.core.render(bag.get());
  }
  engine->renderer.endFrame();
}

void TerrainGame::generateTerrainGrid() {
  // Cap the amount of quads so big terrains stay PS2-friendly.
  // Cell size grows with terrain size instead.
  const u32 maxCells = 32;
  const u32 cellsX = TERRAIN_WIDTH > maxCells ? maxCells : (u32)TERRAIN_WIDTH;
  const u32 cellsZ = TERRAIN_DEPTH > maxCells ? maxCells : (u32)TERRAIN_DEPTH;
  const float stepX = TERRAIN_WIDTH / cellsX;
  const float stepZ = TERRAIN_DEPTH / cellsZ;
  const float startX = -TERRAIN_WIDTH * 0.5F;
  const float startZ = -TERRAIN_DEPTH * 0.5F;

  // Two greens in a checker pattern, so the grid is visible.
  // PS2 colors: RGB 0-255, alpha 0-128.
  const Color colorA(96.0F, 160.0F, 72.0F, 128.0F);
  const Color colorB(74.0F, 128.0F, 56.0F, 128.0F);

  vertices.clear();
  colors.clear();
  vertices.reserve(cellsX * cellsZ * 6);
  colors.reserve(cellsX * cellsZ * 6);

  for (u32 z = 0; z < cellsZ; ++z) {
    for (u32 x = 0; x < cellsX; ++x) {
      const float x0 = startX + x * stepX;
      const float x1 = x0 + stepX;
      const float z0 = startZ + z * stepZ;
      const float z1 = z0 + stepZ;
      const Color& c = ((x + z) % 2 == 0) ? colorA : colorB;

      const Vec4 v00(x0, 0.0F, z0, 1.0F);
      const Vec4 v10(x1, 0.0F, z0, 1.0F);
      const Vec4 v01(x0, 0.0F, z1, 1.0F);
      const Vec4 v11(x1, 0.0F, z1, 1.0F);

      vertices.push_back(v00);
      vertices.push_back(v10);
      vertices.push_back(v01);
      vertices.push_back(v10);
      vertices.push_back(v11);
      vertices.push_back(v01);

      for (int i = 0; i < 6; ++i) colors.push_back(c);
    }
  }

  infoBag = std::make_unique<StaPipInfoBag>();
  infoBag->model = &model;
  infoBag->shadingType = TyraShadingFlat;
  infoBag->fullClipChecks = false;

  colorBag = std::make_unique<StaPipColorBag>();
  colorBag->many = colors.data();

  bag = std::make_unique<StaPipBag>();
  bag->info = infoBag.get();
  bag->color = colorBag.get();
  bag->vertices = vertices.data();
  bag->count = static_cast<u32>(vertices.size());
  bag->texture = nullptr;
  bag->lighting = nullptr;
}

void TerrainGame::updateCameraOrbit() {
  orbitAngle += 0.005F;
  const float diag = TERRAIN_WIDTH > TERRAIN_DEPTH ? TERRAIN_WIDTH : TERRAIN_DEPTH;
  const float orbitRadius = diag * 0.9F;
  const float orbitHeight = diag * 0.55F;

  cameraPosition.x = orbitRadius * cosf(orbitAngle);
  cameraPosition.y = orbitHeight;
  cameraPosition.z = orbitRadius * sinf(orbitAngle);
}

}  // namespace {{NAME_UPPER_NS}}
)";

// Script API header (inc/scripts/script.hpp). Marker-owned: regenerated on
// build while the marker is present, so the API can evolve with the editor.
static const char* TPL_SCRIPT_HPP =
    R"(// Generated by tyra-editor. Delete this line to take ownership of this file.
#pragma once

#include <tyra>
#include <vector>
#include "scene_data.hpp"

namespace {{NAME_UPPER_NS}} {

/** A scene object at runtime. Mutate `data` (position/rotation/scale/color),
 * `visible` or `velocityY`, then set `dirty = true` so the geometry gets
 * rebuilt on the next frame. */
struct RuntimeObject {
  SceneObjectData data;
  bool visible = true;
  float velocityY = 0.0F;  // vertical velocity (object physics)
  bool dirty = true;
};

/** Everything a script can see and touch each frame. */
struct ScriptContext {
  Tyra::Engine* engine = nullptr;  // pad, renderer, audio, ...
  Tyra::Vec4 playerPosition;       // camera/player position this frame
  RuntimeObject* objects = nullptr;  // mutable scene objects
  int objectCount = 0;
  Tyra::Color skyColor;  // write to change the clear color
};

/** Base class for game scripts. Put .cpp files in src/scripts/. */
class Script {
 public:
  virtual ~Script() {}
  virtual void init(ScriptContext&) {}
  virtual void update(ScriptContext&) {}
};

inline std::vector<Script*>& getScripts() {
  static std::vector<Script*> scripts;
  return scripts;
}

}  // namespace {{NAME_UPPER_NS}}

/** Registers a script class. Put TYRA_SCRIPT(MyScript); at file scope. */
#define TYRA_SCRIPT_CONCAT_INNER(a, b) a##b
#define TYRA_SCRIPT_CONCAT(a, b) TYRA_SCRIPT_CONCAT_INNER(a, b)
#define TYRA_SCRIPT(ClassName)                                             \
  static const bool TYRA_SCRIPT_CONCAT(_tyraScript_, __COUNTER__) = []() { \
    {{NAME_UPPER_NS}}::getScripts().push_back(new ClassName());            \
    return true;                                                           \
  }()
)";

// Example script for FPP projects - user-owned, written only at creation.
static const char* TPL_EXAMPLE_SCRIPT_FPP =
    R"(// Example tyra-editor script. This file is yours - it is never regenerated.
// Walk close to the box and press X: the sky changes color (and a message
// lands in the PCSX2 log via TYRA_LOG).
#include "scripts/script.hpp"
#include "terrain_config.hpp"

namespace {{NAME_UPPER_NS}} {

class ExampleInteraction : public Script {
 public:
  void update(ScriptContext& ctx) override {
    // Find the first box in the scene
    RuntimeObject* box = nullptr;
    for (int i = 0; i < ctx.objectCount; ++i) {
      if (ctx.objects[i].data.type == 0) {  // 0 = box
        box = &ctx.objects[i];
        break;
      }
    }
    if (!box) return;

    const float dx = ctx.playerPosition.x - box->data.position[0];
    const float dz = ctx.playerPosition.z - box->data.position[2];
    const bool nearBox = (dx * dx + dz * dz) < 8.0F * 8.0F;

    if (nearBox && ctx.engine->pad.getClicked().Cross) {
      toggled = !toggled;
      TYRA_LOG("Box says hello! Sky toggled: ", (int)toggled);
      ctx.skyColor = toggled ? Tyra::Color(230.0F, 120.0F, 60.0F)
                             : Tyra::Color(SKY_R, SKY_G, SKY_B);
    }
  }

 private:
  bool toggled = false;
};

}  // namespace {{NAME_UPPER_NS}}

TYRA_SCRIPT({{NAME_UPPER_NS}}::ExampleInteraction);
)";

// Example script for orbit projects (no player to walk around with).
static const char* TPL_EXAMPLE_SCRIPT_ORBIT =
    R"(// Example tyra-editor script. This file is yours - it is never regenerated.
// Press X on the pad: the sky changes color (and a message lands in the
// PCSX2 log via TYRA_LOG).
#include "scripts/script.hpp"
#include "terrain_config.hpp"

namespace {{NAME_UPPER_NS}} {

class ExampleInteraction : public Script {
 public:
  void update(ScriptContext& ctx) override {
    if (ctx.engine->pad.getClicked().Cross) {
      toggled = !toggled;
      TYRA_LOG("X pressed! Sky toggled: ", (int)toggled);
      ctx.skyColor = toggled ? Tyra::Color(230.0F, 120.0F, 60.0F)
                             : Tyra::Color(SKY_R, SKY_G, SKY_B);
    }
  }

 private:
  bool toggled = false;
};

}  // namespace {{NAME_UPPER_NS}}

TYRA_SCRIPT({{NAME_UPPER_NS}}::ExampleInteraction);
)";

// Stub for "New script..." in the editor.
static const char* TPL_SCRIPT_STUB =
    R"(// {{SCRIPT_FILE}} - created by tyra-editor. This file is yours.
#include "scripts/script.hpp"

namespace {{NAME_UPPER_NS}} {

class {{SCRIPT_CLASS}} : public Script {
 public:
  void init(ScriptContext& ctx) override {
    // Called once at game start.
  }

  void update(ScriptContext& ctx) override {
    // Called every frame. Examples:
    //   ctx.engine->pad.getClicked().Cross  - X pressed this frame
    //   ctx.playerPosition                  - camera/player position
    //   ctx.skyColor = Tyra::Color(255.0F, 0.0F, 0.0F);
  }
};

}  // namespace {{NAME_UPPER_NS}}

TYRA_SCRIPT({{NAME_UPPER_NS}}::{{SCRIPT_CLASS}});
)";

static const char* TPL_RUN_PS1 = R"($ConfigFile = Join-Path $PSScriptRoot './windows-pcsx2.ps1'
. $ConfigFile

RunPCSX2
)";

static const char* TPL_PCSX2_PS1 = R"PS1(# =======================
$CUSTOM_PCSX2_PATH = "" # "D:/My/Path/To/PCSX2"
# =======================

function GetTargetELFName {
    return (Select-String -Path './Makefile' -Pattern "[^ ]*.elf").Matches.Value
}

function FindPCSX2Directory {
    if (-not [string]::IsNullOrEmpty($CUSTOM_PCSX2_PATH)) {
        return $CUSTOM_PCSX2_PATH
    }
    else {
        $pcsx2Path = "${Env:ProgramFiles}/PCSX2"
        $pcsx2Pathx86 = "${Env:ProgramFiles(x86)}/PCSX2"

        if (Test-Path -Path $pcsx2Path) {
            return $pcsx2Path
        }
        elseif (Test-Path -Path $pcsx2Pathx86) {
            return $pcsx2Pathx86
        }
        else {
            throw "PCSX2 directory not found!"
        }
    }
}

function FindPCSX2Executable {
    param ([string]$directory)

    foreach ($name in 'pcsx2.exe', 'pcsx2-qt.exe') {
        if (Test-Path -Path (Join-Path $directory $name)) { return $name }
    }
    throw "PCSX2 executable not found in: $directory!"
}

function RunPCSX2 {
    $dirPath = FindPCSX2Directory
    $isNewVersion = Test-Path -Path "$dirPath/qt.conf"
    $executableName = FindPCSX2Executable -directory $dirPath
    $executableNameWithoutExt = (Split-Path $executableName -Leaf).Split('.')[0]
    $targetFileName = "$PWD/bin/$(GetTargetELFName)"

    Stop-Process -Name $executableNameWithoutExt -ErrorAction 'SilentlyContinue'

    if ($isNewVersion) {
        Start-Process -FilePath "$dirPath/$executableName" -ArgumentList "-elf", $targetFileName
    }
    else {
        Start-Process -FilePath "$dirPath/$executableName" -ArgumentList "--elf=$targetFileName"
    }
}
)PS1";

static const char* TPL_GITIGNORE = R"(obj/
bin/*.elf
*.tyra
.vscode/
.tyra-engine-patch/
)";

static const char* TPL_DIR_KEEP = "*\n!.gitignore\n";

static std::string floatLit(float v) {
    char buf[40];
    std::snprintf(buf, sizeof(buf), "%.6g", (double)v);
    std::string s = buf;
    // "8" -> "8.0": the F suffix is only valid on floating-point literals
    if (s.find('.') == std::string::npos && s.find('e') == std::string::npos &&
        s.find("inf") == std::string::npos && s.find("nan") == std::string::npos)
        s += ".0";
    return s + "F";
}

static std::string vec3Init(const float* v) {
    return "{" + floatLit(v[0]) + ", " + floatLit(v[1]) + ", " + floatLit(v[2]) + "}";
}

// inc/scene_data.hpp - pure data mirror of project.json, regenerated on build
static std::string sceneDataContent(const Project& p, const std::string& ns) {
    std::ostringstream out;
    out << "// Generated by tyra-editor. Do not edit - regenerated on every build.\n"
           "#pragma once\n"
           "\n"
           "namespace "
        << ns
        << " {\n"
           "\n"
           "struct SceneObjectData {\n"
           "  int type;  // 0=box 1=sphere 2=cylinder 3=cone 4=spawn-point\n"
           "  float position[3];\n"
           "  float rotation[3];  // degrees\n"
           "  float scale[3];\n"
           "  float color[3];  // 0..1\n"
           "  int physics;  // 1 = falls with gravity\n"
           "  int model;    // index into MODELS (model_data.gen.hpp), -1 = none\n"
           "};\n"
           "\n"
           "constexpr int SCENE_OBJECT_COUNT = "
        << p.objects.size() << ";\n"
        << "constexpr SceneObjectData SCENE_OBJECTS[SCENE_OBJECT_COUNT > 0 ? "
           "SCENE_OBJECT_COUNT : 1] = {\n";
    if (p.objects.empty()) {
        out << "    {0, {0, 0, 0}, {0, 0, 0}, {1, 1, 1}, {1, 1, 1}, 0, -1},\n";
    } else {
        for (const SceneObject& o : p.objects) {
            out << "    {" << (int)o.type << ", " << vec3Init(o.position) << ", "
                << vec3Init(o.rotation) << ", " << vec3Init(o.scale) << ", "
                << vec3Init(o.color) << ", " << (o.physics ? 1 : 0) << ", "
                << modelIndexOf(p, o) << "},  // " << o.name << "\n";
        }
    }
    out << "};\n"
           "\n"
           "}  // namespace "
        << ns << "\n";
    return out.str();
}

static std::string sanitizeNamespace(const std::string& name) {
    // Project name -> valid C++ namespace: letters/digits/underscore, no leading digit
    std::string ns;
    for (char c : name) {
        if (isalnum((unsigned char)c) || c == '_')
            ns += c;
        else
            ns += '_';
    }
    if (ns.empty() || isdigit((unsigned char)ns[0])) ns = "Game" + ns;
    if (!ns.empty() && islower((unsigned char)ns[0])) ns[0] = (char)toupper((unsigned char)ns[0]);
    return ns;
}

static std::string fillTemplate(const Project& p, const char* tpl) {
    // docker compose project name: lowercase, must start with letter/digit
    std::string nameLower;
    for (char c : p.name) nameLower += (char)tolower((unsigned char)c);
    if (nameLower.empty() || !isalnum((unsigned char)nameLower[0]))
        nameLower = "tyra-" + nameLower;

    std::string s = tpl;
    s = replaceAll(s, "{{NAME_LOWER}}", nameLower);
    s = replaceAll(s, "{{NAME}}", p.name);
    s = replaceAll(s, "{{NAME_UPPER_NS}}", sanitizeNamespace(p.name));
    s = replaceAll(s, "{{WIDTH}}", std::to_string(p.terrain.width));
    s = replaceAll(s, "{{DEPTH}}", std::to_string(p.terrain.depth));

    const ProjectSettings& st = p.settings;
    s = replaceAll(s, "{{DETAIL}}", std::to_string(st.terrainDetail));
    s = replaceAll(s, "{{CLIP_PRECISE}}", st.clipping == "fast" ? "false" : "true");
    s = replaceAll(s, "{{SKY_R}}", floatLit(st.skyColor[0] * 255.0f));
    s = replaceAll(s, "{{SKY_G}}", floatLit(st.skyColor[1] * 255.0f));
    s = replaceAll(s, "{{SKY_B}}", floatLit(st.skyColor[2] * 255.0f));
    s = replaceAll(s, "{{EYE_HEIGHT}}", floatLit(st.eyeHeight));
    s = replaceAll(s, "{{WALK_SPEED}}", floatLit(st.walkSpeed));
    s = replaceAll(s, "{{LOOK_SPEED}}", floatLit(st.lookSpeed));
    s = replaceAll(s, "{{ORBIT_SPEED}}", floatLit(st.orbitSpeed));
    s = replaceAll(s, "{{GRAVITY}}", floatLit(st.gravity));
    s = replaceAll(s, "{{JUMP_SPEED}}", floatLit(st.jumpSpeed));
    s = replaceAll(s, "{{SKY_DOME}}", st.skyDome ? "true" : "false");
    s = replaceAll(s, "{{SKY_TOP_R}}", floatLit(st.skyTopColor[0] * 255.0f));
    s = replaceAll(s, "{{SKY_TOP_G}}", floatLit(st.skyTopColor[1] * 255.0f));
    s = replaceAll(s, "{{SKY_TOP_B}}", floatLit(st.skyTopColor[2] * 255.0f));
    {
        float lx = st.lightDir[0], ly = st.lightDir[1], lz = st.lightDir[2];
        const float len = std::sqrt(lx * lx + ly * ly + lz * lz);
        if (len > 1e-5f) lx /= len, ly /= len, lz /= len;
        else lx = 0, ly = 1, lz = 0;
        s = replaceAll(s, "{{LIGHT_X}}", floatLit(lx));
        s = replaceAll(s, "{{LIGHT_Y}}", floatLit(ly));
        s = replaceAll(s, "{{LIGHT_Z}}", floatLit(lz));
    }
    s = replaceAll(s, "{{AMBIENT}}", floatLit(st.ambient));
    s = replaceAll(s, "{{DIFFUSE}}", floatLit(st.diffuse));
    return s;
}

bool matchesLegacy(const Project& p, const std::string& relativePath,
                   const std::string& content) {
    const char* tpl = nullptr;
    if (relativePath == "src\\terrain_game.cpp")
        tpl = TPL_GAME_CPP_V1;
    else if (relativePath == "inc\\terrain_game.hpp")
        tpl = TPL_GAME_HPP_V1;
    if (!tpl) return false;
    return content == fillTemplate(p, tpl);
}

// ---------------------------------------------------------------------------
// Flow graph -> C++ script. Object names are resolved to indices at codegen
// time; unknown names produce a comment instead of code.
// ---------------------------------------------------------------------------
std::string flowGraphScript(const Project& p) {
    const std::string ns = sanitizeNamespace(p.name);

    auto objectIndex = [&](const std::string& name) {
        for (size_t i = 0; i < p.objects.size(); ++i)
            if (p.objects[i].name == name) return (int)i;
        return -1;
    };

    // action node -> inline statements
    auto actionCode = [&](const FlowNode& n, const std::string& pad) -> std::string {
        std::ostringstream c;
        const int idx = objectIndex(n.str);
        const bool needsObject = flowNodeType(n.type)->strKind == FlowParamKind::ObjectName;
        if (needsObject && idx < 0) {
            c << pad << "// node " << n.id << " (" << n.type << "): unknown object '"
              << n.str << "'\n";
            return c.str();
        }
        const std::string obj = "ctx.objects[" + std::to_string(idx) + "]";
        if (n.type == "SetSky") {
            c << pad << "ctx.skyColor = Tyra::Color(" << floatLit(n.num[0] * 255.0f) << ", "
              << floatLit(n.num[1] * 255.0f) << ", " << floatLit(n.num[2] * 255.0f) << ");\n";
        } else if (n.type == "ShowObject") {
            c << pad << obj << ".visible = true;\n";
        } else if (n.type == "HideObject") {
            c << pad << obj << ".visible = false;\n";
        } else if (n.type == "ToggleObject") {
            c << pad << obj << ".visible = !" << obj << ".visible;\n";
        } else if (n.type == "MoveObjectBy") {
            for (int a = 0; a < 3; ++a)
                if (n.num[a] != 0.0f)
                    c << pad << obj << ".data.position[" << a << "] += " << floatLit(n.num[a])
                      << ";\n";
            c << pad << obj << ".dirty = true;\n";
        } else if (n.type == "SetObjectColor") {
            for (int a = 0; a < 3; ++a)
                c << pad << obj << ".data.color[" << a << "] = " << floatLit(n.num[a]) << ";\n";
            c << pad << obj << ".dirty = true;\n";
        } else if (n.type == "Log") {
            std::string text = n.str;
            text = replaceAll(text, "\\", "\\\\");
            text = replaceAll(text, "\"", "\\\"");
            c << pad << "TYRA_LOG(\"" << text << "\");\n";
        }
        return c.str();
    };

    // all actions linked to a trigger
    auto linkedActions = [&](int triggerId, const std::string& pad) {
        std::ostringstream c;
        for (const FlowLink& l : p.flowGraph.links) {
            if (l.fromNode != triggerId) continue;
            for (const FlowNode& n : p.flowGraph.nodes) {
                if (n.id != l.toNode) continue;
                const FlowNodeType* t = flowNodeType(n.type);
                if (t && !t->trigger) c << actionCode(n, pad);
            }
        }
        return c.str();
    };

    std::ostringstream out;
    out << "// Generated by tyra-editor from the Flow Graph. Do not edit -\n"
           "// regenerated on every build. Edit the graph in the editor instead.\n"
           "#include \"scripts/script.hpp\"\n\n"
           "namespace "
        << ns
        << " {\n\n"
           "class FlowGraphScript : public Script {\n"
           " public:\n"
           "  void update(ScriptContext& ctx) override {\n"
           "    frame++;\n";

    std::ostringstream members;
    for (const FlowNode& n : p.flowGraph.nodes) {
        const FlowNodeType* t = flowNodeType(n.type);
        if (!t || !t->trigger) continue;
        const std::string body = linkedActions(n.id, "      ");
        if (body.empty()) continue;

        if (n.type == "OnStart") {
            out << "    if (!started) {\n      started = true;\n" << body << "    }\n";
        } else if (n.type == "OnButton") {
            std::string btn = n.str.empty() ? "Cross" : n.str;
            out << "    if (ctx.engine->pad.getClicked()." << btn << ") {\n" << body
                << "    }\n";
        } else if (n.type == "NearObject") {
            const int idx = objectIndex(n.str);
            if (idx < 0) {
                out << "    // node " << n.id << " (NearObject): unknown object '" << n.str
                    << "'\n";
                continue;
            }
            const std::string flag = "near" + std::to_string(n.id);
            members << "  bool " << flag << " = false;\n";
            const float r = n.num[0] > 0.01f ? n.num[0] : 3.0f;
            out << "    {\n      const float dx = ctx.playerPosition.x - ctx.objects[" << idx
                << "].data.position[0];\n      const float dz = ctx.playerPosition.z - "
                   "ctx.objects["
                << idx << "].data.position[2];\n      const bool isNear = dx * dx + dz * dz < "
                << floatLit(r * r) << ";\n      if (isNear && !" << flag << ") {\n"
                << body << "      }\n      " << flag << " = isNear;\n    }\n";
        } else if (n.type == "EverySeconds") {
            int frames = (int)(n.num[0] * 50.0f);
            if (frames < 1) frames = 1;
            out << "    if (frame % " << frames << " == 0) {\n" << body << "    }\n";
        }
    }

    out << "  }\n\n"
           " private:\n"
           "  int frame = 0;\n"
           "  bool started = false;\n"
        << members.str()
        << "};\n\n"
           "}  // namespace "
        << ns << "\n\nTYRA_SCRIPT(" << ns << "::FlowGraphScript);\n";
    return out.str();
}

// inc/model_data.gen.hpp - .obj meshes compiled into the game (pos + normal,
// 6 floats per vertex). Capped per model to stay PS2-friendly.
static std::string modelDataHeader(const Project& p) {
    const std::string ns = sanitizeNamespace(p.name);
    const auto paths = collectModelPaths(p);
    constexpr int kMaxTris = 3000;

    std::ostringstream out;
    out << "// Generated by tyra-editor. Do not edit - regenerated on every build.\n"
           "#pragma once\n\nnamespace "
        << ns
        << " {\n\n"
           "struct ModelData {\n"
           "  const float* verts;  // 6 floats per vertex: x,y,z,nx,ny,nz\n"
           "  int vertexCount;\n"
           "};\n\n"
        << "constexpr int MODEL_COUNT = " << paths.size() << ";\n\n";

    for (size_t m = 0; m < paths.size(); ++m) {
        std::vector<float> data;
        const bool ok =
            objparser::load((std::filesystem::path(p.dir) / paths[m]).string(), data);
        int vertexCount = ok ? (int)(data.size() / 6) : 0;
        if (vertexCount > kMaxTris * 3) {
            out << "// " << paths[m] << ": truncated from " << vertexCount / 3 << " to "
                << kMaxTris << " triangles\n";
            vertexCount = kMaxTris * 3;
        }
        out << "// " << paths[m] << (ok ? "" : " (missing or unparseable)") << "\n";
        out << "constexpr float MODEL_" << m << "_VERTS[] = {";
        for (int i = 0; i < vertexCount * 6; ++i) {
            if (i % 6 == 0) out << "\n    ";
            out << floatLit(data[i]) << ",";
        }
        if (vertexCount == 0) out << "0.0F";  // avoid empty array
        out << "\n};\nconstexpr int MODEL_" << m << "_COUNT = " << vertexCount << ";\n\n";
    }

    out << "inline const ModelData MODELS[MODEL_COUNT > 0 ? MODEL_COUNT : 1] = {\n";
    if (paths.empty()) {
        out << "    {nullptr, 0},\n";
    } else {
        for (size_t m = 0; m < paths.size(); ++m)
            out << "    {MODEL_" << m << "_VERTS, MODEL_" << m << "_COUNT},\n";
    }
    out << "};\n\n}  // namespace " << ns << "\n";
    return out.str();
}

// inc/hud_data.gen.hpp - HUD image sprites (PNG paths relative to bin/)
static std::string hudDataHeader(const Project& p) {
    const std::string ns = sanitizeNamespace(p.name);
    std::ostringstream out;
    out << "// Generated by tyra-editor. Do not edit - regenerated on every build.\n"
           "#pragma once\n\nnamespace "
        << ns
        << " {\n\n"
           "struct HudImageData {\n"
           "  const char* path;  // relative to the game binary (res/ is copied there)\n"
           "  float x, y;        // normalized screen position, center anchor\n"
           "  float w, h;        // size in pixels\n"
           "};\n\n"
        << "constexpr int HUD_COUNT = " << p.hud.size() << ";\n"
        << "inline const HudImageData HUD_IMAGES[HUD_COUNT > 0 ? HUD_COUNT : 1] = {\n";
    if (p.hud.empty()) {
        out << "    {\"\", 0, 0, 0, 0},\n";
    } else {
        for (const HudImage& h : p.hud) {
            // res/hud/x.png on the host lands as hud/x.png next to the ELF
            std::string binPath = h.imagePath;
            if (binPath.rfind("res/", 0) == 0) binPath = binPath.substr(4);
            out << "    {\"" << binPath << "\", " << floatLit(h.pos[0]) << ", "
                << floatLit(h.pos[1]) << ", " << floatLit(h.size[0]) << ", "
                << floatLit(h.size[1]) << "},  // " << h.name << "\n";
        }
    }
    out << "};\n\n}  // namespace " << ns << "\n";
    return out.str();
}

std::string scriptStub(const Project& p, const std::string& className,
                       const std::string& fileName) {
    std::string s = fillTemplate(p, TPL_SCRIPT_STUB);
    s = replaceAll(s, "{{SCRIPT_CLASS}}", className);
    s = replaceAll(s, "{{SCRIPT_FILE}}", fileName);
    return s;
}

// .vscode/c_cpp_properties.json - IntelliSense for scripts in VS Code.
// Uses the editor's bundled Tyra engine headers and the PS2SDK headers
// exported from the docker toolchain (see Runner). Machine-specific paths,
// hence regenerated on every build.
static std::string vscodeCppProperties() {
    auto slashes = [](std::string s) {
        for (auto& c : s)
            if (c == '\\') c = '/';
        return s;
    };

    std::string engineInc;
    char exePath[MAX_PATH] = {};
    if (GetModuleFileNameA(nullptr, exePath, MAX_PATH) > 0) {
        std::filesystem::path candidate = std::filesystem::path(exePath).parent_path() /
                                          ".." / "vendor" / "tyra" / "engine" / "inc";
        std::error_code ec;
        if (std::filesystem::exists(candidate, ec))
            engineInc = slashes(std::filesystem::weakly_canonical(candidate, ec).string());
    }

    std::string sdk;
    if (const char* lad = getenv("LOCALAPPDATA"))
        sdk = slashes(std::string(lad) + "\\tyra-editor\\ps2sdk");

    std::ostringstream out;
    out << "{\n"
           "  \"configurations\": [\n"
           "    {\n"
           "      \"name\": \"PS2 (Tyra)\",\n"
           "      \"includePath\": [\n"
           "        \"${workspaceFolder}/inc\",\n"
           "        \"${workspaceFolder}/src\"";
    if (!engineInc.empty()) out << ",\n        \"" << engineInc << "\"";
    if (!sdk.empty())
        out << ",\n        \"" << sdk << "/ee/include\",\n        \"" << sdk
            << "/common/include\"";
    out << "\n      ],\n"
           "      \"defines\": [\"_EE\"],\n"
           "      \"cStandard\": \"c11\",\n"
           "      \"cppStandard\": \"c++20\",\n"
           "      \"intelliSenseMode\": \"linux-gcc-x86\"\n"
           "    }\n"
           "  ],\n"
           "  \"version\": 4\n"
           "}\n";
    return out.str();
}

std::vector<File> generate(const Project& p) {
    const std::string ns = sanitizeNamespace(p.name);
    auto fill = [&](const char* tpl) { return fillTemplate(p, tpl); };

    const bool fpp = p.gameTemplate == "fpp";
    const std::string gameCpp =
        fill(TPL_GAME_CPP_PROLOG) +
        fill(fpp ? TPL_GAME_CPP_FPP_HEAD : TPL_GAME_CPP_ORBIT_HEAD) +
        fill(TPL_GAME_CPP_SCENE) +
        fill(fpp ? TPL_GAME_CPP_FPP_TAIL : TPL_GAME_CPP_ORBIT_TAIL) +
        fill(TPL_GAME_CPP_FOOTER);

    return {
        {"Makefile", fill(TPL_MAKEFILE)},
        {"Dockerfile", fill(TPL_DOCKERFILE)},
        {"docker-compose.yml", fill(TPL_COMPOSE)},
        {"src\\main.cpp", fill(TPL_MAIN_CPP)},
        {"src\\terrain_game.cpp", gameCpp},
        {"inc\\terrain_game.hpp", fill(fpp ? TPL_GAME_HPP_FPP : TPL_GAME_HPP_ORBIT)},
        {"inc\\terrain_config.hpp", fill(TPL_TERRAIN_CONFIG_HPP)},
        {"inc\\scene_data.hpp", sceneDataContent(p, ns)},
        {"inc\\model_data.gen.hpp", modelDataHeader(p)},
        {"inc\\hud_data.gen.hpp", hudDataHeader(p)},
        {"inc\\scripts\\script.hpp", fill(TPL_SCRIPT_HPP)},
        {"src\\scripts\\flow_graph.gen.cpp", flowGraphScript(p)},
        {".tyra-engine-patch\\planes_clip_algorithm.cpp", TPL_ENGINE_PATCH_ALGO},
        {".tyra-engine-patch\\stapip_clipper.cpp", TPL_ENGINE_PATCH_CLIPPER},
        {".tyra-engine-patch\\stapip_qbuffer.cpp", TPL_ENGINE_PATCH_QBUFFER},
        {".tyra-engine-patch\\render_bbox.cpp", TPL_ENGINE_PATCH_BBOX},
        {".tyra-engine-patch\\apply_vu1_guardband.sh", TPL_ENGINE_PATCH_VU1_SH},
        {"src\\scripts\\example_interaction.cpp",
         fill(fpp ? TPL_EXAMPLE_SCRIPT_FPP : TPL_EXAMPLE_SCRIPT_ORBIT)},
        {".vscode\\c_cpp_properties.json", vscodeCppProperties()},
        {"run.ps1", fill(TPL_RUN_PS1)},
        {"windows-pcsx2.ps1", fill(TPL_PCSX2_PS1)},
        {".gitignore", fill(TPL_GITIGNORE)},
        {"res\\.gitignore", TPL_DIR_KEEP},
        {"bin\\.gitignore", TPL_DIR_KEEP},
        {"obj\\.gitignore", TPL_DIR_KEEP},
    };
}

}  // namespace templates
