#pragma once
#include "night_plan.hpp"
#include "debug/night_ablation.hpp"
#include <type_traits>
namespace NightRuntime {
inline NightPlan::Config planConfig{};inline FILE* file=nullptr;inline bool initialized=false,done=false;
using Counter=typename std::remove_reference<decltype(NightAblation::commonCounter[0])>::type;

inline bool readFlag(const char* path,unsigned& value,bool optional=false,unsigned defaultValue=0){FILE* f=fopen(path,"r");if(!f){value=defaultValue;return optional;}int firstChar;do{firstChar=fgetc(f);}while(firstChar!=EOF&&isspace(static_cast<unsigned char>(firstChar)));bool good=firstChar=='0'||firstChar=='1';value=good?unsigned(firstChar-'0'):defaultValue;int c;while((c=fgetc(f))!=EOF)if(!isspace(static_cast<unsigned char>(c)))good=false;if(ferror(f))good=false;fclose(f);return good;}
inline bool init(const char* path,const char* artifact){NightSampler::PhaseConfig phases[3]{};bool ok=NightPlan::readConfig(path,planConfig)&&NightPlan::build(planConfig,phases);ok=NightSampler::initPlan(phases)&&ok;file=fopen(artifact,"w");initialized=true;done=false;NightSampler::valid=NightSampler::valid&&ok&&file;return NightSampler::valid;}
inline void config(unsigned video,unsigned display,unsigned depth,unsigned width,unsigned height,unsigned refreshMilliHz,unsigned requested,unsigned night,unsigned rasterWidth,unsigned rasterHeight,unsigned scaleX,unsigned scaleY){
 printf("LOG: NIGHTPLAN schema=1 kind=%u order=%u joint=%u restored=%u phases=3\n",unsigned(planConfig.kind),unsigned(planConfig.order),unsigned(planConfig.joint),unsigned(planConfig.restored));
 printf("LOG: NIGHTCONFIG order=%u valid=%u profile=0 hardwareTrace=0 ringBytes=0 ordinaryClocks=1 fixedDt=0 sampleBytes=%u chunkBytes=%u phases=3 phaseFrames=1800 taxFirst=800 taxLoops=320 chunkFrames=64 sampleFirst=900 sampleCount=128 video=%u display=%u depth=%u width=%u height=%u refreshMilliHz=%u requested=%u night=%u\n",unsigned(planConfig.order),unsigned(NightSampler::valid?1u:0u),unsigned(sizeof(NightSampler::samples)),unsigned(sizeof(NightSampler::chunks)),unsigned(video),unsigned(display),unsigned(depth),unsigned(width),unsigned(height),unsigned(refreshMilliHz),unsigned(requested),unsigned(night));
 printf("LOG: NIGHTQUALITY rasterWidth=%u rasterHeight=%u scaleX=%u scaleY=%u\n",unsigned(rasterWidth),unsigned(rasterHeight),unsigned(scaleX),unsigned(scaleY));fflush(stdout);
}
inline void begin(unsigned pacing){if(!initialized)return;unsigned index=NightSampler::expectedIndex,p=index/1800,o=index%1800;if(p<3&&o==0){bool applied=NightAblation::setMask(NightSampler::phaseMask(index));NightSampler::valid=NightSampler::valid&&applied&&NightAblation::valid;printf("LOG: NIGHTPHASE phase=%u first=%u mask=%u appliedMask=%u sampler=%u countReads=%u samplePtr=%08x\n",unsigned(p),unsigned(index),unsigned(NightSampler::plan[p].mask),unsigned(NightAblation::mask),unsigned(NightSampler::mode(p)?1u:0u),unsigned(NightSampler::mode(p)?262u:6u),unsigned(reinterpret_cast<uintptr_t>(NightSampler::samples)));fflush(stdout);}NightAblation::collectCounters=p<3&&(o==750||o==1155);if(NightAblation::collectCounters)for(unsigned i=0;i<7;++i)NightAblation::commonCounter[i]=Counter{};NightSampler::beginLoop(index,pacing);}
inline void afterLoop(unsigned pacing){if(!initialized)return;using namespace NightSampler;endLoop(pacing);unsigned p=frame/1800,o=frame%1800;valid=valid&&NightAblation::valid;if(p>=3)return;
 NightAblation::collectCounters=false;
 if(o==750||o==1155){printf("LOG: NIGHTGATES phase=%u offset=%u first=%u frames=1 mask=%u",unsigned(p),unsigned(o),unsigned(o),unsigned(plan[p].mask));for(unsigned i=0;i<7;++i){unsigned bit=1u<<i;const auto& c=NightAblation::commonCounter[i];printf(" attempted%u=%u executed%u=%u skipped%u=%u submitted%u=%u",unsigned(bit),unsigned(c.attempted),unsigned(bit),unsigned(c.executed),unsigned(bit),unsigned(c.skipped),unsigned(bit),unsigned(c.submitted));}printf("\n");fflush(stdout);}
 if(o>=1200&&o<1328){if(!file){valid=false;return;}unsigned i=o-1200;if(i<5){const auto& c=chunks[p][i];fprintf(file,"LOG: NIGHTCHUNK phase=%u i=%u first=%u loops=%u elapsed=%u pacing=%u totalFlips=%u renderedFlips=%u syntheticFlips=%u\n",unsigned(p),unsigned(i),unsigned(c.first),unsigned(c.loops),unsigned(c.elapsed),unsigned(c.pacing),unsigned(c.totalFlips),unsigned(c.renderedFlips),unsigned(c.syntheticFlips));}if(mode(p)){const auto& s=samples[i];fprintf(file,"LOG: NIGHTRAW phase=%u i=%u frame=%u entryPeriod=%u wholeLoop=%u pacing=%u totalFlips=%u renderedFlips=%u syntheticFlips=%u presentPeriod=%u renderedPeriod=%u lastKind=%u sequence=%u context=%u\n",unsigned(p),unsigned(i),unsigned(s.frame),unsigned(s.entryPeriod),unsigned(s.wholeLoop),unsigned(s.pacing),unsigned(s.totalFlips),unsigned(s.renderedFlips),unsigned(s.syntheticFlips),unsigned(s.presentPeriod),unsigned(s.renderedPeriod),unsigned(s.lastKind),unsigned(s.sequence),unsigned(s.context));}if(ferror(file))valid=false;if(i==127){markExported(p);fprintf(file,"LOG: NIGHTWINDOW phase=%u sampler=%u raw=%u chunks=%u valid=%u\n",unsigned(p),unsigned(mode(p)?1u:0u),unsigned(counts[p]),unsigned(chunkCounts[p]),unsigned(valid?1u:0u));if(fflush(file)!=0)valid=false;}}
 if(frame==5399&&!done){done=true;if(file){if(fclose(file)!=0)valid=false;file=nullptr;}printf("LOG: NIGHTDONE order=%u valid=%u loops=5400\n",unsigned(planConfig.order),unsigned(complete()?1u:0u));fflush(stdout);}
}
}
