// Generated by TyraX. Do not edit - regenerated on every build.
#include "save_system.gen.hpp"

#include <tyra>
#include <libmc.h>
#include <loadfile.h>
#include <stdio.h>
#include <string>

namespace Mirror_room {

static bool mcTried = false;
static bool mcReady = false;
// [xmcman, mcman, xmcserv, mcserv] SifLoadModule codes + [mcInit, getInfo,
// probeOpen, formatResult, probeOpen-after-format]
static int initCodes[9] = {-999, -999, -999, -999, -999, -999, -999, -999, -999};

// ioman-style open flags understood by mcserv
static const int kMcRdonly = 0x0001, kMcWronly = 0x0002, kMcCreat = 0x0200;

// Judges card health by doing exactly what saves do: ensure the save dir
// and open/close/delete a probe file. Returns the mcOpen result; -2 is
// sceMcResNoFormat (a virgin card).
static int probeCard() {
  int r = -100;
  mcMkDir(0, 0, SAVE_MC_DIR);
  mcSync(MC_WAIT, nullptr, &r);  // "already exists" is fine - the open decides
  std::string probe = std::string(SAVE_MC_DIR) + "/probe.tmp";
  int fd = -100;
  mcOpen(0, 0, probe.c_str(), kMcWronly | kMcCreat);
  mcSync(MC_WAIT, nullptr, &fd);
  if (fd >= 0) {
    mcClose(fd);
    mcSync(MC_WAIT, nullptr, &r);
    mcDelete(0, 0, probe.c_str());
    mcSync(MC_WAIT, nullptr, &r);
  }
  return fd;
}

bool saveInit() {
  if (mcTried) return mcReady;
  mcTried = true;
  // BIOS ROM modules - nothing to embed. The X variants pair with the
  // ps2sdk sio2man the engine already loaded; plain MCMAN/MCSERV are the
  // fallback for early BIOSes. Never load a variant twice - a second
  // instance over a resident one hangs the IOP.
  initCodes[0] = SifLoadModule("rom0:XMCMAN", 0, nullptr);
  if (initCodes[0] < 0) initCodes[1] = SifLoadModule("rom0:MCMAN", 0, nullptr);
  const bool useX = initCodes[0] >= 0;
  const bool mcman = useX || initCodes[1] >= 0;
  bool mcserv = false;
  if (mcman) {
    if (useX) {
      initCodes[2] = SifLoadModule("rom0:XMCSERV", 0, nullptr);
      mcserv = initCodes[2] >= 0;
    } else {
      initCodes[3] = SifLoadModule("rom0:MCSERV", 0, nullptr);
      mcserv = initCodes[3] >= 0;
    }
  }
  if (mcman && mcserv) {
    initCodes[4] = mcInit(useX ? MC_TYPE_XMC : MC_TYPE_MC);
    if (initCodes[4] >= 0) {
      // Clear the "card changed" latch (the first query after boot always
      // reports a change). The out params are unreliable across module
      // variants, so card health is judged by a real probe write instead.
      int type = 0, freeSpace = 0, format = 0, ret = -100;
      mcGetInfo(0, 0, &type, &freeSpace, &format);
      mcSync(MC_WAIT, nullptr, &ret);
      initCodes[5] = ret;
      int fd = probeCard();
      if (fd == -1) fd = probeCard();  // -1 = changed-card latch; retry once
      initCodes[6] = fd;
      if (fd == -2) {
        // sceMcResNoFormat: a virgin card (PCSX2 images start unformatted)
        // holds no data, so formatting it destroys nothing. Formatted
        // cards never return this code.
        int fr = -100;
        mcFormat(0, 0);
        mcSync(MC_WAIT, nullptr, &fr);
        initCodes[7] = fr;
        fd = probeCard();
        if (fd == -1) fd = probeCard();
        initCodes[8] = fd;
      }
      mcReady = fd >= 0;
    }
  }
  if (mcReady) saveEnsureIcons();
  TYRA_LOG("Save system: ", mcReady ? "memory card ready"
                                    : "no memory card - using host files");
  return mcReady;
}

bool saveMcReady() { return mcReady; }

const int* saveInitCodes() { return initCodes; }

// --- Save icon (icon.sys + list.icn) ----------------------------------------
// The editor bakes both into res/save/ (savebake.cpp) and the Makefile ships
// them next to the ELF as save/icon.sys + save/list.icn; here they are copied
// into the save directory so the PS2 browser shows the game's title and icon.
// mcWrite DMAs straight from the buffer - same 64-byte alignment rule as the
// slot payload. The buffer is sized by codegen to this build's baked icon.
alignas(64) static unsigned char iconBuf[33792];

static bool mcCopyToCard(const char* hostRel, const char* cardName) {
  FILE* f = fopen(Tyra::FileUtils::fromCwd(hostRel).c_str(), "rb");
  if (!f) return false;
  fseek(f, 0, SEEK_END);
  const long n = ftell(f);
  fseek(f, 0, SEEK_SET);
  if (n <= 0 || n > (long)sizeof(iconBuf)) {
    fclose(f);
    return false;
  }
  const size_t got = fread(iconBuf, 1, (size_t)n, f);
  fclose(f);
  if ((long)got != n) return false;
  std::string path = std::string(SAVE_MC_DIR) + "/" + cardName;
  int fd = -1;
  mcOpen(0, 0, path.c_str(), kMcWronly | kMcCreat);
  mcSync(MC_WAIT, nullptr, &fd);
  if (fd < 0) return false;
  int wrote = -1, ret = 0;
  mcWrite(fd, iconBuf, (int)n);
  mcSync(MC_WAIT, nullptr, &wrote);
  mcClose(fd);
  mcSync(MC_WAIT, nullptr, &ret);
  return wrote == (int)n;
}

void saveEnsureIcons() {
  static bool tried = false;
  if (!mcReady || tried) return;
  tried = true;
  // Already iconized by a previous boot - skip the ~33KB rewrite.
  int fd = -100;
  std::string probe = std::string(SAVE_MC_DIR) + "/icon.sys";
  mcOpen(0, 0, probe.c_str(), kMcRdonly);
  mcSync(MC_WAIT, nullptr, &fd);
  if (fd >= 0) {
    int r = 0;
    mcClose(fd);
    mcSync(MC_WAIT, nullptr, &r);
    return;
  }
  const bool sys = mcCopyToCard("save/icon.sys", "icon.sys");
  const bool icn = mcCopyToCard("save/list.icn", "list.icn");
  TYRA_LOG("Save icons: ", sys && icn ? "written to the card" : "copy failed");
}

static std::string mcSlotName(int slot) {
  char buf[96];
  snprintf(buf, sizeof(buf), "%s/save%d.sav", SAVE_MC_DIR, slot);
  return std::string(buf);
}

static std::string hostSlotPath(int slot) {
  char buf[32];
  snprintf(buf, sizeof(buf), "save%d.sav", slot);  // next to the ELF
  return Tyra::FileUtils::fromCwd(buf);
}

bool saveWrite(int slot, const SaveGameData& data) {
  if (slot < 0 || slot >= SAVE_SLOTS) return false;
  if (mcReady) {
    int fd = -1;
    mcOpen(0, 0, mcSlotName(slot).c_str(), kMcWronly | kMcCreat);
    mcSync(MC_WAIT, nullptr, &fd);
    if (fd < 0) return false;
    int wrote = -1, ret = 0;
    mcWrite(fd, &data, sizeof(data));
    mcSync(MC_WAIT, nullptr, &wrote);
    mcClose(fd);
    mcSync(MC_WAIT, nullptr, &ret);
    return wrote == (int)sizeof(data);
  }
  FILE* f = fopen(hostSlotPath(slot).c_str(), "wb");
  if (!f) return false;
  const size_t written = fwrite(&data, 1, sizeof(data), f);
  fclose(f);
  return written == sizeof(data);
}

// --- Asynchronous write (docs/save-editor.md) --------------------------------
// Every libmc call is asynchronous already - the blocking saveWrite above just
// answers each one with mcSync(MC_WAIT). Here the same open/write/close chain
// is driven ONE STEP PER FRAME with mcSync(MC_NOWAIT), whose contract is:
// 0 = still executing, 1 = finished (result written out), -1 = nothing
// registered. The game keeps running in between.
//
// The payload is copied into asyncData up front, so nothing the player does
// during the transfer can change the bytes being written.
static SaveGameData asyncData;
static int asyncStage = 0;  // 0 idle, 1 open, 2 write, 3 close, 4 host one-shot
static int asyncSlot = -1, asyncFd = -1;
static bool asyncOk = false;

bool saveWriteBusy() { return asyncStage != 0; }

bool saveWriteBegin(int slot, const SaveGameData& data) {
  if (asyncStage != 0) return false;  // one transfer at a time
  if (slot < 0 || slot >= SAVE_SLOTS) return false;
  asyncData = data;
  asyncSlot = slot;
  asyncOk = false;
  asyncFd = -1;
  if (!mcReady) {
    // The host fallback is a plain fwrite next to the ELF - microseconds, and
    // there is no libmc chain to step through. Finish it on the next poll so
    // both paths look identical to the caller.
    asyncStage = 4;
    return true;
  }
  mcOpen(0, 0, mcSlotName(slot).c_str(), kMcWronly | kMcCreat);
  asyncStage = 1;
  return true;
}

bool saveWritePoll(bool* okOut) {
  if (asyncStage == 0) return true;
  if (asyncStage == 4) {  // host fallback
    asyncOk = saveWrite(asyncSlot, asyncData);
    asyncStage = 0;
    if (okOut) *okOut = asyncOk;
    return true;
  }
  int cmd = 0, res = -1;
  const int sync = mcSync(MC_NOWAIT, &cmd, &res);
  if (sync == 0) return false;  // still executing - come back next frame
  if (sync < 0) {               // nothing registered: the chain is broken
    asyncStage = 0;
    if (okOut) *okOut = false;
    return true;
  }
  if (asyncStage == 1) {
    asyncFd = res;
    if (asyncFd < 0) {
      asyncStage = 0;
      if (okOut) *okOut = false;
      return true;
    }
    mcWrite(asyncFd, &asyncData, sizeof(asyncData));
    asyncStage = 2;
    return false;
  }
  if (asyncStage == 2) {
    asyncOk = res == (int)sizeof(asyncData);
    mcClose(asyncFd);
    asyncStage = 3;
    return false;
  }
  // stage 3: the close landed, so the slot is on the card
  asyncStage = 0;
  if (okOut) *okOut = asyncOk;
  return true;
}

bool saveRead(int slot, SaveGameData& out) {
  if (slot < 0 || slot >= SAVE_SLOTS) return false;
  int got = -1;
  if (mcReady) {
    int fd = -1;
    mcOpen(0, 0, mcSlotName(slot).c_str(), kMcRdonly);
    mcSync(MC_WAIT, nullptr, &fd);
    if (fd < 0) return false;
    int ret = 0;
    mcRead(fd, &out, sizeof(out));
    mcSync(MC_WAIT, nullptr, &got);
    mcClose(fd);
    mcSync(MC_WAIT, nullptr, &ret);
  } else {
    FILE* f = fopen(hostSlotPath(slot).c_str(), "rb");
    if (!f) return false;
    got = (int)fread(&out, 1, sizeof(out), f);
    fclose(f);
  }
  if (got != (int)sizeof(out)) return false;
  if (out.magic != SAVE_MAGIC || out.version != SAVE_VERSION) return false;
  if (out.scene < 0 || out.scene >= SCENE_COUNT) return false;
  if (out.valueCount < 0 || out.valueCount > SAVE_VALUE_COUNT) return false;
  if (out.objectCount < 0 || out.objectCount > SAVE_OBJECT_MAX) return false;
  return true;
}

bool saveSlotUsed(int slot) {
  static SaveGameData probe;  // static - the payload can be a few KB
  return saveRead(slot, probe);
}

}  // namespace Mirror_room
