// Generated by TyraX. Do not edit - regenerated on every build.
#pragma once

namespace Reverb_rooms {

// A glyph's cell in the atlas and how to lay it down. Mirrors
// menubake::AtlasGlyph - the metrics here and the baked pixels come
// from the same atlasLayout() call, so they cannot drift.
struct FontGlyph {
  short u, v;        // top-left texel in the atlas
  short w, h;        // glyph size (0 = nothing to draw)
  short xoff, yoff;  // pen/line-top -> glyph top-left, at baseSize
  short adv;         // pen step to the next glyph, at baseSize
};

struct FontData {
  const char* atlas;  // relative to the game binary
  short texW, texH;
  short lineH;        // baseline pitch at baseSize
  short baseSize;     // size the metrics were baked at
  unsigned char r, g, b;  // tint (glyphs bake white)
  unsigned char shadow;   // 1 = draw a dark 1px offset pass first
  const FontGlyph* glyphs;
};

constexpr int FONT_FIRST_CHAR = 32;
constexpr int FONT_CHAR_COUNT = 95;
constexpr int FONT_COUNT = 1;

inline const FontGlyph FONT_GLYPHS_0[FONT_CHAR_COUNT] = {
    {0, 0, 0, 0, 0, 13, 5},
    {16, 0, 4, 11, 1, 2, 6},
    {32, 0, 5, 5, 1, 2, 7},
    {48, 0, 11, 10, 0, 3, 12},
    {64, 0, 8, 14, 1, 2, 10},
    {80, 0, 14, 12, 0, 2, 14},
    {96, 0, 12, 12, 0, 2, 12},
    {112, 0, 2, 5, 1, 2, 4},
    {0, 16, 5, 13, 1, 2, 6},
    {16, 16, 5, 13, 1, 2, 6},
    {32, 16, 7, 8, 0, 2, 7},
    {48, 16, 10, 9, 1, 4, 12},
    {64, 16, 4, 5, 0, 10, 5},
    {80, 16, 5, 3, 0, 8, 6},
    {96, 16, 3, 3, 1, 10, 5},
    {112, 16, 6, 13, 0, 2, 5},
    {0, 32, 9, 12, 0, 2, 10},
    {16, 32, 8, 11, 1, 2, 10},
    {32, 32, 8, 11, 1, 2, 10},
    {48, 32, 9, 12, 0, 2, 10},
    {64, 32, 9, 11, 0, 2, 10},
    {80, 32, 8, 12, 1, 2, 10},
    {96, 32, 9, 12, 0, 2, 10},
    {112, 32, 9, 11, 0, 2, 10},
    {0, 48, 9, 12, 0, 2, 10},
    {16, 48, 9, 12, 0, 2, 10},
    {32, 48, 3, 8, 1, 5, 5},
    {48, 48, 4, 10, 0, 5, 5},
    {64, 48, 10, 9, 1, 4, 12},
    {80, 48, 10, 6, 1, 6, 12},
    {96, 48, 10, 9, 1, 4, 12},
    {112, 48, 8, 11, 0, 2, 8},
    {0, 64, 13, 13, 0, 3, 14},
    {16, 64, 11, 11, 0, 2, 11},
    {32, 64, 9, 11, 1, 2, 10},
    {48, 64, 10, 12, 0, 2, 10},
    {64, 64, 10, 11, 1, 2, 11},
    {80, 64, 8, 11, 1, 2, 9},
    {96, 64, 8, 11, 1, 2, 9},
    {112, 64, 11, 12, 0, 2, 11},
    {0, 80, 10, 11, 1, 2, 12},
    {16, 80, 3, 11, 1, 2, 5},
    {32, 80, 5, 14, -1, 2, 5},
    {48, 80, 11, 11, 1, 2, 11},
    {64, 80, 8, 11, 1, 2, 9},
    {80, 80, 12, 11, 1, 2, 14},
    {96, 80, 10, 11, 1, 2, 12},
    {112, 80, 11, 12, 0, 2, 12},
    {0, 96, 9, 11, 1, 2, 10},
    {16, 96, 11, 14, 0, 2, 12},
    {32, 96, 10, 11, 1, 2, 11},
    {48, 96, 9, 12, 0, 2, 10},
    {64, 96, 10, 11, 0, 2, 9},
    {80, 96, 9, 12, 1, 2, 11},
    {96, 96, 11, 11, 0, 2, 11},
    {112, 96, 15, 11, 0, 2, 15},
    {0, 112, 11, 11, 0, 2, 11},
    {16, 112, 12, 11, -1, 2, 10},
    {32, 112, 10, 11, 0, 2, 10},
    {48, 112, 5, 13, 1, 2, 6},
    {64, 112, 6, 13, 0, 2, 5},
    {80, 112, 6, 13, 0, 2, 6},
    {96, 112, 10, 5, 1, 2, 12},
    {112, 112, 7, 3, 0, 14, 7},
    {0, 128, 5, 3, 0, 2, 7},
    {16, 128, 9, 9, 0, 5, 9},
    {32, 128, 9, 12, 1, 2, 10},
    {48, 128, 8, 9, 0, 5, 8},
    {64, 128, 9, 12, 0, 2, 10},
    {80, 128, 9, 9, 0, 5, 9},
    {96, 128, 7, 11, 0, 2, 6},
    {112, 128, 9, 11, 0, 5, 10},
    {0, 144, 8, 11, 1, 2, 10},
    {16, 144, 3, 11, 1, 2, 5},
    {32, 144, 5, 14, -1, 2, 5},
    {48, 144, 9, 11, 1, 2, 9},
    {64, 144, 3, 11, 1, 2, 5},
    {80, 144, 13, 8, 1, 5, 14},
    {96, 144, 8, 8, 1, 5, 10},
    {112, 144, 9, 9, 0, 5, 9},
    {0, 160, 9, 11, 1, 5, 10},
    {16, 160, 9, 11, 0, 5, 10},
    {32, 160, 6, 8, 1, 5, 7},
    {48, 160, 8, 9, 0, 5, 8},
    {64, 160, 7, 10, 0, 3, 7},
    {80, 160, 8, 9, 1, 5, 10},
    {96, 160, 9, 8, 0, 5, 9},
    {112, 160, 13, 8, 0, 5, 13},
    {0, 176, 9, 8, 0, 5, 9},
    {16, 176, 9, 11, 0, 5, 9},
    {32, 176, 8, 8, 0, 5, 8},
    {48, 176, 8, 14, 1, 2, 10},
    {64, 176, 3, 15, 1, 2, 5},
    {80, 176, 8, 14, 1, 2, 10},
    {96, 176, 10, 4, 1, 7, 12},
};

inline const FontData FONTS[FONT_COUNT > 0 ? FONT_COUNT : 1] = {
    {"fonts/atlas-default.png", 128, 256, 16, 16, 255, 255, 255, 1, FONT_GLYPHS_0},  // Default
};

// One slot per Display Text node (see DynTextSlot in templates.cpp).
struct DynTextData {
  short font;   // index into FONTS
  float x, y;   // normalized screen position, center anchor
  float size;   // glyph height in pixels
};

constexpr int DYN_TEXT_COUNT = 0;
constexpr int DYN_TEXT_LEN = 64;  // per-slot string buffer
inline const DynTextData DYN_TEXTS[DYN_TEXT_COUNT > 0 ? DYN_TEXT_COUNT : 1] = {
    {0, 0, 0, 0},
};

}  // namespace Reverb_rooms
