// Generated by TyraX. Do not edit - regenerated on every build.
#pragma once

namespace Texture_atlas {

inline constexpr int MODEL_COUNT = 0;
inline const char* MODEL_PATHS[MODEL_COUNT > 0 ? MODEL_COUNT : 1] = {
    "",
};
// per-model .mtl override, for the .obj fallback path only (a
// .tmdl already carries the resolved override) - "" = none
inline const char* MODEL_MTLS[MODEL_COUNT > 0 ? MODEL_COUNT : 1] = {
    "",
};
// The AUTHORED asset path each slot was baked from ("res/models/x.obj").
// Nothing loads it - it is the key a runtime procedural volume
// resolves its asset pool against, because a graph names assets the
// way the editor does and the console only has baked .tmdl names.
inline const char* MODEL_SOURCES[MODEL_COUNT > 0 ? MODEL_COUNT : 1] = {
    "",
};
inline constexpr bool MODEL_NEEDS_COLLIDER[MODEL_COUNT > 0 ? MODEL_COUNT : 1] = {false};

inline constexpr int ANIM_MODEL_COUNT = 0;
inline const char* ANIM_MODEL_PATHS[ANIM_MODEL_COUNT > 0 ? ANIM_MODEL_COUNT : 1] = {
    "",
};

// .mtl libraries assigned to primitives (first material = surface)
inline constexpr int MATERIAL_COUNT = 30;
inline const char* MATERIAL_PATHS[MATERIAL_COUNT > 0 ? MATERIAL_COUNT : 1] = {
    "materials/props/prop-00.mtl",
    "materials/props/prop-01.mtl",
    "materials/props/prop-02.mtl",
    "materials/props/prop-03.mtl",
    "materials/props/prop-04.mtl",
    "materials/props/prop-05.mtl",
    "materials/props/prop-06.mtl",
    "materials/props/prop-07.mtl",
    "materials/props/prop-08.mtl",
    "materials/props/prop-09.mtl",
    "materials/props/prop-10.mtl",
    "materials/props/prop-11.mtl",
    "materials/props/prop-12.mtl",
    "materials/props/prop-13.mtl",
    "materials/props/prop-14.mtl",
    "materials/props/prop-15.mtl",
    "materials/props/prop-16.mtl",
    "materials/props/prop-17.mtl",
    "materials/props/prop-18.mtl",
    "materials/props/prop-19.mtl",
    "materials/props/prop-20.mtl",
    "materials/props/prop-21.mtl",
    "materials/props/prop-22.mtl",
    "materials/props/prop-23.mtl",
    "materials/props/prop-24.mtl",
    "materials/props/prop-25.mtl",
    "materials/props/prop-26.mtl",
    "materials/props/prop-27.mtl",
    "materials/props/prop-28.mtl",
    "materials/props/prop-29.mtl",
};

// texture atlas summary, logged at scene boot ("" = no atlas)
inline constexpr const char* TEXTURE_ATLAS_INFO = "Texture atlas: 30 textures in 1 page(s)";

// Rigid-body shapes (docs/physics.md): convex hulls in mesh-local
// units with their solid mass properties at unit density - volume,
// centre of mass and the second moment about it (xx yy zz xy xz yz).
// The game scales them per object and derives the inertia tensor.
inline constexpr int PHYS_MAX_HULL_VERTS = 24;
inline constexpr int PHYS_MAX_HULL_PLANES = 44;
struct PhysHullData {
  short verts, planes;  // counts
  int vert0, plane0;    // first entry in the tables below
  float volume, com[3], cov[6];
};
inline constexpr int PHYS_HULL_COUNT = 0;
inline const PhysHullData PHYS_HULLS[PHYS_HULL_COUNT > 0 ? PHYS_HULL_COUNT : 1] = {
    {0, 0, 0, 0, 0.0F, {0.0F, 0.0F, 0.0F}, {0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F}},
};
inline const float PHYS_HULL_VERTS[1] = {0.0F};
inline const float PHYS_HULL_PLANES[1] = {0.0F};
// PHYS_HULLS slot per MODEL_PATHS slot (-1 = collide as the mesh box)
inline const short MODEL_PHYS_HULL[MODEL_COUNT > 0 ? MODEL_COUNT : 1] = {-1};
// unit box, cylinder, cone, plane
inline const short PHYS_PRIM_HULL[4] = {-1, -1, -1, -1};

}  // namespace Texture_atlas
