// Generated by tyra-editor. Do not edit - regenerated on every build.
#pragma once

namespace Object_spawning {

// Terrain size and lighting are per scene - see scene_data.hpp arrays and
// the TERRAIN_*/SCENE_* accessor macros defined there.

// Project preferences (Project > Preferences in the editor). These are
// project-wide; sky, clipping, post-FX and the usable-highlight can be
// overridden per scene and live as SCENE_COUNT arrays in scene_data.hpp
// (reached through the accessor macros defined in scene_data.hpp).
constexpr int TERRAIN_MAX_CELLS = 32;

// Terrain streaming (Preferences > Terrain). The terrain mesh is built in
// TERRAIN_CHUNK_CELLS x TERRAIN_CHUNK_CELLS tiles; with a view distance > 0
// only the tiles within that range of the view focus are kept in memory
// (the rest streams in as the player moves - pair with fog to hide pop-in).
// 0 keeps the whole map resident, like before chunking existed.
constexpr int TERRAIN_CHUNK_CELLS = 16;
constexpr float TERRAIN_VIEW_DISTANCE = 0.0F;

constexpr float EYE_HEIGHT = 1.8F;
constexpr float WALK_SPEED = 0.4F;
constexpr float LOOK_SPEED = 1.0F;    // multiplier
// Stick offsets below this fraction of full deflection read as zero
// (worn pads rest off-center); motion rescales smoothly above it.
// Per stick: left drives movement, right drives the camera.
constexpr float ANALOG_DEADZONE_L = 0.2F;
constexpr float ANALOG_DEADZONE_R = 0.2F;
constexpr float ORBIT_SPEED = 1.0F;  // multiplier
constexpr float GRAVITY = 9.8F;          // units/s^2
constexpr float JUMP_SPEED = 4.5F;    // units/s

// Scene switches show res/hud/loading.png on black for a moment
constexpr bool LOADING_SCREEN = true;

// Experimental (Preferences > Build > Disable VSync): false skips the vsync
// wait before the flip - continuous frame rate, screen tearing possible.
constexpr bool FRAME_LIMIT = true;

// Animation LOD (Preferences > Rendering): animated instances farther than
// this refresh pose/skinning every 2nd frame, every 4th beyond twice the
// distance (staggered per object). 0 = off. Playback time is unaffected.
constexpr float ANIM_LOD_DISTANCE = 0.0F;

// Mesh LOD (Preferences > Rendering): instances farther than this render
// the ~50%-vertex variant baked into the .tskl, beyond twice the distance
// the ~25% one. 0 = off (the build then bakes no LOD chains at all).
constexpr float MESH_LOD_DISTANCE = 0.0F;

// Debug-profile HUD (Project > Preferences > Build). All forced false in a
// release-profile build, which folds the overlay + instrumentation away.
constexpr bool DEBUG_SHOW_FPS = false;
constexpr bool DEBUG_SHOW_MEM = false;
// Per-phase EE-time breakdown (scene / usable-highlight / particles / whole
// frame), averaged over ~1s. The COP0-timer reads that feed it are guarded
// by this constexpr, so a build with it false pays nothing (see drawDebugHud
// / renderScene). This is the profiling harness used to diagnose the
// usable-highlight cost, wired in as a shippable debug option.
constexpr bool DEBUG_SHOW_PROFILER = false;

}  // namespace Object_spawning
