// Generated by TyraX from the per-object Flow Graphs. Do not
// edit - regenerated on every build. Edit the graphs in the editor.
#include "scripts/script.hpp"
#include "scripts/sequences.gen.hpp"  // Play/Stop Sequence nodes
#include "scripts/scroller.gen.hpp"  // Start/Stop Scroller nodes
#include "scripts/flow_nodes.hpp"  // custom-node C++ bodies

#include <math.h>
#include <stdio.h>

#include <string>

namespace Endless_scroller {

// No object has a flow graph yet.

}  // namespace Endless_scroller

