// Generated by TyraX. Do not edit - regenerated on every build.
#pragma once

// Ambient-occlusion occluders: solid authored objects as oriented
// boxes / spheres, baked on the host. ax/ay/az = the object's local
// axes in world space; sphere = 1 reads half[0] as the radius;
// objIndex = scene-table index (an object never occludes itself).

namespace {
struct AoOccData {
  float pos[3];
  float ax[3], ay[3], az[3];
  float half[3];
  int sphere;
  int objIndex;
};

static const AoOccData S0_AO_OCC[9] = {
    {{-10.0F, 1.0F, -1.8F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.2F, 1.0F, 0.2F}, 0, 2},
    {{7.0F, 1.0F, -1.8F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.2F, 1.0F, 0.2F}, 0, 4},
    {{2.0F, 0.05F, 0.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {4.0F, 0.05F, 4.0F}, 0, 6},
    {{-6.0F, 1.16575F, -1.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.18F, 0.34425F, 0.15588F}, 0, 7},
    {{-3.0F, 1.16575F, 1.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.18F, 0.34425F, 0.15588F}, 0, 8},
    {{10.0F, 1.16575F, -1.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.18F, 0.34425F, 0.15588F}, 0, 9},
    {{13.0F, 1.16575F, 1.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.18F, 0.34425F, 0.15588F}, 0, 10},
    {{16.0F, 0.75F, -3.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.75F, 0.75F, 0.75F}, 0, 11},
    {{16.0F, 0.6F, 3.0F}, {1.0F, 0.0F, 0.0F}, {0.0F, 1.0F, 0.0F}, {0.0F, 0.0F, 1.0F}, {0.6F, 0.6F, 0.6F}, 0, 12},
};

static const AoOccData* const SCENE_AO_OCC_TABLES[] = {S0_AO_OCC};
static const int SCENE_AO_OCC_COUNTS[] = {9};

struct EmisLightData {
  float pos[3];
  float ax[3], ay[3], az[3];
  float half[3];
  int sphere;
  int objIndex;
  float color[3];
  float range, bright;
};


static const EmisLightData* const SCENE_EMIS_TABLES[] = {nullptr};
static const int SCENE_EMIS_COUNTS[] = {0};

struct AoAtlasRect {
  float u0, v0, du, dv;
};
static const AoAtlasRect S0_AO_RECTS[24] = {{0.496094F, 0.980469F, 0.210938F, 0.0078125F}, {0.261719F, 0.980469F, 0.210938F, 0.0078125F}, {0.683594F, 0.941406F, 0.0078125F, 0.0078125F}, {0.964844F, 0.722656F, 0.0234375F, 0.0234375F}, {0.777344F, 0.0117188F, 0.0078125F, 0.210938F}, {0.808594F, 0.0117188F, 0.0078125F, 0.210938F}, {0.449219F, 0.941406F, 0.210938F, 0.0078125F}, {0.0820312F, 0.941406F, 0.34375F, 0.0078125F}, {0.0507812F, 0.941406F, 0.0078125F, 0.0078125F}, {0.574219F, 0.722656F, 0.0078125F, 0.0625F}, {0.285156F, 0.722656F, 0.015625F, 0.164062F}, {0.246094F, 0.722656F, 0.015625F, 0.164062F}, {0.714844F, 0.0117188F, 0.0078125F, 0.578125F}, {0.746094F, 0.0117188F, 0.0078125F, 0.460938F}, {0.0117188F, 0.722656F, 0.210938F, 0.195312F}, {0.0117188F, 0.0117188F, 0.679688F, 0.6875F}, {0.714844F, 0.941406F, 0.226562F, 0.0078125F}, {0.0117188F, 0.980469F, 0.226562F, 0.0078125F}, {0.605469F, 0.722656F, 0.15625F, 0.03125F}, {0.785156F, 0.722656F, 0.15625F, 0.03125F}, {0.0117188F, 0.941406F, 0.015625F, 0.015625F}, {0.433594F, 0.722656F, 0.117188F, 0.117188F}, {0.378906F, 0.722656F, 0.03125F, 0.15625F}, {0.324219F, 0.722656F, 0.03125F, 0.15625F}};
static const int S0_AO_FIRST[14] = {-1, -1, 0, -1, 6, -1, 12, -1, -1, -1, -1, 18, -1, -1};
static const unsigned char S0_AO_LIT[14] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static const AoAtlasRect* const SCENE_AO_ATLAS_RECTS_T[] = {S0_AO_RECTS};
static const int* const SCENE_AO_ATLAS_FIRSTS_T[] = {S0_AO_FIRST};
static const unsigned char* const SCENE_AO_ATLAS_LITS_T[] = {S0_AO_LIT};
static const char* const SCENE_AO_ATLAS_PATHS[] = {"aoatlas/scene0.png"};
static const char* const SCENE_AO_MAP_PATHS[] = {"aomap/scene0.png"};
static const unsigned char SCENE_AO_MAP_OCCS[] = {1};
static const unsigned char SCENE_AO_MAP_LITS[] = {0};
static const unsigned char SCENE_AO_ATLAS_GIS[] = {0};
static const unsigned char SCENE_AO_MAP_GIS[] = {0};
}  // namespace

#define SCENE_AO_OCC SCENE_AO_OCC_TABLES[g_activeScene]
#define SCENE_AO_OCC_COUNT SCENE_AO_OCC_COUNTS[g_activeScene]
#define SCENE_EMIS SCENE_EMIS_TABLES[g_activeScene]
#define SCENE_EMIS_COUNT SCENE_EMIS_COUNTS[g_activeScene]
#define SCENE_AO_ATLAS_RECTS SCENE_AO_ATLAS_RECTS_T[g_activeScene]
#define SCENE_AO_ATLAS_FIRST SCENE_AO_ATLAS_FIRSTS_T[g_activeScene]
#define SCENE_AO_ATLAS_LIT SCENE_AO_ATLAS_LITS_T[g_activeScene]
#define SCENE_AO_ATLAS_PATH SCENE_AO_ATLAS_PATHS[g_activeScene]
#define SCENE_AO_MAP_PATH SCENE_AO_MAP_PATHS[g_activeScene]
#define SCENE_AO_MAP_OCC SCENE_AO_MAP_OCCS[g_activeScene]
#define SCENE_AO_MAP_LIT SCENE_AO_MAP_LITS[g_activeScene]
#define SCENE_AO_ATLAS_GI SCENE_AO_ATLAS_GIS[g_activeScene]
#define SCENE_AO_MAP_GI SCENE_AO_MAP_GIS[g_activeScene]
