// Generated by TyraX (navmesh bake). Do not edit - regenerated on every build.
#pragma once

namespace Save_points {

// No flow graph uses the AI nodes - no nav data baked.
constexpr int NAV_ENABLED = 0;

}  // namespace Save_points
